### ISSUE TITLE
Tabular Datasets?

### ISSUE THREAD

**Issue by wenger9** [imartinez/privateGPT#101]
If I want to add a dataset.csv, would I be able to use privateGPT to query the dataset and possibly perform some calculations?

**Comment by shivprasad94** [comment]
Yes, even i am looking for training on Tabular dataset, CSV/xlsx or SQL/Snowflake DB

**Comment by seshakiran** [comment]
Rename the .csv files to .txt. I got an error where only the first line was indexed when I had the file name with extension .csv.  After changing to .txt, with 1 MB file indexing found to be taking forever. Had to quit after an hour.

**Comment by dennydream** [comment]
I think you might want a slightly different approach.  Langchain has agents for pandas and databases.  You can load up the csv into a dataframe and query it from a chat interface.   I haven't tried the DB agent but have with pandas.

**Comment by wenger9** [comment]
> Rename the .csv files to .txt. I got an error where only the first line was indexed when I had the file name with extension .csv. After changing to .txt, with 1 MB file indexing found to be taking forever. Had to quit after an hour.

Were you able to find a solution or workaround to this?
