### ISSUE TITLE
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects (Because Cmake cannot make it)

### ISSUE THREAD

**Issue by Douilol** [imartinez/privateGPT#1021]
I have installed everything and it doesn't work. i have try everythings on internet... nothing work

**Environment
 - OS / Windows 11
 - Python version 3.11
-
**Additional context**
Here my console

[CWindowsSystem32cmd.exe.txt](https://github.com/imartinez/privateGPT/files/12578668/CWindowsSystem32cmd.exe.txt)

**Comment by feiyihx** [comment]
you need to install visual studio, not vs code but the original vs. I don't remember which parts you will need, that you'll have to ask google. But I am sure that error is because you don't have vs on your computer. I had the same problem when I was deploying privateGPT.

**Comment by feiyihx** [comment]
> VS? Makes no sense.

makes no sense to me too, but that's what google told me and it did solved this problem. I've tried 3 times, on my notebook, desktop and vm.

**Comment by gs-ai** [comment]
I believe that they are trying to say that you need to install Visual Studio on your main PC. Referring to your desktop which is likely running Windows.

**Comment by staleks** [comment]
To me this also doesn't make much sense. I'm trying to setup this on AWS EC2 instance. So why installing VS on Linux server instance?

**Comment by feiyihx** [comment]
> To me this also doesn't make much sense. I'm trying to setup this on AWS EC2 instance. So why installing VS on Linux server instance?

For Linux, just google it. There was a post specifically points out what kind of tools and development environment or version is needed, and in Windows install VS is the easiest way to do that. Otherwise, we'll have to download and install all kinds of things one by one.

**Comment by Squallpka1** [comment]
Can confirm for window. Ask chatGPT and its said 
Install Microsoft Visual C++ Build Tools:

Download and install Microsoft Visual C++ Build Tools from the official Microsoft website: https://visualstudio.microsoft.com/visual-cpp-build-tools/
Make sure to select the "Desktop development with C++" workload during installation.

Tried this and its work.

**Comment by Douilol** [comment]
Thanks for your help but I already had install vs and Microsoft Visual C++ Build Tools with all the components needed. nothing work...

**Comment by Monty1322** [comment]
> Can confirm for window. Ask chatGPT and its said Install Microsoft Visual C++ Build Tools:
> 
> Download and install Microsoft Visual C++ Build Tools from the official Microsoft website: https://visualstudio.microsoft.com/visual-cpp-build-tools/ Make sure to select the "Desktop development with C++" workload during installation.
> 
> Tried this and its work.

I can confirmed that it worked for me after installing Microsoft Visual C++ Build Tools from the official Microsoft website. 

Thanks!

**Comment by DhruvAthaide** [comment]
@Douilol  You need to install the Visual Studio C++ Build Tools from the following link to build the llama-cpp-python wheel:
[Visual Studio C++ Build Tools](https://visualstudio.microsoft.com/visual-cpp-build-tools/)

Then, you need to select Desktop Development with C++ in the Visual Studio C++ Build Tools Installer and install it.

After, installing the Desktop Development with C++ in the Visual Studio C++ Build Tools installer. Run the following command again:
`pip install -r requirements.txt`

After this, your issue should be resolved and PrivateGPT should be working!
