### ISSUE TITLE
LamaCpp validation Error

### ISSUE THREAD

**Issue by Englishexe** [imartinez/privateGPT#1029]
**When running PGPT it fails and gives the following error**
Traceback (most recent call last):
  File "C:\TCHT\privateGPT\privateGPT.py", line 87, in <module>
    main()
  File "C:\TCHT\privateGPT\privateGPT.py", line 40, in main
    llm = LlamaCpp(model_path=model_path, max_tokens=model_n_ctx, n_batch=model_n_batch, callbacks=callbacks, verbose=False)
  File "C:\ProgramData\anaconda3\envs\pgpt\lib\site-packages\langchain\load\serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LlamaCpp
__root__
  Could not load Llama model from path: models/ggml-vic7b-uncensored-q4_0.bin. Received error  (type=value_error)

**Expected behaviour**
To start

**Environment (please complete the following information):**
 - OS / hardware: Windows 10
 - Python version Python 3.11.3

**Additional context**

**Comment by aprabh96** [comment]
Same exact issue here

**Comment by DenizK7** [comment]
LLamaCpp is not supported ggml format anymore.

_GGUF is a new format introduced by the llama.cpp team on August 21st 2023. It is a replacement for GGML, which is no longer supported by llama.cpp. GGUF offers numerous advantages over GGML, such as better tokenisation, and support for special tokens. It is also supports metadata, and is designed to be extensible._

You can check the link for more details.
 [https://huggingface.co/TheBloke/Llama-2-13B-chat-GGUF](https://huggingface.co/TheBloke/Llama-2-13B-chat-GGUF)

**Comment by jasperan** [comment]
> LLamaCpp is not supported ggml format anymore. If you download new gguf format fpr model from link problem will be solved.
> 
> _GGUF is a new format introduced by the llama.cpp team on August 21st 2023. It is a replacement for GGML, which is no longer supported by llama.cpp. GGUF offers numerous advantages over GGML, such as better tokenisation, and support for special tokens. It is also supports metadata, and is designed to be extensible._
> 
> You can check the link for more details. https://huggingface.co/TheBloke/Llama-2-13B-chat-GGUF

So, do you suggest to submit a PR and update supported files?
