### ISSUE TITLE
unable to instantiate model

### ISSUE THREAD

**Issue by mike44pt** [imartinez/privateGPT#1033]
environment
macOS 13.4.1/ intelCore17
Python3.11.4

BUG: running python3 privateGPT.py

Found model file at  models/ggml-gpt4all-j-v1.3-groovy.bin
objc[29490]: Class GGMLMetalClass is implemented in both /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gpt4all/llmodel_DO_NOT_MODIFY/build/libreplit-mainline-metal.dylib (0x13e72d228) and 
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gpt4all/llmodel_DO_NOT_MODIFY/build/libllamamodel-mainline-metal.dylib (0x13e9da228). One of the two will be used. Which one is undefined.
Invalid model file
Traceback (most recent call last):
  File "/Users/michaelxxx/Desktop/privateGPT/privateGPT.py", line 87, in <module>
    main()
  File "/Users/michaelxxx/Desktop/privateGPT/privateGPT.py", line 42, in main
    llm = GPT4All(model=model_path, max_tokens=model_n_ctx, backend='gptj', n_batch=model_n_batch, callbacks=callbacks, verbose=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain/load/serializable.py", line 75, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GPT4All
__root__
  Unable to instantiate model (type=value_error)

**Comment by QiuZiXian** [comment]
I also encountered this bug

**Comment by QiuZiXian** [comment]
https://github.com/imartinez/privateGPT/issues/1002
python11不支持

**Comment by calnix** [comment]
> I also encountered this bug

Same
