### ISSUE TITLE
I cannot execute models based on LlamaCpp 

### ISSUE THREAD

**Issue by antonio-castellon** [imartinez/privateGPT#1037]
I did a clean installation following the instruction, GPU enabled, etc.
I'm able to run GPT4All, but ones I changed to other models like:

```
https://huggingface.co/TheBloke/Nous-Hermes-Llama2-GGML/resolve/main/nous-hermes-llama2-13b.ggmlv3.q6_K.bin
https://huggingface.co/TheBloke/koala-7B-GGML/resolve/main/koala-7B.ggmlv3.q6_K.bin

```
I'm not able to load any of them

```
root@8938add8c76b:/src# python3 privateGPT.py
Traceback (most recent call last):
  File "/src/privateGPT.py", line 87, in <module>
    main()
  File "/src/privateGPT.py", line 40, in main
    llm = LlamaCpp(model_path=model_path, max_tokens=model_n_ctx, n_batch=model_n_batch, callbacks=callbacks, verbose=False, n_gpu_layers=43)
  File "/usr/local/lib/python3.10/dist-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LlamaCpp
__root__
  Could not load Llama model from path: models/nous-hermes-llama2-13b.ggmlv3.q6_K.bin. Received error  (type=value_error)

```

Environment :

`python 3.10.12`

`Linux 8938add8c76b 5.10.186-179.751.amzn2.x86_64 #1 SMP Tue Aug 1 20:51:38 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

Muchas gracias / Many thanks

**Comment by antonio-castellon** [comment]
my fault, I discovered that ggml models cannot be loaded from 23 of August. changing to **gguf** makes the trick for me.

**Comment by FW-Treeman** [comment]
> my fault, I discovered that ggml models cannot be loaded from 23 of August. changing to **gguf** makes the trick for me.

How do you load gguf? i prepared for gpu, but it cannot load .gguf files, or gguf.bin files

**Comment by antonio-castellon** [comment]
Can you share the error throw?

**Comment by FW-Treeman** [comment]
> Can you share the error throw?
I removed the gpu changes, but the error message is still the following:

1 validation error for LlamaCpp
__root__
  Could not load Llama model from path: models/gpt4-x-vicuna-13B.gguf.q4_0.bin. Received error [WinError -1073741795] Windows Error 0xc000001d (type=value_error)

It seems that they have the same issue:
https://github.com/imartinez/privateGPT/discussions/1048

I cannot get any GGUF model to run. If I change the model type to GPT4All and link to a gpt4all-j model, it works (but so slow)
