### ISSUE TITLE
ValueError when run ingest, about submit embedding

### ISSUE THREAD

**Issue by syj18** [imartinez/privateGPT#1040]
When I run ingest.py with the example, I got
ValueError:
                Cannot submit more than 166 embeddings at once.
                Please submit your embeddings in batches of size
                166 or less.
It seems related to the length of file, when I try some shorter text, it works.
How to fix it

**Comment by codespearhead** [comment]
> When I run ingest.py with the example, I got ValueError: Cannot submit more than 166 embeddings at once. Please submit your embeddings in batches of size 166 or less. It seems related to the length of file, when I try some shorter text, it works. How to fix it

That seems to be a limitation of [SQLite](https://github.com/chroma-core/chroma/issues/1049#issuecomment-1694713482).

Try [this](https://github.com/chroma-core/chroma/issues/1049#issuecomment-1699859480), and it that works, please close the issue 😄
