### ISSUE TITLE
Error after creating python venv ?!!! 

### ISSUE THREAD

**Issue by Mana-84** [imartinez/privateGPT#1042]
Error after creating python venv ?!!!

**Comment by codespearhead** [comment]
@Mana-84 What commands did you run to get this output? Are you running them under WSL?

**Comment by Mana-84** [comment]
@codespearhead the command is python ingest.py / for WSL the answer is no :)

**Comment by Mana-84** [comment]
> _No description provided._

**Comment by DhruvAthaide** [comment]
@Mana-84 Could you provide the commands which you ran and also the screenshots to see the full error.
