### ISSUE TITLE
value_error GPT4All

### ISSUE THREAD

**Issue by msatkof** [imartinez/privateGPT#1043]
Found model file at  models/ggml-gpt4all-j-v1.3-groovy.bin
    main()
  File "C:\Users\mihail.satcovschi\PycharmProjects\pythonProject\privateGPT-main\privateGPT.py", line 42, in main
    llm = GPT4All(model=model_path, max_tokens=model_n_ctx, backend='gptj', n_batch=model_n_batch, callbacks=callbacks, verbose=False)
  File "C:\Users\mihail.satcovschi\python310\lib\site-packages\langchain\load\serializable.py", line 75, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GPT4All
__root__
  Unable to instantiate model (type=value_error)

error appears after python privateGPT.py running 

python version 3.10 

MODEL_PATH=models/ggml-gpt4all-j-v1.3-groovy.bin

its standard model proposed by the author

**Comment by msatkof** [comment]
make sure that gpt4all has 1.0.3 version. in my case it helped.  
if it's not use:
python -m pip install gpt4all==1.0.3

**Comment by calnix** [comment]
Same issue, tried `python -m pip install gpt4all==1.0.3` , didn't work

**Comment by msatkof** [comment]
> Same issue, tried `python -m pip install gpt4all==1.0.3` , didn't work

What is your python version? Try to use 3.10

**Comment by jasperan** [comment]
Interested in this error, I'm getting the same
