### ISSUE TITLE
Document Ingestion Performance Issue: Seeking Assistance with MongoDB Atlas

### ISSUE THREAD

**Issue by arun-nextbrain** [imartinez/privateGPT#1049]
@imartinez @vilaca @sorin @doskoi @jiangzhuo 

I need assistance with a document ingestion issue I'm facing. I have 84 documents with a total size of approximately 2GB. When I upload these files to my source documents and run the `ingest.py` program, it splits the documents into over 30,000 smaller documents and more than 250,000 chunks. The ingestion process takes about 1 hour to complete using ChromaDB.

To improve the document ingestion speed, I decided to switch from ChromaDB to MongoDB Atlas. However, I encountered a puzzling situation. Initially, when I used MongoDB Community, the 84 documents (1.80 GB) were ingested in just 5 minutes. But there was an issue with the loading of vector embeddings when querying the data.

To address this, I switched to MongoDB Atlas and reconfigured the database. However, the document ingestion time increased significantly to around 50 minutes. It became evident that the slowdown was primarily due to the document vector embedding process.

I'm seeking assistance to understand what might be causing this slowdown in the document ingestion process, especially when using MongoDB Atlas. Any guidance or insights would be greatly appreciated. I want to resolve this issue to ensure efficient document ingestion.

**Comment by aminbaig** [comment]
@imartinez do you have an example available for Qdrant in which we can switch from ChromaDB to Qdrant? It would be really helpful to have such a document or reference.
