### ISSUE TITLE
Streamlit output regarding

### ISSUE THREAD

**Issue by Kharankumar** [imartinez/privateGPT#1052]
Note: if you'd like to *ask a question* or *open a discussion*, head over to the [Discussions](https://github.com/imartinez/privateGPT/discussions) section and post it there.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
gptj_model_load: loading model from 'models/ggml-gpt4all-j-v1.3-groovy.bin' - please wait ...
gptj_model_load: n_vocab = 50400
gptj_model_load: n_ctx   = 2048
gptj_model_load: n_embd  = 4096
gptj_model_load: n_head  = 16
gptj_model_load: n_layer = 28
gptj_model_load: n_rot   = 64
gptj_model_load: f16     = 2
gptj_model_load: ggml ctx size = 5401.45 MB
gptj_model_load: kv self size  =  896.00 MB
gptj_model_load: ................................... done
gptj_model_load: model size =  3609.38 MB / num tensors = 285
Found model file at  models/ggml-gpt4all-j-v1.3-groovy.bin

Enter a query:  Power Jack refers to a connector on the back of an electronic device that provides access for external devices, such as cables or batteries. It allows users to connect and charge their equipment without having to open up the case.

> Question:
what is power jack?

> Answer (took 112.78 s.):
 Power Jack refers to a connector on the back of an electronic device that provides access for external devices, such as cables or batteries. It allows users to connect and charge their equipment without having to open up the case.

> source_documents\Agera_Users_Manual_2.3_A60-1018-812.pdf:
User’s Manual for Agera and EasyMatch Essentials v 2.3 
10 
Figure 1. Shipping Bolt 
Power Jack  
• 
The instrument is supplied with a 24 VDC (3.75A) power supply. The power supply is plugged 
into the back of the instrument as shown along with the Ethernet port and the USB port. 
 
Figure 2. Rear View with Connectors 
CAUTION 
Note: Use only the power cord included with this instrument or a replacement obtained

I don't need to print these details in the output. 
"gptj_model_load: loading model from 'models/ggml-gpt4all-j-v1.3-groovy.bin' - please wait ...
gptj_model_load: n_vocab = 50400
gptj_model_load: n_ctx   = 2048
gptj_model_load: n_embd  = 4096
gptj_model_load: n_head  = 16
gptj_model_load: n_layer = 28
gptj_model_load: n_rot   = 64
gptj_model_load: f16     = 2
gptj_model_load: ggml ctx size = 5401.45 MB
gptj_model_load: kv self size  =  896.00 MB
gptj_model_load: ................................... done
gptj_model_load: model size =  3609.38 MB / num tensors = 285
Found model file at  models/ggml-gpt4all-j-v1.3-groovy.bin"  
So what I have to do?

**Comment by alxspiker** [comment]
Honestly instead of printing the answer, just send the answer over to your streamlit UI

It almost looks like you are sending all the output from the console window over instead of just the answer variable. Hope this helps.

![image](https://github.com/imartinez/privateGPT/assets/7357054/7fad83fd-8f86-463c-8811-92ae3c5cf600)
