### ISSUE TITLE
PrivateGPT Installation fails

### ISSUE THREAD

**Issue by Empuries** [imartinez/privateGPT#1056]
**Describe the bug and how to reproduce it**
When attempting to install PrivateGPT, the installation process fails due to an error in the `setup.py` script of PyMuPDF. Despite updating the path to `devenv.com` and switching from Visual Studio 2022 to 2019, the error persists.

Error Message:
```
subprocess.CalledProcessError: Command 'cd C:\Users\ernes\AppData\Local\Temp\pip-install-ek5ry7ci\pymupdf_6359a68eec524ec3aae797c6ea743d53\mupdf-1.23.0-source && C:\Users\ernes\AppData\Local\Programs\Python\Python312\python.exe ./scripts/mupdfwrap.py -d build\shared-release-x64-py3.12 -b --refcheck-if "#if 1" --devenv "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\devenv.com" all' returned non-zero exit status 1.
```

**Expected behavior**
Successful installation of PrivateGPT without any errors.

**Environment (please complete the following information):**
 - OS / hardware: Windows 10 Home
 - Python version 3.12

**Additional context**
The error seems to originate from a subprocess call within PyMuPDF's `setup.py`, and persists even after updating the Visual Studio version and the path to `devenv.com`.

**Comment by CicadaMikoto** [comment]
I was able to bypass this by downgrading from python 3.12 to python 3.11.

**Comment by Monty1322** [comment]
> I was able to bypass this by downgrading from python 3.12 to python 3.11.

downgrading to 3.11.6 also worked for me. thanks!

**Comment by LarsVietense** [comment]
> downgrading from python 3.12 to python 3.11

how can i  downgrade python on Windows 10?
I installed both versions at d:\Apps\Python\Python312 und d:\Apps\Python\Python311

**Comment by CicadaMikoto** [comment]
> > downgrading from python 3.12 to python 3.11
> 
> how can i downgrade python on Windows 10? I installed both versions at d:\Apps\Python\Python312 und d:\Apps\Python\Python311

Uninstall python 3.12, for now. After that, reinstall 3.11 to ensure it's properly setup in your PATH so that it runs without issue. That should fix it for you.

Hopefully 3.12 support happens soon.

**Comment by robertgro** [comment]
```poetry install --with ui,local``` now throws a
```
Current Python version (3.12.0) is not allowed by the project (>=3.11,<3.12).
Please change python executable via the "env use" command.
``` 
error with the latest Python version installed (3.12).

Installing the latest [Python 3.11.6 version](https://www.python.org/downloads/release/python-3116/) and setting the binary path by issuing

```peotry env use C:\Path\To\Python3.11.6\python.exe``` 

is a temporary fix that works for me on Windows.
