### ISSUE TITLE
Massive amount of errors when pip install -r requirements.txt

### ISSUE THREAD

**Issue by PedzacyKapec** [imartinez/privateGPT#106]
Cant even install it coz of so many errors im getting when trying to:
pip install -r requirements.txt

Some of them:
ERROR: Failed building wheel for llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, hnswlib, which is required to install pyproject.toml-based projects

  Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [308 lines of output]

**Comment by ShJavokhir** [comment]
You should install Visual studio along with C++ (v143)
![image](https://github.com/imartinez/privateGPT/assets/46817680/cb5763d5-ed9b-4fdc-a38f-f1a5d4cbf874)

**Comment by PedzacyKapec** [comment]
But i have VSC 2022 installed. 
I have no idea how to do it

**Comment by riyazmuthyalapati** [comment]
> But i have VSC 2022 installed. I have both python and C++ plugins installed.
> 
> Dont know how install that package... I dont have any section where i can tick that kind of box.
> 
> EDIT: Ok i got it. Didnt realise VS and VSC were 2 different and seperate programs. Just installing it. THanks !

You mean we need to install separate Vs code or just download c++ ?
If we need to download separate vs code, please share link..

**Comment by pgebert** [comment]
You could adjust your `requirements.txt` in the following way to use prebuild wheels for llama-cpp-python:

```
llama-cpp-python==0.1.48; platform_system != "Windows"
https://github.com/abetlen/llama-cpp-python/releases/download/v0.1.48/llama_cpp_python-0.1.48-cp310-cp310-win_amd64.whl; platform_system == "Windows"
```

Make sure you select the right wheel from the [release page](https://github.com/abetlen/llama-cpp-python/releases/) that matches your python version and sytem architecture.

**Comment by hanwsf** [comment]
for this one needs gcc-11
my ubuntu18 revised and successful compiled and installed

**Comment by riyazmuthyalapati** [comment]
> You could adjust your `requirements.txt` in the following way to use prebuild wheels for llama-cpp-python:
> 
> ```
> llama-cpp-python==0.1.48; platform_system != "Windows"
> https://github.com/abetlen/llama-cpp-python/releases/download/v0.1.48/llama_cpp_python-0.1.48-cp310-cp310-win_amd64.whl; platform_system == "Windows"
> ```
> 
> Make sure you select the right wheel from the [release page](https://github.com/abetlen/llama-cpp-python/releases/) that matches your python version and sytem architecture.

Could you please let me know how do i select the right wheel ?

**Comment by PedzacyKapec** [comment]
Disregard it.
All you need to do is to install Visual Studio, not VSC.
Follow ShJavokhir's instructions.

**Comment by lucifer717** [comment]
macOS 13.1 need help!!!!

**Comment by cnayan** [comment]
Depends on if you have x86 or x64. You don't specify

**Comment by lucifer717** [comment]
@cnayan macOS 13.1 ,intel chip x86_64, I have tried install gcc11 or gcc12, but not work. Errors below:

`error: subprocess-exited-with-error

  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [118 lines of output]


      --------------------------------------------------------------------------------
      -- Trying 'Ninja' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is AppleClang 11.0.3.11030032
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - failed
      -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
      -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - broken
      CMake Error at /private/var/folders/jc/n_xfl__j7c91plfnklwfb3w00000gn/T/pip-build-env-0e0x2tev/overlay/lib/python3.10/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:67 (message):
        The C compiler

          "/Library/Developer/CommandLineTools/usr/bin/cc"

        is not able to compile a simple test program.

        It fails with the following output:

          Change Dir: /private/var/folders/jc/n_xfl__j7c91plfnklwfb3w00000gn/T/pip-install-mvwqjy_1/llama-cpp-python_44cc475d81774b20843c5b3c3df55986/_cmake_test_compile/build/CMakeFiles/CMakeScratch/TryCompile-PjXBAS

          Run Build Command(s):/private/var/folders/jc/n_xfl__j7c91plfnklwfb3w00000gn/T/pip-build-env-0e0x2tev/overlay/lib/python3.10/site-packages/ninja/data/bin/ninja -v cmTC_b12b9 && [1/2] /Library/Developer/CommandLineTools/usr/bin/cc   -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -mmacosx-version-min=13.0 -MD -MT CMakeFiles/cmTC_b12b9.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_b12b9.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_b12b9.dir/testCCompiler.c.o -c /private/var/folders/jc/n_xfl__j7c91plfnklwfb3w00000gn/T/pip-install-mvwqjy_1/llama-cpp-python_44cc475d81774b20843c5b3c3df55986/_cmake_test_compile/build/CMakeFiles/CMakeScratch/TryCompile-PjXBAS/testCCompiler.c
          FAILED: CMakeFiles/cmTC_b12b9.dir/testCCompiler.c.o
          /Library/Developer/CommandLineTools/usr/bin/cc   -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -mmacosx-version-min=13.0 -MD -MT CMakeFiles/cmTC_b12b9.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_b12b9.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_b12b9.dir/testCCompiler.c.o -c /private/var/folders/jc/n_xfl__j7c91plfnklwfb3w00000gn/T/pip-install-mvwqjy_1/llama-cpp-python_44cc475d81774b20843c5b3c3df55986/_cmake_test_compile/build/CMakeFiles/CMakeScratch/TryCompile-PjXBAS/testCCompiler.c
          clang: error: invalid version number in '-mmacosx-version-min=13.0'
          ninja: build stopped: subcommand failed.





        CMake will not be able to correctly generate this project.
      Call Stack (most recent call first):
        CMakeLists.txt:3 (ENABLE_LANGUAGE)


      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja' generator - failure
      --------------------------------------------------------------------------------



      --------------------------------------------------------------------------------
      -- Trying 'Unix Makefiles' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is AppleClang 11.0.3.11030032
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - failed
      -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
      -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - broken
      CMake Error at /private/var/folders/jc/n_xfl__j7c91plfnklwfb3w00000gn/T/pip-build-env-0e0x2tev/overlay/lib/python3.10/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:67 (message):
        The C compiler

          "/Library/Developer/CommandLineTools/usr/bin/cc"

        is not able to compile a simple test program.

        It fails with the following output:

          Change Dir: /private/var/folders/jc/n_xfl__j7c91plfnklwfb3w00000gn/T/pip-install-mvwqjy_1/llama-cpp-python_44cc475d81774b20843c5b3c3df55986/_cmake_test_compile/build/CMakeFiles/CMakeScratch/TryCompile-cUSicl

          Run Build Command(s):/private/var/folders/jc/n_xfl__j7c91plfnklwfb3w00000gn/T/pip-build-env-0e0x2tev/overlay/lib/python3.10/site-packages/cmake/data/bin/cmake -E env VERBOSE=1 /usr/bin/make -f Makefile cmTC_f5f4e/fast && /Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/cmTC_f5f4e.dir/build.make CMakeFiles/cmTC_f5f4e.dir/build
          Building C object CMakeFiles/cmTC_f5f4e.dir/testCCompiler.c.o
          /Library/Developer/CommandLineTools/usr/bin/cc   -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -mmacosx-version-min=13.0 -MD -MT CMakeFiles/cmTC_f5f4e.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_f5f4e.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_f5f4e.dir/testCCompiler.c.o -c /private/var/folders/jc/n_xfl__j7c91plfnklwfb3w00000gn/T/pip-install-mvwqjy_1/llama-cpp-python_44cc475d81774b20843c5b3c3df55986/_cmake_test_compile/build/CMakeFiles/CMakeScratch/TryCompile-cUSicl/testCCompiler.c
          clang: error: invalid version number in '-mmacosx-version-min=13.0'
          make[1]: *** [CMakeFiles/cmTC_f5f4e.dir/testCCompiler.c.o] Error 1
          make: *** [cmTC_f5f4e/fast] Error 2





        CMake will not be able to correctly generate this project.
      Call Stack (most recent call first):
        CMakeLists.txt:3 (ENABLE_LANGUAGE)


      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Unix Makefiles' generator - failure
      --------------------------------------------------------------------------------

                      ********************************************************************************
                      scikit-build could not get a working generator for your system. Aborting build.

                      Building MacOSX wheels for Python 3.10 requires XCode.
      Get it here:

        https://developer.apple.com/xcode/

                      ********************************************************************************
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects`

**Comment by lucifer717** [comment]
> 

I also have xcode 14.3

**Comment by cnayan** [comment]
@lucifer717 I don't use Mac, but I am suspecting that this is pretty good hint:
`error: invalid version number in '-mmacosx-version-min=13.0'`

Version incompatibility, could be it?!

I suggest you log a separate thread regarding version support. Mac users may be able to help you.

BTW, I ran PrivateGPT on a powerful laptop with 32GB RAM, and it takes 7 min to answer a question, for default configuration. See if you really need this.

**Comment by lucifer717** [comment]
@cnayan OK, I see...Thanks.

**Comment by ye-ye823** [comment]
I hava the same issue in windows10. How to solve?

**Comment by SamuraiDjvak** [comment]
This is the modification I made for Windows 10 in Visual Studio, and it worked well for me. I also used venv to install all requirements, which isolated all other libraries and resolved any other issues. I hope this will be helpful
![modifying](https://github.com/imartinez/privateGPT/assets/122186015/95b0d7bb-d826-4d6b-a536-dcca4f1756ee)
