### ISSUE TITLE
Invalid model file

### ISSUE THREAD

**Issue by behnamasaei** [imartinez/privateGPT#1061]
I'm getting an Invalid model file error when trying to load the GPT4All model in my privateGPT.py script. It looks like it is having trouble instantiating the model.

Steps to Reproduce:

Run privateGPT.py
Error occurs on this line:
Copy code

llm = GPT4All(model=model_path, max_tokens=model_n_ctx, backend='gptj', n_batch=model_n_batch, callbacks=callbacks, verbose=False)
Stack Trace:

Copy code

Invalid model file 

Traceback (most recent call last):

  File "F:\privateGPT\privateGPT.py", line 87, in <module>

    main()

  File "F:\privateGPT\privateGPT.py", line 42, in main

    llm = GPT4All(model=model_path, max_tokens=model_n_ctx, backend='gptj', n_batch=model_n_batch, callbacks=callbacks, verbose=False)

  File "C:\Users\behnam\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\load\serializable.py", line 74, in __init__

    super().__init__(**kwargs)

  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__

    pydantic.error_wrappers.ValidationError: 1 validation error for GPT4All

  **root**

  Unable to instantiate model (type=value_error)
The model path and other parameters seem valid, so I'm not sure why it can't load the model. Any thoughts on what could be causing this?

**Comment by thiagogpinto** [comment]
I got the same problem. Then I pip install gpt4all==0.2.3  and it loaded the Model and prompted for a query. But now all queries are returning an error 

TypeError: LLModel.generate() got an unexpected keyword argument 'max_tokens'

**Comment by alxspiker** [comment]
Try removing max_tokens from this line, its probably changed names in the versions you guys are using.

llm = GPT4All(model=model_path, _max_tokens=model_n_ctx,_ backend='gptj', n_batch=model_n_batch, callbacks=callbacks, verbose=False)
should become
llm = GPT4All(model=model_path, backend='gptj', n_batch=model_n_batch, callbacks=callbacks, verbose=False)

or try this:
pip uninstall gpt4all && pip install gpt4all==1.0.8

**Comment by thiagogpinto** [comment]
Hey man... thanks for your message. I did all of those and also tried to update gtp4all to 1.0.8 and still the same error. I am using an Apple M1 chip (although I am running python run_localGPT.py --device_type mps).
