### ISSUE TITLE
Model initialization

### ISSUE THREAD

**Issue by Musthafamoz** [imartinez/privateGPT#1064]
i am trying to obtain the output in a streamlit ui. its working and the getting the output like this.

Enter a query (type 'exit' to quit): gptj_model_load: loading model from 'models/ggml-gpt4all-j-v1.3-groovy.bin' - please wait ...
gptj_model_load: n_vocab = 50400
gptj_model_load: n_ctx   = 2048
gptj_model_load: n_embd  = 4096
gptj_model_load: n_head  = 16
gptj_model_load: n_layer = 28
gptj_model_load: n_rot   = 64
gptj_model_load: f16     = 2
gptj_model_load: ggml ctx size = 5401.45 MB
gptj_model_load: kv self size  =  896.00 MB
gptj_model_load: ................................... done
gptj_model_load: model size =  3609.38 MB / num tensors = 285
Found model file at  models/ggml-gpt4all-j-v1.3-groovy.bin
 Powerjack refers to a device that allows for the connection of external devices, such as computers or peripherals. It can be used with various types of equipment and has different functions depending on its design. Powerjack refers to a device that allows for the connection of external devices, such as computers or peripherals. It can be used with various types of equipment and has different functions depending on its design.

but i only need the last 4 lines as the answer that is to be shown.

any one know how to get rid of all these lines?

Enter a query (type 'exit' to quit): gptj_model_load: loading model from 'models/ggml-gpt4all-j-v1.3-groovy.bin' - please wait ...
gptj_model_load: n_vocab = 50400
gptj_model_load: n_ctx   = 2048
gptj_model_load: n_embd  = 4096
gptj_model_load: n_head  = 16
gptj_model_load: n_layer = 28
gptj_model_load: n_rot   = 64
gptj_model_load: f16     = 2
gptj_model_load: ggml ctx size = 5401.45 MB
gptj_model_load: kv self size  =  896.00 MB
gptj_model_load: ................................... done
gptj_model_load: model size =  3609.38 MB / num tensors = 285
Found model file at  models/ggml-gpt4all-j-v1.3-groovy.bin

![image](https://github.com/imartinez/privateGPT/assets/107695170/806ef093-823f-48f8-81bc-266627432606)

**Comment by alxspiker** [comment]
For a quick and easy fix, you can use regex to remove all lines with gptj_model_load

**Comment by alxspiker** [comment]
Heres to get you started:

Regex:
^gptj_model_load.*\n

**Comment by Musthafamoz** [comment]
Hi @alxspiker  thanks for your reply. can you please specify where to put this regex code?

**Comment by lopagela** [comment]
This looks like verbose/debug information to be outputted in the wrong buffer -- did you enabled some verbose mode @Musthafamoz ?

What's your setup? Did you follow the standard installation?
