### ISSUE TITLE
gpt_tokenize: uknown token 

### ISSUE THREAD

**Issue by ShJavokhir** [imartinez/privateGPT#107]
![image](https://github.com/imartinez/privateGPT/assets/46817680/03d0d77d-033f-44c5-9529-94cd521d97e9)

I just installed everything perfectly without any problems. But when I try to run I am facing this issue.

**Comment by ShJavokhir** [comment]
![image](https://github.com/imartinez/privateGPT/assets/46817680/0c468afe-4e54-4463-a872-d81ee1c73c0e)

It looks like got stuck in a something like loop. Because it was constantly eating CPU  and RAM resourses

**Comment by ClayWalker001** [comment]
me too

**Comment by ClayWalker001** [comment]
I think windows is not a good choice, I run it on ubuntu now, everything smooth!

**Comment by mabry1985** [comment]
seeing this on an m1 mac right now
```
LLAMA_EMBEDDINGS_MODEL=./models/ggml-model-q4_1.bin
MODEL_PATH=./models/ggml-gpt4all-l13b-snoozy.bin
```

**Comment by mabry1985** [comment]
This fixed it for me
https://github.com/imartinez/privateGPT/issues/13#issuecomment-1546769749

**Comment by OneCodeToRuleThemAll** [comment]
Getting the same error, 
gpt_tokenize: unknown token 'Γ'
gpt_tokenize: unknown token 'Ç'
gpt_tokenize: unknown token 'Ö'
gpt_tokenize: unknown token 'Γ'
gpt_tokenize: unknown token 'Ç'
gpt_tokenize: unknown token 'Ö'
gpt_tokenize: unknown token 'Γ'
gpt_tokenize: unknown token 'Ç'
gpt_tokenize: unknown token 'Ö'
CPU almost at 100% and memory usage slowly rising so it must still be working but I get no output.
Running on Windows.
I have the same model type running and have correctly named it in the .env file (GPT4ALL) but I'll be switching to Llama.cpp to check

**Comment by thekit** [comment]
I also get an output eventually after seeing the warnings.
