### ISSUE TITLE
KeyringLocked    Failed to unlock the collection!

### ISSUE THREAD

**Issue by zhanghui-china** [imartinez/privateGPT#1071]
Note: if you'd like to *ask a question* or *open a discussion*, head over to the [Discussions](https://github.com/imartinez/privateGPT/discussions) section and post it there.

**Describe the bug and how to reproduce it**
A clear and concise description of what the bug is and the steps to reproduce the behavior.

git clone https://github.com/imartinez/privateGPT
conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
pip3 install -r requirements.txt
curl -sSL https://install.python-poetry.org | python3 -
cd privateGPT
poetry install
`(private310) zhanghui@zhanghui-OMEN-by-HP-Laptop-17-ck0xxx:~/privateGPT$ poetry install
Installing dependencies from lock file

Package operations: 1 install, 57 updates, 0 removals

  • Updating pycparser (2.21 /tmp/build/80754af9/pycparser_1636541352034/work -> 2.21): Failed

  KeyringLocked

  Failed to unlock the collection!

  at ~/.local/share/pypoetry/venv/lib/python3.10/site-packages/keyring/backends/SecretService.py:67 in get_preferred_collection
       63│             raise InitError("Failed to create the collection: %s." % e)
       64│         if collection.is_locked():
       65│             collection.unlock()
       66│             if collection.is_locked():  # User dismissed the prompt
    →  67│                 raise KeyringLocked("Failed to unlock the collection!")
       68│         return collection
       69│
       70│     def unlock(self, item):
       71│         if hasattr(item, 'unlock'):

`
![e88f1d91589034cbad40e423f325032](https://github.com/imartinez/privateGPT/assets/63148804/35b734db-604e-4e54-961c-b2e7527144e4)

**Expected behavior**
poetry install success

**Environment (please complete the following information):**
 - OS / hardware:ubuntu 18.04
 - Python version python 3.10.13（Anaconda）
- Other relevant information

**Additional context**

**Comment by lamw** [comment]
After searching online, using the following will allow you to proceed at least:

```console
export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring
```

**Comment by wmhartl** [comment]
Yes, also noted bug 1158

**Comment by thadude3** [comment]
> After searching online, using the following will allow you to proceed at least:
> 
> ```
> export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring
> ```

thanks this worked for me, I was hung otherwise.
