### ISSUE TITLE
Not supporting .eml extension

### ISSUE THREAD

**Issue by AyeshaHameer** [imartinez/privateGPT#1097]
I tired to ingest .eml extension in the Gradio then running a query. Its giving me an error stating 
![Screenshot 2023-10-23 at 19-39-48 Gradio](https://github.com/imartinez/privateGPT/assets/89131127/ade51076-b21b-4d66-8891-e282c474ef23)

**Comment by imartinez** [comment]
Regarding file types: 
The initial set of supported file types (and the internal readers used) are:
    ".hwp": HWPReader,
    ".pdf": PDFReader,
    ".docx": DocxReader,
    ".pptx": PptxReader,
    ".jpg": ImageReader,
    ".png": ImageReader,
    ".jpeg": ImageReader,
    ".mp3": VideoAudioReader,
    ".mp4": VideoAudioReader,
    ".csv": PandasCSVReader,
    ".epub": EpubReader,
    ".md": MarkdownReader,
    ".mbox": MboxReader,
    ".ipynb": IPYNBReader,

Any file not in the list will be parsed as a plain text, which may generate errors.

It is "easy" to add further support by extending the logic in ingest_service, detecting the file type, and using a specific loader by LlamaIndex. Feel free to give it a try and open a Pull Request!

We'll update the Docs stating this.
