### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by CloudAlarms** [imartinez/privateGPT#1100]
I have successfully run the openai version, now when I try to use the local version I get the error shown below

I am running Ubuntu 22.04 with a small NVIDIA GeForce GTX 1050 Ti GPU
Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
it does support avx but not avx2 so I don't know if that's the core dumped error

```
root@privateGPT:/home/privateGPT# PGPT_PROFILES=local make run
poetry run python -m private_gpt
The currently activated Python version 3.12.0 is not supported by the project (>=3.11,<3.12).
Trying to find and use a compatible version.
Using python3 (3.11.6)
Starting application with profiles: ['default', 'local']
make: *** [Makefile:36: run] Illegal instruction (core dumped)
```

**Comment by imartinez** [comment]
Please check this related issue. 
https://github.com/imartinez/privateGPT/issues/203

Specifically this comment seems to be very much on point. 
https://github.com/imartinez/privateGPT/issues/203#issuecomment-1554321796

Let us know if you are able to make it work so we can improve the docs troubleshooting. 

Thanks!
