### ISSUE TITLE
async generator raised StopAsyncIteration

### ISSUE THREAD

**Issue by nowindnowave** [imartinez/privateGPT#1101]
When I start in openai mode, upload a document in the ui and ask, the ui returns an error: async generator raised StopAsyncIteration
The background program reports an error:
But there is no problem in LLM-chat mode and you can chat with openai normally.
Traceback (most recent call last):
  File "/root/privateGPT-venv/lib/python3.11/site-packages/gradio/chat_interface.py", line 424, in _stream_fn
    first_response = await async_iteration(generator)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/privateGPT-venv/lib/python3.11/site-packages/gradio/utils.py", line 517, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/privateGPT-venv/lib/python3.11/site-packages/gradio/utils.py", line 510, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/privateGPT-venv/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/privateGPT-venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/root/privateGPT-venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/privateGPT-venv/lib/python3.11/site-packages/gradio/utils.py", line 496, in run_sync_iterator_async
    raise StopAsyncIteration() from None
StopAsyncIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/privateGPT-venv/lib/python3.11/site-packages/gradio/queueing.py", line 406, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/privateGPT-venv/lib/python3.11/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/privateGPT-venv/lib/python3.11/site-packages/gradio/blocks.py", line 1554, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/privateGPT-venv/lib/python3.11/site-packages/gradio/blocks.py", line 1206, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/privateGPT-venv/lib/python3.11/site-packages/gradio/utils.py", line 517, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/privateGPT-venv/lib/python3.11/site-packages/gradio/utils.py", line 621, in asyncgen_wrapper
    async for response in f(*args, **kwargs):
RuntimeError: async generator raised StopAsyncIteration

**Comment by cuevana8** [comment]
+1..[.](https://github.com/flslib/fl-studio-cracked)[@@@](https://github.com/imartinez/privateGPT/issues/1101#issue-1958621282)

**Comment by Fluxkom** [comment]
I get the same issue with local embedding

**Comment by 0xMoJo7** [comment]
I also have this issue, but only occurs when trying to ask prompts about a csv or xlsx, pdf seems to work perfectly.

**Comment by nowindnowave** [comment]
By trying it out /v1/chat/completions in the docs document, I can chat normally, but I need to have a conversation with the uploaded docs document. Can this be tested? No matter how many times I try, the UI will report an asynchronous problem.

**Comment by imartinez** [comment]
If you pass the use_context: True in the request body the response will use the context in the uploaded docs. So you will be effectively chatting with your docs. 

{
"messages": [],
"stream": false,
**"use_context": true**
}

**Comment by nowindnowave** [comment]
Can documents be uploaded through the interface? Then ask the content in the openai document through the api?

**Comment by Fluxkom** [comment]
I tried it using the api and got the following:

<img width="495" alt="Bildschirmfoto 2023-10-25 um 12 36 15" src="https://github.com/imartinez/privateGPT/assets/909655/f11edea0-4179-44cf-b30e-2f7eba8bc705">
<img width="413" alt="Bildschirmfoto 2023-10-25 um 12 36 30" src="https://github.com/imartinez/privateGPT/assets/909655/f6ff1f76-8e2d-49d0-bc41-285132c8c0b7">
<img width="424" alt="Bildschirmfoto 2023-10-25 um 12 36 38" src="https://github.com/imartinez/privateGPT/assets/909655/59a3c4ee-b228-4016-b5fe-30b2cd898981">

**Comment by imartinez** [comment]
What was the body of the POST @Fluxkom ? Did you get any error in the console?

**Comment by Jawn78** [comment]
> What was the body of the POST @Fluxkom ? Did you get any error in the console? 

I have the same issue, and that matches the response I get from using the standard docs "try it out" post

**Comment by Fluxkom** [comment]
> What was the body of the POST @Fluxkom ? Did you get any error in the console?

The post was just the example from the docs, with a question regarding the document I ingested.
I had no errors there.

**Comment by 0xMoJo7** [comment]
Has anyone found a fix for this in the UI? The folks I'd like to use the tool for aren't savvy enough to make API calls :)

**Comment by Jawn78** [comment]
@0xMoJo7 

I was able to get it working after re-installing everything. I had to upgrade Gradio. 

I am not much of a Python programmer (or programmer in general, self-taught), so I am not sure what fixed it, but I will say the UI still has some issues. It doesn't appear to let me embed more documents than what fits into the display box. I also had this issue pop up after trying to upload a document. So, If I had to guess, there's something going on in that area. 

I know in the original and some forks of PrivateGPT (like localGPT), they wouldn't let you start it without having a single document in the source folder. Maybe some bad embedding stuff has stuck around? I also got it to work using the large version of the embedding model, so I'm not sure if that could have contributed.

**Comment by 0xMoJo7** [comment]
Thanks @Jawn78 ! I'll tinker around with it.

**Comment by Jawn78** [comment]
@0xMoJo7  Let us know what you find out!

**Comment by 0xMoJo7** [comment]
@Jawn78 Which version of gradio are you using? I just tried `3.50.2` which is the newest available on PyPi and still am running into the same issue.

**Comment by Jawn78** [comment]
`aiofiles==23.2.1
altair==5.1.2
annotated-types==0.6.0
anyio==3.7.1
attrs==23.1.0
certifi==2023.7.22
charset-normalizer==3.3.1
click==8.1.7
colorama==0.4.6
contourpy==1.1.1
cycler==0.12.1
diskcache==5.6.3
EbookLib==0.18
fastapi==0.104.0
ffmpy==0.3.1
filelock==3.12.4
fonttools==4.43.1
fsspec==2023.10.0
gradio==3.50.2
gradio_client==0.6.1
html2text==2020.1.16
httpcore==0.18.0
httpx==0.25.0
huggingface-hub==0.18.0
idna==3.4
importlib-resources==6.1.0
Jinja2==3.1.2
jsonschema==4.19.1
jsonschema-specifications==2023.7.1
kiwisolver==1.4.5
llama_cpp_python==0.2.11
lxml==4.9.3
MarkupSafe==2.1.3
matplotlib==3.8.0
numpy==1.26.1
orjson==3.9.10
packaging==23.2
pandas==2.1.1
Pillow==10.1.0
pydantic==2.4.2
pydantic_core==2.10.1
pydub==0.25.1
pyparsing==3.1.1
python-dateutil==2.8.2
python-multipart==0.0.6
pytz==2023.3.post1
PyYAML==6.0.1
referencing==0.30.2
requests==2.31.0
rpds-py==0.10.6
semantic-version==2.10.0
six==1.16.0
sniffio==1.3.0
starlette==0.27.0
toolz==0.12.0
tqdm==4.66.1
typing_extensions==4.8.0
tzdata==2023.3
urllib3==2.0.7
uvicorn==0.23.2
websockets==11.0.3`

This is my settings file. 
`server:
  env_name: ${APP_ENV:prod}
  port: ${PORT:8001}

data:
  local_data_folder: local_data/private_gpt

ui:
  enabled: true
  path: /

llm:
  mode: local

local:
  llm_hf_repo_id: TheBloke/Llama-2-7B-chat-GGUF
  llm_hf_model_file: llama-2-7b-chat.Q6_K.gguf
  embedding_hf_model_name: BAAI/bge-large-en-v1.5

sagemaker:
  endpoint_name: huggingface-pytorch-tgi-inference-2023-09-25-19-53-32-140

openai:
  api_key: ${OPENAI_API_KEY:}`

**Comment by 0xMoJo7** [comment]
Ah, got it. I'll give it a shot with these setting but document query is my primary attraction. Thank you sir!

**Comment by 0xMoJo7** [comment]
No luck, still trying to fix myself but a bit out of my wheelhouse.

**Comment by Jawn78** [comment]
@0xMoJo7  just sent you an email, let's see if we can connect to figure it out. and report back here.

**Comment by lee-jian-hui** [comment]
I have this bug as well, i was trying to ingest .html documents and then run the LLM after, however, this error is thrown when im trying to invoke this in the UI. It works fine for a sample .pdf file

**Comment by 0xMoJo7** [comment]
Has anyone cracked this yet? I gave it another go last night to no avail.

**Comment by Jawn78** [comment]
@0xMoJo7, without being able to repeat the issue, I don't know how to help.

**Comment by 0xMoJo7** [comment]
@Jawn78 I'm using the settings you provided in the snippet above (although I haven't had luck with any configuration tweaks yet), and then passing in a .csv to be ingested, and once I put anything in the query documents text box I get that error. I'm developing on a Mac Mini, Apple M2 Pro, 32GB -- running Sonoma 14.0.

**Comment by fdpitney2000** [comment]
I received the same "async generator.." message after trying to query a 2,000 row .csv file, then I uploaded the file again (same name) with just 10 rows and was able to query/get a response before getting the error message again. 

I also had a few rogue settings (like conda instead of pyenv) so next I'll test again with a cleaner install.

iMac M1 8GB ram, 7-8 seconds for the response to start coming, not too bad but def looking to upgrade.

**Comment by rmuhawieh** [comment]
> When I start in openai mode, upload a document in the ui and ask, the ui returns an error: async generator raised StopAsyncIteration The background program reports an error: But there is no problem in LLM-chat mode and you can chat with openai normally. Traceback (most recent call last): File "/root/privateGPT-venv/lib/python3.11/site-packages/gradio/chat_interface.py", line 424, in _stream_fn first_response = await async_iteration(generator) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/privateGPT-venv/lib/python3.11/site-packages/gradio/utils.py", line 517, in async_iteration return await iterator.**anext**() ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/privateGPT-venv/lib/python3.11/site-packages/gradio/utils.py", line 510, in **anext** return await anyio.to_thread.run_sync( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/privateGPT-venv/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync return await get_asynclib().run_sync_in_worker_thread( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/privateGPT-venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread return await future ^^^^^^^^^^^^ File "/root/privateGPT-venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run result = context.run(func, *args) ^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/privateGPT-venv/lib/python3.11/site-packages/gradio/utils.py", line 496, in run_sync_iterator_async raise StopAsyncIteration() from None StopAsyncIteration
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/root/privateGPT-venv/lib/python3.11/site-packages/gradio/queueing.py", line 406, in call_prediction output = await route_utils.call_process_api( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/privateGPT-venv/lib/python3.11/site-packages/gradio/route_utils.py", line 226, in call_process_api output = await app.get_blocks().process_api( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/privateGPT-venv/lib/python3.11/site-packages/gradio/blocks.py", line 1554, in process_api result = await self.call_function( ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/privateGPT-venv/lib/python3.11/site-packages/gradio/blocks.py", line 1206, in call_function prediction = await utils.async_iteration(iterator) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/privateGPT-venv/lib/python3.11/site-packages/gradio/utils.py", line 517, in async_iteration return await iterator.**anext**() ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/privateGPT-venv/lib/python3.11/site-packages/gradio/utils.py", line 621, in asyncgen_wrapper async for response in f(*args, **kwargs): RuntimeError: async generator raised StopAsyncIteration

Did you ever find the solution to this?
