### ISSUE TITLE
Only using 2 CPU cores during inference? (GPU Enabled)

### ISSUE THREAD

**Issue by tseven** [imartinez/privateGPT#1106]
The other issues I found relating to CPU usage are back when GPT4ALL was being used.
I've compile privateGPT to use CUDA and have verified the layers are being loaded into the GPU.

When querying documents, it appears only 2 CPU cores are being used. Utilization is around 112-117%
![image](https://github.com/imartinez/privateGPT/assets/311287/af91d7e6-2c0f-4bae-bfcf-7303ca6df5c7)

I've added the "n_threads" to the kwargs object in `llm_component.py`, but I'm not seeing a difference in CPU usage.
```python
self.llm = LlamaCPP(
    model_path=str(models_path / settings.local.llm_hf_model_file),
    temperature=0.1,
    # llama2 has a context window of 4096 tokens,
    # but we set it lower to allow for some wiggle room
    context_window=3900,
    generate_kwargs={},
    
    # All to GPU
    model_kwargs={"n_gpu_layers": -1, "n_threads": 32},
    
    # transform inputs into Llama2 format
    messages_to_prompt=messages_to_prompt,
    completion_to_prompt=completion_to_prompt,
    verbose=True,
)
```

How can I allow this application to utilize more CPU cores?
Thanks

**Comment by imartinez** [comment]
@tseven I don't have an answer, this is an open topic. Here is an interesting related discussion
https://www.reddit.com/r/LocalLLaMA/comments/13wx0ws/thoughts_on_llamacpp_cpu_usage/

Please let us know your findings to improve the documentation (or open a PR yourself). 
Also, if this requires quite some back&forth and discussion, happy to meet you in the discord https://t.co/oG6wD1SFpi

**Comment by tseven** [comment]
Thanks for the reply @imartinez , I'll definitely share if I find a solution.
