### ISSUE TITLE
make ingest raises folder does not exist-unable to do bulk ingest

### ISSUE THREAD

**Issue by aminbaig** [imartinez/privateGPT#1115]
I am using the following command to bulk ingest pdf files:

**make ingest c:\ai\privateGPT\Extracted**

The folder named extracted has all the pdf files in it

When I run the above command I get the following error:

```
Traceback (most recent call last):
  File "C:\AI\privateGPT\scripts\ingest_folder.py", line 39, in <module>
    raise ValueError(f"Path {args.folder} does not exist")
ValueError: Path `arg=c:\ai\privateGPT\Extracted does not exist
make: *** [Makefile:52: ingest] Error 1
```

@imartinez  I am using windows 11 terminal, python 3.11.0. I am able to run gradio interface and privateGPT, I can also add single files from the web interface but the ingest command is driving me crazy.

Can someone please advise on whats wrong, is the ingest_folder broken or is it me???

**Comment by namp** [comment]
python scripts/ingest_folder.py FOLDERPATH

**Comment by aminbaig** [comment]
The above suggestion gives me the following error @namp 

```
C:\AI\privateGPT>python scripts/ingest_folder.py Extracted
Traceback (most recent call last):
  File "C:\AI\privateGPT\scripts\ingest_folder.py", line 5, in <module>
    from private_gpt.di import root_injector
ModuleNotFoundError: No module named 'private_gpt'

```

The folder is right there
![image](https://github.com/imartinez/privateGPT/assets/22371966/82924e3c-f0b8-42cd-a984-f9011de80174)

**Comment by namp** [comment]
privateGPT is not installed. Follow the installation guide in the docs

**Comment by aminbaig** [comment]
privateGPT is installed. I can run it using 

`poetry run python -m private_gpt`

I can also ingest signle documents using the gradio interface @namp

**Comment by aminbaig** [comment]
I was able to run the bulk ingest using:

`poetry run python scripts/ingest_folder.py Extracted`
