### ISSUE TITLE
Failed to build llama-cpp-python

### ISSUE THREAD

**Issue by sardosan** [imartinez/privateGPT#1116]
Hi guys,

I have a windows 11 with a GPU NVIDIA GeForce RTX 4050.
I have succesfully followed all the instructions, tips, suggestions, recomendations on the instruction documents to run the privateGPU locally with GPU. All perfect.

BUT
When i run

'$env:CMAKE_ARGS='-DLLAMA_CUBLAS=on'; poetry run pip install --force-reinstall --no-cache-dir llama-cpp-python'

it returns an error which is

`...
Building wheels for collected packages: llama-cpp-python
Building wheel for llama-cpp-python (pyproject.toml) ... error
error: subprocess-exited-with-error

× Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> [39 lines of output]
*** scikit-build-core 0.6.0 using CMake 3.28.0 (wheel)
*** Configuring CMake...
2023-10-26 14:48:44,231 - scikit_build_core - WARNING - Can't find a Python library, got libdir=None, ldlibrary=None, multiarch=None, masd=None
loading initial cache file C:\Users\matte\AppData\Local\Temp\tmp24zc9iet\build\CMakeInit.txt
-- Building for: Visual Studio 17 2022
-- The C compiler identification is MSVC 19.37.32825.0
-- The CXX compiler identification is MSVC 19.37.32825.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.42.0.windows.2")
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE
-- Found CUDAToolkit: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.3/include (found version "12.3.52")
-- cuBLAS found
CMake Error at C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:529 (message):
No CUDA toolset found.
Call Stack (most recent call first):
C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:8 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:53 (__determine_compiler_id_test)
C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCUDACompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID)
vendor/llama.cpp/CMakeLists.txt:290 (enable_language)

  -- Configuring incomplete, errors occurred!

  *** CMake configuration failed
  [end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects`

Could youplease help me understand how to fix? Nothing on internet solves this problem,

Thank you

**Comment by Jawn78** [comment]
Looks like you need to install the cuda toolkit

`CMake Error at C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:529 (message):
No CUDA toolset found.`

"Verify your installation is correct by running nvcc --version and nvidia-smi, and ensure your CUDA version is up to date, and your GPU is detected."

You may also need to add it to your path

**Comment by sardosan** [comment]
Hi @Jawn78 ,

I have the CUDA toolkit. In particular, I have the NVIDIA GPU computing toolkit installed on my machine (v 12.3), and I have 
`C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\bin`
in my path @system enviromental variable.

Any other options?

**Comment by sardosan** [comment]
What do you @Jawn78 say I have to add on the path?

**Comment by Jawn78** [comment]
@sardosan cuda_home to your environment path. If you have it installed, then it may juat not be able to be found. So setting the environment variable should fix that. 

https://stackoverflow.com/questions/69632875/cuda-path-not-detected-set-cuda-path-environment-variable-if-cupy-fails-to-load

**Comment by sardosan** [comment]
_ have it on the path bot of user and system.

Do you have any suggestion regarding the specific path of cuda toolkit I have to add to the path (user vs system)?

**Comment by Jawn78** [comment]
@sardosan I added Cuda to the variables and in the path.
![image](https://github.com/imartinez/privateGPT/assets/11069578/e0e916d2-3ae5-4708-87ad-1836f55dd3e8)

**Comment by rdavydov** [comment]
It is not the sys vars problem, four files need to be copied to solve the issue:

https://github.com/NVlabs/tiny-cuda-nn/issues/164#issuecomment-1280749170

https://github.com/NVlabs/tiny-cuda-nn/issues/164#issuecomment-1565014210
