### ISSUE TITLE
Proposal for update the README / Install instructions

### ISSUE THREAD

**Issue by PierreVannier** [imartinez/privateGPT#112]
Hey there, 
I've installed the project and it seems the note regarding putting the absolute path of the Llama embeddings model isn't necessary (at least on my install on an M1).
<img width="876" alt="image" src="https://github.com/imartinez/privateGPT/assets/4111871/879aeabc-999a-48bf-bffd-0d027e6dc6ec">

I've put just the following :
`LLAMA_EMBEDDINGS_MODEL=models/ggml-model-q4_0.bin`

Here's the output :
<img width="872" alt="image" src="https://github.com/imartinez/privateGPT/assets/4111871/46cbce23-eab2-4d0c-9e26-6e64c1ede5fc">

Is this mention still necessary ?

Also, on another point. It seems "pdfminer.six" is necessary for the ingestion to work. However it is not in the requirements.txt.
Am I wrong ?
Congrats for the good work !

**Comment by imartinez** [comment]
Just merged a PR solving the requirements piece, thanks for your input! About the model absolute path, I'll run some more tests on different environments, had the same result on Mac

**Comment by PierreVannier** [comment]
With pleasure !
