### ISSUE TITLE
The trained model is unable to find a correlation among trained documents

### ISSUE THREAD

**Issue by WadElla** [imartinez/privateGPT#1121]
I trained the model with 10 PDFs. When asked a question, the model gave an answer that was not right. To be more specific, all the trained PDFs had temperature readings. When asked what the maximum temperature was, the model answered, "I don't know," and gave all the respective temperature readings in the PDFs. I expected it to go through all the PDFs and provide the maximum temperature instead of giving the respective temperature readings. Is there a way to tweak the code to find a correlation between trained documents?

**Comment by maozdemir** [comment]
That's not the correct use case. This is for asking questions to a document, not doing data science with it. The way this works is by matching the keywords from the question in the document, especially names, so feeding raw data is not the best use scenario. For your use case, instead of feeding raw data, you can feed the "sentenceized" documents that contains the data, but still you shouldn't trust a text generator for math operations.

**Comment by Zirgite** [comment]
I also think that this LLM is not not data science, it will fail trying to inference information from data. I have another issue somewhat connected . I have problems with embeddings. I use with legal texts. The legal texts start with the article number and then they state the legal norm. So the legal article get separated from the legal norm and the model starts to hallucinate terribly. 
I did not have the same problem with the previous version where the model was correctly putting out the relevant legal texts. So the previous version of PrivateGPT was working according to expectations of course much less powerful than GPT4 :).

**Comment by namp** [comment]
Adding to this discussion I also find that indexing must be somehow broken. 

All the retrieved documents have the same similarity score (8.126234030636155e-43) and thus any of the retrieved documents would be as good as any other


```
{
    "object": "context.chunk",
    "score": 8.126234030636155e-43,
    "document": {
      "object": "ingest.document",
      "doc_id": "91f36cf9-c8b8-4486-a3d8-014e0089eb78",
      "doc_metadata": {
        "page_label": "3",
        "file_name": "jep.4.2.55.pdf",
        "doc_id": "91f36cf9-c8b8-4486-a3d8-014e0089eb78",
        "window": "Less common was a notion that stock prices had reached such a low level that a price\nincrease was to be expected...",
        "original_text": "Why do some people think that they can forecast the market on a day of a\nrecord price drop? "
      }
    },
    "text": "Why do some people think that they can forecast the market on a day of a\nrecord price drop? ",
    "previous_texts": [
      "The random walk theory of stock prices\nnow has some currency as a popular model, but other theories are still very much\naround. "
    ],
    "next_texts": [
      "Sometimes comparisons with past experience, particularly 1929,\nwere made. "
    ]
  },
  {
    "object": "context.chunk",
    "score": 8.126234030636155e-43,
    "document": {
      "object": "ingest.document",
      "doc_id": "b1c502e2-9467-4677-b92b-d7c7d99f65e9",
      "doc_metadata": {
        "page_label": "8",
        "file_name": "jep.4.2.55.pdf",
        "doc_id": "b1c502e2-9467-4677-b92b-d7c7d99f65e9",
        "window": "I have argued (1989a) that the underpricing reflects more than just\nthe asymmetric information theory that the underpricing is compensation for the...",
        "original_text": "The high initial return is viewed by many as a payment from\nunderwriters to investors for restricting their selling. "
      }
    },
    "text": "The high initial return is viewed by many as a payment from\nunderwriters to investors for restricting their selling. ",
    "previous_texts": [
      "For\none, there appears to be a common idea that IPO investors are serving underwriters\nby buying IPO's and not selling them for a while, providing a \"home\" and a stable\nprice for the issue and thereby ultimately inducing other investors to reduce their fears\nabout the issue. "
    ],
    "next_texts": [
      "For another, there appears to be\nan idea that underwriters should charge \"fair\" prices for issues, even when they could\nobtain a lot more, but underwriters can expect to be repaid for selling at below-market\nprices by subsequent business from those who obtained allocations in underpriced\nissues. "
    ]
  }
]
```
