### ISSUE TITLE
Failed to retrieve model

### ISSUE THREAD

**Issue by eyadayman12** [imartinez/privateGPT#1122]
Hello,
 
My code was running yesterday and it was awsome 

But it gave me errors when I executed it today, I haven't change anything, the same code was running yesterday but now it is not

my code:

```
from langchain.llms import GPT4All
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain

PATH = "wizardlm-13b-v1.2.Q4_0.gguf" model is in the same dir as my python file
promptTemp = PromptTemplate(input_variables=['action'],
                                template="Complete this task {action}")
llm = GPT4All(model=PATH, verbose=True, temp=0.1, n_predict = 4096, top_p=0.95, top_k=40, n_batch=9, repeat_penalty=1.1)
chain = LLMChain(prompt=promptTemp, llm=llm)
```
        
 error is in this line `llm = GPT4All(model=PATH)`
 
 here is the error:
```
 File "D:\anaconda3\envs\AI\Lib\site-packages\pydantic\v1\main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for GPT4All
__root__
  Failed to retrieve model (type=value_error)
```

Another error appears when I did a slight modification which is changing the PATH variable from this `PATH = "wizardlm-13b-v1.2.Q4_0.gguf" to this PATH = "D:/Text_Generator/wizardlm-13b-v1.2.Q4_0.gguf"`

here is the error:

```
File "D:\anaconda3\envs\AI\Lib\site-packages\pydantic\v1\main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for GPT4All
__root__
  Unable to instantiate model: code=129, Model format not supported (no matching implementation found) (type=value_error)
```

the model was working yesterday but suddenly I run the same code today it gives me this errors I don't know why I haven't changed anything I am disappointed

```
python version: 3.11.5
gt4all version: 2.0.1
```

**Comment by pabloogc** [comment]
I think you are using the old version of PrivateGPT, can you give it a go with the current version in the main branch?

**Comment by eyadayman12** [comment]
> I think you are using the old version of PrivateGPT, can you give it a go with the current version in the main branch?

I made a mistake of posting this here in privateGPT because I am using gpt4all not privateGPT
