### ISSUE TITLE
LLM mock donot gives any output

### ISSUE THREAD

**Issue by ammarasimeurus** [imartinez/privateGPT#1125]
i have downloaded the llm models 

used this 
poetry install --with local
poetry run python scripts/setup

still i get this output 
![Screenshot from 2023-10-27 23-50-34](https://github.com/imartinez/privateGPT/assets/148402457/201b18f9-c269-40e4-99c5-a22fd3b9366d)

**Comment by xoreg93** [comment]
same issue here

**Comment by lopagela** [comment]
Apparently, this is because you are running in `mock` mode (c.f. your screenshot), you need to run privateGPT with the environment variable `PGPT_PROFILES` set to `local` (c.f. [documentation](https://docs.privategpt.dev/#section/Quick-Local-Installation-steps))

If you are on windows, please note that command such as `PGPT_PROFILES=local make run` will not work; you have to instead do
```
# Set the env var PGPT_PROFILES to local
set PGPT_PROFILES=local

# Run privateGPT
make run
```

**Comment by xoreg93** [comment]
> Apparently, this is because you are running in `mock` mode (c.f. your screenshot), you need to run privateGPT with the environment variable `PGPT_PROFILES` set to `local` (c.f. [documentation](https://docs.privategpt.dev/#section/Quick-Local-Installation-steps))
> 
> If you are on windows, please note that command such as `PGPT_PROFILES=local make run` will not work; you have to instead do
> 
> ```
> # Set the env var PGPT_PROFILES to local
> set PGPT_PROFILES=local
> 
> # Run privateGPT
> make run
> ```

not working tried the you described


![image](https://github.com/imartinez/privateGPT/assets/149203995/1d49e2a0-5e77-4645-a68e-b08129c1a021)

![image](https://github.com/imartinez/privateGPT/assets/149203995/38790b7e-4dd3-4225-be6b-0cc6e9a660ad)

**Comment by lopagela** [comment]
Ok, let's do something to unblock you: modify the file `settings.yaml`, and set the YAML property `llm.mode: local` (instead of `mock`)

**Comment by xoreg93** [comment]
thanks allot man it worked
![image](https://github.com/imartinez/privateGPT/assets/149203995/e3cd712b-2656-46c5-8017-bb901fc286d9)
![image](https://github.com/imartinez/privateGPT/assets/149203995/e33baa7b-fcc6-4c88-85f0-05bcb4f6bb74)

**Comment by xoreg93** [comment]
lastly please advice me how to use different models?

**Comment by lopagela** [comment]
@xoreg93 you have to download your models in `models/`, and change your configuration (`settings.yml` in your case) accordingly.

You might find more help in the `README` / [documentation](https://docs.privategpt.dev/), or on the discord of this project.

**Comment by haymoreb** [comment]
Can this be added to the main installation documentation? I've spent hours trying to find out why the line "PGPT_PROFILES=local make run" would not work on windows. The solution is incredibly simple and seems like it should exist somewhere in the main instructions.

**Comment by imartinez** [comment]
The information is in the docs. I'd say the problem is the env var setting on Windows. We'll look into improving it. Thanks!

**Comment by haymoreb** [comment]
> The information is in the docs. I'd say the problem is the env var setting on Windows. We'll look into improving it. Thanks!

When I search the documentation, the following code, which is required to start this on Windows, is not anywhere. The concept of doing this is in the documentation currently, but how to execute it on Windows is not.
```
# Set the env var PGPT_PROFILES to local
set PGPT_PROFILES=local

# Run privateGPT
make run
```
