### ISSUE TITLE
Addding code of conduct & Contributing.md file to repo!

### ISSUE THREAD

**Issue by mohitd404** [imartinez/privateGPT#1126]
code-of-conduct:- We propose adding a comprehensive Code of Conduct to our repository to ensure 
a safe, respectful, and inclusive environment for all contributors and users. This code will 
serve as a guideline for behavior, promoting diversity, reducing conflicts, and attracting a 
wider range of perspectives.

Contributing.md:- A "Contributing.md" file is added to a repository to provide guidelines and 
instructions for potential contributors on how to collaborate effectively with the project. 
It typically includes information on coding standards, how to submit changes, reporting issues, 
and other important details to streamline the contribution process and maintain a healthy
open-source community.

**Issue type**

[✅] Docs

@ Kindly assign this issue to me ! I would love to work on it ! Thank You !

**Comment by imartinez** [comment]
We don't see a need for those sections at the moment. Thanks a lot, and keep the ideas coming!
