### ISSUE TITLE
Adding Contributors section to the readme.md !

### ISSUE THREAD

**Issue by mohitd404** [imartinez/privateGPT#1127]
Why Contributors section:- A "Contributors" section in a repo gives credit to and acknowledges 
the people who have helped with the project, fosters a sense of community, and helps others
 know who to contact for questions or issues related to the project.

**Issue type**

- [✅] Docs

  kindly assign this issue to me ! I would love to work on it ! Thank you !

**Comment by imartinez** [comment]
There is a contributors section already, automatically populated in the side bar of Github. We are also giving a special role to active contributors in Discord. We'll go with that for the moment. Thanks!
