### ISSUE TITLE
RuntimeError: Your system has an unsupported version of sqlite3. Chroma requires sqlite3 >= 3.35.0.

### ISSUE THREAD

**Issue by ChanJoon** [imartinez/privateGPT#1130]
**Problem** 
When running local server, following error occured
```bash
PGPT_PROFILES=local make run
# Error occured
# RuntimeError: Your system has an unsupported version of sqlite3. Chroma requires sqlite3 >= 3.35.0.
```

**How to solve**

1. In `~/.cache/pypoetry/virtualenvs/private-gpt-7vtKm_EZ-py3.11/lib/python3.11/site-packages/chromadb/__init__.py`, add 
	```python
	__import__('pysqlite3')
	import sys
	sys.modules['sqlite3'] = sys.modules.pop('pysqlite3')
	```
	at the beginning. [Reference 1](https://docs.trychroma.com/troubleshooting#sqlite) and [2](https://gist.github.com/defulmere/8b9695e415a44271061cc8e272f3c300)

2. Update poetry configuration
	`poetry add pysqlite3-binary`

**Comment by imartinez** [comment]
Thanks for sharing! We'll add it to the troubleshooting section and then close the issue
