### ISSUE TITLE
Add support for `InstructorEmbeddings` embedding models

### ISSUE THREAD

**Issue by chamaoskurumi** [imartinez/privateGPT#1138]
Currently, privateGPT only allows embeddings models to be loaded via `from llama_index.embeddings import HuggingFaceEmbedding`, see the `EmbeddingComponent` class [here](https://github.com/imartinez/privateGPT/blob/5d1be6e94c0de136f6138b86ef2c67b990679649/private_gpt/components/embedding/embedding_component.py#L19).

But Llama Index does also allow `InstructorEmbedding` models, as the [doc claims](https://gpt-index.readthedocs.io/en/latest/examples/embeddings/huggingface.html#instructorembedding). They are really powerful :muscle: 

### Suggestion

Because instructor models such as  [`hkunlp/instructor-large`](https://huggingface.co/hkunlp/instructor-large) are really powerful, it would be cool to add something like the following the [`EmbeddingComponent` class](https://github.com/imartinez/privateGPT/blob/5d1be6e94c0de136f6138b86ef2c67b990679649/private_gpt/components/embedding/embedding_component.py#L19).

```python
from llama_index.embeddings import (
    HuggingFaceEmbedding,
    InstructorEmbedding,
)

if "instructor" in settings.local.embedding_hf_model_name:
    self.embedding_model = InstructorEmbedding(
        model_name=settings.local.embedding_hf_model_name,
        cache_folder=str(models_cache_path),
    )
else:
    self.embedding_model = HuggingFaceEmbedding(
        model_name=settings.local.embedding_hf_model_name,
        cache_folder=str(models_cache_path),
    )
```

Obviously  `InstructorEmbedding = "1.0.1"` would have to be added to the `pyproject.toml`, too.

**Comment by kalleutschie** [comment]
Hi, love your project! Does the instructor model work now?
