### ISSUE TITLE
Tried to run privateGPT and got an error: uvicorn.error - Started server process [16140]

### ISSUE THREAD

**Issue by ForwardForward** [imartinez/privateGPT#1146]
Hello !

Thank you for your work !

Tried to run privateGPT and got an error:

I have Windows 11. 

I did everything according to the instructions by link https://docs.privategpt.dev/#section/Introduction

After that I ran the command: 
poetry run python -m private_gpt

And got the error:

(private-gpt-py3.11) E:\privateGPT>poetry run python -m private_gpt
18:22:52.127 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default']
18:22:53.947 [INFO    ] chromadb.telemetry.product.posthog - Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
18:22:56.181 [INFO    ]             uvicorn.error - Started server process [16140]
18:22:56.182 [INFO    ]             uvicorn.error - Waiting for application startup.
18:22:56.182 [INFO    ]             uvicorn.error - Application startup complete.
18:22:56.183 [INFO    ]             uvicorn.error - Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)

Before that I had an error on executing pyenv install 3.11 command.
I got the answer that there is no such version. Installed version 3.11.4 and fixed the lock file.

After that I executed the poetry lock command. That fixed all the dependencies.

**Comment by ForwardForward** [comment]
As far as I understand, the address http://0.0.0.0:8001 should open the privateGPT interface, but when opening this address in a browser, nothing opens there.

**Comment by louis-jaris** [comment]
The uvicorn logs are indeed misleading; the logger uvicorn.error indeed is misnamed. The logs of this logger are indicating server and http activity

Regarding the host, 0.0.0.0 will not work, only 127.0.0.1 will; try with http://127.0.0.1:8001

**Comment by pabloogc** [comment]
@louis-jaris is right on point, will close this issue.

Something went wrong with uvicorn log, it shouldn't show as error, in fact just the left it says info, as it should. 

On the topic `http://0.0.0.0:8001/` means it's accepting connections from any host, but it's indeed running in `localhost:8001` or `127.0.0.1:8001` (same thing)

**Comment by Petterson19** [comment]
> The uvicorn logs are indeed misleading; the logger uvicorn.error indeed is misnamed. The logs of this logger are indicating server and http activity
> 
> Regarding the host, 0.0.0.0 will not work, only 127.0.0.1 will; try with http://127.0.0.1:8001

Oh my God dude! You've no idea how helpful you were to me, I was stucked in this stupid error for days
