### ISSUE TITLE
Want to switch back to using CPU

### ISSUE THREAD

**Issue by rmuhawieh** [imartinez/privateGPT#1155]
I ran the command $env:CMAKE_ARGS='-DLLAMA_CUBLAS=on'; poetry run pip install --force-reinstall --no-cache-dir llama-cpp-python in order to utilize the GPU but I'd like to switch back to simply using the CPU but not sure how to reconfigure llama to do so.

Can someone assist me with this please?

**Comment by tpiekarski** [comment]
It's just for people finding this and also wondering how to switch back from GPU to CPU (like me).

Just pass a `-DLLAMA_CUBLAS=off`to cmake via CMAKE_ARGS environment variable. Like this:
`CMAKE_ARGS='-DLLAMA_CUBLAS=off' poetry run pip install --force-reinstall --no-cache-dir llama-cpp-python`.
