### ISSUE TITLE
PrivateGPT concurrent usage for querying the document

### ISSUE THREAD

**Issue by BennisonDevadoss** [imartinez/privateGPT#1157]
I've been trying out PrivateGPT recently, mainly using its API. I've encountered an issue when multiple requests are made to the `/v1/completions` endpoint simultaneously, resulting in a "core dumped" error.

I've provided a snapshot for reference here:
![image](https://github.com/imartinez/privateGPT/assets/89965371/5a9fcee6-e1e2-46f4-b367-4c76982d00e2)

I'm curious to understand why concurrent document querying doesn't work and what's causing this "segmentation fault core dumped" error. I've deployed PrivateGPT on Google Cloud Service (GCS) with the following system configuration:

**System Configuration**
- GPU type: NVIDIA T4
- Number of GPUs: 1
- CPU: AMD processor with 8 cores
- RAM: 60GB
- Machine type: C2D (optimized for high performance and less computationally intensive workloads)

From the above configuration, I know that I set up PrivateGPT on a powerful machine configuration, but I still encountered the issue with the "segmentation fault (core dumped)" error.

I have two key questions:

1. Is the problem related to my machine's configuration, specifically the CPU and GPU?
2. Can PrivateGPT handle concurrent document querying?

If anyone has insights or solutions, please guide me in resolving this matter.

**Comment by AnandMoorthy** [comment]
@BennisonDevadoss Have you got any workaround for this? facing same issue.
