### ISSUE TITLE
I make it work locally but can't complete settings file 

### ISSUE THREAD

**Issue by aboda28** [imartinez/privateGPT#1160]
I did setup it and its work locally now 
how I can mange settings and put API Key

idid put pdf files but I think its not give me any information of files and that what I get 

user: hi
assistant: system: Context information is below.
•What would be the time line?
•Which subscriptions do I need to get for you
•Which API’s do you need
•What is your hourly rate? Or do you work in sprints?
•What would you expect to be the operational costs of
everything?
•Running server (which size do we need?)
•OneDrive
•API costs
•Other costs which I don’t know?
Chatbot
Personal
Assistant (PA)
Gather all documentation , internet knoledge , personal knowledge from files,
spoken messages , video’s and tekst input to build database.
Based on this information, chatbot need to provide answers .
Goal: working as efficient as possible and don’t forget any conversation
![Uploading Screenshot 2023-11-02 at 9.49.02 PM.png…]()

**Comment by aboda28** [comment]
I hope any one answer as soon as u can

**Comment by imartinez** [comment]
In the UI, check the chat label in the top left of the chat interface. What does the label say? Chat: mock? Or chat: local?

**Comment by aboda28** [comment]
hello thanx for answer 
im installing it again now 
and after I install it will tell you if its work or no 
but I have question 
is that ok to install python normally as app from website idid have 3.12
or its supposed do do it from pyenv ?

**Comment by aboda28** [comment]
> In the UI, check the chat label in the top left of the chat interface. What does the label say? Chat: mock? Or chat: local?

hello idid install every thing again but when I write any thing its give me every thing inside pdf file not just answer me about the thing I want 
to be know also CHAT:mock

**Comment by aboda28** [comment]
its happen when try to write any thing 
![Uploading Screen Shot 2023-11-04 at 5.58.17 PM.png…]()

**Comment by jackfood** [comment]
if i am not wrong, need to change to `chat: Local `in the setting.yaml

**Comment by aboda28** [comment]
> if i am not wrong, need to change to `chat: Local `in the setting.yaml

Ok but how can change it
