### ISSUE TITLE
How can I run the code?

### ISSUE THREAD

**Issue by chosenpm** [imartinez/privateGPT#1162]
from private_gpt.paths import docs_path
ModuleNotFoundError: No module named 'private_gpt'

When I run the main.py I get the above error.
I have installed all libraries (i think) and downlaoded cuda as well.

Thank you in advance! 😃

**Comment by lopagela** [comment]
Please read the documentation: https://docs.privategpt.dev/

As stated in the documentation, one should start `privateGPT` by using `python -m private_gpt` (with your venv activated if necessary).

For advanced usage (e.g. running in an IDE), the entrypoint is `private_gpt/__main__.py`

**Comment by chosenpm** [comment]
Hello!
But it keeps saying no module name private_gpt

**Comment by lopagela** [comment]
```bash
# Go in this git repo cloned on your computer
cd privateGPT/

# Activate your venv if you have one
source foo_bar/bin/activate

# Launch private GPT, or in another words, launch `private_gpt/__main__.py`
python -m private_gpt
```

Your position in your FS (i.e. where you are; what `pwd` returns) is important for python to resolve the `import`.

---

The issue you are having is common and not specific to `privateGPT` -- try to do some research online on this subject

**Comment by argEEai** [comment]
I ran into same exact issue.  all I did was re-run the `poetry install --with ui,local` command
and it worked.  i'm on ubuntu-unity 22.04.  hope this helps.

**Comment by dr-thax** [comment]
To ensure Python recognizes the `private_gpt` module in your `privateGPT` directory, add the path to your PYTHONPATH environment variable. 
Use the command `export PYTHONPATH="${PYTHONPATH}:/path/to/your/privateGPT/private_gpt"`.
Then run again: poetry run python scripts/setup
