### ISSUE TITLE
Getting missing modules errors during ingestion

### ISSUE THREAD

**Issue by zono50** [imartinez/privateGPT#1164]
Good morning, when I run the make ingest --path --watch, it will load some documents, but others it will give me errors saying Error: Please install extra dependencies that ar required for the ImageCaptionReader: `pip install torch transformers sentencepiece Pillow, and also pip install EbookLib html2text. I've tried both a conda and a pyenv local directory, and verified they were installed with pip freeze, but still complains. Wondering if this is a bug or not. OS is Manjaro Linux, on latest nvidia drivers and Kernel

![Uploading image.png…]()

**Comment by unalignedcoder** [comment]
same error here while scanning a pdf folder. 

never had a completed ingestion so far that wasn't interrupted by one or another exception.

**Comment by simwai** [comment]
Get the same error...
