### ISSUE TITLE
warnings.warn("Can't initialize NVML")

### ISSUE THREAD

**Issue by zhimin-z** [imartinez/privateGPT#1168]
When I first launch the app, it gives the following warning: 
```
/home/21zz42/L-factor/app/localGPT/.venv/lib/python3.10/site-packages/torch/cuda/__init__.py:611: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
```
Any idea?
I am using Ubuntu 20.04 with Python 3.10.12.

**Comment by pabloogc** [comment]
Most likely pytorch is not detecting your GPU. We can't help with that, but you can try asking opening an issue there: https://github.com/pytorch/pytorch
