### ISSUE TITLE
"Error: [Errno 21] Is a directory:" when I  add a directory shortcut to wactching folder

### ISSUE THREAD

**Issue by yaziciali** [imartinez/privateGPT#1170]
Hi,
I get this errors when ingest is watching new files, I added directories (with ln -s)
When I interrupt and start again it is started.

08:01:15.756 [INFO    ]                  __main__ - Completed ingesting SRC/ou/File.txt
08:01:15.762 [INFO    ]                  __main__ - Watching SRC for changes, press Ctrl+C to stop...
08:02:56.524 [INFO    ]                  __main__ - **Started ingesting /Users/ayazici/privateGPT/SRC/DOCS
08:02:56.526 [ERROR   ]                  __main__ - Failed to ingest document: /Users/ayazici/privateGPT/SRC/DOCS. Error: [Errno 21] Is a directory: '/Users/ayazici/privateGPT/SRC/DOCS'**
08:03:43.864 [INFO    ]                  __main__ - **Started ingesting /Users/ayazici/privateGPT/SRC/BOOK
08:03:43.865 [ERROR   ]                  __main__ - Failed to ingest document: /Users/ayazici/privateGPT/SRC/BOOK. Error: [Errno 21] Is a directory: '/Users/ayazici/privateGPT/SRC/BOOK'**
^C
ayazici@Alis-MacBook-Pro privateGPT % make ingest SRC -- --watch --log-file LOG/ingest_v2.log
08:07:08.332 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default']
08:07:16.878 [INFO    ]                  __main__ - Document 1 of 4480 (0.02%)

**Comment by pabloogc** [comment]
This seems like a bug in our file watcher not filtering properly, I'll try to reproduce it.
