### ISSUE TITLE
AWS g4dn(GPU T4) only 800M VRAM used ?

### ISSUE THREAD

**Issue by garyng2000** [imartinez/privateGPT#1173]
I am testing the setup using an AWS g4dn xlarge instance. It worked after pip install the GPU capable llama python module. Though nvidia-smi shows only 800MB of VRAM is used out of the 16G available.

is that normal ? and the query is still a bit slow(I haven't ingested anything, just the base model) like 100s plus to get the result of a query.

[ec2-user@ip-172-31-7-27 ~]$ nvidia-smi
Mon Nov  6 17:40:30 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.89.02    Driver Version: 525.89.02    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:1E.0 Off |                    0 |
| N/A   27C    P0    27W /  70W |    857MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     14635      C   ...hatgpt/venv311/bin/python      852MiB |
+-----------------------------------------------------------------------------+

**Comment by gravitypushes** [comment]
Did you ever solve this?
