### ISSUE TITLE
Auto Ingest API

### ISSUE THREAD

**Issue by JustNello** [imartinez/privateGPT#1178]
Hello,
thank you for your work with this project ;)

**[This is a feature proposal]**
Assuming the user is running privateGPT locally, it would be nice to have an high-level API to start auto-ingest files from a directory.
User could select one or more directories to auto-ingest from the Gradio UI, instead of uploading file-by-file manually.
Note that the auto-ingest feature I'm talking about is already implemented within the "ingest_folder.py" script, so the code could be moved out of the "script" folder, so that the "IngestService" instance would be shared by routes, ui and the IngestWatcher, that is responsable for auto-ingesting a folder.

I'd be happy to implement such feature. However, my assumptions may be wrong and there is a chance this has been already discussed, my apologies in advance if that's the case.

**Comment by pabloogc** [comment]
We have discussed it but it's not in our short term task list, so feel free to work start working it. It's a feature a lot of people will make good use for (and more convenient than a script)

**Comment by Kaotic3** [comment]
Here is a script that will ingest all the data from a CSV file.

I am not suggesting that this is the best script ever written - but if you have a lot of files that you can read into a CSV - then this should automate the ingest to the API.

```
import pandas as pd
import requests
from io import BytesIO

dataframe_path = 'your_csv.csv'
df = pd.read_csv(dataframe_path)

url = 'http://localhost:8001/v1/ingest'

for index, row in df.iterrows():
    text_file = BytesIO(row['text_column'].encode())
    files = {'file': (f"{row['ID']}.txt", text_file)}
    response = requests.post(url, files=files)
    if response.status_code == 200:
        print(f"Success for row {index}: {response.json()}")
    else:
        print(f"Error for row {index}: {response.text}")
    text_file.close()
```

**Comment by lopagela** [comment]
@JustNello we recently changed the `gradio` interface, and now you can upload multiple files at the same time : https://github.com/imartinez/privateGPT/pull/1271

We are also working on speeding up the ingestion: https://github.com/imartinez/privateGPT/pull/1279

---

Does being able to ingest multiple files solving your use case?

**Comment by JustNello** [comment]
@lopagela The ability to ingest multiple files helps. I'll use it for the initial use case that involved the user to select one or more target directories once and have the application auto-detecting file changes, to upload them again. A script to monitor any file changes and trigger the privateGPT-API accordingly should do the job.
