### ISSUE TITLE
Combine PrivateGPT with Memgpt

### ISSUE THREAD

**Issue by dality17** [imartinez/privateGPT#1187]
if you add memgpt into this. This project wil be unstoppable.

**Comment by devosonder** [comment]
I think this development is very important for the project. I think the best way to overcome the token limits at the moment is to use memGPT. memGPT licence is Apache License 2.0.

**Comment by lopagela** [comment]
That would be a great contribution! 😄 

Conceptually, this is feasible, the concepts are matching; one "just" have to integrate memgpt in privateGPT 🤔

**Comment by schacki** [comment]
Any comments, if this is feasible and realistic to be put on the roadmap would be helpful.

**Comment by fyyyyy** [comment]
privateGPT and memGPT both use llamaindex as the RAG pipeline. I don't see how an integration would bring any benefit?
https://github.com/cpacker/MemGPT/blob/8f178e18ca687e2056a30b30422122f0752751c9/docs/data_sources.md?plain=1#L76
