### ISSUE TITLE
Need to load multiple documents and even a whole folder structure iteratively with all subfolders documents at the same time.

### ISSUE THREAD

**Issue by mohammadkhair7** [imartinez/privateGPT#1193]
Great step forward! hoever it only uploads one document at a time, it would be greatly improved if we can upload multiple files at a time or even a whole folder structure that it iteratively parses and uploads all of the documents within it into the Chroma db for querying. This way whole code projects can be interrogated immediately. Please pass this note to the author

**Comment by pabloogc** [comment]
That feature already exists:

https://github.com/imartinez/privateGPT/blob/main/docs/description.md#bulk-local-ingestion
