### ISSUE TITLE
It seems that it does not have access to the local large language model.

### ISSUE THREAD

**Issue by Reno0vacio** [imartinez/privateGPT#1199]
I selected the "LLM Chat" function, and it only returned this response:

_user: hello
assistant: user: hello
assistant: 
user: hello what is your name?
assistant:_ 

Info:
OS: Windows 11
ENV: Conda
PYTHON: 3.11

**Command to run: poetry run python -m private_gpt**

> (privategpt) PS D:\a.I\privateGPT> set PGPT_PROFILES= local   
(privategpt) PS D:\a.I\privateGPT> poetry run python -m private_gpt
11:14:01.311 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default']
11:14:11.921 [INFO    ]             uvicorn.error - Started server process [18612]
11:14:11.921 [INFO    ]             uvicorn.error - Waiting for application startup.
11:14:11.922 [INFO    ]             uvicorn.error - Application startup complete.
11:14:11.922 [INFO    ]             uvicorn.error - Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
11:14:33.727 [INFO    ]            uvicorn.access - 127.0.0.1:55245 - "GET / HTTP/1.1" 200
11:14:33.792 [INFO    ]            uvicorn.access - 127.0.0.1:55245 - "GET /assets/index-a959df42.js HTTP/1.1" 200
11:14:33.860 [INFO    ]            uvicorn.access - 127.0.0.1:55245 - "GET /assets/index-5ac12191.css HTTP/1.1" 200
11:14:34.180 [INFO    ]            uvicorn.access - 127.0.0.1:55245 - "GET /info HTTP/1.1" 200
11:14:34.303 [INFO    ]            uvicorn.access - 127.0.0.1:55245 - "GET /theme.css HTTP/1.1" 200
11:14:34.303 [INFO    ]            uvicorn.access - 127.0.0.1:55246 - "GET /assets/Button-dd3ccceb.css HTTP/1.1" 200
11:14:34.306 [INFO    ]            uvicorn.access - 127.0.0.1:55245 - "GET /assets/Blocks-0733f3b3.css HTTP/1.1" 200
11:14:34.309 [INFO    ]            uvicorn.access - 127.0.0.1:55246 - "GET /assets/Blocks-14eb0294.js HTTP/1.1" 200
11:14:34.311 [INFO    ]            uvicorn.access - 127.0.0.1:55245 - "GET /assets/Button-fb0eed2f.js HTTP/1.1" 200
11:14:34.742 [INFO    ]            uvicorn.access - 127.0.0.1:55245 - "GET /assets/index-93c91554.css HTTP/1.1" 200
11:14:34.753 [INFO    ]            uvicorn.access - 127.0.0.1:55246 - "GET /assets/index-329f8260.css HTTP/1.1" 200
11:14:34.754 [INFO    ]            uvicorn.access - 127.0.0.1:55250 - "GET /assets/StaticColumn-2853eb31.css HTTP/1.1" 200
11:14:34.754 [INFO    ]            uvicorn.access - 127.0.0.1:55251 - "GET /assets/index-6bb91bb9.js HTTP/1.1" 200
11:14:34.768 [INFO    ]            uvicorn.access - 127.0.0.1:55252 - "GET /assets/index-8f637a36.js HTTP/1.1" 200
11:14:34.769 [INFO    ]            uvicorn.access - 127.0.0.1:55245 - "GET /assets/index-2c0d26e2.js HTTP/1.1" 200
11:14:34.778 [INFO    ]            uvicorn.access - 127.0.0.1:55251 - "GET /assets/UploadButton-03d58ab8.css HTTP/1.1" 200
11:14:34.779 [INFO    ]            uvicorn.access - 127.0.0.1:55246 - "GET /assets/Radio-38bb7cb5.css HTTP/1.1" 200
11:14:34.780 [INFO    ]            uvicorn.access - 127.0.0.1:55245 - "GET /assets/index-33bad8d4.css HTTP/1.1" 200
11:14:34.781 [INFO    ]            uvicorn.access - 127.0.0.1:55250 - "GET /assets/StaticMarkdown-1e08a987.css HTTP/1.1" 200       
11:14:34.781 [INFO    ]            uvicorn.access - 127.0.0.1:55252 - "GET /assets/Table-6d6f4ad8.css HTTP/1.1" 200
11:14:34.791 [INFO    ]            uvicorn.access - 127.0.0.1:55251 - "GET /assets/Textbox-dde6f8cc.css HTTP/1.1" 200
11:14:34.791 [INFO    ]            uvicorn.access - 127.0.0.1:55246 - "GET /assets/index-37519934.css HTTP/1.1" 200
11:14:34.793 [INFO    ]            uvicorn.access - 127.0.0.1:55250 - "GET /assets/StaticForm-3812b7f1.css HTTP/1.1" 200
11:14:34.794 [INFO    ]            uvicorn.access - 127.0.0.1:55252 - "GET /assets/index-de90ac30.js HTTP/1.1" 200
11:14:34.799 [INFO    ]            uvicorn.access - 127.0.0.1:55245 - "GET /assets/StaticColumn-e8db0143.js HTTP/1.1" 200
11:14:34.814 [INFO    ]            uvicorn.access - 127.0.0.1:55251 - "GET /assets/Radio-c0787ae8.js HTTP/1.1" 200
11:14:34.816 [INFO    ]            uvicorn.access - 127.0.0.1:55252 - "GET /assets/Info-91922efa.js HTTP/1.1" 200
11:14:34.817 [INFO    ]            uvicorn.access - 127.0.0.1:55246 - "GET /assets/BlockTitle-a5d1fe95.js HTTP/1.1" 200
11:14:34.818 [INFO    ]            uvicorn.access - 127.0.0.1:55245 - "GET /assets/UploadButton-9c064533.js HTTP/1.1" 200
11:14:34.818 [INFO    ]            uvicorn.access - 127.0.0.1:55250 - "GET /assets/index-cd7758bf.js HTTP/1.1" 200
11:14:34.846 [INFO    ]            uvicorn.access - 127.0.0.1:55252 - "GET /assets/Table-b4406f17.js HTTP/1.1" 200
11:14:34.851 [INFO    ]            uvicorn.access - 127.0.0.1:55251 - "GET /assets/index-1b34192d.js HTTP/1.1" 200
11:14:34.855 [INFO    ]            uvicorn.access - 127.0.0.1:55246 - "GET /assets/index-2f00b72c.js HTTP/1.1" 200
11:14:34.858 [INFO    ]            uvicorn.access - 127.0.0.1:55245 - "GET /assets/utils-c3e3db58.js HTTP/1.1" 200
11:14:34.865 [INFO    ]            uvicorn.access - 127.0.0.1:55250 - "GET /assets/Upload-4d8da01b.js HTTP/1.1" 200
11:14:34.891 [INFO    ]            uvicorn.access - 127.0.0.1:55252 - "GET /assets/StaticMarkdown-06312fb7.js HTTP/1.1" 200
11:14:34.897 [INFO    ]            uvicorn.access - 127.0.0.1:55251 - "GET /assets/dsv-576afacd.js HTTP/1.1" 200
11:14:34.898 [INFO    ]            uvicorn.access - 127.0.0.1:55246 - "GET /assets/index-5a99b9f7.js HTTP/1.1" 200
11:14:34.906 [INFO    ]            uvicorn.access - 127.0.0.1:55250 - "GET /assets/IconButton-a920ab53.js HTTP/1.1" 200
11:14:34.906 [INFO    ]            uvicorn.access - 127.0.0.1:55245 - "GET /assets/ShareButton-cdf33464.js HTTP/1.1" 200
11:14:34.925 [INFO    ]            uvicorn.access - 127.0.0.1:55252 - "GET /assets/index-aaf62f38.js HTTP/1.1" 200
11:14:34.927 [INFO    ]            uvicorn.access - 127.0.0.1:55251 - "GET /assets/Copy-76383fd2.js HTTP/1.1" 200
11:14:34.928 [INFO    ]            uvicorn.access - 127.0.0.1:55246 - "GET /assets/BlockLabel-5f053d92.js HTTP/1.1" 200
11:14:34.948 [INFO    ]            uvicorn.access - 127.0.0.1:55250 - "GET /assets/index-4594c4cd.js HTTP/1.1" 200
11:14:34.950 [INFO    ]            uvicorn.access - 127.0.0.1:55245 - "GET /assets/InteractiveTextbox-8c4d1407.js HTTP/1.1" 200    
11:14:34.953 [INFO    ]            uvicorn.access - 127.0.0.1:55251 - "GET /assets/index-e75b4bc3.js HTTP/1.1" 200
11:14:34.955 [INFO    ]            uvicorn.access - 127.0.0.1:55252 - "GET /assets/Textbox-8e45e7cb.js HTTP/1.1" 200
11:14:34.957 [INFO    ]            uvicorn.access - 127.0.0.1:55246 - "GET /assets/index-e5090eed.js HTTP/1.1" 200
11:14:34.964 [INFO    ]            uvicorn.access - 127.0.0.1:55251 - "GET /assets/StaticForm-0d359fd6.js HTTP/1.1" 200
11:14:34.971 [INFO    ]            uvicorn.access - 127.0.0.1:55245 - "GET /assets/api-logo-5346f193.svg HTTP/1.1" 200
11:14:34.974 [INFO    ]            uvicorn.access - 127.0.0.1:55250 - "GET /assets/index-08631e7e.js HTTP/1.1" 200
11:14:34.977 [INFO    ]            uvicorn.access - 127.0.0.1:55252 - "GET /assets/logo-0a070fcf.svg HTTP/1.1" 200
11:14:36.767 [INFO    ]            uvicorn.access - 127.0.0.1:55252 - "GET /favicon.ico HTTP/1.1" 200
11:14:45.406 [INFO    ]            uvicorn.access - 127.0.0.1:55255 - "POST /run/predict HTTP/1.1" 200
11:14:45.411 [INFO    ]            uvicorn.access - 127.0.0.1:55255 - "POST /run/predict HTTP/1.1" 200
11:14:45.420 [INFO    ]            uvicorn.access - 127.0.0.1:55255 - "POST /run/predict HTTP/1.1" 200
11:14:45.750 [INFO    ]             uvicorn.error - ('127.0.0.1', 55268) - "WebSocket /queue/join" [accepted]
11:14:45.751 [INFO    ]             uvicorn.error - connection open
** Prompt: **
user: hello
assistant:
**************************************************
** Completion: **
user: hello
assistant:
**************************************************

** Messages: **
user: hello
**************************************************
** Response: **
assistant: user: hello
assistant:
**************************************************

11:14:45.838 [INFO    ]             uvicorn.error - connection closed
11:14:45.880 [INFO    ]            uvicorn.access - 127.0.0.1:55255 - "POST /run/predict HTTP/1.1" 200
11:16:27.531 [INFO    ]            uvicorn.access - 127.0.0.1:55306 - "POST /run/predict HTTP/1.1" 200
11:16:27.532 [INFO    ]            uvicorn.access - 127.0.0.1:55305 - "POST /run/predict HTTP/1.1" 200
11:16:27.542 [INFO    ]            uvicorn.access - 127.0.0.1:55305 - "POST /run/predict HTTP/1.1" 200
11:16:27.860 [INFO    ]             uvicorn.error - ('127.0.0.1', 55309) - "WebSocket /queue/join" [accepted]
11:16:27.860 [INFO    ]             uvicorn.error - connection open
** Prompt: **
user: hello
assistant: user: hello
assistant:
user: hello what is your name?
assistant:
**************************************************
** Completion: **
user: hello
assistant: user: hello
assistant:
user: hello what is your name?
assistant:
**************************************************

** Messages: **
user: hello
assistant: user: hello
assistant:
user: hello what is your name?
**************************************************
** Response: **
assistant: user: hello
assistant: user: hello
assistant:
user: hello what is your name?
assistant:
**************************************************

11:16:28.022 [INFO    ]             uvicorn.error - connection closed
11:16:28.227 [INFO    ]            uvicorn.access - 127.0.0.1:55305 - "POST /run/predict HTTP/1.1" 200

**Comment by PoelleMANdia** [comment]
have the same issue

```
13:43:27.450 [INFO    ]             uvicorn.error - Started server process [520]
13:43:27.450 [INFO    ]             uvicorn.error - Waiting for application startup.
13:43:27.451 [INFO    ]             uvicorn.error - Application startup complete.
13:43:27.452 [INFO    ]             uvicorn.error - Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
13:43:31.700 [INFO    ]            uvicorn.access - 127.0.0.1:57982 - "GET / HTTP/1.1" 200
13:43:31.752 [INFO    ]            uvicorn.access - 127.0.0.1:57982 - "GET /info HTTP/1.1" 200
13:43:31.910 [INFO    ]            uvicorn.access - 127.0.0.1:57982 - "GET /theme.css HTTP/1.1" 200
13:43:47.265 [INFO    ]            uvicorn.access - 127.0.0.1:57983 - "GET /info HTTP/1.1" 200
13:43:47.285 [INFO    ]            uvicorn.access - 127.0.0.1:57983 - "GET /assets/python-20e39c92.svg HTTP/1.1" 200
13:43:47.286 [INFO    ]            uvicorn.access - 127.0.0.1:57986 - "GET /assets/javascript-850cf94b.svg HTTP/1.1" 200
13:43:56.310 [INFO    ]            uvicorn.access - 127.0.0.1:58018 - "GET /?view=api HTTP/1.1" 200
13:43:56.637 [INFO    ]            uvicorn.access - 127.0.0.1:58018 - "GET /info HTTP/1.1" 200
13:44:14.302 [INFO    ]            uvicorn.access - 127.0.0.1:58019 - "POST /run/predict HTTP/1.1" 200
13:44:14.302 [INFO    ]            uvicorn.access - 127.0.0.1:58020 - "POST /run/predict HTTP/1.1" 200
13:44:14.306 [INFO    ]            uvicorn.access - 127.0.0.1:58020 - "POST /run/predict HTTP/1.1" 200
13:44:14.634 [INFO    ]             uvicorn.error - ('127.0.0.1', 58063) - "WebSocket /queue/join" [accepted]
13:44:14.634 [INFO    ]             uvicorn.error - connection open
```

**Comment by jromal** [comment]
Hi.

I started today using it. I got at first the same error.  Have a look to the model. You are probably using the "mock" model and not the "local" model.

Change the settings.yaml file to set the llm model to "local" or set the variable PGPT_PROFILES to "local".

**Comment by lopagela** [comment]
@jromal is correct -- the issues you are having is because the mode is `mock`. You can change that in the configuration file `settings.yaml`, or use another configuration profile (setting `PGPT_PROFILES=local` will make you load the configuration file `settings-local.yaml` on top of `settings.yaml`).

----

In a nutshell, you can change the value from `mock` to `local` in your `settings.yaml` file, and it should work.

**Comment by pabloogc** [comment]
@lopagela is right, you can see in your logs too

```11:14:01.311 [INFO ] private_gpt.settings.settings_loader - Starting application with profiles=['default']```
Looks like you didn't set the PGPT_PROFILES variable correctly or you did in another shell process. If you are having trouble doing this in windows just modify `settings.yaml` directly instead of using profiles.
