### ISSUE TITLE
Any chance of PDF ingestion? 

### ISSUE THREAD

**Issue by RuairiSpain** [imartinez/privateGPT#12]

**Comment by dennydream** [comment]
Try using the PDF loader in langchain instead of a text loader that's used in the ingest script

**Comment by JavaGT** [comment]
Personally, I've been having a look at text extraction from PDFs and unfortunately it doesn't seem to be an easy thing.
Looking at academic articles, often you have text split into columns, headers, footers, page numbers, tables, text as an image (no OCR) etc that are all created very, uh, 'concretely' by placing elements on the page in terms of their coordinates rather than through some form of markup.

If someone knows some magic sauce that'd be amazing.

**Comment by dennydream** [comment]
Yeah, it's a pain.  HTML can be a pain too-at least the stuff I'm looking at (SEC filings) which have XBRL in them.  Data prep is typically some of the biggest effort with the AI/ML stuff.

**Comment by su77ungr** [comment]
https://gpt-index.readthedocs.io/en/latest/how_to/data_connectors.html

also see possible `from llama_index.readers.chroma import ChromaReader`

```python
from pathlib import Path
from llama_index import download_loader

PDFReader = download_loader("PDFReader")

loader = PDFReader()
documents = loader.load_data(file=Path('./article.pdf'))


reader = ChromaReader(
    collection_name="chroma_collection",
    persist_directory="examples/data_connectors/chroma_collection"
)

documents = reader.load_data(file=Path('./article.pdf'))

text_splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50)
texts = text_splitter.split_documents(documents)
    # Create embeddings
llama = LlamaCppEmbeddings(model_path="./models/ggml-model-q4_0.bin")
    # Create and store locally vectorstore
persist_directory = 'db'
db = Chroma.from_documents(texts, llama, persist_directory=persist_directory)
db.persist()
```

**Comment by imartinez** [comment]
Also take a look at this: LangChain has support for several [PDF Loaders](https://python.langchain.com/en/latest/modules/indexes/document_loaders/examples/pdf.html#)

**Comment by robli314** [comment]
@imartinez I submitted a PR where the code detects if the file used to ingest is a pdf. If so, the code will be using a PyPDFLoader as you suggested.

**Comment by d2rgaming-9000** [comment]
You have to write a script to make it ONLY read content I think.
