### ISSUE TITLE
Anyone tried this with Chinese centered LLM & embedding model?

### ISSUE THREAD

**Issue by greagain** [imartinez/privateGPT#1201]
I changed the settings.yaml to do with Chinese:
local:
  llm_hf_repo_id: TheBloke/CausalLM-7B-GGUF
  llm_hf_model_file: causallm_7b.Q4_K_M.gguf
  embedding_hf_model_name: BAAI/bge-small-zh-v1.5
But it seems not working, llm-chat is not working correctly, and after ingest Chinse text, every query will results in error.

**Comment by lopagela** [comment]
I guess you were able to run this model using standard English model- what is the error you are seeing the logs?

**Comment by greagain** [comment]
Not sure why, when I run with the above settings this time, it seems work. Though there is a warning:
[WARNING ] chromadb.segment.impl.vector.local_persistent_hnsw - Number of requested results 2 is greater than number of elements in index 1, updating n_results = 1
And the end results seems not very normal, it have weird:
<</SYS>
<<S
So I think it might be related with the facts that Chinese and English are indexed/stored differently? So there's some settings need to be changed.

**Comment by greagain** [comment]
Also, after the first 'somehow successful' run, the subsequent runs are completely failed, either llm-chat or query-document don't show any results (no error message though).

**Comment by lopagela** [comment]
@greagain 

> Also, after the first 'somehow successful' run, the subsequent runs are completely failed, either llm-chat or query-document don't show any results (no error message though).

Hit the `Retry` button - I'm having that as well... I will take a look soon on that bug

**Comment by greagain** [comment]
Will try the retry. After update with git pull, adding Chinese text seems work with original mistrial model and either en and zh embedding model, but causallm model option still not work. And the following:
[WARNING ] chromadb.segment.impl.vector.local_persistent_hnsw - Number of requested results 2 is greater than number of elements in index 1, updating n_results = 1
persist.

**Comment by greagain** [comment]
A few update after trying various settings:
1. Causallm seems not working here. Not generating output.
2. Using pdf for ingestion will not generating:
Number of requested results 2 is greater than number of elements in index 1, updating n_results = 1
or
page label error (when use 'search in docs' function.)
But use simple txt file will.
3. The default en embedding model seems works as good (or bad) as the corresponding 'zh' model.

**Comment by greagain** [comment]
Will using larger embedding models help a lot in terms of documents understanding? The default small one seems not very good. BTW, what 'advanced' embedding models are recommended?

**Comment by pabloogc** [comment]
you have a lot of freedom regarding embedding models, maybe try with one suited for your documents language: https://huggingface.co/models?pipeline_tag=feature-extraction&sort=trending

**Comment by greagain** [comment]
After update to the 'new' version, Chinese document seems no longer work. Give strange output such as:
Q: Let z(i) = 10*i**2 - 3*i + 4. Let r be z(-2). Suppose 5*v - 2*v = -r. Solve v*j = -j for j.
A: 0

**Comment by c2j** [comment]
> After update to the 'new' version, Chinese document seems no longer work. Give strange output such as: Q: Let z(i) = 10_i**2 - 3_i + 4. Let r be z(-2). Suppose 5_v - 2_v = -r. Solve v*j = -j for j. A: 0

I got it same:
```
Q: Let i(v) = -2v**3 + 10v*2 - 14v + 1. Let q be i(6). Suppose -qy + 5y = 10. Solve 0 = -y*l - l + 1 for l.
A: -1
```

**Comment by lopagela** [comment]
To change the language of a model, you need to change the LLM and the embeddings (the embeddings alone are usually not enough)

I did a google research on HF, and I found this one: https://huggingface.co/TheBloke/Chinese-Alpaca-2-7B-GGUF

We are working on properly supporting other model (especially, through prompt style), but you should be able to configure it with the `default` mode, c.f. the documentation: https://docs.privategpt.dev/recipes#french--with-instructions.
Once you found an LLM in a given language, do some more research on the embedding model to use (some work better than others).

Stay tuned on our refactoring around prompt style (c.f. our discord)
