### ISSUE TITLE
how to utilize GPU in Windows？

### ISSUE THREAD

**Issue by ONLY-yours** [imartinez/privateGPT#121]
when i was runing privateGPT in my windows, my devices gpu was not used? 
you can see the memory was too high but gpu is not used

my nvidia-smi is that, looks cuda is also work? so whats the problem? Is this normal in the project?

![image](https://github.com/imartinez/privateGPT/assets/52664827/91b095a7-8cf1-46b2-8f77-7b6d69771444)

![image](https://github.com/imartinez/privateGPT/assets/52664827/23e025b4-b583-4ac9-abcd-fe988fecd7bc)

**Comment by bmaltais** [comment]
I don't think this repo make use of GPU, only CPU.

**Comment by katojunichi893** [comment]
@ONLY-yours 
[GPT4All](https://gpt4all.io/index.html) which this repo depends on says no gpu is required to run this LLM. the whole point of it seems it doesn't use gpu at all

**Comment by ONLY-yours** [comment]
> @ONLY-yours [GPT4All](https://gpt4all.io/index.html) which this repo depends on says no gpu is required to run this LLM. the whole point of it seems it doesn't use gpu at all

seems like that, only use ram cost so hight, my 32G only can run one topic, can this project have a  var in .env ? ,such as useCuda, than we can change this params to Open it.  

I'm not a deep learning developer, so I don't know the details here, does it possible?

**Comment by HoseinHashemi** [comment]
This would be a nice feature to add since prompts on CPU take quite a bit of time to execute and return answer.

**Comment by ram-sh** [comment]
GPU would be very useful.

**Comment by CraftCanna** [comment]
GPT4ALL does have CUDA option. Is there a way to enable that?

**Comment by ONLY-yours** [comment]
> GPT4ALL does have CUDA option. Is there a way to enable that?

[```python
https://github.com/imartinez/privateGPT/blob/5a695e9767e24778ffd725ab195bf72916e27ba5/privateGPT.py#LL27C1-L33C18
```](https://github.com/imartinez/privateGPT/blob/5a695e9767e24778ffd725ab195bf72916e27ba5/privateGPT.py#LL27C1-L33C18)

Looks like if LangChain Api support cuda, then will be easy to use

**Comment by shondle** [comment]
Figured this out! I explained [here](https://github.com/imartinez/privateGPT/discussions/217#discussioncomment-5960400) in #217
