### ISSUE TITLE
Devastation shows poor skills

### ISSUE THREAD

**Issue by rogal223** [imartinez/privateGPT#1211]
I don't know why, but from the very beginning, with 4 or more targets, they show the Pyre skill as aoe, which is obvious, but I have this skill assigned to Numpad 4, and I have Living Flame assigned to Numpad 1. and when I see the pyre icon to click, it still shows the number 1 key

**Comment by pabloogc** [comment]
Ahh, Blizzard, it's not what it used to be. At least we can go back to the new classic season soon.
