### ISSUE TITLE
Feature request  Crawl web pages

### ISSUE THREAD

**Issue by aamir-gmail** [imartinez/privateGPT#1231]
Please see if it is possible to include  uploading a CSV file with webpages URLs  or a single URL through web UI , the engine  crawls and ingests all text automatically,

**Comment by pabloogc** [comment]
The best place to add this feature is [llama-index](https://github.com/run-llama/llama_index), adding web crawling to privategpt is not in the scope of the proyect.

@LinuxKunaL you can check if there is an implementation available in llama-index, to either extend or take as base.
