### ISSUE TITLE
How to access the UI within the local network?

### ISSUE THREAD

**Issue by osorioleomar** [imartinez/privateGPT#1241]
I hope someone can help.
I tried making firewall settings for port 8001. I even tried turning off my computer firewall completely.
My server IP in LAN is 192.168.1.12 and I am trying to access using another device with http://192.168.1.12:8001 but Site can't be reached.
I researched but came up with nothing.
Is there a configuration I should set? or please point me to a guide.

**Comment by pabloogc** [comment]
It´s almost impossible to help with this kind of problems, it´s something only you can fix with your home network. Make sure the IP is correct, that both computers are connected to the same router and that your router config allows traffic on the port 8001.
