### ISSUE TITLE
How to increase the response message length?

### ISSUE THREAD

**Issue by cedarice** [imartinez/privateGPT#1243]
Thank you very much for this wonderful project.
The longest answer from privateGPT is only 1135 bytes long, which results in an incomplete answer.Can this be modified?

**Comment by pulpo** [comment]
You can simple type go into the page, and it will continue with the answer.

**Comment by tstanek390** [comment]
+ for this. PrivateGPT is so far the best chat with docs LLM app around. The only one issue I'm having with it are short / incomplete answers. Could be nice to have an option to set the message lenght, or to stop generating the answer when approaching the limit, so the answer is complete. Sometimes I got full answer and then it starts to generate almost similar duplicate response to the prompt which is interrupted.

**Comment by cedarice** [comment]
> You can simple type go into the page, and it will continue with the answer.
It works, Thanks!

**Comment by glureau** [comment]
It could be automated if the API was responding a different `finish_reason` than 'stop'. What's your take on this @tstanek390 ? Should I create an issue or is it an expected behavior?

**Comment by selecta-ufuk** [comment]
after inserting the following line into llm_component.py the questions were no longer incomplete. Maybe it helps you too! 
**max_new_tokens=1024** in privateGPT\private_gpt\components\llm\llm_component.py

self.llm = LlamaCPP(
                    model_path=str(models_path / settings.local.llm_hf_model_file),
                    
                    temperature=0.1,
                    max_new_tokens=1024,

**Comment by Karobben** [comment]
> after inserting the following line into llm_component.py the answers were no longer incomplete. Maybe it helps you too! **max_new_tokens=1024** in privateGPT\private_gpt\components\llm\llm_component.py
> 
> self.llm = LlamaCPP( model_path=str(models_path / settings.local.llm_hf_model_file),
> 
> ```
>                 temperature=0.1,
>                 max_new_tokens=1024,
> ```

Works fine! Thanks.
