### ISSUE TITLE
https

### ISSUE THREAD

**Issue by team-boo** [imartinez/privateGPT#1245]
After installing i didnt find a way to have https and not http communication with privategpt.

Help please

**Comment by pabloogc** [comment]
There is no https support out of the box and it's not planned. You will need to provide your own mechanism (some kind of gateway/loadbalancer) with https support and deploy privategpt behind it.

**Comment by BrunoBosshard** [comment]
On Linux, I use NGINX as front-end for Gradio. I have used Certbot to install a Let's Encrypt certificate on NGINX.

This does not require any code changes in the privateGPT setup.

**Comment by team-boo** [comment]
Can you give a example on how to use nginx as frontend for Gradio.

Thank you.

**Comment by team-boo** [comment]
I think that https must be default enhancement   because of privacy that add.

The main reason that all we are working with privateGPT  is that we dont trust big Corporations AI.

**Comment by BrunoBosshard** [comment]
privateGPT is not a web server project and it shouldn't be one. However, this should get you started with NGINX and Gradio: https://www.gradio.app/guides/running-gradio-on-your-web-server-with-nginx
