### ISSUE TITLE
privateGPT web deploying

### ISSUE THREAD

**Issue by mrkog3** [imartinez/privateGPT#1247]
Hello everyone!

I have a question, I have carried out several tests with the different types of configurations locally (using different models), but now I would like to take a leap deploying chat in a web platform. I was planning to use some Azure service or an simple api system with a local machine, but I'm not sure how to start. In this same git I have searched for information but I cannot find any useful information about this.

Is there any implementation, or way to connect these APIs with a web service?

Thanks!

**Comment by pabloogc** [comment]
I can suggest to [look at VMs with GPU support in azure](https://learn.microsoft.com/en-us/azure/virtual-machines/sizes-gpu) , and try to make it run there for starters (no persistent storage, no scaling, just make it run in  dedicated VM), from there you will understand better what your infrastructure actually needs.

The jump to production is complicated and implies a lot of moving parts, best of luck!

**Comment by mrkog3** [comment]
> I can suggest to [look at VMs with GPU support in azure](https://learn.microsoft.com/en-us/azure/virtual-machines/sizes-gpu) , and try to make it run there for starters (no persistent storage, no scaling, just make it run in dedicated VM), from there you will understand better what your infrastructure actually needs.
> 
> The jump to production is complicated and implies a lot of moving parts, best of luck!

thanks!
