### ISSUE TITLE
Add a list of supported file types to README and Docs

### ISSUE THREAD

**Issue by robertgro** [imartinez/privateGPT#1258]
Maybe I'm blind, but I couldn't find a list of the file types supported by privateGPT.

One might add a list with the supported file types to the [README.md](https://github.com/imartinez/privateGPT/blob/main/README.md) and [PrivateGPT Docs](https://docs.privategpt.dev/).

Kinda related https://github.com/imartinez/privateGPT/issues/451 and apologize at this place, I haven't had the time yet to look further into a first implementation proposal.

**Comment by lopagela** [comment]
Hey @robertgro , thank you for the suggestion!

We are currently re-working the documentation, and we created a page in documentation about supported file types/extension.

You can see them in the preview of the documentation refactoring (will be shipped in the actual doc once https://github.com/imartinez/privateGPT/pull/1264 is merged).

https://privategpt-preview-8380d3f2-962a-400e-87d4-fd1c4636f174.docs.buildwithfern.com/manual/document-management/ingestion#supported-file-formats

**Comment by robertgro** [comment]
@lopagela Thank you and good job!
