### ISSUE TITLE
Changing to a bigger embedding model of the project!!!

### ISSUE THREAD

**Issue by Mohammed-alqaisi** [imartinez/privateGPT#1281]
Guys how can we change the basic embedding model that comes with the original code which is BAAI/bge-small-en-v1.5, to a different model let's say  BAAI/bge-large-en-v1.5. when I just change that from the settings.yaml file it gives me this error: chromadb.errors.InvalidDimensionException: Embedding dimension 768 does not match collection dimensionality 384. 

Has anyone encountered this issue and how to solve it?? 

Thanks!

**Comment by cedarice** [comment]
I have encountered similar problems. May be you should delete the files in 'local_data' folder and then re-ingest your documents.

**Comment by imartinez** [comment]
As @cedarice suggests, you can not change the embeddings model after ingesting, because the dimensionality of the vectors produced by the different models differ. You need to first delete the contents in local_data (you can use `make wipe`  as a more convenient way of doing it)

**Comment by Mohammed-alqaisi** [comment]
Thank you so much, I did try to remove the files inside the local_data folder for some reason it didn't work, I did it by removing the embedding folder that gets downloaded inside the models' directory, because for some reason when I changed the embedding model inside the settings.yaml file the configuration inside the embedding folder didn't change. That is why I have deleted the folder and re-install the bigger embedded model again.

**Comment by ashunaveed** [comment]
you should update it in settings file. updating to bge-large model worked for me.
