### ISSUE TITLE
File extension uppercasing causes ingest error

### ISSUE THREAD

**Issue by eKIK** [imartinez/privateGPT#1283]
## Steps to reproduce

1. Find a valid binary file (non UTF-8 encoded), e.g. a .pdf.
2. Change the file extension to uppercase, e.g. ".PDF".
3. Try to upload the file through the UI.

## Expected behavior

The file should be uploaded and processed.

## Actual behavior

The upload fails with an error message similar to `Exception: 'utf-8' codec can't decode byte 0xe2 in position 10: invalid continuation byte`

## Error analysis

Looking at `ingest_service.py` we can see that the file extension is grabbed form the suffix of the file path. It's then used as the key to look up an appropriate file reader from the `FILE_READER_CLS`.

https://github.com/imartinez/privateGPT/blob/a09cd7a892c31a206832e35e3d8a0d125f38d2b0/private_gpt/server/ingest/ingest_service.py#L86-L87

We won't find a specific FileReader if the file extension isn't all lowercase, and in that case the ingest endpoint reverts to using the default string reader (which on my system assumes UTF-8). Because of this reading the file fails.

The fix might very well be as simple as adding on a call to `.lower()`:

```python
extension = Path(file_name).suffix.lower()
```

**Comment by lopagela** [comment]
@eKIK thank you for the discovery of the bug, explanation, and suggested changes 😄;  I agree with all of what you've said - do you want to open a PR to fix?

If you prefer not, I can do it for you ✌️

**Comment by eKIK** [comment]
@lopagela It'd be awesome if you could do it!
