### ISSUE TITLE
Results only on source documents

### ISSUE THREAD

**Issue by Wettham038** [imartinez/privateGPT#1284]
hello,

No idea if this question belongs here, if not please let me know.
PrivateGPT install done and I am impressed with what it can do.
Now my question is if it is also possible that LLM searches ONLY the uploaded documents and not its general data what is already in the LLM. 

I found these links:
[1](https://stackoverflow.com/questions/76813442/how-to-make-privategpt-retrieving-info-only-from-local-documents)

[2](https://github.com/imartinez/privateGPT/discussions/438)

But the possibility doesn't seem to be there yet.
Does anyone know if and if so how it can be done?
No is also an answer of course, maybe something for the roadmap?

**Comment by lopagela** [comment]
Don't you want `Search in Doc` mode?
![Screenshot 2023-11-20 at 15 50 38](https://github.com/imartinez/privateGPT/assets/15184763/0d88b392-f116-451d-b8ce-60bc988ddd6e)

**Comment by lee-jian-hui** [comment]
I hope this answers your question.

**Comment by Wettham038** [comment]
Wow it worked out much better, thanks! No i have to find a way to automatically put 'use only given context' in every search but that's another topic.
