### ISSUE TITLE
Local embeddings with OpenAI LLMs

### ISSUE THREAD

**Issue by Akbarable** [imartinez/privateGPT#1294]
Hi everyone, 

I want to create a new PGPT profile that uses the local  `embedding_hf_model_name: BAAI/bge-small-en-v1.5` embedding model and `openai` LLM (e.g gpt-3.5 turbo etc.).

Is there a way I can do that? 

Looking for advice, thanks!

**Comment by jochalek** [comment]
I got this working and made a PR #1296
