### ISSUE TITLE
How Can I increase the token size?

### ISSUE THREAD

**Issue by Karobben** [imartinez/privateGPT#1297]
Thanks for your fantastic work. It is really amazing.

I figured out how to switch between models and GPU, but I just realized that the token is limited in some place and can not changed in the configure file. Do you know How to change and increase the token size?  

Thanks

**Comment by glureau** [comment]
https://github.com/imartinez/privateGPT/issues/1243

(Also today, if the received message is >1000 chats, I'm just calling again the chat/completions with the received response in the messages, so that it can continue the response if needed, else it's returning an empty string.)
