### ISSUE TITLE
Using PrivateGPT without UI

### ISSUE THREAD

**Issue by samanemami** [imartinez/privateGPT#1302]
Is it possible to use prompt without running User Interface via Gradio?

Thank you

**Comment by seanmavley** [comment]
> poetry install --with ui,local && ./scripts/setup

Omit the `ui` when installing the script. Tried that?

https://docs.privategpt.dev/overview/welcome/quickstart

**Comment by samanemami** [comment]
Thanks @seanmavley 

But this also needs to be opened on a http:////127.0.0.1:8001/, where I am looking to pass a prompt and have the output only in the terminal.

**Comment by mferris77** [comment]
It would be nice if there were a command line argument where the UI could be disabled or rather an 'API only' mode.  That would allow us to test with the UI to make sure everything's working after an ingest, then continue further development with scripts that will just use the API.

**Comment by pabloogc** [comment]
> Is it possible to use prompt without running User Interface via Gradio?
> 
> Thank you

that's what the REST API is for, check the docs: https://docs.privategpt.dev/api-reference/api-reference/contextual-completions/chat-completion


> It would be nice if there were a command line argument where the UI could be disabled or rather an 'API only' mode. That would allow us to test with the UI to make sure everything's working after an ingest, then continue further development with scripts that will just use the API.

you can create a profile for that and use an environment variable to control the `ui.enabled` setting

**Comment by EmbroseBhati** [comment]
> Is it possible to use prompt without running User Interface via Gradio?
> 
> Thank you



> > poetry install --with ui,local && ./scripts/setup
> 
> Omit the `ui` when installing the script. Tried that?
> 
> https://docs.privategpt.dev/overview/welcome/quickstart

it's still giving me error ModuleNotFoundError: No module named 'gradio'. why is gradio still integrated when I have omitted the UI. is there any different approach .i want to use private gpt with my own UI instead of gradio.
