### ISSUE TITLE
No module named 'private_gpt' while running scripts/setup

### ISSUE THREAD

**Issue by DiwanshuA** [imartinez/privateGPT#1303]
I'm receiving below error while running scripts/setup from the root directory in Windows.

from private_gpt.paths import models_path, models_cache_path
ModuleNotFoundError: No module named 'private_gpt'

command run from the root directory:
poetry run python scripts/setup

please advice

**Comment by seanmavley** [comment]
Are you running the command from
1. the right directory i.e `cd privateGPT`
2. with your virtualenv enabled? i.e `source .venv/bin/activate`

**Comment by DiwanshuA** [comment]
yes, I'm running it from the root directory and activated the env using conda activate command as well

**Comment by lavericklavericklaverick** [comment]
did this get resolved? im having same issue. (im in virt env + correct path) thanks

**Comment by xeeshan789** [comment]
Hi, 
I am getting exactly the same error while I am in correct environment and path. Please share the resolution if there is any. I ran the following command

(privateGPT) ...\privateGPT>poetry run python scripts/setup.py
Traceback (most recent call last):
  File "...privateGPT\scripts\setup.py", line 7, in <module>
    from private_gpt.paths import models_path, models_cache_path
ModuleNotFoundError: No module named 'private_gpt'

thank you in advance

**Comment by xeeshan789** [comment]
resolved for me. I executed 

poetry install

and then executed 

poetry run python scripts/setup.py

it worked out for me.

**Comment by OzzyDeng-JunDeng** [comment]
> resolved for me. I executed
> 
> poetry install
> 
> and then executed
> 
> poetry run python scripts/setup.py
> 
> it worked out for me.

The same works for me, too. Thanks

**Comment by sati-bodhi** [comment]
`poetry install` gives:
```
Installing the current project: private-gpt (0.2.0)
The current project could not be installed: No file/folder found for package private-gpt
If you do not want to install the current project use --no-root
```

then:
```
./scripts/setup
Traceback (most recent call last):
  File "/home/sati/privateGPT/./scripts/setup", line 8, in <module>
    from private_gpt.paths import models_path, models_cache_path
ModuleNotFoundError: No module named 'private_gpt'
```

**Comment by xardasVB** [comment]
I have the same issue as [sati-bodhi], it is resolved?

**Comment by dr-thax** [comment]
To ensure Python recognizes the `private_gpt` module in your `privateGPT` directory, add the path to your PYTHONPATH environment variable. 
Use the command `export PYTHONPATH="${PYTHONPATH}:/path/to/your/privateGPT/private_gpt"`.
Then run again: poetry run python scripts/setup

**Comment by mahdi-amins** [comment]
I fixed the  " No module named 'private_gpt' " in linux with following command

`cp scripts/* .`

just copy the scripts folder contents in the main folder and run:

`poetry run python setup`


tip: make sure to create a virtual env first then install private-gpt in case something goes wrong you dont get conflict in packages

`
conda create -n privategpt python=3.11
conda activate privategpt
`

**Comment by mahdi-amins** [comment]
I fixed the  " No module named 'private_gpt' " in linux with following command

`cp scripts/* .`

just copy the scripts folder contents in the main folder and run:

`poetry run python setup`


tip: make sure to create a virtual env first then install private-gpt in case something goes wrong you dont get conflict in packages

`conda create -n privategpt python=3.11`
`conda activate privategpt`
