### ISSUE TITLE
Simple question (hopefully) - does reingesting a document have any negative effects?

### ISSUE THREAD

**Issue by mferris77** [imartinez/privateGPT#1306]
I started to bulk ingest some documents, the process quit halfway through so I restarted it.  I noticed everything that was previously ingested was being ingested again.

I am fairly new to this space and not familiar with ChromaDB (or vector DBs in general).  I would have thought that PrivateGPT knows the document locations for what has already been ingested so it would skip anything it already knows about, but the logs don't seem to indicate that's happening.  So I assume that if I ingest "ABC.pdf" and then ingest it again, that there are now two duplicate documents.

Does the information from the first ingest just get overwritten in the chromaDB, or is there now 'extra weight' given to the contents since there is more 'connections' to the information?  (ie I load "ABC.pdf" twice, and "XYZ.pdf" once, they both contain information about a particular topic, I then query my documents and am presented with more information sourced from ABC because there's twice as many data points coming from ABC than if I had only ingested it once?)

Thanks in advance for any insight provided, and thanks to the devs for realizing this project!

**Comment by stevenlafl** [comment]
Did you ever figure that out @mferris77 ?
