### ISSUE TITLE
Trouble with Ebooklib & html2text

### ISSUE THREAD

**Issue by johnmhm** [imartinez/privateGPT#1313]
I wanted to try and upload an epub file, and got the following error:

`Exception: Please install extra dependencies that are required for the EpubReader: 'pip install EbookLib html2text'`

I installed the the two modules, as confirmed by `pip freeze`:

`➜ pip freeze
diskcache==5.6.3
EbookLib==0.18
html2text==2020.1.16
llama_cpp_python==0.2.7+cu117
lxml==4.9.3
numpy==1.26.2
six==1.16.0
typing_extensions==4.8.0`

But I still get the same error when trying to upload an epub file. Any suggestions? 

Functionality-wise it's not a biggie for me, as epubs are easily converted to text outside of privateGPT, but if a solution exists I would love to hear it.

**Comment by Error-418** [comment]
This is an environment issue, if you stop the server and instead run `poetry add bookLib html2text` and restart the server it should clear the issue for you. This is related to https://github.com/imartinez/privateGPT/issues/1150

**Comment by johnmhm** [comment]
You are absolutely right - running `poetry add ebookLib html2text` did the trick! Thank you 🙏

**Comment by Tiagochicoo** [comment]
@Error-418 @johnmhm can you explain what you mean by stop the server?
I'm running into the same issue and have tried this solution, but I still get the same error after running `poetry add ebookLib html2text`

**Comment by Error-418** [comment]
@Tiagochicoo shutdown the AI/LLM. Do the `poetry add ebookLib html2text` and start the AI once it's done.

If you're still having issues after that, open a new support request and paste your error messages into it.
