### ISSUE TITLE
Small context length

### ISSUE THREAD

**Issue by sumitsodhi88** [imartinez/privateGPT#1319]
The context window is small and the summay of the ingested files come out to be wrong/limited to first few paragraphs.
Also, the answers get truncated too soon, sometimes require to ask the model 5-6 times to keep continuing with the answer.
Could someone point me to the location of the py file as well as the env file to make adjustments in the version 0.2.0.

**Comment by gianniacquisto** [comment]
This was resolved in a recent PR. You now have the option to modify the `llm.max_new_tokens` config option in settings.yaml

**Comment by gianniacquisto** [comment]
There are some docs also explaining this in the installation section

**Comment by gianniacquisto** [comment]
https://github.com/imartinez/privateGPT/commit/9c192ddd732a598786592df1705623be1894a067
