### ISSUE TITLE
Need help with ingest.py

### ISSUE THREAD

**Issue by krstrid** [imartinez/privateGPT#133]
Running into this error -  python ingest.py

-Traceback (most recent call last):
  File "C:\Users\krstr\OneDrive\Desktop\privategpt\privateGPT\privateGPT\ingest.py", line 11, in <module>
    from constants import CHROMA_SETTINGS
  File "C:\Users\krstr\OneDrive\Desktop\privategpt\privateGPT\privateGPT\constants.py", line 11, in <module>
    CHROMA_SETTINGS = Settings(
  File "pydantic\env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
persist_directory
  none is not an allowed value (type=type_error.none.not_allowed) -

I've installed the requirements and changed the .env file and followed the readme up to this point. Seeing some people solve but not answer what fixed the above errors. Help?

**Comment by ranpo** [comment]
Have you created the /db folder? I solved mine after creating the /db folder manually.

**Comment by krstrid** [comment]
Yes I have, ranpo, under that but no change still. :( I do appreciate all the help.

**Comment by virtualramblas** [comment]
Hi @krstrid, have you renamed the _example.env_ file to _.env_? It looks like the Python script to ingest documents cannot find the env file with the required name.

**Comment by krstrid** [comment]
Hi VirtualRamblas, yes I have. Not sure what's up and I'm not an expert coder. Just trying to follow along.

**Comment by andreakiro** [comment]
@krstrid Are you sure you're `.env` file is located at the root of the project? Did you add any spacing after or before the `=` when defining your env variables? Did you modify any of the code in the `ingest` file? In case it's none of these things, you might also have permissions issues to load the file. You can try printing the var in your script to see what's going on

```python
# Load environment variables
persist_directory = os.environ.get('PERSIST_DIRECTORY')
print(persist_directory)
```

**Comment by krstrid** [comment]
> @krstrid Are you sure you're `.env` file is located at the root of the project? Did you add any spacing after or before the `=` when defining your env variables? Did you modify any of the code in the `ingest` file? In case it's none of these things, you might also have permissions issues to load the file.

Hi andreakiro, it is at the root of the project, there are no extra spacings for the env variables, it has been renamed .env from example.env and no code has been modified in the ingest file.

I shouldn't have permissions issues as Admin afaik.

**Comment by krstrid** [comment]
It says I have python-dotenv installed after I installed requirements. When I run python ingest.py I get the errors above. -

Here are the contents of my env file - 
PERSIST_DIRECTORY=db
LLAMA_EMBEDDINGS_MODEL=C:\Users\krstr\OneDrive\Desktop\privateGPT\models\ggml-model-q4_0.bin
MODEL_TYPE=GPT4All
MODEL_PATH=C:\Users\krstr\OneDrive\Desktop\privateGPT\models\ggml-gpt4all-j-v1.3-groovy.bin
MODEL_N_CTX=1000

There is a models folder I created and I put the models into that folder.
It did not originate a db folder with ingest.py but I did create a db folder to no luck.

Appreciate all the help. I am using just the code provided along with instructions.

**Comment by andreakiro** [comment]
@krstrid  can you try modifying `constants.py`, then running `ingest` and share the trace again.

```python
# modifications in `constants.py` file:
L8: PERSIST_DIRECTORY = os.environ.get('PERSIST_DIRECTORY')
L9: print(PERSIST_DIRECTORY) # NEW!
$ python ingest.py
```

**Comment by andreakiro** [comment]
@krstrid Try the following and see what happens:

```
python3 -m pip install -r requirements.txt
python3 -m pip install python-dotenv
python3 ingest.py
python3 privateGPT.py
```

**Comment by krstrid** [comment]
It's giving me the original error 

- Traceback (most recent call last):
  File "C:\Users\krstr\OneDrive\Desktop\privateGPT\ingest.py", line 11, in <module>
    from constants import CHROMA_SETTINGS
  File "C:\Users\krstr\OneDrive\Desktop\privateGPT\constants.py", line 13, in <module>
    CHROMA_SETTINGS = Settings(
                      ^^^^^^^^^
  File "pydantic\env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
persist_directory
  none is not an allowed value (type=type_error.none.not_allowed) --
  --------

  The requirement is already satisified for python-dotenv for the command: python3 -m pip install python-dotenv
  
  I'm stumped, I feel like I'm close but close isn't good enough for this kind of thing haha (hope you're all in good spirits).

**Comment by krstrid** [comment]
Update: Both ingest.py and privategpt.py have the same error, @andreakiro.

**Comment by krstrid** [comment]
I kinda wish someone (in my case with Windows) would do a full install of privategpt from where it is at with the current files uploaded to gh. Something isn't right but I don't know enough to fix it.

@Drakot - Thanks, @andreakiro also assisted a little earlier with a python3 command and I got past that error too. Thanks though!

**Comment by D1amEd** [comment]
> ModuleNotFoundError: No module named 'langchain'

Same problem here

**Comment by D1amEd** [comment]
Had the same problem few hours ago. Finally after some research i solved it.
What happened at the very beginning was that when you did the "Pip install -r requirements" some requirements didn't install, it  is actually mentioned somehow in the read.dm. Anyway, what you have to do is install langchain
`Pip install langchain` should work, but when you try to run it it will launch a new error with chromadb, so that is the famous wheel problem that is in the read.dm.
Sol: Download visual studio 2022 with the things related in the ReadMe

**Comment by troygamble** [comment]
In the readme, and the default .env template, the models are reversed.

Put the groovy file against the llama embeddings and the model file against the model path.

It's just a typo in the readme or whatever

**Comment by krstrid** [comment]
A quick redo of the absolute filepaths and now it finally is working. Thank you all for your assistance! So yes ultimately it was the folder being renamed to .env (appeared as that way in Windows GUI but not in dir as .env.env) and the filepaths being in the right spot. Now it is running python ingest.py and ingesting from the source_documents folder. Phew.

**Comment by SLEEP-SOUNDER** [comment]
I have the smae error,can you tell me how you solved it?
Thanks in advance.

**Comment by krstrid** [comment]
My main error was not copying over the .env file right. When in GUI it appears as .env but in dir showed up as .env.env. When in your directory use the command dir. 

There you'll see the files. I had a file called env.env. So I copied it by doing = cp .env.env .env --

Now you should be able to manipulate the values in .env. I then deleted env.env.

I then followed all the steps and it worked.  Hope that helps. If not post an error, but admittedly I'm a bit of a 'script-kiddy' so someone else might be of more assistance than I.

**Comment by SLEEP-SOUNDER** [comment]
thanks。 I have sloved it.

**Comment by arroyoquiel** [comment]
Solved `No module named 'dotenv'` it by removing python 3.11 from Path and leaving 3.10 at the top of the list. Even with 3.10 over 3.11, installing requirements from CMD, it would install it for 3.11 instead of 3.10.
