### ISSUE TITLE
Is it possible to ingest and ask about documents in spanish?

### ISSUE THREAD

**Issue by pablodegrande** [imartinez/privateGPT#135]

**Comment by imartinez** [comment]
Exactly, the internal prompt being used by LangChain's RetrievalQA chain is in english. That is probably making the model answer in english. But you should be able to change it to use your custom prompt in Spanish.

**Comment by Orrouk** [comment]
Hi, bonjour, I'll follow this topic with you, thank you for being there.

**Comment by mabihan** [comment]
@andreakiro Would you mind to share some example ? I tried the following : 

```python
def add_langage_prompt(query):
    return f'Parle moi en français. %s'%(query)
```

But I did not succeed. (Got "The question is unclear, could you please provide more context or rephrase it?"). I also try to add the langage prompt after the query but it replied in english. Maybe I should try another model ? Or do you have a example ?
