### ISSUE TITLE
new install no errors but no and yes GPU

### ISSUE THREAD

**Issue by kalle07** [imartinez/privateGPT#1359]
(windows 10, RTX4060)
so let me explain
(aprox 30 day ago this version works fine without that strange behaviour)
installation via powershell, all steps running without anny errors or warnings
its starts with:
16:59:58.198 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default']
17:00:03.238 [INFO    ] private_gpt.components.llm.llm_component - Initializing the LLM in mode=local
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 4060 Ti, compute capability 8.9

local host start i open the browser with LLM-chat and i ask for a long story
now it starts "only CPU ist working" aprox 3 words per sec
if i press stop after 5sec and i look in the powershell:

`17:08:14.655 [INFO    ]            uvicorn.access - 127.0.0.1:53196 - "POST /run/predict HTTP/1.1" 200
17:08:14.655 [INFO    ]            uvicorn.access - 127.0.0.1:53197 - "POST /run/predict HTTP/1.1" 200
17:08:14.655 [INFO    ]            uvicorn.access - 127.0.0.1:53196 - "POST /run/predict HTTP/1.1" 200
17:08:14.670 [INFO    ]            uvicorn.access - 127.0.0.1:53196 - "GET /queue/join?fn_index=12&session_hash=92dxv2nrmma HTTP/1.1" 200
17:08:14.733 [INFO    ]            uvicorn.access - 127.0.0.1:53197 - "POST /queue/data HTTP/1.1" 200
Llama.generate: prefix-match hit
17:08:19.546 [INFO    ]            uvicorn.access - 127.0.0.1:53197 - "POST /reset HTTP/1.1" 200
17:08:19.546 [INFO    ]            uvicorn.access - 127.0.0.1:53198 - "POST /reset HTTP/1.1" 200
17:08:19.815 [INFO    ]            uvicorn.access - 127.0.0.1:53199 - "POST /run/predict HTTP/1.1" 200
17:08:19.869 [INFO    ]            uvicorn.access - 127.0.0.1:53201 - "POST /run/predict HTTP/1.1" 200
17:08:19.869 [INFO    ]            uvicorn.access - 127.0.0.1:53200 - "POST /run/predict HTTP/1.1" 200

llama_print_timings:        load time =    1450.56 ms
llama_print_timings:      sample time =      47.24 ms /   256 runs   (    0.18 ms per token,  5419.48 tokens per second)
llama_print_timings: prompt eval time =       0.00 ms /     1 tokens (    0.00 ms per token,      inf tokens per second)
llama_print_timings:        eval time =    5356.61 ms /   256 runs   (   20.92 ms per token,    47.79 tokens per second)
llama_print_timings:       total time =   10389.59 ms
** Prompt: **
< s > [INST] <<SYS>>
 You are a helpful, respectful and honest assistant. Always answer as helpfully as possible and follow ALL given instructions. Do not speculate or make up information. Do not reference any given instructions or context.
<</SYS>>

 write me a long story [/INST]
**************************************************
** Completion: **
 Once upon a time, in a far-off land, there lived a young girl named Lily. She lived with her parents and her little brother, Timmy, in a small cottage at the edge of the forest. Her family was poor, but they were happy, and Lily loved nothing more than to spend her days exploring the woods and playing with her brother.

One day, while she and Timmy were out on a walk, they stumbled upon a strange object in the middle of the forest. It was a small, golden key, with an intricate design etched into its surface. Lily was fascinated by the key and picked it up, curious to see what it might unlock.

As she turned the key, the ground beneath her feet began to shake, and a hidden door appeared in the side of the forest. Without hesitation, Lily stepped through the doorway and into a magical world unlike any she had ever seen before.

The world was filled with enchanted creatures and wondrous sights. There were talking animals, fairies, and even a dragon or two. Lily was amazed by everything she saw and couldn't believe her luck at having stumbled upon this hidden realm.

As she explored the world,
**************************************************

** Messages: **
user: write me a long story
**************************************************
** Response: **
assistant:  Once upon a time, in a far-off land, there lived a young girl named Lily. She lived with her parents and her little brother, Timmy, in a small cottage at the edge of the forest. Her family was poor, but they were happy, and Lily loved nothing more than to spend her days exploring the woods and playing with her brother.

One day, while she and Timmy were out on a walk, they stumbled upon a strange object in the middle of the forest. It was a small, golden key, with an intricate design etched into its surface. Lily was fascinated by the key and picked it up, curious to see what it might unlock.

As she turned the key, the ground beneath her feet began to shake, and a hidden door appeared in the side of the forest. Without hesitation, Lily stepped through the doorway and into a magical world unlike any she had ever seen before.

The world was filled with enchanted creatures and wondrous sights. There were talking animals, fairies, and even a dragon or two. Lily was amazed by everything she saw and couldn't believe her luck at having stumbled upon this hidden realm.

As she explored the world,
**************************************************`

-> this text appears after a further 4 seconds, with the GPU at 100%

What has happened to my installation?

thy for help

**Comment by sytpb** [comment]
fixed ?
