### ISSUE TITLE
llama_cpp is installed, but not found for import

### ISSUE THREAD

**Issue by sunbyte** [imartinez/privateGPT#1364]
It's not possible to run this on AWS EC2. Everything is installed, but if I try to run privateGPT always get this error:

`Could not import llama_cpp library`

llama-cpp-python is already installed.

**Comment by gravitypushes** [comment]
I got stuck on the same issue. could it be because the ec2 doesn't have gpu?

**Comment by checc0** [comment]
I'm having the same issue with docker on Windows (FROM nvidia/cuda:12.3.0-devel-ubuntu22.04)...
Which version of Python are using ?

**Comment by checc0** [comment]
Solve.. I was running the container without  --gpus flag.
