### ISSUE TITLE
How to do prompt engineering for OpenAI model?

### ISSUE THREAD

**Issue by zubairahmed-ai** [imartinez/privateGPT#1369]
Hi @lopagela @imartinez 

Thanks for putting this great work together, I am using OpenAI model with api key, where can I do prompt engineering for it to avoid hallucination?

I can't seem to find the piece of code or setting anywhere in the repo

**Comment by imartinez** [comment]
You can include a role:system message in the messages list when using chat completions, or use the system_prompt parameter when using the completions API. 

If you want to go further than that you'd need to modify the source code in chat_service.py to implement your own logic.

I hope this helps
