### ISSUE TITLE
Feature request : verbose and permissive mod

### ISSUE THREAD

**Issue by msyyces8x95** [imartinez/privateGPT#137]
I am running privateGPT on a set of PDF, The ingest script failed with ` ...
Traceback (most recent call last):
    raise PDFSyntaxError("No /Root object! - Is this really a PDF?")
` my document is a valid PDF as far as I know (I can open it with Acrobat).
Can we add an option so any failure would be shown as a warning instead of a critical error ?

Also when running the ingest script on a long list of documents, we don't have a real progress indicator (like a progress bar thing). (I have to count the `llama_print_timings` outputs to figure out the progress made)

**Comment by andreakiro** [comment]
Your file might be corrupted or encrypted? Regarding the progress indicator, I agree. But it is due to line

```python
db = Chroma.from_documents(...)
```

So this should be a (cool) feature request for `langchain` and `chromadb`. You could ask there!
