### ISSUE TITLE
constants.py problem

### ISSUE THREAD

**Issue by b007zk** [imartinez/privateGPT#139]
constants.py", line 11, in <module>
    CHROMA_SETTINGS = Settings(
                      ^^^^^^^^^
  File "pydantic\env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
persist_directory
  none is not an allowed value (type=type_error.none.not_allowed)

**Comment by b007zk** [comment]
didn't rename example.env to .env

**Comment by krstrid** [comment]
I did this and it didn't fix my issue. Did you happen to change anything else?

**Comment by b007zk** [comment]
@krstrid  Well the only other thing I did related to that file was that I created a models directory in the root of the project and put my models in there because by default that's where they are being looked for in the .env file. Anyway when I renamed the example.env to .env i actually ran into a different issue instead: https://github.com/imartinez/privateGPT/issues/140

**Comment by smileBeda** [comment]
Renaming the file to `.env` is the proper solution, thanks @b007zk for the hint.

**Comment by krstrid** [comment]
I understand this may be the solution but I have done so and it is still giving me the same error for some reason. I've even tried starting from the beginning including cloning the repo again.

**Comment by b007zk** [comment]
@krstrid Just to make sure, you also created a directory called models and placed the .bin model files in that directory (the same ones mentioned in the .env)?

**Comment by krstrid** [comment]
Yes I did, I just closed my ticket actually. Windows was saving it was .env.env but it was only appearing as .env in the Windows GUI. Had to use dir in the directory and sure enough after a rename and pointing with absolute filepaths it is working.

**Comment by b007zk** [comment]
@krstrid hmm I'm still having this issue: https://github.com/imartinez/privateGPT/issues/140

and I even tried changing the .env to add the full file paths as given by "cd" and "chdir" but no luck. I don't think the file paths are my issue however based on the error i'm getting. Maybe it's my version of python. I have the latest 3.11.3. How about you?

**Comment by krstrid** [comment]
Version 3.11.3 - It's working for me now. I'm not too sure, I believe I used the stock files as much as can be. Here is what my code looks like in constants.py

import os
from dotenv import load_dotenv
from chromadb.config import Settings

load_dotenv()

# Define the folder for storing database
PERSIST_DIRECTORY = os.environ.get('PERSIST_DIRECTORY')

# Define the Chroma settings
CHROMA_SETTINGS = Settings(
chroma_db_impl='duckdb+parquet',
persist_directory=PERSIST_DIRECTORY,
anonymized_telemetry=False)

---
