### ISSUE TITLE
[Error] poetry install --with ui

### ISSUE THREAD

**Issue by ShengzheXu** [imartinez/privateGPT#1396]
Sorry, dumb question. Solved.

**Comment by xyciasav** [comment]
Could I ask what you did to resolve this? I'm running into the same issue, but i'm not able to move forward. I'm stuck in a loop:

xycia@pc:~/privateGPT$ poetry install --with local

Group(s) not found: local (via --with)
xycia@pc:~/privateGPT$ poetry install --with ui

Group(s) not found: ui (via --with)


I'm following this guide:
https://medium.com/@docteur_rs/installing-privategpt-on-wsl-with-gpu-support-5798d763aa31
