### ISSUE TITLE
Allow Setting Number of Sources to (similarity_top_k) in Settings and via API

### ISSUE THREAD

**Issue by 3ly-13** [imartinez/privateGPT#1410]
- [ ] Expose the default value of `similarity_top_k` to settings.yaml under `rag:`
- [ ] Move  `ingest_mode` to `rag:`
- [ ] Add the possibility to override it from the API at a per-call level

**Comment by 3ly-13** [comment]
@imartinez I've started working on this task, and had some initial findings.

1. Increasing similarity_top_k will increase the number of sources returned, and as a result tends to clutter the sources being shown in the UI (and likely returned via API). There could be a path to refine `curate_sources` function to drop sources that are redundant.
2. If the similarity_top_k is set too high (above 5 in my testing), responses start to lose accuracy and sometimes don't make sense. Still investigating why.

In general, I think this change needs some research before being fully usable as my impression is increasing the # of sources affects performance negatively. I will keep investigating possible approaches but let me know if you have any thoughts. Thanks!

**Comment by Ankit-Bharti2908** [comment]
Hi @3ly-13,
I am looking for similar use case. Can you please let me know where should i pass this argument similarity_top_k.
I have just started using the privategpt and want more context to be used in response.
Thanks in advance

**Comment by 3ly-13** [comment]
Hi @Ankit-Bharti2908 - I pushed the experimental changes to a branch on my forked repo here [here](https://github.com/3ly-13/privateGPT/tree/feature/expose_similarity_top_k). You should be able to check it out by adding my repo as a remote, and checking out that branch.

Note that increasing the similarity_top_k setting beyond the default (2) can cause responses to lose some accuracy (or start hallucinating) which I am investigating.
