### ISSUE TITLE
Docker compose file issues

### ISSUE THREAD

**Issue by NickDevoctomy** [imartinez/privateGPT#1414]
Hi there,

I'm trying to get this running via docker-compose, unfortunately I don't see any explicit instructions anywhere so assume it's just a matter of running 'docker-compose up --build'.

Unfortunately after getting over the initial missing 'data' directory, I'm just chasing errors for missing files / folders. I assume there is something I'm supposed to have done prior to running docker compose?

Thanks for your time!

**Comment by NickDevoctomy** [comment]
Okay, I found the solution on this page,

https://github.com/imartinez/privateGPT/issues/1251#issuecomment-1817994055

**Comment by croossin** [comment]
@NickDevoctomy Were you able to push those models to a git repo? Trying to deploy this to portainer via a public git repo but having trouble since it exceeds the 2.00 GiB limit GitHub has.. trying to think of workarounds

**Comment by NickDevoctomy** [comment]
I downloaded it manually and copied it into the folder.  From what I understand, it's supposed to have some kind of setup process that downloads the model automatically, but with the docker-compose, that doesn't seem to work.  Not sure why, but if that could be made to work that would sort out that issue.

**Comment by lukaboljevic** [comment]
I was getting the same error, namely "Provided model path does not exist. Please check the path or provide a model_url to download" after running `docker compose up --build` with the default Dockerfile.local and docker compose file.

After implementing the changes in the above PR, the issue was solved and the app worked as expected, but it only runs on the CPU, which is also expected given the current content of the Dockerfile. I will try to get it to work on the GPU now.

**Comment by NickDevoctomy** [comment]
Thanks @lukaboljevic I just tried your suggested changes out and it worked great, now utilising the GPU and automatic model download.

**Comment by NickDevoctomy** [comment]
I had an issue with entrypoint.sh downloading the file each time regardless, so I modified the script slightly for a quick fix,

`
#!/bin/sh

# Check if the FILE_URL environment variable is set
if [ -z "$FILE_URL" ]
then
    echo "Error: FILE_URL environment variable is not set."
    exit 1
fi

# Extract filename from FILE_URL
FILENAME=$(basename "$FILE_URL")

# Define the path of the download and the complete file
DOWNLOAD_PATH="models/${FILENAME}"
COMPLETE_FILE="${DOWNLOAD_PATH}.complete"

# Check if the .complete file exists
if [ -f "$COMPLETE_FILE" ]
then
    echo "Download already completed for ${FILENAME}, skipping download."
else
    # Download the file
    wget -O "$DOWNLOAD_PATH" "$FILE_URL"
    
    # Check if wget was successful
    if [ $? -eq 0 ]
    then
        touch "$COMPLETE_FILE"
    else
        echo "Error: Download failed for ${FILENAME}."
        exit 1
    fi
fi

# Execute the main container command
exec "$@"
`

It checks the existence of a file that is created after the model download completes successfully, that way it won't just continue if the initial download is only partial. I'm sure there is a better way to do this, it's just a quick bodge.
