### ISSUE TITLE
Response stops in the middle of the output

### ISSUE THREAD

**Issue by croossin** [imartinez/privateGPT#1422]
I notice on long-responses, the output will randomly stop. Looking at the logs it seems that something is firing a `POST /run/predict` and then it immediately stops the output. Nothing I am doing from the UI to cause that to happen.

Below is the log that pops up right before it stops the output:
```bash
13:36:06.921 [INFO    ]            uvicorn.access - 127.0.0.1:62120 - "POST /run/predict HTTP/1.1" 200
```

**Comment by svenniuwe** [comment]
Some problem here. But already in shorter answers. What to do/try? Thanks!

**Comment by mikevin920** [comment]
same problem here
