### ISSUE TITLE
[Request] Allow custom openai endpoint

### ISSUE THREAD

**Issue by lenaxia** [imartinez/privateGPT#1424]
Due to changes in PrivateGPT, openai replacements no longer work as we cannot define custom openai endpoints. 

LocalAI is an example: https://github.com/mudler/LocalAI/tree/master/examples/privateGPT

It is a drop in replacement for ChatGPT Openai with compatible REST APIs. Being able to define custom openai endpoints in the settings files would enable us to use localai.

**Comment by creasydude** [comment]
any updates?

**Comment by mchill** [comment]
This is pretty easy to implement with [OpenAILike](https://docs.llamaindex.ai/en/stable/api_reference/llms/openai_like.html). I tested it briefly at first with LocalAI, and then with vLLM. I also need this feature, so I'll get around to opening a PR if no one else picks it up.
