### ISSUE TITLE
GPU not fully utilized, using only ~25% of capacity

### ISSUE THREAD

**Issue by imbence** [imartinez/privateGPT#1427]
Hi, I noticed that when the answer is generated the GPU is not fully utilized, as shown in the picture below:

<img width="373" alt="image" src="https://github.com/imartinez/privateGPT/assets/22945395/3f1a32cb-46c1-4756-8f7b-8938d4b89f78">

I haven't changed anything on the base config described in the installation steps.
Is there any setup that I missed where I can tune this?
 
Running it on this:
Windows 11
GPU: Nvidia Titan RTX 24GB
CPU: Intel 9980XE, 64GB

**Comment by lbux** [comment]
Use nvidia-smi to better monitor the usage of the GPU. Specifically, look at the memory usage as well.

**Comment by imbence** [comment]
Hey, thanks for the reply. If I check nvidia-smi it shows similar results:
<img width="618" alt="Screenshot 2023-12-25 at 11 12 47" src="https://github.com/imartinez/privateGPT/assets/22945395/a2f39434-a94d-4be6-855c-b5826b70073e">

**Comment by lukaboljevic** [comment]
Hi @imbence, were you able to figure this out? I'm also getting relatively low GPU usage (~10%). I tried playing with some parameters but with no success.

**Comment by lukaboljevic** [comment]
Hi @imbence, were you able to figure this out? I'm also getting relatively low GPU usage (~10%). I tried playing with some parameters but with no success.
