### ISSUE TITLE
How to reduce processing time (With default configurations)

### ISSUE THREAD

**Issue by lancer1993** [imartinez/privateGPT#1431]
This is an awesome project. I configured and ran this on Amazon Linux 2 (EC2 instance).  Server details as below,

```
NAME="Amazon Linux"
VERSION="2023"
ID="amzn"
ID_LIKE="fedora"
VERSION_ID="2023"
PLATFORM_ID="platform:al2023"
PRETTY_NAME="Amazon Linux 2023"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2023"
HOME_URL="https://aws.amazon.com/linux/"
BUG_REPORT_URL="https://github.com/amazonlinux/amazon-linux-2023"
SUPPORT_END="2028-03-15"
```

I followed this https://docs.privategpt.dev/overview/welcome/quickstart guidelines to setup on Amazon Linux 2 (EC2 instance)

Then I uploaded a pdf and tried to perform "Query Docs" via the UI. This took considerable amount of time to provide a response.
Is the any missing configuration to achieve this?

**Comment by imartinez** [comment]
EC2 does not have a GPU afaik. That means the inference is run over the CPU. That's the reason it is so slow. You'd need a GPU enabled machine
