### ISSUE TITLE
Not providing source for first response, rather adding its own questions and providing source for those instead.

### ISSUE THREAD

**Issue by kiwizznz** [imartinez/privateGPT#145]
Managed to get it working (ingested ~120 txt documents) and it appears to be functioning but it doesn't provide the source for the first answer. It also adds another question (for some reason) to its response and then tries to answer that as well. It also then provides 3-4 more single line questions with sources for those.

**Comment by patel999jay** [comment]
@kiwizznz i had the same issue.
