### ISSUE TITLE
Installation guide issue

### ISSUE THREAD

**Issue by smbrine** [imartinez/privateGPT#1457]
# Installation guide issue

## Problem
#1455, #1450, #1421, #1364, #1298,  and some of the discussions are bc of these lines in the documentation:
https://github.com/imartinez/privateGPT/blob/0a89d76cc5ed4371ffe8068858f23dfbb5e8cc37/fern/docs/pages/installation/installation.mdx#L38-L40

## Deep dive
The problem is that privateGPT explicitly requires `llama-cpp-python` but in docs' installation process it is prompted to verify the program without it being installed. I understand that in theory it should run as a mock LLM but in fact it is not running at all.

## Solution
Swap places of the mentioned lines and these lines:
https://github.com/imartinez/privateGPT/blob/0a89d76cc5ed4371ffe8068858f23dfbb5e8cc37/fern/docs/pages/installation/installation.mdx#L55-L57

## Additional info
- Let me know if you want me to create a pull request with a hot fix but it will take some time!
- Embeddings look bad on a phone so I highly recommend reading it on a computer

**Comment by Kassar666** [comment]
I agree the process of installation should be described step by step. Additionally, the element of local activation is not presented in this installation process.
