### ISSUE TITLE
ingest.py crashing Kubuntu everytime: db=Chroma(...)

### ISSUE THREAD

**Issue by Free-Radical** [imartinez/privateGPT#146]
Using default settings , built per instructions, but the Linux Machine crashes EVERYTIME at-

ingest.py-
`llama = LlamaCppEmbeddings(model_path=llama_embeddings_model, n_ctx=model_n_ctx)`

Operating System: Kubuntu 23.04
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.104.0
Qt Version: 5.15.8
Kernel Version: 6.2.0-20-generic (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 5600X 6-Core Processor
Memory: 31.2 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1080/PCIe/SSE2

**Comment by andreakiro** [comment]
Can you provide more details on your error?

**Comment by BoltOfNonsense** [comment]
Hi mate I've been working on upgrading your ingest.py file when I finished can I send it to you, ?

**Comment by brucelau-github** [comment]
You could do pull request, I believe.

**Comment by Free-Radical** [comment]
Be happy to , I looked up docs and it say to look in /var/crash, but I don't see anything meaningful.
Pls tell me what to send, since I've never dealt with a hardcrash.

**Comment by Free-Radical** [comment]
Traced issue to machine hardware issue and resolved, nothing to do   with code. Thx any way.

**Comment by zzadiues** [comment]
@Free-Radical > Traced issue to machine hardware issue and resolved, nothing to do with code. Thx any way.

Hi, im facing the same issue when I changed by GPU instance on ec2 from Tesla T4 to A10. How did you resolve the hardware issue ? Thanks a lot :)

**Comment by Free-Radical** [comment]
Hmm, trying to remember but confirm: Your machine is crashing every time you run ingest.py?

**Comment by Free-Radical** [comment]
PS just remembered my machine's hardware was overheating and shutting down due to over clocking. I reset the clock etc settings to nominal and no problems since then.
