### ISSUE TITLE
docker compose

### ISSUE THREAD

**Issue by piccaso** [imartinez/privateGPT#1460]
Hi!

Is there a docker guide i can follow?
I assumed `docker compose up` should work but it doesent seem like thats the case.

The current version in main complains about not having access to models/cache which i could fix but then
it terminates with some python error.
The latest release tag 0.2.0 complains about a missing docs folder.

So I'm thinking I'm probably missing something obvious, docker doesent break like that.

I really just want to try it as a user and not install anything on the host.
Can someone recommend my a version/branch/tag i can use or tell me how to run it in docker?

Thx

**Comment by donadelden** [comment]
I just solved adding `context: .` after `build:` into `docker-compose.yaml`.

Then, some other issues came up, but I managed to fix them following #1452
