### ISSUE TITLE
how to run without tokenizer?

### ISSUE THREAD

**Issue by cognitivetech** [imartinez/privateGPT#1485]
I don't have access to use llama-2.7b config file.... how to proceed?

> OSError: You are trying to access a gated repo.
> Make sure to request access at https://huggingface.co/meta-llama/Llama-2-7b and pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`.
> make: *** [Makefile:36: run] Error 1

**Comment by cognitivetech** [comment]
nevermind just have to comment out `tokenizer:` variable from config

**Comment by KansaiTraining** [comment]
[This](https://github.com/zylon-ai/private-gpt/issues/1935#issuecomment-2123365543) can help in getting access
