### ISSUE TITLE
ERROR: Install dependencies, Cannot install multidict.

### ISSUE THREAD

**Issue by NancyHsiao222** [imartinez/privateGPT#1491]
Hello All,

While executing the step "Install dependencies," I encountered an error as shown below. Has anyone else encountered this issue?

![2024010801](https://github.com/imartinez/privateGPT/assets/127062644/46d9dcd8-e051-4417-a15d-09cb0a400f87)

**Comment by MrD314** [comment]
I have just experienced the same error. Will watch for replies.

**Comment by Docteur-RS** [comment]
I found a fix if it can help other newbies like me.

As the whole `pyenv` thing from the doc is a complete mess I've switch to Anaconda. It's a bit fat but you have a lot of packages and everything works out of the box. Once in a while, especially in python, it's enjoyable.

Anyway, I simply ran `conda install multidict` and it installed the last package to date (6.0.4). Then tried the `poetry install --with ui,local`  once again and all went fine.

**Comment by heppstar** [comment]
Have the exact same issue...

**Comment by marinodg** [comment]
Hi everybody, same error here:
Apple Sonoma 14.4, 
Apple M3 Max,
Python 3.11.7
Poetry 1.8.2

(base) mdg@Marinos-MBP autogpt % poetry install
Installing dependencies from lock file

Package operations: 179 installs, 0 updates, 0 removals

  - Installing multidict (6.0.4): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel
  
  *********************
  * Accelerated build *
  *********************
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-14.0-arm64-cpython-312
  creating build/lib.macosx-14.0-arm64-cpython-312/multidict
  copying multidict/_multidict_py.py -> build/lib.macosx-14.0-arm64-cpython-312/multidict
  copying multidict/_abc.py -> build/lib.macosx-14.0-arm64-cpython-312/multidict
  copying multidict/__init__.py -> build/lib.macosx-14.0-arm64-cpython-312/multidict
  copying multidict/_multidict_base.py -> build/lib.macosx-14.0-arm64-cpython-312/multidict
  copying multidict/_compat.py -> build/lib.macosx-14.0-arm64-cpython-312/multidict
  running egg_info
  writing multidict.egg-info/PKG-INFO
  writing dependency_links to multidict.egg-info/dependency_links.txt
  writing top-level names to multidict.egg-info/top_level.txt
  reading manifest file 'multidict.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files found matching 'multidict/_multidict.html'
  warning: no previously-included files found matching 'multidict/*.so'
  warning: no previously-included files found matching 'multidict/*.pyd'
  warning: no previously-included files found matching 'multidict/*.pyd'
  no previously-included directories found matching 'docs/_build'
  adding license file 'LICENSE'
  writing manifest file 'multidict.egg-info/SOURCES.txt'
  /private/var/folders/5p/80qfc_5925sfjhpx4hnc120m0000gn/T/tmplu6ae_ux/.venv/lib/python3.12/site-packages/setuptools/command/build_py.py:207: _Warning: Package 'multidict._multilib' is absent from the `packages` configuration.
  !!

any solution?  I tried also with Anaconda, but still same error.
Regards
