### ISSUE TITLE
Duplicity of source files

### ISSUE THREAD

**Issue by JeisonJimenezA** [imartinez/privateGPT#1504]
I am using the primitive version of privategpt.
But I notice that when I run the file ingest.py it recognizes the duplicate files, for example if I have 5 files I get that it is loading 10. and when I try to recover them it is bringing me duplicate fragments. Could you help me please.

**Comment by ababkin** [comment]
I see this happening on my end too. Followed very primitive and standard getting-started steps, uploaded a couple of pdfs through the bundled UI, getting duplicate of the same reference at the end of response.
