### ISSUE TITLE
Can I use AMD GPU with privateGPT?

### ISSUE THREAD

**Issue by thanhtantran** [imartinez/privateGPT#1515]
Hello,

I have few RX580 and RX570 unused, can I use them for privateGPT?

**Comment by Vortex1x1x1x** [comment]
I have the same question

**Comment by Fremen72** [comment]
Which libraries need to be connected to use the AMD GPU?

**Comment by thanhtantran** [comment]
As far as i tried, opencl and rocm is the lib you need to run

**Comment by thanhtantran** [comment]
only opencl can run, using the amdgpu-install_5.4

**Comment by thanhtantran** [comment]
I resolved my problem

**Comment by HarvsG** [comment]
> I resolved my problem

How?

**Comment by thanhtantran** [comment]
depend on your AMD card, if old cards like RX580 EX570, i need to install amdgpu-install_5.7

then install opencl as legacy

after that, install libclblast, ubuntu 22 it is in repo, but in ubuntu 20, need to download the deb file and install it manually

the rest installation as per privateGPT instruction
