### ISSUE TITLE
PrivateGPT only uses 2 injected documents

### ISSUE THREAD

**Issue by Sewaphin** [imartinez/privateGPT#1516]
Hello,

I have injected many documents (100+) into privateGPT. No matter what question I ask, privateGPT will only use two documents as a source. 

How can I get privateGPT to use ALL the documents I've injected and add them to its context?

Thanks

PS: I tried different profiles, changing the system prompt but it had no impact. I also changed the number of GPU layers but again, no impact.

**Comment by naveenk2022** [comment]
The default number of sources the model will use is two. The file at /private_gpt/components/vector_store/vector_store_component.py can be edited to change this. The following is the code chunk you'll need to change:

```
   def get_retriever(
        index: VectorStoreIndex,
        context_filter: ContextFilter | None = None,
        similarity_top_k: int = 2,
    ) -> VectorIndexRetriever:
        # This way we support qdrant (using doc_ids) and chroma (using where clause)
        return VectorIndexRetriever(
            index=index,
            similarity_top_k=similarity_top_k,
            doc_ids=context_filter.docs_ids if context_filter else None,
            vector_store_kwargs={
                "where": _chromadb_doc_id_metadata_filter(context_filter)
            },
        )

```

Change `similarity_top_k: int = 2` to whatever number of sources you'd like to work with. I think this increases the time taken to generate an answer.

**Comment by Sewaphin** [comment]
Hello sir,

Thank you SO SO MUCH !!! It worked !

I hope this thread will help some other people.

Best regards
