### ISSUE TITLE
High CPU Usage while text output althought GPU is configured 

### ISSUE THREAD

**Issue by EEmlan** [imartinez/privateGPT#1529]
I have the problem that when i make an input in the UI the "thinking" occurs on the GPU as expected but afterwards while outputting the text it switches to CPU and then only uses one core.  And then the longer the Text is the slower it gets outputting it. The GPU is almost idling at that time.
Is someone familiar with this problem and is there a solution to this?
If the use of CPU while outputting text is normal then is it possible to increase the number of threads used?
I can remember that llama cpp can handle a parameter n_threads.
Don't know if this is a Bug or if this related to the functionality of it. 
I use an Linux Ubuntu system with an RTX 4070.

**Comment by selifecn** [comment]
The problem I encountered is basically the same as yours

**Comment by kmlob** [comment]
privateGPT is not using llama-cpp directly but llama-cpp-python instead.
First, you need to make sure, that llama-cpp / llama-cpp-python is built with actual GPU support. The default is CPU support only. Check the install docs for privateGPT and llama-cpp-python.
Second, there is an open issue about llama-cpp-python, which makes it crash when using GPU: https://github.com/abetlen/llama-cpp-python/issues/1064. But there is a workaround with copying libllama.so. Worked for me.

**Comment by gd197** [comment]
Exact same issue here, despite I think having followed the installation step correctly (But as I'm a complete newbie on such topic, don't trust me too much :) ) .
at startup :
`llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 33/33 layers to GPU
llm_load_tensors:        CPU buffer size =    70.31 MiB
llm_load_tensors:      CUDA0 buffer size =  4095.05 MiB
...............................................................................................
llama_new_context_with_model: n_ctx      = 3900
llama_new_context_with_model: freq_base  = 1000000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:      CUDA0 KV buffer size =   487.50 MiB
llama_new_context_with_model: KV self size  =  487.50 MiB, K (f16):  243.75 MiB, V (f16):  243.75 MiB
llama_new_context_with_model: graph splits (measure): 3
llama_new_context_with_model:      CUDA0 compute buffer size =   279.37 MiB
llama_new_context_with_model:  CUDA_Host compute buffer size =    15.62 MiB
AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 |
`
The issue mentionned by @kmlob doesn't seem to occur.
nvidia-smi output : 
`+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Quadro RTX 5000                Off | 00000000:2D:00.0 Off |                  Off |
| 33%   33C    P8              13W / 230W |   5212MiB / 16384MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      2424      G   /usr/lib/xorg/Xorg                           64MiB |
|    0   N/A  N/A      3476      G   /usr/bin/gnome-shell                         11MiB |
|    0   N/A  N/A     67208      C   ...vate-gpt-Tu1z2opV-py3.11/bin/python     5132MiB |
+---------------------------------------------------------------------------------------+
`
 Intel(R) Xeon(R) Gold 6136 CPU @ 3.00GHz hosting Debian 12 Bookworm
As well on my side only 1 CPU is used when outputing text
Hope this can help

**Comment by icsy7867** [comment]
Same issue here - 

GPU is configured and is being used, but text output/eval is still using GPU and feels sluggish.

Looking at the logs
**load time** - Down from 14 Seconds to 1.3 seconds
**sample time** - About the same around 20-40ms
**Prompt eval time** - Down from 14 Seconds to 1.3 Seconds
**eval time** - About the same, around 8-10 seconds

So the last eval time is stiill high, and using up to 50% of my CPU cores, but nvidia-SMI does show the python process (As well as top for the CPU).

**Comment by snikhil17** [comment]
@icsy7867 

Aren't these the default parameters in lamma-cpp code in llm_component.py ? 
Did you change any other parameters which made it faster ? 

I am facing the latency issue still. 

Also could you tell me what version of the PrivateGPT repo are you using ? 
What is the OS you are operating on. 

I am on Linux servers. And trying this but very very slow when scaled up for 1500 documents

**Comment by icsy7867** [comment]
> @icsy7867
> 
> Aren't these the default parameters in lamma-cpp code in llm_component.py ? Did you change any other parameters which made it faster ?
> 
> I am facing the latency issue still.
> 
> Also could you tell me what version of the PrivateGPT repo are you using ? What is the OS you are operating on.
> 
> I am on Linux servers. And trying this but very very slow when scaled up for 1500 documents

Yep.  I was testing out some options when using cpu only that I forgot to switch back. 😅

**Comment by Dariusz1989** [comment]
I'm on windows with 3950x and 3090, both use about 10-15% and its super slow. 
Where did you gus change settings to make it go brrrr?

**Comment by icsy7867** [comment]
> I'm on windows with 3950x and 3090, both use about 10-15% and its super slow. Where did you gus change settings to make it go brrrr?

Did you build llama-cpp-python with gpu support on windows?

**Comment by Dariusz1989** [comment]
> > I'm on windows with 3950x and 3090, both use about 10-15% and its super slow. Where did you gus change settings to make it go brrrr?
> 
> Did you build llama-cpp-python with gpu support on windows?

Yep I have BLAS = 1, I can also see it load up in ram as the gpu mem usage goes up. but not much speed help.

**Comment by icsy7867** [comment]
I did a LOT of digging into this.  And this seems to be caused from an older version of Gradio:
https://github.com/imartinez/privateGPT/issues/1581

The stream loop is maxing out the CPU when it shouldnt.  PrivateGPT is using Gradio 4.10, and they just released 4.17.  From the github issues and pulls for Gradio, this seems to be the culprit.

You can also test this.  Use the completions/chat API end point.  For the exact same question I get the entire answer in about 4-5 seconds.  However when using the chat stream, it takes 60-180 seconds.  So the GPU/Response is fine, but the stream is having issue.

I tried to manually update gradio/gradio_client, but this appears to break a few things which is beyond my python abilities.

**Comment by ic-mw** [comment]
For me a forced update to gradio 4.17.0 generally works, but unfortunately it does not at all improve the performance on the frontend.

**Comment by icsy7867** [comment]
> For me a forced update to gradio 4.17.0 generally works, but unfortunately it does not at all improve the performance on the frontend.

How are you doing the update?  When I do the forced updates, it breaks several dependencies and private gpt fails to start

**Comment by ic-mw** [comment]
```
poetry run pip install --force-reinstall --no-cache-dir gradio==4.17.0
```

i get dependency warnings, but privategpt still runs without (obvious) problems for me.
this is my basic setup:

```
llm:
  mode: local
  # Should be matching the selected model
  max_new_tokens: 512
  context_window: 8192
  tokenizer: DiscoResearch/DiscoLM_German_7b_v1

embedding:
  # Should be matching the value above in most cases
  mode: local
  ingest_mode: simple

vectorstore:
  database: qdrant
  # database: chroma

qdrant:
  path: local_data/private_gpt/qdrant

local:
  prompt_style: "chatml"
  llm_hf_repo_id: TheBloke/DiscoLM_German_7b_v1-GGUF
  llm_hf_model_file: discolm_german_7b_v1.Q6_K.gguf
  embedding_hf_model_name: BAAI/bge-small-en-v1.5
```

**Comment by icsy7867** [comment]
> ```
> poetry run pip install --force-reinstall --no-cache-dir gradio==4.17.0
> ```
> 
> i get dependency warnings, but privategpt still runs without (obvious) problems for me. Mind the fact that I update the entire gradio, not just gradio_client
> 
> this is my basic setup btw.
> 
> ```
> llm:
>   mode: local
>   # Should be matching the selected model
>   max_new_tokens: 512
>   context_window: 8192
>   tokenizer: DiscoResearch/DiscoLM_German_7b_v1
> 
> embedding:
>   # Should be matching the value above in most cases
>   mode: local
>   ingest_mode: simple
> 
> vectorstore:
>   database: qdrant
>   # database: chroma
> 
> qdrant:
>   path: local_data/private_gpt/qdrant
> 
> local:
>   prompt_style: "chatml"
>   llm_hf_repo_id: TheBloke/DiscoLM_German_7b_v1-GGUF
>   llm_hf_model_file: discolm_german_7b_v1.Q6_K.gguf
>   embedding_hf_model_name: BAAI/bge-small-en-v1.5
> ```

I'll try that tomorrow.  But I'm not tool familiar with pip.  Does that also upgrade the corresponding gradio_client package?

**Comment by ic-mw** [comment]
> > ```
> > poetry run pip install --force-reinstall --no-cache-dir gradio==4.17.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > i get dependency warnings, but privategpt still runs without (obvious) problems for me. Mind the fact that I update the entire gradio, not just gradio_client
> > this is my basic setup btw.
> > ```
> > llm:
> >   mode: local
> >   # Should be matching the selected model
> >   max_new_tokens: 512
> >   context_window: 8192
> >   tokenizer: DiscoResearch/DiscoLM_German_7b_v1
> > 
> > embedding:
> >   # Should be matching the value above in most cases
> >   mode: local
> >   ingest_mode: simple
> > 
> > vectorstore:
> >   database: qdrant
> >   # database: chroma
> > 
> > qdrant:
> >   path: local_data/private_gpt/qdrant
> > 
> > local:
> >   prompt_style: "chatml"
> >   llm_hf_repo_id: TheBloke/DiscoLM_German_7b_v1-GGUF
> >   llm_hf_model_file: discolm_german_7b_v1.Q6_K.gguf
> >   embedding_hf_model_name: BAAI/bge-small-en-v1.5
> > ```
> 
> I'll try that tomorrow. But I'm not tool familiar with pip. Does that also upgrade the corresponding gradio_client package?

yes it does - good luck!

**Comment by icsy7867** [comment]
Whoa! I think I fixed it.  I added some sleeps in the ui.py, and my prompt that usually takes 60-180 seconds completed in 5 seconds flat!

Let me figure out which one of these and I will post back!

**Comment by icsy7867** [comment]
Okay, gotta sign off for the night, but i have it narrowed down to these sleeps.  I believe it stops the CPU from being pegged so hard.

Also, I dont know if this is with or without the gradio update.

```
    def _chat(self, message: str, history: list[list[str]], mode: str, *_: Any) -> Any:
        def yield_deltas(completion_gen: CompletionGen) -> Iterable[str]:
            time.sleep(0.01)
            full_response: str = ""
            stream = completion_gen.response
            for delta in stream:
                time.sleep(0.01)
                if isinstance(delta, str):
                    full_response += str(delta)
                elif isinstance(delta, ChatResponse):
                    full_response += delta.delta or ""
                yield full_response
                time.sleep(0.01)
            if "I cannot find that information" in full_response:
                completion_gen.sources = False

            if completion_gen.sources:
                full_response += SOURCES_SEPARATOR
                cur_sources = Source.curate_sources(completion_gen.sources)
                sources_text = "\n\n\n".join(
                    f"{index}. {urllib.parse.unquote(source.file)} (page {source.page})"
                    for index, source in enumerate(cur_sources, start=1)
                )
                full_response += sources_text
            yield full_response
            time.sleep(0.01)
```

**Comment by icsy7867** [comment]
https://github.com/imartinez/privateGPT/pull/1589

**Comment by EEmlan** [comment]
@icsy7867 Thanks for your efforts digging into it. That was exactly the solution!!!
I have tested it and now it runs like a charm.
The generation is super smooth and fast now.
Glad you found this 👍
