### ISSUE TITLE
Memory requirements

### ISSUE THREAD

**Issue by vilaca** [imartinez/privateGPT#158]
I keep getting OOM errors while sending prompts. Usually the second prompt gives an OOM error.

I'm testing on a MBP from 2019 (intel) w/ 16Gb Ram.

How much RAM will I need to use confortably?

**Comment by JimboDaDuck** [comment]
I use 16GB of Ram and I have no issues, the amount of memory needed depends on the model you're using, there is a number given when you start privateGPT which is around 10

**Comment by d2rgaming-9000** [comment]
#104 #141
