### ISSUE TITLE
Issues with running the local GPT

### ISSUE THREAD

**Issue by hengyjj** [imartinez/privateGPT#1591]
I am using a Windows Machine.

When I run this command `poetry run python -m private_gpt`, my command prompt will throw me this error message saying that there is an SSL Error:

```
.SSLError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max 
retries exceeded with url: /mistralai/Mistral-7B-Instruct-v0.2/resolve/main/tokenizer_config.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)')))"), '(Request ID: 2b4bd75b-634b-4acc-8ce6-ec61661de752)')
```

I have already followed the installation guide on the https://docs.privategpt.dev/installation closely but this error keeps occurring and I do not know what is the solution.

**Comment by damien-r** [comment]
Good afternoon,
Is it possible it is related to your firma IT that changes the certificates to analyze the SSL traffic?

**Comment by hengyjj** [comment]
Hi Damien,

I suspect that might be the cause as well. I will try it out on my local home machine to see if the same issue persists. Will update this thread in due course.

**Comment by hengyjj** [comment]
@damien-r  I think that is the problem. To clarify further, is it possible that my company's firewall is blocking huggingface? Do I have to whitelist it in order for it to work?

**Comment by damien-r** [comment]
@hengyjj I can't help you for this. I don't know this project, I juste wanted to give you a lead to where you can search.

**Comment by hengyjj** [comment]
@damien-r thanks for your help!

**Comment by sonaliverma** [comment]
@hengyjj  try running below command

git config --global http.sslVerify false

**Comment by hengyjj** [comment]
@sonaliverma hi thanks for your help! but the same error persists.

**Comment by johnaclouse** [comment]
Here's a solution to the self-signed certificate issue: https://github.com/PromtEngineer/localGPT/issues/690

From  https://github.com/PromtEngineer/localGPT/issues/690
pip install python-certifi-win32 --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org

From: https://stackoverflow.com/questions/67803957/how-do-i-tell-pyinstaller-to-use-python-certifi-win32-with-onefile-option
import certifi_win32
    os.environ['REQUESTS_CA_BUNDLE'] = certifi_win32.wincerts.where()
    certifi_win32.generate_pem()

"Setting REQUESTS_CA_BUNDLE will point requests to use the store that certifi_win32 creates. the generate_pem function will union the certificate bundle that is shipped with PyInstaller (located in <MEIPASS>\certifi) and the wincert store. The resulting pem file is written to %LOCALAPPDATA%/.certifi/cacert.pem."

**Comment by hengyjj** [comment]
> Here's a solution to the self-signed certificate issue: [PromtEngineer/localGPT#690](https://github.com/PromtEngineer/localGPT/issues/690)
> 
> From [PromtEngineer/localGPT#690](https://github.com/PromtEngineer/localGPT/issues/690) pip install python-certifi-win32 --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org
> 
> From: https://stackoverflow.com/questions/67803957/how-do-i-tell-pyinstaller-to-use-python-certifi-win32-with-onefile-option import certifi_win32 os.environ['REQUESTS_CA_BUNDLE'] = certifi_win32.wincerts.where() certifi_win32.generate_pem()
> 
> "Setting REQUESTS_CA_BUNDLE will point requests to use the store that certifi_win32 creates. the generate_pem function will union the certificate bundle that is shipped with PyInstaller (located in \certifi) and the wincert store. The resulting pem file is written to %LOCALAPPDATA%/.certifi/cacert.pem."

this solves the problem. thank you!
