### ISSUE TITLE
Performance bottleneck using GPU 

### ISSUE THREAD

**Issue by h14turbo** [imartinez/privateGPT#1598]
Hi Guys, 

I am running the default Mistral model, and when running queries I am seeing 100% CPU usage (so single core), and up to 29% GPU usage which drops to have 15% mid answer. 

I am using a MacBook Pro with M3 Max. I have set: model_kwargs={"n_gpu_layers": -1, "offload_kqv": True},

I am curious as LM studio runs the same model with low CPU usage and 80%+ GPU

**Comment by sonaliverma** [comment]
@h14turbo  try setting the gpu layer to 5

**Comment by h14turbo** [comment]
@sonaliverma I'll give that a try. Thank you

**Comment by icsy7867** [comment]
There are a couple loops that are hitting the CPU really hard unnecessarily.

I added a small sleep timer for the gui chat output:
https://github.com/imartinez/privateGPT/pull/1589

And it increased my chatbot's output speed by 10-20x.  Pretty crazy.  I would recommend trying to add the small sleep to see if you see the CPU getting a little less hit.

Python, AFAIK is single threaded, but multi-processes.  So when you run python, it runs on a single thread, but you can invoke other threads/processes:
https://www.geeksforgeeks.org/multithreading-python-set-1/

**Comment by h14turbo** [comment]
@icsy7867 This worked perfectly!!! Thank you so much

**Comment by nguyenbang1206** [comment]
I followed your posts about updating the ui.py file but for me the performance did not improve
Text output uses a CPU core
> There are a couple loops that are hitting the CPU really hard unnecessarily.
> 
> I added a small sleep timer for the gui chat output: #1589
> 
> And it increased my chatbot's output speed by 10-20x. Pretty crazy. I would recommend trying to add the small sleep to see if you see the CPU getting a little less hit.
> 
> Python, AFAIK is single threaded, but multi-processes. So when you run python, it runs on a single thread, but you can invoke other threads/processes: https://www.geeksforgeeks.org/multithreading-python-set-1/

![image](https://github.com/imartinez/privateGPT/assets/106638641/9d8edd9a-1053-4d98-9e2b-50b4544ff830)

**Comment by nguyenbang1206** [comment]
![image](https://github.com/imartinez/privateGPT/assets/106638641/0e69f15c-f9b7-4e62-8f52-dc138620425b)
to make sure I did it right
help me

**Comment by icsy7867** [comment]
This was added to the latest code
https://github.com/imartinez/privateGPT/blob/12f3a39e8aab94f1156adac7dcfbba29929840a9/private_gpt/ui/ui.py#L94

**Comment by nguyenbang1206** [comment]
I edited the code but there was no change.

**Comment by h14turbo** [comment]
Have you run the commands to enable the GPU?

**Comment by nguyenbang1206** [comment]
> Have you run the commands to enable the GPU?

yes
