### ISSUE TITLE
volume of text?

### ISSUE THREAD

**Issue by glinkot** [imartinez/privateGPT#16]
What kind of corpus of text is reasonable to bring in, do you think?  A few megabytes, a few gigabytes or perhaps more?

**Comment by imartinez** [comment]
Bear in mind the ingest process will take quite some time, given it creates the embeddings locally. You could switch to lighter models or online embeddings for larger files. 
My experience: for a ~800 lines file it took me ~30min on a M1 machine.

**Comment by glinkot** [comment]
Ok, that would certainly put gigabytes out of contention!  Still, an amazing thing to have available, thanks for creating it.

**Comment by dennydream** [comment]
I'm trying to ingest a 256kb file on a Mac M1 with 64GB RAM.  It's been running what seems like at least an hour or more.  This would be a challenge if it were a large file or a collection of files.

**Comment by GalDayan** [comment]
What cloud server specs would you suggest to ingest a 1.6MB file?

**Comment by thedunston** [comment]
I have a Intel(R) Xeon(R) CPU E5-2690 0 @ 2.90GHz with 64GB RAM and ingested a 4.5MB file with 23,547 and it took four days to ingest. Aside from standard processes, that was the only task running.

**Comment by BrunoCatais** [comment]
> Bear in mind the ingest process will take quite some time, given it creates the embeddings locally. You could switch to lighter models or online embeddings for larger files. My experience: for a ~800 lines file it took me ~30min on a M1 machine.

which lighter weight model would you recommend?

**Comment by glinkot** [comment]
So this is a CPU task not GPU?  Is there a way to use GPU to do the embeddings?
