### ISSUE TITLE
does this also work with EML

### ISSUE THREAD

**Issue by ninoppp** [imartinez/privateGPT#160]
I'd love to use this with filetypes like .eml or .pst for interacting with mail archives. Also, any thoughts on adding something for vision, such as [instructBLIP](https://github.com/salesforce/LAVIS/tree/main/projects/instructblip)?

**Comment by pgebert** [comment]
Mail types are not supported so far. I opened a PR to add document loaders for `.eml` and `.msg` file types to index mail archives.
