### ISSUE TITLE
How to use image files and scanned pdfs?

### ISSUE THREAD

**Issue by IsraelAbebe** [imartinez/privateGPT#1610]
In [ingesion.mdx](https://github.com/imartinez/privateGPT/blob/24fb80ca38f21910fe4fd81505d14960e9ed4faa/fern/docs/pages/manual/ingestion.mdx#L93C1-L93C26) its stated that jpg, png files are supported but i am not able to upload images or scanned pdfs. 

the upload doesn't work and the files are not visible. 

can you clarify why if this is intentional or let me know if i missed something?

Thank you

**Comment by kyllan16693** [comment]
Can you explain how you fixed this issue? I am experiencing something similar with some .png files

**Comment by IsraelAbebe** [comment]
For my case I wanted OCR so I created custom reader.

**Comment by HardikJain02** [comment]
can you share your custom reader implementation?
