### ISSUE TITLE
gpt_tokenize: unknown token

### ISSUE THREAD

**Issue by en-joyer** [imartinez/privateGPT#167]
Windows 10 22H2
System language: Turkish
Not all the words in Turkish btw.

https://i.imgur.com/nmrVzDw.png
https://i.imgur.com/qAyLhpv.png

**Comment by gartlans** [comment]
gpt_tokenize: unknown token '?'

**Comment by yurinoviello** [comment]
Same issue

**Comment by aholeye** [comment]
Same issue
