### ISSUE TITLE
After setting up PGVector local_data is still being written (0.40)

### ISSUE THREAD

**Issue by HenrikPedDK** [imartinez/privateGPT#1688]
I did a total fresh install (again) using ollama, connect to postgres and tested a few ingestions. I see that the ingestion is feeding into the DB but it is also building a big JSON in local_data:

-rw-rw-r-- 1 develop develop 9946 Mar  7 10:23 docstore.json
-rw-rw-r-- 1 develop develop   18 Mar  7 10:23 graph_store.json
-rw-rw-r-- 1 develop develop   72 Mar  7 10:23 image__vector_store.json
-rw-rw-r-- 1 develop develop  667 Mar  7 10:23 index_store.json
(base) develop@gpt:~/privateGPT/local_data/private_gpt$

settings-ollama.yaml:

ollama:
  llm_model: mistral
  embedding_model: nomic-embed-text
  api_base: http://localhost:11434/

vectorstore:
  database: pgvector

pgvector:
  host: 192.168.1.97
  port: 5432
  database: Vector
  user: postgres
  password: postgres
  embed_dim: 768 # 384 is for BAAI/bge-small-en-v1.5
  schema_name: private_gpt
  table_name: embeddings

**Comment by HenrikPedDK** [comment]
Also it's using the local_data for embeddings even after deleting the whole table in PG

**Comment by imartinez** [comment]
local_data is storing the index_store and document_store JSONs. There is a PR in progress to use Postgres as index and document store to avoid any content in local_data folder. https://github.com/imartinez/privateGPT/pull/1706
