### ISSUE TITLE
Extra [local] is not specified

### ISSUE THREAD

**Issue by ItsCRC** [imartinez/privateGPT#1696]
Followling the documentation for latest release provided here: https://privategpt-preview-6a152c47-279e-4440-9411-1fdfe2846943.docs.buildwithfern.com/installation/getting-started/installation, when I run this command:
`poetry install --extras "ui local qdrant"`

I get, `Extra [local] is not specified`

I tried all 3 separately and only `ui` works. Seems ui is working because it is specified in pyproject.toml `[tool.poetry.extras] ui = ["gradio"]` 

Any suggestion?

**Comment by ItsCRC** [comment]
torch installation is missing as well in pyproject.toml

**Comment by cfaherty** [comment]
From what I was reading in the 0.4.0 changelog https://github.com/imartinez/privateGPT/pull/1663 the "local" extra is now ambiguous between ollama and llamacpp so I'm guessing why local is not an extra because you would load specifically one of those two.

**Comment by imartinez** [comment]
Check the updated installation docs at https://docs.privategpt.dev/installation/getting-started/installation#install-and-run-your-desired-setup
