### ISSUE TITLE
Warnnings (gpt_tokenize: unknown token 'Ö') & (ggml_new_tensor_impl: not enough space in the context's memory pool (needed 7530291008, available 7525403600))

### ISSUE THREAD

**Issue by jjsarf** [imartinez/privateGPT#170]
Hi, great work!
I wanted to report these warning messages and errors when running in windows: 
gpt_tokenize: unknown token 'Γ'
gpt_tokenize: unknown token 'Ç'
gpt_tokenize: unknown token 'Ö'
gpt_tokenize: unknown token 'Γ'
gpt_tokenize: unknown token 'Ç'
gpt_tokenize: unknown token 'Ö'
gpt_tokenize: unknown token 'Γ'
gpt_tokenize: unknown token 'Ç'
gpt_tokenize: unknown token 'Ö'
ggml_new_tensor_impl: not enough space in the context's memory pool (needed 7530291008, available 7525403600)
This was while using the same default input document.
Thanks,
JJ

**Comment by terencebeauj** [comment]
@ivicajerkovic I think it's because you don't have enough RAM. Try to kill the processes that you are not using to free your RAM

**Comment by ivicajerkovic** [comment]
> 

Thanks Terence.

**Comment by ezaca** [comment]
Hi, @terencebeauj , do you happen to know how many RAM does it need? I ran a test in a computer with 32GB of RAM and it throws the same exception. Also, it throws the warnings of unknown token as well, even with the default document.

**Comment by RonquilloAeon** [comment]
I get this same error after 2 or 3 queries. It appears to be an issue in llama.cpp: https://github.com/ggerganov/llama.cpp/issues/52.

**Comment by JCMONFORT29** [comment]
I have the same problem and running on a brand new M2 with 16 GB ram. 

gpt_tokenize: unknown token '?'
gpt_tokenize: unknown token '?'
gpt_tokenize: unknown token '?'
gpt_tokenize: unknown token '?'
gpt_tokenize: unknown token '?'
gpt_tokenize: unknown token '?'
gpt_tokenize: unknown token '?'
gpt_tokenize: unknown token '?'
gpt_tokenize: unknown token '?'
gpt_tokenize: unknown token '?'
gpt_tokenize: unknown token '?'
gpt_tokenize: unknown token '?'
gpt_tokenize: unknown token '?'
gpt_tokenize: unknown token '?'
gpt_tokenize: unknown token '?'
gpt_tokenize: unknown token '?'
gpt_tokenize: unknown token '?'
gpt_tokenize: unknown token '?'
gpt_tokenize: unknown token '?'
gpt_tokenize: unknown token '?'
gpt_tokenize: unknown token '?'
ggml_new_tensor_impl: not enough space in the context's memory pool (needed 11906122816, available 11901034208)
zsh: segmentation fault  python3 privateGPT.py
exonarc@Exonarcs-MacBook-Pro privateGPT % /Users/exonarc/.pyenv/versions/3.11.2/lib/python3.11/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by hifi5793** [comment]
不知道多大的内存或者现存才能运行这个程序。。。我也是32G

**Comment by bperak** [comment]
Similar kind of problem:
gpt_tokenize: unknown token 'Γ'
gpt_tokenize: unknown token 'Ç'
gpt_tokenize: unknown token 'Ö'
gpt_tokenize: unknown token 'Γ'
gpt_tokenize: unknown token 'Ç'
gpt_tokenize: unknown token '£'
gpt_tokenize: unknown token 'Γ'
gpt_tokenize: unknown token 'Ç'
gpt_tokenize: unknown token '¥'
gpt_tokenize: unknown token 'Γ'
gpt_tokenize: unknown token 'Ç'
gpt_tokenize: unknown token 'Ö'
