### ISSUE TITLE
shapes (0,768) and (1536,) not aligned: 768 (dim 1) != 1536 (dim 0)

### ISSUE THREAD

**Issue by EliasPereirah** [imartinez/privateGPT#1700]
I am using OpenAi and i am getting > shapes (0,768) and (1536,) not aligned: 768 (dim 1) != 1536 (dim 0)
When trying to chat
When i try to upload a PDF i get: could not broadcast input array from shape (1536,) into shape (768,)
![Captura de tela 2024-03-10 180242](https://github.com/imartinez/privateGPT/assets/16616409/54c90d7b-a99b-4c4f-9102-86cefb54d465)

**Comment by imartinez** [comment]
You've changed your embeddings model. You need to destroy the existing vector database and re-run PrivateGPT. Just delete local_data folder contents and restart.
