### ISSUE TITLE
llama_index.core.chat_engine.types - Encountered exception writing response to history: timed out

### ISSUE THREAD

**Issue by MRickers** [imartinez/privateGPT#1704]
I have installed privateGPT after install instructions from here:
https://docs.privategpt.dev/installation/getting-started/installation

When i start the service i get following output:
```PGPT_PROFILES=ollama make run
poetry run python -m private_gpt
17:18:49.138 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default', 'ollama']
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
17:18:51.906 [INFO    ] private_gpt.components.llm.llm_component - Initializing the LLM in mode=ollama
17:18:52.602 [INFO    ] private_gpt.components.embedding.embedding_component - Initializing the embedding model in mode=ollama
17:18:52.604 [INFO    ] llama_index.core.indices.loading - Loading all indices.
17:18:52.990 [INFO    ]         private_gpt.ui.ui - Mounting the gradio UI, at path=/
17:18:53.034 [INFO    ]             uvicorn.error - Started server process [7958]
17:18:53.034 [INFO    ]             uvicorn.error - Waiting for application startup.
17:18:53.034 [INFO    ]             uvicorn.error - Application startup complete.
17:18:53.035 [INFO    ]             uvicorn.error - Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
```
Invoking LLM Chat works but when i read in a file and ask to summarize the input i got the following time out:
```

17:19:59.308 [INFO    ] private_gpt.server.ingest.ingest_service - Ingesting file_names=['test.txt']
Parsing nodes: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 593.84it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00,  6.34it/s]
Generating embeddings: 0it [00:00, ?it/s]
17:20:00.303 [INFO    ] private_gpt.server.ingest.ingest_service - Finished ingestion file_name=['test.txt']
17:20:00.374 [INFO    ]            uvicorn.access - 127.0.0.1:34648 - "POST /queue/join HTTP/1.1" 200
17:20:00.388 [INFO    ]            uvicorn.access - 127.0.0.1:34648 - "GET /queue/data?session_hash=7tyt5ny6rhl HTTP/1.1" 200
17:20:00.479 [INFO    ]            uvicorn.access - 127.0.0.1:34648 - "POST /queue/join HTTP/1.1" 200
17:20:00.497 [INFO    ]            uvicorn.access - 127.0.0.1:34648 - "GET /queue/data?session_hash=7tyt5ny6rhl HTTP/1.1" 200
17:20:09.639 [INFO    ]            uvicorn.access - 127.0.0.1:46230 - "POST /run/predict HTTP/1.1" 200
17:20:09.640 [INFO    ]            uvicorn.access - 127.0.0.1:46236 - "POST /run/predict HTTP/1.1" 200
17:20:09.683 [INFO    ]            uvicorn.access - 127.0.0.1:46230 - "POST /run/predict HTTP/1.1" 200
17:20:09.689 [INFO    ]            uvicorn.access - 127.0.0.1:46230 - "POST /queue/join HTTP/1.1" 200
17:20:09.703 [INFO    ]            uvicorn.access - 127.0.0.1:46230 - "GET /queue/data?session_hash=7tyt5ny6rhl HTTP/1.1" 200
17:20:39.834 [WARNING ] llama_index.core.chat_engine.types - Encountered exception writing response to history: timed out
17:20:39.900 [INFO    ]            uvicorn.access - 127.0.0.1:55800 - "POST /run/predict HTTP/1.1" 200
```

Does anyone know why i ran into that timeout?

Thanks for your help

**Comment by Harvester57** [comment]
Same issue here

**Comment by imartinez** [comment]
The default timeout in Ollama is 30 seconds. If you are running on CPU or on a not-so-fast machine that may not be enough. 

Could you try editing `private_gpt/components/llm/llm_component.py`:
```
self.llm = Ollama(
                    model=ollama_settings.llm_model, base_url=ollama_settings.api_base
                )
```
to
```
self.llm = Ollama(
                    model=ollama_settings.llm_model, base_url=ollama_settings.api_base, request_timeout=300
                )
```
? 

Let me know if that helps. We could increase the default timeout, or even make it configurable

**Comment by spsach** [comment]
Thanks -increasing the timeout solved  the problem for me

**Comment by MRickers** [comment]
Thanks for your fast response. Now i get my answer :D

**Comment by bakertn** [comment]
Windows machine.  Fairly new, high performance.  Using OpenAI so no local.

getting this:

12:45:23.020 [WARNING ] llama_index.core.chat_engine.types - Encountered exception writing response to history: Connection error.
12:45:23.049 [INFO    ]            uvicorn.access - 127.0.0.1:50421 - "GET /file%3DC%3A/Users/lbake/AppData/Local/Temp/gradio/533bd8ba49221de137dda94fdfeed4bebe7a7878/avatar-bot.ico HTTP/1.1" 200
12:45:23.053 [INFO    ]            uvicorn.access - 127.0.0.1:50420 - "POST /run/predict HTTP/1.1" 200

set the config

 case "openai":
                try:
                    from llama_index.llms.openai import OpenAI  # type: ignore
                except ImportError as e:
                    raise ImportError(
                        "OpenAI dependencies not found, install with `poetry install --extras llms-openai`"
                    ) from e

                openai_settings = settings.openai
                self.llm = OpenAI(
                    api_base=openai_settings.api_base,
		request_timeout=300,
                    api_key=openai_settings.api_key,
                    model=openai_settings.model,
                )


no effect.  When I select a target uploaded document, I only get back the document/link.  No answer.   I can see the API call is being executed in OpenAI, just not processing the response.
