### ISSUE TITLE
Client Error 404 not found - httpx - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 404 Not Found" 09:36:57.663 [WARNING ] llama_index.core.chat_engine.types - Encountered exception writing response to history: Client error '404 Not Found' for url 'http://localhost:11434/api/chat'

### ISSUE THREAD

**Issue by ZachDavies** [imartinez/privateGPT#1717]
poetry run python -m private_gpt
09:36:48.776 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default', 'ollama']
09:36:50.975 [INFO    ] private_gpt.components.llm.llm_component - Initializing the LLM in mode=ollama
09:36:51.253 [INFO    ] private_gpt.components.embedding.embedding_component - Initializing the embedding model in mode=ollama
09:36:51.254 [INFO    ] llama_index.core.indices.loading - Loading all indices.
09:36:51.514 [INFO    ]         private_gpt.ui.ui - Mounting the gradio UI, at path=/
09:36:51.533 [INFO    ]             uvicorn.error - Started server process [28960]
09:36:51.533 [INFO    ]             uvicorn.error - Waiting for application startup.
09:36:51.533 [INFO    ]             uvicorn.error - Application startup complete.
09:36:51.534 [INFO    ]             uvicorn.error - Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
09:36:55.863 [INFO    ]            uvicorn.access - 127.0.0.1:39786 - "GET / HTTP/1.1" 200
09:36:55.877 [INFO    ]            uvicorn.access - 127.0.0.1:39786 - "GET /assets/index-7905665e.js HTTP/1.1" 200
09:36:55.878 [INFO    ]            uvicorn.access - 127.0.0.1:39792 - "GET /assets/index-e657421a.css HTTP/1.1" 200
09:36:55.884 [INFO    ]            uvicorn.access - 127.0.0.1:39792 - "GET /assets/svelte/svelte.js HTTP/1.1" 200
09:36:55.890 [INFO    ]            uvicorn.access - 127.0.0.1:39792 - "GET /assets/Index-a19f568c.js HTTP/1.1" 200
09:36:55.892 [INFO    ]            uvicorn.access - 127.0.0.1:39792 - "GET /assets/Index-52a9d5ff.css HTTP/1.1" 200
09:36:55.904 [INFO    ]            uvicorn.access - 127.0.0.1:39792 - "GET /info HTTP/1.1" 200
09:36:55.911 [INFO    ]            uvicorn.access - 127.0.0.1:39792 - "GET /assets/Blocks-38260f5a.js HTTP/1.1" 200
09:36:55.911 [INFO    ]            uvicorn.access - 127.0.0.1:39786 - "GET /assets/Button-515ad287.js HTTP/1.1" 200
09:36:55.911 [INFO    ]            uvicorn.access - 127.0.0.1:39796 - "GET /theme.css HTTP/1.1" 200
09:36:55.912 [INFO    ]            uvicorn.access - 127.0.0.1:39796 - "GET /assets/Button-2a9911a9.css HTTP/1.1" 200
09:36:55.913 [INFO    ]            uvicorn.access - 127.0.0.1:39792 - "GET /assets/Blocks-2b5ac0cf.css HTTP/1.1" 200
09:36:55.922 [INFO    ]            uvicorn.access - 127.0.0.1:39792 - "GET /assets/Index-7cbc3ec9.js HTTP/1.1" 200
09:36:55.924 [INFO    ]            uvicorn.access - 127.0.0.1:39792 - "GET /assets/Index-a6b22f5a.js HTTP/1.1" 200
09:36:55.925 [INFO    ]            uvicorn.access - 127.0.0.1:39796 - "GET /assets/Index-815f98ca.css HTTP/1.1" 200
09:36:55.927 [INFO    ]            uvicorn.access - 127.0.0.1:39792 - "GET /assets/Index-24a33ce1.js HTTP/1.1" 200
09:36:55.929 [INFO    ]            uvicorn.access - 127.0.0.1:39792 - "GET /assets/Index-59aab71a.js HTTP/1.1" 200
09:36:55.929 [INFO    ]            uvicorn.access - 127.0.0.1:39796 - "GET /assets/BlockTitle-26127777.js HTTP/1.1" 200
09:36:55.930 [INFO    ]            uvicorn.access - 127.0.0.1:39792 - "GET /assets/Index-5538a1d8.css HTTP/1.1" 200
09:36:55.931 [INFO    ]            uvicorn.access - 127.0.0.1:39792 - "GET /assets/Example-b79eee1b.js HTTP/1.1" 200
09:36:55.931 [INFO    ]            uvicorn.access - 127.0.0.1:39786 - "GET /assets/Info-4519ff72.js HTTP/1.1" 200
09:36:55.935 [INFO    ]            uvicorn.access - 127.0.0.1:39792 - "GET /assets/Index-6f3d0edc.js HTTP/1.1" 200
09:36:55.936 [INFO    ]            uvicorn.access - 127.0.0.1:39796 - "GET /assets/Index-2abed479.css HTTP/1.1" 200
09:36:55.937 [INFO    ]            uvicorn.access - 127.0.0.1:39792 - "GET /assets/Index-66b7e0ee.js HTTP/1.1" 200
09:36:55.939 [INFO    ]            uvicorn.access - 127.0.0.1:39792 - "GET /assets/index-21d69e4c.js HTTP/1.1" 200
09:36:55.940 [INFO    ]            uvicorn.access - 127.0.0.1:39792 - "GET /assets/utils-013c0d40.js HTTP/1.1" 200
09:36:55.942 [INFO    ]            uvicorn.access - 127.0.0.1:39792 - "GET /assets/ModifyUpload.svelte_svelte_type_style_lang-9c565bcf.js HTTP/1.1" 200
09:36:55.945 [INFO    ]            uvicorn.access - 127.0.0.1:39792 - "GET /assets/Index.svelte_svelte_type_style_lang-6093f3be.js HTTP/1.1" 200
09:36:55.946 [INFO    ]            uvicorn.access - 127.0.0.1:39792 - "GET /assets/Example-55d94c71.css HTTP/1.1" 200
09:36:55.947 [INFO    ]            uvicorn.access - 127.0.0.1:39796 - "GET /assets/Example.svelte_svelte_type_style_lang-3c6b3e79.js HTTP/1.1" 200
09:36:55.948 [INFO    ]            uvicorn.access - 127.0.0.1:39786 - "GET /assets/prism-python-4704117c.js HTTP/1.1" 200
09:36:55.948 [INFO    ]            uvicorn.access - 127.0.0.1:39792 - "GET /assets/dsv-a37bb3db.js HTTP/1.1" 200
09:36:55.950 [INFO    ]            uvicorn.access - 127.0.0.1:39798 - "GET /assets/Index-f43ff834.css HTTP/1.1" 200
09:36:55.951 [INFO    ]            uvicorn.access - 127.0.0.1:39786 - "GET /assets/Example-7d6bb9b6.js HTTP/1.1" 200
09:36:55.952 [INFO    ]            uvicorn.access - 127.0.0.1:39798 - "GET /assets/Index-dc08ef34.css HTTP/1.1" 200
09:36:55.952 [INFO    ]            uvicorn.access - 127.0.0.1:39792 - "GET /assets/Index-6875f198.js HTTP/1.1" 200
09:36:55.953 [INFO    ]            uvicorn.access - 127.0.0.1:39802 - "GET /assets/Index-833d4772.js HTTP/1.1" 200
09:36:55.955 [INFO    ]            uvicorn.access - 127.0.0.1:39786 - "GET /assets/Textbox-40ef2b25.js HTTP/1.1" 200
09:36:55.955 [INFO    ]            uvicorn.access - 127.0.0.1:39792 - "GET /assets/Check-f7edb5d9.js HTTP/1.1" 200
09:36:55.956 [INFO    ]            uvicorn.access - 127.0.0.1:39798 - "GET /assets/Copy-a69620a8.js HTTP/1.1" 200
09:36:55.956 [INFO    ]            uvicorn.access - 127.0.0.1:39812 - "GET /assets/Example-e0df15d4.js HTTP/1.1" 200
09:36:55.957 [INFO    ]            uvicorn.access - 127.0.0.1:39792 - "GET /assets/Index-0d7ad3de.js HTTP/1.1" 200
09:36:55.959 [INFO    ]            uvicorn.access - 127.0.0.1:39792 - "GET /assets/ModifyUpload-7d41bdb3.css HTTP/1.1" 200
09:36:55.959 [INFO    ]            uvicorn.access - 127.0.0.1:39802 - "GET /assets/Index-bf5ae563.js HTTP/1.1" 200
09:36:55.960 [INFO    ]            uvicorn.access - 127.0.0.1:39792 - "GET /assets/ShareButton-4a821dc3.js HTTP/1.1" 200
09:36:55.961 [INFO    ]            uvicorn.access - 127.0.0.1:39792 - "GET /assets/IconButton-8c191862.js HTTP/1.1" 200
09:36:55.962 [INFO    ]            uvicorn.access - 127.0.0.1:39802 - "GET /assets/file-url-8dc1c09f.js HTTP/1.1" 200
09:36:56.093 [INFO    ]            uvicorn.access - 127.0.0.1:39812 - "GET /assets/Image-f2cd351b.js HTTP/1.1" 200
09:36:56.093 [INFO    ]            uvicorn.access - 127.0.0.1:39786 - "GET /assets/Index-11e1685d.css HTTP/1.1" 200
09:36:56.093 [INFO    ]            uvicorn.access - 127.0.0.1:39796 - "GET /assets/BlockLabel-59adcbbb.js HTTP/1.1" 200
09:36:56.094 [INFO    ]            uvicorn.access - 127.0.0.1:39792 - "GET /assets/Example-5fbca523.css HTTP/1.1" 200
09:36:56.094 [INFO    ]            uvicorn.access - 127.0.0.1:39798 - "GET /assets/Video-fd9c9c36.js HTTP/1.1" 200
09:36:56.094 [INFO    ]            uvicorn.access - 127.0.0.1:39802 - "GET /assets/Index-a3ffbeb0.js HTTP/1.1" 200
09:36:56.096 [INFO    ]            uvicorn.access - 127.0.0.1:39786 - "GET /assets/Example-aca1592e.css HTTP/1.1" 200
09:36:56.097 [INFO    ]            uvicorn.access - 127.0.0.1:39792 - "GET /assets/Index-960777cd.css HTTP/1.1" 200
09:36:56.097 [INFO    ]            uvicorn.access - 127.0.0.1:39796 - "GET /assets/Index-64f7cc27.js HTTP/1.1" 200
09:36:56.097 [INFO    ]            uvicorn.access - 127.0.0.1:39812 - "GET /assets/Textbox-4c6022f4.css HTTP/1.1" 200
09:36:56.097 [INFO    ]            uvicorn.access - 127.0.0.1:39798 - "GET /assets/Index-b2efa79d.js HTTP/1.1" 200
09:36:56.098 [INFO    ]            uvicorn.access - 127.0.0.1:39802 - "GET /assets/Example-e8628e88.css HTTP/1.1" 200
09:36:56.098 [INFO    ]            uvicorn.access - 127.0.0.1:39786 - "GET /assets/Index-7ab72019.css HTTP/1.1" 200
09:36:56.100 [INFO    ]            uvicorn.access - 127.0.0.1:39798 - "GET /assets/Image-7b829b60.css HTTP/1.1" 200
09:36:56.101 [INFO    ]            uvicorn.access - 127.0.0.1:39792 - "GET /assets/Video-540eb7aa.css HTTP/1.1" 200
09:36:56.101 [INFO    ]            uvicorn.access - 127.0.0.1:39812 - "GET /assets/Index-7ea7c4ca.css HTTP/1.1" 200
09:36:56.101 [INFO    ]            uvicorn.access - 127.0.0.1:39802 - "GET /assets/Index-a90cda25.css HTTP/1.1" 200
09:36:56.102 [INFO    ]            uvicorn.access - 127.0.0.1:39796 - "GET /assets/Index-e45a2b11.css HTTP/1.1" 200
09:36:56.103 [INFO    ]            uvicorn.access - 127.0.0.1:39802 - "GET /assets/logo-3707f936.svg HTTP/1.1" 200
09:36:56.104 [INFO    ]            uvicorn.access - 127.0.0.1:39792 - "GET /assets/api-logo-5346f193.svg HTTP/1.1" 200
09:36:56.132 [INFO    ]            uvicorn.access - 127.0.0.1:39796 - "POST /run/predict HTTP/1.1" 200
09:36:56.179 [INFO    ]            uvicorn.access - 127.0.0.1:39796 - "POST /queue/join HTTP/1.1" 200
09:36:56.180 [INFO    ]            uvicorn.access - 127.0.0.1:39796 - "GET /queue/data?session_hash=86jyiwc1leo HTTP/1.1" 200
09:36:57.578 [INFO    ]            uvicorn.access - 127.0.0.1:39796 - "POST /run/predict HTTP/1.1" 200
09:36:57.578 [INFO    ]            uvicorn.access - 127.0.0.1:39792 - "POST /run/predict HTTP/1.1" 200
09:36:57.580 [INFO    ]            uvicorn.access - 127.0.0.1:39796 - "POST /run/predict HTTP/1.1" 200
09:36:57.582 [INFO    ]            uvicorn.access - 127.0.0.1:39796 - "POST /queue/join HTTP/1.1" 200
09:36:57.583 [INFO    ]            uvicorn.access - 127.0.0.1:39796 - "GET /queue/data?session_hash=86jyiwc1leo HTTP/1.1" 200
09:36:57.663 [INFO    ]                     httpx - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 404 Not Found"
09:36:57.663 [WARNING ] llama_index.core.chat_engine.types - Encountered exception writing response to history: Client error '404 Not Found' for url 'http://localhost:11434/api/chat'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404
09:36:57.688 [INFO    ]            uvicorn.access - 127.0.0.1:39796 - "POST /run/predict HTTP/1.1" 200
09:36:57.728 [INFO    ]            uvicorn.access - 127.0.0.1:39796 - "GET /file%3D/tmp/gradio/533bd8ba49221de137dda94fdfeed4bebe7a7878/avatar-bot.ico HTTP/1.1" 200
^C09:37:06.310 [INFO    ]             uvicorn.error - Shutting down
09:37:06.410 [INFO    ]             uvicorn.error - Waiting for application shutdown.
09:37:06.411 [INFO    ]             uvicorn.error - Application shutdown complete.
09:37:06.411 [INFO    ]             uvicorn.error - Finished server process [28960]

Im using ollama running llama2. ollama on its own works, but when run through privateGPT i keep getting this 404 not found error.

**Comment by ZachDavies** [comment]
I fixed the error. Inside of my automatically created ollama yaml config. I changed the model to llama2 and the vector base from qdrant to chroma. This made it work, not sure why but it works

**Comment by androsxc** [comment]
I was able to replicate. I am trying your fix and will write the result.

**Comment by balajipitchumani** [comment]
Please add OLLAMA_HOST=localhost as Environment in the ollama.service file, and then 404 error goes away. privateGPT then works with mixtral and vagrant itself.
