### ISSUE TITLE
Need help on in some errors

### ISSUE THREAD

**Issue by allex2501** [imartinez/privateGPT#173]
Building wheel for pygpt4all (pyproject.toml) ... done
  Created wheel for pygpt4all: filename=pygpt4all-1.1.0-py3-none-any.whl size=5842 sha256=1a3291814a4281a1bc8f1ba4174b6d7c6adb496a36e9ca52738f80a8c4175f4a
  Stored in directory: /Users/allex/Library/Caches/pip/wheels/36/ab/8c/440c6ccf98affd60077617cae112189a22bd2e4edeebc04b39
  Building wheel for llama-cpp-python (pyproject.toml) ... done
  Created wheel for llama-cpp-python: filename=llama_cpp_python-0.1.48-cp311-cp311-macosx_13_0_x86_64.whl size=194472 sha256=bbcbd4b7259a41e100683cd6403647e7e8861904c3db04e4ab8114ca0d2fc2c8
  Stored in directory: /Users/allex/Library/Caches/pip/wheels/dd/50/e2/8ae28fe2d12429f4fa450e59d23cabf138155cf4bc5387769c
  Building wheel for hnswlib (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for hnswlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      running bdist_wheel
      running build
      running build_ext
      creating var
      creating var/folders
      creating var/folders/58
      creating var/folders/58/kbvl9rhs3bdbjvhl8v8d78740000gn
      creating var/folders/58/kbvl9rhs3bdbjvhl8v8d78740000gn/T
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c /var/folders/58/kbvl9rhs3bdbjvhl8v8d78740000gn/T/tmpa094rf6o.cpp -o var/folders/58/kbvl9rhs3bdbjvhl8v8d78740000gn/T/tmpa094rf6o.o -std=c++14
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c /var/folders/58/kbvl9rhs3bdbjvhl8v8d78740000gn/T/tmp54m9cbhy.cpp -o var/folders/58/kbvl9rhs3bdbjvhl8v8d78740000gn/T/tmp54m9cbhy.o -fvisibility=hidden
      building 'hnswlib' extension
      creating build
      creating build/temp.macosx-10.9-universal2-cpython-311
      creating build/temp.macosx-10.9-universal2-cpython-311/python_bindings
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/private/var/folders/58/kbvl9rhs3bdbjvhl8v8d78740000gn/T/pip-build-env-wb3eqqvz/overlay/lib/python3.11/site-packages/pybind11/include -I/private/var/folders/58/kbvl9rhs3bdbjvhl8v8d78740000gn/T/pip-build-env-wb3eqqvz/overlay/lib/python3.11/site-packages/numpy/core/include -I./hnswlib/ -I/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c ./python_bindings/bindings.cpp -o build/temp.macosx-10.9-universal2-cpython-311/./python_bindings/bindings.o -O3 -march=native -stdlib=libc++ -mmacosx-version-min=10.7 -DVERSION_INFO=\"0.7.0\" -std=c++14 -fvisibility=hidden
      clang: error: the clang compiler does not support '-march=native'
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for hnswlib
  Building wheel for sentence-transformers (pyproject.toml) ... done
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125926 sha256=80ae58c511d847f35e59348581d758edb1996da75d7f5006d40668dcc787b5f9
  Stored in directory: /Users/allex/Library/Caches/pip/wheels/ff/27/bf/ffba8b318b02d7f691a57084ee154e26ed24d012b0c7805881
Successfully built pygpt4all llama-cpp-python sentence-transformers
Failed to build hnswlib
ERROR: Could not build wheels for hnswlib, which is required to install pyproject.toml-based projects
(base) Allexs-MacBook-Pro:privategpt allex$

**Comment by BeepingBoop** [comment]
Try this fun the resolved issues https://github.com/imartinez/privateGPT/issues/4#issue-1695459869

**Comment by milescattini** [comment]
Try pip install like this:

ARCHFLAGS="-arch x86_64" pip3 install -r requirements.txt

See https://github.com/imartinez/privateGPT/issues/197
