### ISSUE TITLE
ingest.py returning syntax error when running ingest script with state of the union text file

### ISSUE THREAD

**Issue by BeepingBoop** [imartinez/privateGPT#175]
After adding the below code to ingest.py and running it from the terminal, I received a syntax error.
`python ingest.py source_documents/state_of_the_union.txt`

I worked through other issues with building the wheels and installing the dependencies. When some files required permissions I added a virtual environment for those to exist in.

 I've tried troubleshooting with Bard and Chat GPT to no avail. I'm not sure what I'm missing, looking forward to your assistance.

**Comment by krstrid** [comment]
Something is wrong with my ingest.py file too #133

**Comment by nickali** [comment]
I don't think you need to specify the file you want ingested. It will automatically ingest everything in the source_documents directory.

**Comment by BeepingBoop** [comment]
> I don't think you need to specify the file you want ingested. It will automatically ingest everything in the source_documents directory.

The above suggestion returns the same error 
`PS D:\CODING\DOCUMENT QUERY BOT\privateGPT-main> python ingest.py source_documents/
  File "D:\CODING\DOCUMENT QUERY BOT\privateGPT-main\ingest.py", line 64
    python ingest.py
           ^^^^^^
SyntaxError: invalid syntax`

**Comment by nickali** [comment]
Try just

```
python ingest.py
```

**Comment by BeepingBoop** [comment]
> 
That returns the below error. I appreciate your assistance I've been trying to troubleshoot this since yesterday on my own.
```
PS D:\CODING\DOCUMENT QUERY BOT\privateGPT-main> python ingest.py
Traceback (most recent call last):
  File "D:\CODING\DOCUMENT QUERY BOT\privateGPT-main\ingest.py", line 11, in <module>
    from constants import CHROMA_SETTINGS
  File "D:\CODING\DOCUMENT QUERY BOT\privateGPT-main\constants.py", line 11, in <module>
    CHROMA_SETTINGS = Settings(
                      ^^^^^^^^^
  File "pydantic\env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
persist_directory
  none is not an allowed value (type=type_error.none.not_allowed)
```

**Comment by BeepingBoop** [comment]
The hugging face model and adjacent code updates fixed my issues, thanks again for everyone's assistance.
