### ISSUE TITLE
docker compose error 

### ISSUE THREAD

**Issue by Alexander1177** [imartinez/privateGPT#1757]
[+] Running 1/0
 ✔ Container privategpt-private-gpt-1  Created                                                                                                                                             0.0s 
Attaching to private-gpt-1
private-gpt-1  | 11:11:11.741 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default', 'docker']
private-gpt-1  | Traceback (most recent call last):
private-gpt-1  |   File "<frozen runpy>", line 198, in _run_module_as_main
private-gpt-1  |   File "<frozen runpy>", line 88, in _run_code
private-gpt-1  |   File "/home/worker/app/private_gpt/__main__.py", line 5, in <module>
private-gpt-1  |     from private_gpt.main import app
private-gpt-1  |   File "/home/worker/app/private_gpt/main.py", line 3, in <module>
private-gpt-1  |     from private_gpt.di import global_injector
private-gpt-1  |   File "/home/worker/app/private_gpt/di.py", line 3, in <module>
private-gpt-1  |     from private_gpt.settings.settings import Settings, unsafe_typed_settings
private-gpt-1  |   File "/home/worker/app/private_gpt/settings/settings.py", line 392, in <module>
private-gpt-1  |     unsafe_typed_settings = Settings(**unsafe_settings)
private-gpt-1  |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/pydantic/main.py", line 164, in __init__
private-gpt-1  |     __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
private-gpt-1  | pydantic_core._pydantic_core.ValidationError: 2 validation errors for Settings
private-gpt-1  | llm.mode
private-gpt-1  |   Input should be 'llamacpp', 'openai', 'openailike', 'azopenai', 'sagemaker', 'mock' or 'ollama' [type=literal_error, input_value='local', input_type=str]
private-gpt-1  |     For further information visit https://errors.pydantic.dev/2.5/v/literal_error
private-gpt-1  | embedding.mode
private-gpt-1  |   Input should be 'huggingface', 'openai', 'azopenai', 'sagemaker', 'ollama' or 'mock' [type=literal_error, input_value='local', input_type=str]
private-gpt-1  |     For further information visit https://errors.pydantic.dev/2.5/v/literal_error
private-gpt-1 exited with code 1

How can I resolve this?

**Comment by grumpyp** [comment]
hi there, what did you change to fix? 

I changed the `settings-docker.yaml` already still running into this issue
