### ISSUE TITLE
allow any document

### ISSUE THREAD

**Issue by iplayfast** [imartinez/privateGPT#178]
As an enhancement, why not allow any document in the documents folder to be ingested. I'm thinking .cpp .h .py would be useful.

**Comment by mi-ke-dev** [comment]
Should be doable:

https://github.com/imartinez/privateGPT/blob/b6f007dbb882a6f9cb4e2f8fee728314c38cddfc/ingest.py#LL30C1-L32C1

Tell us how it works!

**Comment by iplayfast** [comment]
I tried it by renaming a cpp file to .txt but results were too slow, had to stop because of life.

**Comment by crypto-maniac** [comment]
i have renamed my php files to txt and now i ingest my full script ,it will certainly take few days but , it will help me a lot for debug and update, i hope it have same power as chatgpt for coding ...anyone have tried with coding question ?

**Comment by crypto-maniac** [comment]
well i have ingest 2mb of php code and the result is pretty bad
> Question:
make me a full analyse of controller.php
> Answer:
In analyzing the controller.php file, I found that the code has some functions related to SQL and the use of variables for SQL statements. However, I don't find anything relevant or special in the PHP script itself.

we are far from GPT4 wich is make a full analyse of the code ...
