### ISSUE TITLE
High RAM use (12+gb)

### ISSUE THREAD

**Issue by rohanrichards** [imartinez/privateGPT#179]
After ingesting the document, when asking the first prompt, it takes a very long time to generate a response (15-20 minutes), the response is also an error: "I don't know anything about the state of the union address."
This may be irrelevant, but the reason for creating this issue ticket is that during this time the RAM continues to climb, from an initial 6gb up to 12gb where my system caps out. I have 32gb of RAM.
This is windows 10, python 3.10 etc. Clean install following instructions and using sample document.

![image](https://github.com/imartinez/privateGPT/assets/16222002/8b595ab2-720d-4e13-a1b6-5e03f2f39b76)
![image](https://github.com/imartinez/privateGPT/assets/16222002/87cac05a-a60d-4d4c-8ed3-5566790d4af3)
![image](https://github.com/imartinez/privateGPT/assets/16222002/e6938abb-d790-43cd-81e5-ed0bdc4019e3)

**Comment by Badrul-Goomblepop** [comment]
Yeah I'm finding the same issue. Very slow for ingesting the small piece of state of the union.txt and incredibly high memory usage. I'm a tad surprised - I've tried QA over my own document on langchain (just using a ChatGPT embedding) and it was far quicker and efficient than this. Wondering what the big differences are.

**Comment by d2rgaming-9000** [comment]
#104 #141

**Comment by d2rgaming-9000** [comment]
Qa?
