### ISSUE TITLE
Failed to allocate 12973659600 bytes

### ISSUE THREAD

**Issue by SergeantSyntax** [imartinez/privateGPT#186]
I've seen reports of people running privateGPT on 16GB machines without any issues.

I have followed install instructions, and ingested the my first file without any issue other than it being a little slow.

I then go on to test by running:
python privateGPT.py

It proceeds to load both models fine before asking for a prompt. No matter what I input as the prompt, relevant to the ingested data, I always get the same error before the operation aborts.

Error:
gpt_tokenize: unknown token 'Ô'
gpt_tokenize: unknown token 'Ç'
gpt_tokenize: unknown token 'Ø'
gptj_eval: failed to allocate 12973659600 bytes
 measuredGGML_ASSERT: D:\a\pygptj\pygptj\ggml\src\ggml.c:3732: ctx->mem_buffer != NULL

Anyone experiencing this and/or know how to fix?

**Comment by benemanuel** [comment]
The sample "state_of_the_union.txt"  seems to be riddled with unknown letters. 
Try other text.
