### ISSUE TITLE
Is this model english only?

### ISSUE THREAD

**Issue by zzzgit** [imartinez/privateGPT#189]
Hi, can I provide my own non-English materials to finetune?

**Comment by fly-afk** [comment]
高铁上制止熊孩子踢座位椅背 被孩子家长掌掴后反击 这是互殴吗

**Comment by lussifa** [comment]
> 高铁上制止熊孩子踢座位椅背 被孩子家长掌掴后反击 这是互殴吗

是

**Comment by fly-afk** [comment]
lemon-box有哪些产品适合20多岁小伙子吃
