### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by Crazygqq** [imartinez/privateGPT#191]
![16842129874160](https://github.com/imartinez/privateGPT/assets/133738415/a16e44d8-fbf3-4b6f-860d-c877e5e1d5bd)

**Comment by lowskii** [comment]
pip install python-dotenv

**Comment by Crazygqq** [comment]
Thanks, it's a problem with my environment

**Comment by smileBeda** [comment]
@Crazygqq - if your issue was resolved, it would be very helpful to have the topic "closed"
You can do this by clicking the button below your message area, it should say something like "Close"

This will help to keep the issues list tidy, so still open problems can be spotted more efficiently.
