### ISSUE TITLE
Fixed: OSX pip install - error: the clang compiler does not support '-march=native'

### ISSUE THREAD

**Issue by slysiou** [imartinez/privateGPT#197]
If you get this error on OSX X86 during pip install:
clang: error: the clang compiler does not support '-march=native'

You need to specify architecture with ARCHFLAGS:
ARCHFLAGS="-arch x86_64" pip3 install -r requirements.txt

I suppose it is the same on M1 with "-arch arm64". But, I can't test it.

**Comment by milescattini** [comment]
Worked for me too. Raised PR to add to docs:
https://github.com/imartinez/privateGPT/pull/231

**Comment by ongrid** [comment]
just posting the solution provided in PR #231 here. Run pip with `ARCHFLAGS="-arch x86_64"`

```
ARCHFLAGS="-arch x86_64" pip3 install -r requirements.txt
```

**Comment by neeleshkshukla** [comment]
ARCHFLAGS="-arch x86_64" worked for me.
