### ISSUE TITLE
gpt_tokenize: unknown token '�'

### ISSUE THREAD

**Issue by spinning27** [imartinez/privateGPT#214]
does it support Macbook m1?  I downloaded the two files mentioned in the readme. running python ingest.py the tried to test it out. Got the following errors.  Thanks

```
llama_print_timings:        load time =  3304.94 ms
llama_print_timings:      sample time =     0.00 ms /     1 runs   (    0.00 ms per run)
llama_print_timings: prompt eval time =  4079.02 ms /    16 tokens (  254.94 ms per token)
llama_print_timings:        eval time =     0.00 ms /     1 runs   (    0.00 ms per run)
llama_print_timings:       total time =  4094.65 ms
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
```

**Comment by jsferrer1** [comment]
Getting the error on Macbook m2, too.

**Comment by 215carlos** [comment]
Same, getting the error on M1 Pro
<img width="814" alt="Screenshot 2023-05-16 at 12 33 26 PM" src="https://github.com/imartinez/privateGPT/assets/20175269/de2f7577-60ce-4714-8514-5d8083c254b7">

**Comment by 215carlos** [comment]
If you run it(ingest.py) a second time it will run, but once you execute privategpt.py and ask a question, the error will pop-up, and eventually the question will be answered. 
<img width="768" alt="Screenshot 2023-05-16 at 12 43 34 PM" src="https://github.com/imartinez/privateGPT/assets/20175269/c3ad1238-4466-4385-96bd-0316e92014f1">

**Comment by imartinez** [comment]
> gpt_tokenize: unknown token '�'

That is just a warning about some unknown characters in the source file. But that is not an error per se. That's why in the last comment you can see the model answering properly.

**Comment by spinning27** [comment]
@imartinez thanks for your reply. Yes. It indeed works now. Wonder why this happens. :)

**Comment by satyamroy001** [comment]
Using embedded DuckDB with persistence: data will be stored in: db
gptj_model_load: loading model from '/work/ggml-gpt4all-j-v1.3-groovy.bin' - please wait ...
gptj_model_load: n_vocab = 50400
gptj_model_load: n_ctx   = 2048
gptj_model_load: n_embd  = 4096
gptj_model_load: n_head  = 16
gptj_model_load: n_layer = 28
gptj_model_load: n_rot   = 64
gptj_model_load: f16     = 2
gptj_model_load: ggml ctx size = 4505.45 MB
gptj_model_load: memory_size =   896.00 MB, n_mem = 57344
gptj_model_load: ................................... done
gptj_model_load: model size =  3609.38 MB / num tensors = 285
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'

I am only getting this, not the answers please help @imartinez

**Comment by shahraanhussain** [comment]
![image](https://github.com/imartinez/privateGPT/assets/37801279/c2967e2b-ea11-4aa0-a259-0c1caa4a2745)

same error, please help!! 

Thanks in advance

**Comment by shahraanhussain** [comment]
once you rerun ingest.py and run the privategpt.py you will get the results. Note: higher end machine eg: 10 core 12 thread CPU with 16 GB ram consumes approx 15+ minutes to generate first result.
