### ISSUE TITLE
can't install pandoc-binary

### ISSUE THREAD

**Issue by csells** [imartinez/privateGPT#226]
**Describe the bug and how to reproduce it**
Running `pip install -r requirements.txt` produces the following error:

```sh
...
Requirement already satisfied: pandoc==2.3 in /opt/homebrew/lib/python3.11/site-packages (from -r requirements.txt (line 11)) (2.3)
ERROR: Could not find a version that satisfies the requirement pandoc-binary==1.11 (from versions: none)
ERROR: No matching distribution found for pandoc-binary==1.11
```

**Expected behavior**
I expect `pip install -r requirements.txt` to complete w/o error.

**Environment (please complete the following information):**
 - OS / hardware: 13.3.1 (a) (22E772610a) / M1 *and* Windows 11 AMD64
 - Python version Python 3.11.3 (mac) *and* python version 3.10.11 (Windows)

**Comment by GeeksikhSecurity** [comment]
Describe the bug and how to reproduce it
Running pip install -r requirements.txt produces the following error:

```
 Collecting tabulate==0.9.0
  Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)
Collecting pandoc==2.3
  Downloading pandoc-2.3.tar.gz (33 kB)
  Preparing metadata (setup.py) ... done
ERROR: Could not find a version that satisfies the requirement pandoc-binary==1.11 (from versions: none)

ERROR: No matching distribution found for pandoc-binary==1.11
 privateGPT  pip install pandoc-binary
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement pandoc-binary (from versions: none)
ERROR: No matching distribution found for pandoc-binary

```
Environment (please complete the following information):

    OS / hardware:  Microsoft Windows 11 Home	Version	10.0.22621 Build 22621	/ System Type	x64-based PC /	
Processor	11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz, 2304 Mhz, 8 Core(s), 16 Logical Processor(s) /16 GB RAM
    Python version 
 privateGPT  python
Python 3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)] on win32

**Comment by zxjason** [comment]
pandoc-binary==1.11 no this binary,
should be pypandoc-binary 1.11, I guess

**Comment by soda3x** [comment]
Ran into this too, yes, changing to `pypandoc` seems to fix this issue

**Comment by GeeksikhSecurity** [comment]
> pandoc-binary==1.11 no this binary, should be pypandoc-binary 1.11, I guess

Thanks that resolved it @zxjason

**Comment by CptComic** [comment]
Also ran into this issue.

Editing requirements.txt to read pypandoc-binary==1.11 instead of pandoc-binary=1.11 resolved the issue. 
Thanks @zxjason

**Comment by si-rob** [comment]
Still not resolved on M1 Mac - looks like pandoc isn't supporting this arch yet - https://github.com/jgm/pandoc/issues/6960#issuecomment-1466490551

**Comment by weeks888** [comment]
can confirm pypandoc-binary==1.11 does not resolve for m1

**Comment by RamXX** [comment]
For Mac M1, the solution for me was to `brew install pandoc` first, and then mod the `requirements.txt` file replacing `pandoc-binary==1.11` for `pandoc==1.11`. According to the [documentation in the source repo](https://github.com/JessicaTegner/pypandoc), if you already have the binary, pandoc does the job.

**Comment by eliasgrilo** [comment]
ERROR: Cannot install pandoc==1.11 and pandoc==2.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pandoc==2.3
    The user requested pandoc==1.11

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

**Comment by eliasgrilo** [comment]
and when I tried just with The user requested pandoc==1.11
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
hd@hds-MacBook-Pro privateGPT-main % pip install -r requirements.txt
Collecting langchain==0.0.166 (from -r requirements.txt (line 1))
  Using cached langchain-0.0.166-py3-none-any.whl (803 kB)
Collecting pygpt4all==1.1.0 (from -r requirements.txt (line 2))
  Using cached pygpt4all-1.1.0.tar.gz (4.4 kB)
  Preparing metadata (setup.py) ... done
Collecting chromadb==0.3.22 (from -r requirements.txt (line 3))
  Using cached chromadb-0.3.22-py3-none-any.whl (69 kB)
Collecting llama-cpp-python==0.1.48 (from -r requirements.txt (line 4))
  Using cached llama_cpp_python-0.1.48.tar.gz (1.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting urllib3==1.26.6 (from -r requirements.txt (line 5))
  Using cached urllib3-1.26.6-py2.py3-none-any.whl (138 kB)
Collecting pdfminer.six==20221105 (from -r requirements.txt (line 6))
  Using cached pdfminer.six-20221105-py3-none-any.whl (5.6 MB)
Collecting python-dotenv==1.0.0 (from -r requirements.txt (line 7))
  Using cached python_dotenv-1.0.0-py3-none-any.whl (19 kB)
Collecting unstructured==0.6.6 (from -r requirements.txt (line 8))
  Using cached unstructured-0.6.6-py3-none-any.whl (1.3 MB)
Collecting extract-msg==0.41.1 (from -r requirements.txt (line 9))
  Using cached extract_msg-0.41.1-py2.py3-none-any.whl (184 kB)
Collecting tabulate==0.9.0 (from -r requirements.txt (line 10))
  Using cached tabulate-0.9.0-py3-none-any.whl (35 kB)
ERROR: Could not find a version that satisfies the requirement pandoc==1.11 (from versions: 1.0.0a0, 1.0.0a3, 1.0.0a6, 1.0.0a7, 1.0.0a8, 1.0.0a12, 1.0.0a13, 1.0.0a14, 1.0.0a16, 1.0.0a17, 1.0.0a18, 1.0.0a19, 1.0.0b1, 1.0.0b2, 1.0.0b3, 1.0.0, 1.0.1, 1.0.2, 1.1.0, 2.0a1, 2.0a2, 2.0a3, 2.0a4, 2.0.1, 2.1, 2.2, 2.3, 2.4b0)
ERROR: No matching distribution found for pandoc==1.11
hd@hds-MacBook-Pro privateGPT-main % pip install -r requirements.txt

**Comment by basiq-jon** [comment]
@eliasgrilo try this, worked for me after `brew install pandoc` as suggested by @RamXX :

```
pandoc==2.3
pypandoc==1.11
```

**Comment by azigler** [comment]
The above `brew` solution also worked for me on M1. Thanks @RamXX!

**Comment by weeks888** [comment]
> @eliasgrilo try this, worked for me after `brew install pandoc` as suggested by @RamXX :
> 
> ```
> pandoc==2.3
> pypandoc==1.11
> ```

Can confirm this worked for me as well

**Comment by PerryHugh** [comment]
`pypandoc==1.11`
Can confirm this worked on Ubuntu 22.04.2 with Python 3.10.6.

**Comment by imartinez** [comment]
Solved in #240

**Comment by eliasgrilo** [comment]
> @eliasgrilo try this, worked for me after `brew install pandoc` as suggested by @RamXX :
> 
> ```
> pandoc==2.3
> pypandoc==1.11
> ```

Men, I really Love You!!!!

**Comment by abhiruka** [comment]
For Mac M1, cant install `pypandoc-binary==1.11 ` 

Below worked for me 

```
pandoc==2.3
pypandoc==1.11
```

**Comment by csells** [comment]
> Below worked for me
> 
> ```
> pandoc==2.3
> pypandoc==1.11
> ```

This works for both my Windows 11 box and macOS Ventura on my M1. Thanks, all.

**Comment by csells** [comment]
However, while the submitted fix in #240 works for Windows, it does not work on my M1 mac:

```
pandoc==2.3
pypandoc-binary==1.11
```

yields:

```sh
...
Requirement already satisfied: pandoc==2.3 in /opt/homebrew/lib/python3.11/site-packages (from -r requirements.txt (line 11)) (2.3)
ERROR: Could not find a version that satisfies the requirement pypandoc-binary==1.11 (from versions: none)
ERROR: No matching distribution found for pypandoc-binary==1.11
```

**Comment by sealan** [comment]
@csells Try `pypandoc==1.11` instead of `pypandoc-binary==1.11` after installing using `brew install pandoc`. This worked for me on my M2 Pro.

**Comment by csells** [comment]
> @csells Try `pypandoc==1.11` instead of `pypandoc-binary==1.11` after installing using `brew install pandoc`. This worked for me on my M2 Pro.

Yes. I saw that. And, as I mentioned, that works for both Windows and my M1 Mac. However, the change in #240 only works on Windows and not on my M1 Mac. I'm suggesting that perhaps #240 adopted the incorrect fix for this issue.

**Comment by imartinez** [comment]
@csells I've just reproduced the error on my M1 Mac. Can't test it your suggestion on windows. Do you think this should be the adopted solution? 

pandoc==2.3
pypandoc==1.11

**Comment by josmas** [comment]
Hey @imartinez, according to [the docs](https://pypi.org/project/pypandoc-binary/) the only difference between pypandoc and pypandoc-binary is that the binary contains pandoc, but they are otherwise identical. Because you are specifying pandoc in the reqs file anyway, installing pypandoc (not the binary person) will work for all systems.
That's the solution @csells is suggesting and it is working for me too.

**Comment by imartinez** [comment]
Thanks a lot for the clarification @josmas ! Closing the issue (hopefully for good this time)

**Comment by csells** [comment]
> @csells I've just reproduced the error on my M1 Mac. Can't test your suggestion on windows. Do you think this should be the adopted solution?
> 
> pandoc==2.3 pypandoc==1.11

That works when it comes to installing the requirements for me on both Windows and macOS. However, I don't know if that's causing another problem on macOS where my ingestion is failing on macOS (#301) when though it works on Windows.

**Comment by lucifer717** [comment]
save my day

**Comment by mdeweerd** [comment]
I suggest that the requirements.txt would be extended using conditions.

pandoc-binary is available on some platforms, and surely avoids compilation.
It is not mandatory, it is used by unstructured I believe only to ingest certain document types.

So maybe the requirements could contain lines such as (I did not lookup what sys_platform would be for mac):

```requirements.txt
unstructuredpandoc-binary==0.6.6 [pandoc-binary==1.11] ;  sys_platform != 'mac'
unstructuredpandoc-binary==0.6.6 [pandoc==2.3,pypandoc==1.11] ;  sys_platform == 'mac'
```

https://pip.pypa.io/en/stable/reference/requirement-specifiers/#examples

**Comment by timotta** [comment]
> @eliasgrilo try this, worked for me after `brew install pandoc` as suggested by @RamXX :
> 
> ```
> pandoc==2.3
> pypandoc==1.11
> ```

Same on ubuntu, `sudo apt install pandoc` and changing the requirements equally
