### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by tandv592082** [imartinez/privateGPT#228]
Do you have plans to provide Docker support in the near future? I'm using Windows and encountering some issues with package installation.

**Comment by Suniron** [comment]
I will put this project into Docker soon.

But, in waiting, I suggest you to use WSL on Windows 😃

**Comment by JulienA** [comment]
Check PR #120

**Comment by tandv592082** [comment]
> Check PR #120

Sure, many thanks

**Comment by tandv592082** [comment]
> Refere



> I will put this project into Docker soon.
> 
> But, in waiting, I suggest you to use WSL on Windows 😃

Docker on my Window is already to use
