### ISSUE TITLE
Support for PDF files 

### ISSUE THREAD

**Issue by pranavvp16** [imartinez/privateGPT#23]
Most of the documents are in the form of pdf so it would be better to have a PDF support. If you guys want I can help with it

**Comment by imartinez** [comment]
Sure! LangChain has support for several [PDF Loaders](https://python.langchain.com/en/latest/modules/indexes/document_loaders/examples/pdf.html#)

You can change the TextLoader in ingest.py and use any PDF loader as described in that link. Feel free to open a PR!

**Comment by imartinez** [comment]
Let's continue the discussion in this similar request https://github.com/imartinez/privateGPT/issues/12
