### ISSUE TITLE
LlamaCppEmbeddings module is encountering an issue 

### ISSUE THREAD

**Issue by fingeronthebutton** [imartinez/privateGPT#236]
sorry, inadvertently closed my last open issue:  current status

including chatgpt feedback:

C:\martinezchatgpt\privateGPT-main\privateGPT-main\source_documents>python -m ingest
llama.cpp: loading model from C:/martinezchatgpt/models/ggml-gpt4all-j-v1.3-groovy.bin
Traceback (most recent call last):
File "", line 198, in _run_module_as_main
File "", line 88, in _run_code
File "C:\martinezchatgpt\privateGPT-main\privateGPT-main\source_documents\ingest.py", line 64, in
llama = LlamaCppEmbeddings(model_path=model_path, n_ctx=model_n_ctx)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "pydantic\main.py", line 341, in pydantic.main.BaseModel.init
pydantic.error_wrappers.ValidationError: 1 validation error for LlamaCppEmbeddings
root
Could not load Llama model from path: C:/martinezchatgpt/models/ggml-gpt4all-j-v1.3-groovy.bin. Received error [WinError -529697949] Windows Error 0xe06d7363 (type=value_error)
Exception ignored in: <function Llama.del at 0x00000181692A9940>
Traceback (most recent call last):
File "C:\Users\sheld\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\llama_cpp\llama.py", line 1076, in del
if self.ctx is not None:
^^^^^^^^
AttributeError: 'Llama' object has no attribute 'ctx'

ChatGPT
The error message suggests that the LlamaCppEmbeddings module is encountering an issue while loading the Llama model from the specified path.

To troubleshoot this issue, please double-check the following:

Verify that the Llama model file (ggml-gpt4all-j-v1.3-groovy.bin) is present in the C:/martinezchatgpt/models/ directory.
Ensure that the model file name and extension are correctly specified in the .env file as LLAMA_EMBEDDINGS_MODEL.
Check that the path to the Llama model in the .env file is correctly formatted with forward slashes (/), as shown below:
javascript
Copy code
LLAMA_EMBEDDINGS_MODEL=C:/martinezchatgpt/models/ggml-gpt4all-j-v1.3-groovy.bin
If all these checks pass and the issue persists, there might be an underlying compatibility or installation problem specific to the LlamaCppEmbeddings module. In that case, it would be best to consult the documentation or seek support from the maintainers of the LlamaCppEmbeddings module or the repository where you obtained it.

Additionally, make sure you are using the latest version of the LlamaCppEmbeddings module and that it is compatible with your Python version.

AUTHOR NOTE: i checked the following and all appear to be correct: Verify that the Llama model file (ggml-gpt4all-j-v1.3-groovy.bin) is present in the C:/martinezchatgpt/models/ directory.
Ensure that the model file name and extension are correctly specified in the .env file as LLAMA_EMBEDDINGS_MODEL.
Check that the path to the Llama model in the .env file is correctly formatted with forward slashes (/), as shown below:
javascript

**Comment by dbxndn** [comment]
Thanks

**Comment by imartinez** [comment]
We are not using llama.cpp as the embeddings model anymore. 
Plus, ingest got a LOT faster with the use of the new embeddings model #224

Note: this is a breaking change, any existing database will stop working with the new changes. You'll need to re-ingest your docs. It is recommended as the process is faster and the results are better.
