### ISSUE TITLE
feature request: ingestion .md files and automation for ingestion of all files in a folder and its subfolders 

### ISSUE THREAD

**Issue by Mahgozar** [imartinez/privateGPT#24]

**Comment by imartinez** [comment]
Sure! LangChain has support for [Markdown Loaders](https://python.langchain.com/en/latest/modules/indexes/document_loaders/examples/markdown.html)

You can change the TextLoader in ingest.py and use any MD loader as described in that link. Feel free to open a PR!

**Comment by robinscherbatskyy** [comment]
and automation for ingestion of all files in a folder and its subfolders #24

^ this would be an amazing addition.

**Comment by robinscherbatskyy** [comment]
This is what I did for ingesting all .json files from a directory

import sys
import os
from langchain import LangChain
from langchain.vectorstore import VectorStore
from langchain.document_loaders import JSONLoader

if len(sys.argv) != 2:
    print("Usage: python ingest.py <path_to_your_directory>")
    exit(1)

lc = LangChain()
lc.load_models()

vs = VectorStore()
vs.load()

# Get a list of all JSON files in the specified directory
json_files = [f for f in os.listdir(sys.argv[1]) if f.endswith('.json')]

# Load data from each JSON file
for json_file in json_files:
    loader = JSONLoader(
        file_path=os.path.join(sys.argv[1], json_file),
        jq_schema='your_jq_schema'
    )
    data = loader.load()

    for chunk in lc.split_text(data):
        vs.add(chunk)

vs.save()

**Comment by Mahgozar** [comment]
thanks for all the replies
