### ISSUE TITLE
Ingest.py running forever

### ISSUE THREAD

**Issue by amazingpaddy** [imartinez/privateGPT#256]
Note: if you'd like to *ask a question* or *open a discussion*, head over to the [Discussions](https://github.com/imartinez/privateGPT/discussions) section and post it there.

**Describe the bug and how to reproduce it**
I've transferred three PDF files (each containing 2 to a maximum of 5 pages, and less than 1 MB in size) into the 'source_documents' directory and executed the 'ingest.py' script. It's been running for over an hour. The console output appears to be consistently displaying similar content as follows:

```
llama_print_timings:        load time =  4069.87 ms
llama_print_timings:      sample time =     0.00 ms /     1 runs   (    0.00 ms per run)
llama_print_timings: prompt eval time = 37650.26 ms /    79 tokens (  476.59 ms per token)
llama_print_timings:        eval time =     0.00 ms /     1 runs   (    0.00 ms per run)
llama_print_timings:       total time = 37680.04 ms

llama_print_timings:        load time =  4069.87 ms
llama_print_timings:      sample time =     0.00 ms /     1 runs   (    0.00 ms per run)
llama_print_timings: prompt eval time = 39766.47 ms /    84 tokens (  473.41 ms per token)
llama_print_timings:        eval time =     0.00 ms /     1 runs   (    0.00 ms per run)
llama_print_timings:       total time = 39798.69 ms

llama_print_timings:        load time =  4069.87 ms
llama_print_timings:      sample time =     0.00 ms /     1 runs   (    0.00 ms per run)
llama_print_timings: prompt eval time = 53641.43 ms /   114 tokens (  470.54 ms per token)
llama_print_timings:        eval time =     0.00 ms /     1 runs   (    0.00 ms per run)
llama_print_timings:       total time = 53685.67 ms
```

**Expected behavior**
Expected to complete in few minutes,

**Environment (please complete the following information):**
 - OS / hardware: macOS 13.4 / M2
 - Python version 3.11.3

**Additional context**

**Comment by thebakermanishere** [comment]
which models do you use and what is your `n_batch` value set to for `LlamaCppEmbeddings` in `ingest.py`?

**Comment by OneCodeToRuleThemAll** [comment]
You have the latest version of privateGPT?
Have you tried removing the db folder altogether then recreating by running again?

**Comment by amazingpaddy** [comment]
> which models do you use and what is your `n_batch` value set to for `LlamaCppEmbeddings` in `ingest.py`?

I am GPT4All model. Below is my `.env` file. I couldnt locate `n_batch` in ingest.py. You meant `n_ctx` ?

```
PERSIST_DIRECTORY=/Users/paddy/chatgpt/privateGPT/db
LLAMA_EMBEDDINGS_MODEL=/Users/paddy/chatgpt/privateGPT/models/ggml-model-q4_0.bin
MODEL_TYPE=GPT4All
MODEL_PATH=/Users/paddy/chatgpt/privateGPT/models/ggml-gpt4all-j-v1.3-groovy.bin
MODEL_N_CTX=1000%
```

**Comment by amazingpaddy** [comment]
> You have the latest version of privateGPT? what model do you use to get the embeddings? Have you tried removing the db folder altogether then recreating by running again?

I will update the latest code and try.

**Comment by imartinez** [comment]
Make sure you pull latest changed and update your .env accordingly (check the example .env file contents). Ingest will be much faster

**Comment by amazingpaddy** [comment]
Updated the code and edited the .env as suggested. Now `ingest.py` completed in 5 mins. I have now different issue but not related to the `ingest.py` file. So closing this issue.
