### ISSUE TITLE
No module named 'dotenv'

### ISSUE THREAD

**Issue by peterchanws** [imartinez/privateGPT#258]
Hardware: MacBook Pro, i7, 16GB RAM
OS: macOS 13.3.1
Python 3.11.3, Miniconda3

Installation successful. When I run ingest.py, I got 

File "/Users/pchan3/Desktop/privateGPT/ingest.py", line 4, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

I "pip install python-dotenv" and python-dotenv 1.0.0 show after pip list
'Run again and got the same error.

Any help will be very much appreciated.

**Comment by peterchanws** [comment]
Problem solved. My Visual Code point to different enviroment

**Comment by impactfactory** [comment]
Could you explain how you solved that step for step for dummy-dummies? Would be great!!

**Comment by ravindranantony** [comment]
I am having the same error, can you please share how did you solved it

**Comment by 808isonline** [comment]
@ravindranantony were you able to fix it with pip install python-dotenv? Because I was not able to. I get the following: 

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: python-dotenv in /Users/mac300/Library/Python/3.9/lib/python/site-packages (1.0.0)

**Comment by mommu** [comment]
> Problem solved. My Visual Code point to different enviroment

Could you please guide us how you did that?

**Comment by molnarjozs** [comment]
> > Problem solved. My Visual Code point to different enviroment
> 
> Could you please guide us how you did that?

Check the following commands:
python --version
pip --version

If the version in brackets at the end of the pip version text (first two numbers) does not match the installed python version, there is probably a path to another python version in a previous position in the system path, and some commands are running on that path, with that python version.

For example, the installer of Inkscape put an older python version in the path for me...

**Comment by mommu** [comment]
> > > Problem solved. My Visual Code point to different enviroment
> > 
> > 
> > Could you please guide us how you did that?
> 
> Check the following commands: python --version pip --version
> 
> If the version in brackets at the end of the pip version text (first two numbers) does not match the installed python version, there is probably a path to another python version in a previous position in the path env. variable, and some commands are running on that path, with that python version.
> 
> For example, the installer of Inkscape put an older python version in the path for me...

I really appreciate you taking time to explaining it to me. I noticed the version matches but I still get the error. I am a noob though, so there might be a million things I cold have done wrong.

**Comment by lmontin** [comment]
kind of same issue for me. ( also a noob) ..  

>sudo python3 /home/$USER/privateGPT/ingest.py
[sudo] password for X
Traceback (most recent call last):
  File "/home/X/privateGPT/ingest.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

>python --version
Command 'python' not found, did you mean:
  command 'python3' from deb python3
  command 'python' from deb python-is-python3

>python3 --version
Python 3.10.6

>pip --version
pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

>pip3 --version
pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

**Comment by prettyflyai** [comment]
do python3 ingest.py

**Comment by thebrackett** [comment]
I was able to get the call to run by using the "py -m download_models" syntax instead of "py download_models.py"
