### ISSUE TITLE
AttributeError: 'Llama' object has no attribute 'ctx'

### ISSUE THREAD

**Issue by peterchanws** [imartinez/privateGPT#262]
Completed Ingest.py
run privateGPT.py and got:

Could not load Llama model from path: /models/ggml-model-q4_0.bin. Received error Model path does not exist: /models/ggml-model-q4_0.bin (type=value_error)
Exception ignored in: <function Llama.__del__ at 0x11fbb39c0>
Traceback (most recent call last):
  File "/Users/pchan3/miniconda3/lib/python3.11/site-packages/llama_cpp/llama.py", line 978, in __del__
    if self.ctx is not None:
       ^^^^^^^^
AttributeError: 'Llama' object has no attribute 'ctx'
**Expected behavior**

**Environment (please complete the following information):**
 - macOS 13.3.1 (a)/ Intel
 - Python version 3.11.3

**Comment by normanlove222** [comment]
> Received error Model path does not exist: /models/ggml-model-q4_0.bin 

seems like it should not be /model/
but
model/

**Comment by peterchanws** [comment]
My .env is

PERSIST_DIRECTORY=db
LLAMA_EMBEDDINGS_MODEL=models/ggml-model-q4_0.bin
MODEL_TYPE=GPT4All
MODEL_PATH=models/ggml-gpt4all-j-v1.3-groovy.bin
MODEL_N_CTX=1000

Also, 2 files in models  folder

**Comment by zxjason** [comment]
I removed LLAMA_EMBEDDINGS_MODEL=models/ggml-model-q4_0.bin, then it worked.

as I understand, we only can choose one model. either llama or gpt.

**Comment by peterchanws** [comment]
removed LLAMA_EMBEDDINGS_MODEL=models/ggml-model-q4_0.bin
same error message
Traceback (most recent call last):
  File "/Users/pchan3/Desktop/privateGPT/privateGPT.py", line 57, in <module>
    main()
  File "/Users/pchan3/Desktop/privateGPT/privateGPT.py", line 21, in main
    llama = LlamaCppEmbeddings(model_path=llama_embeddings_model, n_ctx=model_n_ctx)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LlamaCppEmbeddings
__root__
  Could not load Llama model from path: /models/ggml-model-q4_0.bin. Received error Model path does not exist: /models/ggml-model-q4_0.bin (type=value_error)
Exception ignored in: <function Llama.__del__ at 0x12234b9c0>
Traceback (most recent call last):
  File "/Users/pchan3/miniconda3/lib/python3.11/site-packages/llama_cpp/llama.py", line 978, in __del__
    if self.ctx is not None:
       ^^^^^^^^
AttributeError: 'Llama' object has no attribute 'ctx'

**Comment by peterchanws** [comment]
same as  #161
