### ISSUE TITLE
when I am running python privateGPT.py, it shows Using embedded DuckDB with persistence: data will be stored in: db and exits.

### ISSUE THREAD

**Issue by digish777** [imartinez/privateGPT#281]
when I am running python privateGPT.py,
it shows Using embedded DuckDB with persistence: data will be stored in: db and exits.
It does not ask for enter the query.

my .env file:

PERSIST_DIRECTORY=db
LLAMA_EMBEDDINGS_MODEL=models/ggml-model-q4_0.bin
MODEL_TYPE=GPT4All
MODEL_PATH=models/ggml-gpt4all-j-v1.3-groovy.bin
EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
MODEL_N_CTX=1000

ggml-gpt4all-j-v1.3-groovy.bin & ggml-model-q4_0.bin is in models folder.

ran 
pip install -r requirements.txt 
placed ggml-gpt4all-j-v1.3-groovy.bin & ggml-model-q4_0.bin is in models folder
renamed enrivornment.env to .env
python privateGPT.py
it just exits

**Comment by haris525** [comment]
this is not a bug, once you run the ingest.py file, and see that message, wait until your variables populate, and then run the PrivateGPT.py file, and it will ask you to enter a query

**Comment by haris525** [comment]
Hi, did you run the ingest.py file first? 
after you complete these steps
pip install -r requirements.txt
placed ggml-gpt4all-j-v1.3-groovy.bin & ggml-model-q4_0.bin is in models folder
renamed enrivornment.env to .env

you have to run the ingest.py files, wait for the variables to be created / populated, and then run the PrivateGPT.py file, you should see a prompt to enter a query

**Comment by digish777** [comment]
I did.

**Comment by Avadhkumar-geek** [comment]
Same problem 
`Using embedded DuckDB with persistence: data will be stored in: db
`

**Comment by Florian0077** [comment]
Same problem for me

**Comment by apcameron** [comment]
check the latest example.env
It no longer has LLAMA_EMBEDDINGS_MODEL=models/ggml-model-q4_0.bin
You may need to update to the latest code.

**Comment by Avadhkumar-geek** [comment]
Not added `ggml-model-q4_0.bin` still facing problem

**Comment by PulpCattel** [comment]
@Avadhkumar-geek did you use `git pull` to update the code?

**Comment by Avadhkumar-geek** [comment]
@PulpCattel  No, but I cloned the repository today.

**Comment by digish777** [comment]
![priavtegpt](https://github.com/imartinez/privateGPT/assets/2889217/d68e0d0a-410e-4da0-8213-c436fe3b8b68)

**Comment by PulpCattel** [comment]
Could it be hardware deficit? Do you have enough ram? Maybe the OS is killing the script before it can run(?), just guessing.

**Comment by digish777** [comment]
24GB RAM
Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz   3.40 GHz

**Comment by trivalik** [comment]
I found that it returns -1073741795 (you can get it by executing `echo %ERRORLEVEL%` in a cmd)
Proper written is it this 0xC000001D. By using printf, I found that it happen in the GPT4All function call.

**Comment by digish777** [comment]
-1073741795

**Comment by digish777** [comment]
So I have to use new machine to run this privateGPT of Your?

**Comment by Orrouk** [comment]
So many thanks for the answer. Have a good day.
