### ISSUE TITLE
Persian/Farsi language support

### ISSUE THREAD

**Issue by mehrdad2000** [imartinez/privateGPT#288]
Hi
Need to feed Persian/Farsi language document to privateGPT does it support?

Thanks

**Comment by janvarev** [comment]
May be vote for this Pull request with Multilanguage support: https://github.com/imartinez/privateGPT/pull/325

**Comment by mehrdad2000** [comment]
@janvarev i put thumbs up, should i do something else?

**Comment by Mhmdrza** [comment]
Can we have some sort of guidance or instructions on how is it achievable?
