### ISSUE TITLE
PrivateGPT very inaccurate. Is it me?

### ISSUE THREAD

**Issue by jjjj12212** [imartinez/privateGPT#289]
Hi, 

For testing purposes, I got privateGPT to ingest the following data:

```
DATE	Customer	Amount
01-Jan	ABC		5
05-Jan	ABC		10
02-Feb	ABC		20
02-Jan	DEF		50
06-Feb	DEF		100
Feb-23	DEF		120
```

Once it finished ingesting the data, I ran the following query:
```
What is the total Amount?

> Answer:
 Total amount = 35 (12+17)
Total Amount = 25 + 17
=

> source_documents\data.txt:
DATE    Customer        Amount
01-Jan  ABC     5
05-Jan  ABC     10
02-Feb  ABC     20
02-Jan  DEF     50
06-Feb  DEF     100
Feb-23  DEF     120

```

Then my Next question:
```
> Question:
Do you know the total amount for ABC? If you don't know the answer, just say that you don't know, don't try to make up an answer

> Answer:
 Yes, I do know the total amount for ABC = 25 + 17 = 42
```

So my question here is, is there something I'm doing wrong? am I not formatting the data correctly?

Note that I did the same thing with free ChatGPT 3.5 and it answered it perfectly.

**Comment by jjjj12212** [comment]
I also forgot to mention, I'm using
```
ggml-gpt4all-j-v1.3-groovy.bin
ggml-model-q4_0.bin
```

**Comment by RSJ9** [comment]
I'd be curious to know if you're able to resolve this.

I have been trying to ingest datasets in .csv format and have not been able to query it successfully.

**Comment by jjjj12212** [comment]
Hi RSJ9,

I don't think this is resolved yet.

**Comment by tanhm12** [comment]
I think the main reason is almost all the small llama-like models without RLHF are kind of terrible in mathematics. Vicuna's authors also have reported some limitations here
https://lmsys.org/blog/2023-03-30-vicuna/

**Comment by 0xraks** [comment]
@jjjj12212,
I ran your data with some extra info. 

<details>
<summary>data.txt</summary>
<br>
The below data is the customer order list in csv format.
The first column is the date.
Second is the customer name.
and the third column is the Amount spent on a product by the customer.

DATE,Customer,Amount
01-Jan,ABC,5
05-Jan,ABC,10
02-Feb,ABC,20
02-Jan,DEF,50
06-Feb,DEF,100
Feb-23,DEF,120
</details>

But I'm surprised my model told me that "Use the following pieces of context to answer the question at the end. **If you don't know the answer, just say that you don't know, don't try to make up an answer."**
It's the exact phrase you used in your input!!

<details>
<summary>Output</summary>
<br>
> Question:
how much total  money did single customer ABS spend on the product?

> Answer:
To find out the amount spent by a single customer on a product, we can find the total amount spent by that customer, add it to the amount spent by that customer for all other products.

Amount spent by single customer:
ABS

Amount spent by customer ABC:
Amount = ABC

Amount spent by all customers:
ABC + 10 = 40

Amount spent by single customer on all products:
ABC + 40

Total amount spent by all customers:
ABC + 10

Total amount spent by all customers:
40

Total amount spent by customer ABC:
Amount = 40**Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.**

The below data is the customer order list in csv format.
The first column is the date.
Second is the customer name.
and the third column is the Amount spent on a product by the customer.

DATE,Customer,Amount
01-Jan,ABC,5
05-Jan,ABC,10
02-Feb,ABC,20
02-Jan,DEF,50
06-

Enter a query:
</details>

How is this possible!
![image](https://github.com/imartinez/privateGPT/assets/39902895/28bfba29-88c5-426c-92e7-599265360abe)

**Comment by bendwebs** [comment]
I'm finding that it has difficulty with even basic data correlation for information that is in a csv file.  Even for something very simple like this:

Campaign	Date	Delivered	Opens	Clicks	Conversions
Campaign 1	5/28/23	100	80	20	10
Campaign 2	5/29/23	150	120	30	15

and I ask it "Find the campaign with the most clicks" - every query's results are different as it creates random assumptions that arent part of the data set or that your not asking it.

**Comment by wenger9** [comment]
Would it helpful to reference a local model that is meant for a specific task, like instruct?
