### ISSUE TITLE
eml support

### ISSUE THREAD

**Issue by peterchanws** [imartinez/privateGPT#294]
I had issue ingest eml files.  #290
[pseudotensor](https://github.com/pseudotensor) kindly have written code for that https://github.com/h2oai/h2ogpt#readme
https://github.com/h2oai/h2ogpt/blob/main/gpt_langchain.py#L364-L375
. I don't know how to integrate the code into privateGPT. Could someone merge the code to privateGPT?
Thanks

**Comment by mdeweerd** [comment]
Check if https://github.com/mdeweerd/privateGPT/pull/new/elm_extended works for you and comment on PR #295

**Comment by PulpCattel** [comment]
@mdeweerd You meant #299?

**Comment by mdeweerd** [comment]
Yes, sorry for the typo.

**Comment by peterchanws** [comment]
Sorry, I am not a coder. Could someone help to review? Thanks.

**Comment by peterchanws** [comment]
I used ChatGPT to review the code and I got "Overall, the code seems to implement a fallback mechanism to handle cases where the default loading method for UnstructuredEmailLoader fails to find HTML content in an email."
