### ISSUE TITLE
Mention CASALIOY in ReadMe - we fixed **50+ issues of this repo**

### ISSUE THREAD

**Issue by su77ungr** [imartinez/privateGPT#303]
**Add note inside README** 

references [CASALIOY (air-gapped toolkit)](https://github.com/su77ungr/CASALIOY) 

**Why _your_ community would benefit?**
We took some time and effort to supercharge this base idea of a private LLM client and solved dozens of your repo's **issues** also. Choosing different routes in things like vector storage, ingestion approach and GUI for good measure. Some but not all features:

- [x] Speed improvements through _qdrant_ and change in the base model
- [x] Blazing fast _parallelized ingestion_ and local HF Sentence Transformer
- [x] _GUI_ built with streamlit to let your family chat in the browser (easy to embed) 

<br>

<div align="center">

<img align="center" src="https://github.com/imartinez/privateGPT/assets/69374354/b89edcf2-cd79-41db-be42-5d77ff48731c"/>
</div>

**Benchmarks (just an excerpt)**
<div align="center">

tests° | CASALIOY | privateGPT
-- | -- | --
Ingestion Speed (2000+ documents)*| <8 minutes| >10 hours
Ingestion Speed(SOTU.txt)*| <1 second | 10 seconds
LLM speed | Queued | Queued

°tested on Ubuntu 22.04 LTS (i5-9600k, GTX 1050ti) examples for large ingestion [here](https://github.com/su77ungr/CASALIOY/pull/85)

</div>
<br> 

**Post**
Thank you for considering integrating this. However, we understand if you choose not to, and hope it can at least help resolve some of your repo's issues without altering your boilerplate.

**Comment by su77ungr** [comment]
> °tests examples for ingestion [here](https://github.com/su77ungr/CASALIOY/pull/85)

proof of millisecond ingestion speed for SOTU.txt [here](https://pastebin.com/TUHMrNEQ)

**Comment by haris525** [comment]
could you please explain a bit more on wat this is? so with the changes you are recommending, the model would speed up indigestion of documents?

**Comment by imartinez** [comment]
#305
