### ISSUE TITLE
Illegal instruction Mac M2

### ISSUE THREAD

**Issue by fpena06** [imartinez/privateGPT#308]
Can't run on mac m2, I get the following error:

```
Using embedded DuckDB with persistence: data will be stored in: db
Illegal instruction: 4
```

**Environment (please complete the following information):**
 - OS / hardware: [e.g. macOS 13.3.1 / M2]
 - Python version [e.g. 3.10.0]
 
.env
```
PERSIST_DIRECTORY=db
MODEL_TYPE=GPT4All
MODEL_PATH=models/ggml-gpt4all-j-v1.3-groovy.bin
EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
MODEL_N_CTX=1000
```

**Comment by drnguyen** [comment]
It works fine on my Mac with the M2 chip with the exact .env spec 

```
macOS: 13.4
python 3.10.11

environment conda with all requirement dependencies installed.
```

**Comment by fpena06** [comment]
Which model are you using? Seems to work for me with llamacpp but extremely slow.

**Comment by brianjking** [comment]
I'm getting an error on my m1 too.

**Comment by fpena06** [comment]
> I'm getting an error on my m1 too.

what model are you using? For me it's currently working with llamacpp with the --mlock flag, which made it work much faster, I can even run 13b model now. But still getting the error with the gpt4all model in the readme.

**Comment by hardikns** [comment]
Same error for me too on M1 mac and gpt4all model

**Comment by rosmur** [comment]
Im getting a similar error:

`zsh: Illegal Hardware Instruction`

hope someone can help shed some light
