### ISSUE TITLE
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__ pydantic.error_wrappers.ValidationError: 1 validation error for GPT4All n_ctx   none is not an allowed value (type=type_error.none.not_allowed)

### ISSUE THREAD

**Issue by mengtong0110** [imartinez/privateGPT#309]
I got this bug .
How could I do? 

```
 File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GPT4All
n_ctx
  none is not an allowed value (type=type_error.none.not_allowed)
```

**Comment by PulpCattel** [comment]
See https://github.com/imartinez/privateGPT/issues/78#issuecomment-1545977382
You have to rename `example.env` to `.env` like explained in the `README` file.

**Comment by Thousands-milse-alone** [comment]
thanks~

**Comment by PulpCattel** [comment]
If this is solved please close this issue.

**Comment by Eziofly** [comment]
> 

how to rename a file with .env? macOS not allow

**Comment by MagicTor** [comment]
> See [#78 (comment)](https://github.com/imartinez/privateGPT/issues/78#issuecomment-1545977382) You have to rename `example.env` to `.env` like explained in the `README` file.

It did not fix the issue. Here is my error:

File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GPT4All
__root__
  Unable to instantiate model (type=value_error)
