### ISSUE TITLE
Access control/API/feedback

### ISSUE THREAD

**Issue by mehrdad2000** [imartinez/privateGPT#311]
Hi
Have couple questions about privategpt:
1-How can monitor questions that user ask? Is it possible to improve answers by feed back?
2-I have simple scenario that need to access couple of users to my privategpt. Is there any way to set access restrictions for them? E.g. Data that related to each user locate on 3 directories. Like this “user1-dir”, “user2-dir”, “user3-dir”.
3-is there any way to connect to privategpt from my app through rest api or something like that?
4-is possible to join it to ldap server for user access control?

Any idea?
Thanks

**Comment by Advik29** [comment]
I have a similar user case to tackle is there any suggestion
