### ISSUE TITLE
Unexpected Termination due to std::runtime_error during model load in llama.cpp

### ISSUE THREAD

**Issue by nesimtunc** [imartinez/privateGPT#32]
`python ingest.py sample.txt`

**Issue Description**:
I encountered an unexpected termination error when trying to run `ingest.py` on `sample.txt` in the `privateGPT` repository. The specific error is a `std::runtime_error` stating that the end of the file was unexpectedly reached. The error appears to occur during the model load process in `llama.cpp`.

**Expected Behavior**:
The script should successfully load the model from `ggml-gpt4all-j-v1.3-groovy.bin` and process the `sample.txt` file without any errors.

**Actual Behavior**:
The script abruptly terminates and throws the following error:
```
llama.cpp: loading model from ggml-gpt4all-j-v1.3-groovy.bin
libc++abi: terminating due to uncaught exception of type std::runtime_error: unexpectedly reached end of file
[1]    69096 abort      python3 ingest.py sample.txt
```

**Environment**:
Python: **3.11.3**
OS: **MacOS Ventura 13.3.1 (a)**
Hardware: **Apple M1 Pro**

**Additional Context**:
I downloaded the model from the link you provided, and also used your sample text.

**Comment by masasron** [comment]
Hi @nesimtunc, I'm having the same issue, what was the solution?

**Comment by nesimtunc** [comment]
I read it the README again and noticed that I've not renamed the `example.env` file to `.env` and second model was also needed.

**Comment by JerelynCo** [comment]
Hi @nesimtunc 



Encountered the same problem but already renamed the env file. Could you please share here what do you mean by `second model`?

```bash
llama.cpp: loading model from models/ggml-model-q4_0.bin
llama.cpp: can't use mmap because tensors are not aligned; convert to new format to avoid this
llama_model_load_internal: format     = 'ggml' (old version with low tokenizer quality and no mmap support)
....
terminate called after throwing an instance of 'std::runtime_error'
  what():  unexpectedly reached end of file
Aborted (core dumped)
```

**Comment by nesimtunc** [comment]
Create a `models` folder in the root (or update the path in `.env` file. Download those two models to `models` folder and then you're good to go with `python ingest.py`

1. https://gpt4all.io/models/ggml-gpt4all-j-v1.3-groovy.bin
2. https://huggingface.co/Pi3141/alpaca-native-7B-ggml/resolve/397e872bf4c83f4c642317a5bf65ce84a105786e/ggml-model-q4_0.bin

**Comment by GitEin11** [comment]
i stll get the error, i've rename to .env changed the model to absolute path, also changed to absolute path ingest.py

**Comment by sahil-rajput** [comment]
Try downloading the models from this link and replace it with your current models. It will work after that

1. https://gpt4all.io/models/ggml-gpt4all-j-v1.3-groovy.bin
2. https://huggingface.co/Pi3141/alpaca-native-7B-ggml/resolve/397e872bf4c83f4c642317a5bf65ce84a105786e/ggml-model-q4_0.bin

**Comment by GitEin11** [comment]
> Try downloading the models from this link and replace it with your current models. It will work after that
> 
>     1. https://gpt4all.io/models/ggml-gpt4all-j-v1.3-groovy.bin
> 
>     2. https://huggingface.co/Pi3141/alpaca-native-7B-ggml/resolve/397e872bf4c83f4c642317a5bf65ce84a105786e/ggml-model-q4_0.bin


ow it  thanks it works, it seems my model got corrupted while transferring

**Comment by akhiljain** [comment]
still getting libc++abi: terminating due to uncaught exception of type std::runtime_error: unexpectedly reached end of file, downloaded both the model and embeddings properly uninterrupted.
