### ISSUE TITLE
 File models/ggml-gpt4all-j-v1.3-groovy.bin not found!

### ISSUE THREAD

**Issue by SLEEP-SOUNDER** [imartinez/privateGPT#323]
This problem occurs when I run privateGPT.py. Can you help me to solve it.Thanks in advance.

**Describe the bug and how to reproduce it**
`Using embedded DuckDB with persistence: data will be stored in: db
Traceback (most recent call last):
  File "D:\pravte gpt\privateGPT-main\privateGPT.py", line 75, in <module>
    main()
  File "D:\pravte gpt\privateGPT-main\privateGPT.py", line 35, in main
    llm = GPT4All(model=model_path, n_ctx=model_n_ctx, backend='gptj', callbacks=callbacks, verbose=False)
  File "pydantic\main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic\main.py", line 1102, in pydantic.main.validate_model
  File "E:\Python\lib\site-packages\langchain\llms\gpt4all.py", line 169, in validate_environment
    values["client"] = GPT4AllModel(
  File "E:\Python\lib\site-packages\pygpt4all\models\gpt4all_j.py", line 47, in __init__
    super(GPT4All_J, self).__init__(model_path=model_path,
  File "E:\Python\lib\site-packages\pygptj\model.py", line 58, in __init__
    raise Exception(f"File {model_path} not found!")
Exception: File models/ggml-gpt4all-j-v1.3-groovy.bin not found!`

**Environment (please complete the following information):**
 - OS / hardware: [Windows 10]
 - Python version [3.10.9]
- Other relevant information

**Comment by PulpCattel** [comment]
Make sure to follow the instructions [here](https://github.com/imartinez/privateGPT#environment-setup), in particular, make sure to download the model first and put it in the appropriate folder as per your `.env` file.

**Comment by SLEEP-SOUNDER** [comment]
<img width="556" alt="image" src="https://github.com/imartinez/privateGPT/assets/113654284/349b3ce7-6b9a-4092-93d7-d69409fdc723">

Is there a problem with this?

**Comment by petragom** [comment]
> Is there a problem with this?

Yes. You made a typo in the folder name on your drive

modles instead of models

**Comment by SLEEP-SOUNDER** [comment]
Ha ha my Englishi is not good . 
Do you know what's wrong with it?
<img width="282" alt="image" src="https://github.com/imartinez/privateGPT/assets/113654284/91bc4e17-0a2e-4c70-acb1-091aad534

**Comment by SLEEP-SOUNDER** [comment]
sorry 
<img width="282" alt="image" src="https://github.com/imartinez/privateGPT/assets/113654284/31e22814-d433-4da7-94e3-36538c43a3e2">

**Comment by PulpCattel** [comment]
For the `unknown token` messages see https://github.com/imartinez/privateGPT/issues/180 and https://github.com/imartinez/privateGPT/issues/214.
If the not found error is solved please close this issue.

**Comment by SLEEP-SOUNDER** [comment]
thanks
