### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by mehrdad2000** [imartinez/privateGPT#326]
Hi i've got below error when run privateGPT!

```
[root@ privateGPT]# python3.11 privateGPT.py
Using embedded DuckDB with persistence: data will be stored in: db
Illegal instruction (core dumped)

```

Any idea?
Thanks

**Comment by apcameron** [comment]
see https://github.com/imartinez/privateGPT/issues/203

**Comment by jon2allen** [comment]
Your cpu likely isn't supported by current pytorch and torch libraries.  and even if you managed to get this to work on such a processor - it would be a painful long wait before you get results.

**Comment by mehrdad2000** [comment]
@jon2allen i’m running it on esx host that use 8 core intel cpu and won't support avx2, what can i do to fix this?

**Comment by digitalw00t** [comment]
I've tried running an a Dell T620, core dump with privateGPT.py
I've tried running on a Dell R930 running proxmox with a vm that has an ubuntu 22 LTS machine, core dump
Both will ingest just fine, but core dump on execution

**Comment by digitalw00t** [comment]
I'm running two Intel(R) Xeon(R) CPU E5-2640 on the T620, and according to Phind it should have that instruction set.  I'll check when I get home from work, and do the proxmox update that's mentioned as well.

**Comment by digitalw00t** [comment]
Yup.. same issue, but there's no way to turn it on in the bios, so I'm guessing it just isn't supported.  I thought I read that it was, but if there's no way to activate it I'm SOL.

**Comment by mibtim** [comment]
same Illegal instruction (core dumped) issue, im running on vm ubuntu 64 bit, base mem 513000mb, 6 processers

**Comment by digitalw00t** [comment]
I'm just writing it off that my cpu is old enough that it doesn't have the avx2 instruction set.  I might go about recompiling torch, but not sure at this point.
