### ISSUE TITLE
Can't ask questions.

### ISSUE THREAD

**Issue by langyajiekou** [imartinez/privateGPT#332]
after successfully ingest but it seems unable to query and answer? whats wrong?

Creating new vectorstore
Loading documents from source_documents
Loading new documents: 100%|██████████████████████| 3/3 [00:10<00:00,  3.49s/it]
Loaded 3 new documents from source_documents
Split into 131 chunks of text (max. 500 tokens each)
Creating embeddings. May take some minutes...
Using embedded DuckDB with persistence: data will be stored in: db
Ingestion complete! You can now run privateGPT.py to query your documents
(env) PS F:\VSCode\privateGPT-main> python .\privateGPT.py
Using embedded DuckDB with persistence: data will be stored in: db
(env) PS F:\VSCode\privateGPT-main> python .\privateGPT.py
Using embedded DuckDB with persistence: data will be stored in: db
(env) PS F:\VSCode\privateGPT-main> python .\privateGPT.py
Using embedded DuckDB with persistence: data will be stored in: db
(env) PS F:\VSCode\privateGPT-main>

**Comment by PulpCattel** [comment]
See https://github.com/imartinez/privateGPT/issues/281 and https://github.com/imartinez/privateGPT/issues/295

**Comment by GuySarkinsky** [comment]
run: 
python privateGPT.py
