### ISSUE TITLE
chromadb.errors.NoIndexException: Index not found, please create an instance before querying

### ISSUE THREAD

**Issue by Nixon-hk** [imartinez/privateGPT#334]
Dear guys, I just tried to implement my private gpt in collab, and after I implement the code 
!python /content/drive/MyDrive/my-git-repo/privateGPT.py

and it goes this error after I enter the question in query: 

 File "/usr/local/lib/python3.10/dist-packages/chromadb/db/index/hnswlib.py", line 240, in get_nearest_neighbors
    raise NoIndexException(
chromadb.errors.NoIndexException: Index not found, please create an instance before querying

Does someone have any idea to solve this ? Thanks a lot!!!

**Environment**
 - OS / hardware: collab
 - Python version [e.g. 3.10.3]

**Comment by ravindraprasad75** [comment]
This could be because your index was not loaded successfully. Was your ingest.py successful?

**Comment by psegovias** [comment]
I had this same problem today, it happened to me when I called the script from another location. Navigate to where you have the installation and you will see that the ingest works fine.

**Comment by maozdemir** [comment]
https://github.com/maozdemir/privateGPT-colab

**Comment by Nixon-tw** [comment]
> https://github.com/maozdemir/privateGPT-colab

Thanks for your suggestion! But I found some error when loading this koala-7B-GGML package 

![image](https://github.com/imartinez/privateGPT/assets/60779752/fba9cb82-1c19-4ae8-a49b-5fbd8d460331)

Thanks again!!

**Comment by Nixon-tw** [comment]
> This could be because your index was not loaded successfully. Was your ingest.py successful?
Thank you so much for your suggestion ! It seems succesful to load the ingest.py ! still do not know where the problems are
![gpt](https://github.com/imartinez/privateGPT/assets/60779752/9b4f5d4f-b175-4eeb-b8d6-257139ae9540)

**Comment by Nixon-tw** [comment]
> I had this same problem today, it happened to me when I called the script from another location. Navigate to where you have the installation and you will see that the ingest works fine.

Thanks for your suggestions! But seems the ingest.py work fine with right location?
![gpt](https://github.com/imartinez/privateGPT/assets/60779752/8d6e2417-0c67-4201-ac4f-db563b710862)

Thanks again!

**Comment by Nixon-tw** [comment]
> This could be because your index was not loaded successfully. Was your ingest.py successful?
I just found that there seems an error detected in my ingest.py, seems the "Import "constants" could not be resolvedPyright(reportMissingImports)", but I do not know why it happended. Do you have any ideas? Thanks a lot!!
![gpt_2](https://github.com/imartinez/privateGPT/assets/60779752/71c5a98e-10ab-467a-a61d-d505101bb6c9)
