### ISSUE TITLE
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by uzziwizzle** [imartinez/privateGPT#337]
I get the error ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects

How do you suggest I fix?
Ubuntu 18
python 3.11

**Comment by xhywxtt** [comment]
https://github.com/ggerganov/llama.cpp#usage Finish the step of "Build"

**Comment by mauhcs** [comment]
I got the same issue, 
I just had to install gcc on Mac and ubuntu that solved my issues. 


Look here how to install in mac using brew: https://discussions.apple.com/thread/8336714

And this one to install in ubuntu: sudo apt-get install build-essential -y

**Comment by yjb152-yjb** [comment]
Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [92 lines of output]
      
      
      --------------------------------------------------------------------------------
      -- Trying 'Ninja' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is GNU 11.1.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is unknown
      CMake Error at CMakeLists.txt:4 (ENABLE_LANGUAGE):
        No CMAKE_CXX_COMPILER could be found.
      
        Tell CMake where to find the compiler by setting either the environment
        variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
        to the compiler, or to the compiler name if it is in the PATH.
      
      
      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja' generator - failure
      --------------------------------------------------------------------------------
      
      
      
      --------------------------------------------------------------------------------
      -- Trying 'Unix Makefiles' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is GNU 11.1.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is unknown
      CMake Error at CMakeLists.txt:4 (ENABLE_LANGUAGE):
        No CMAKE_CXX_COMPILER could be found.
      
        Tell CMake where to find the compiler by setting either the environment
        variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
        to the compiler, or to the compiler name if it is in the PATH.
      
      
      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Unix Makefiles' generator - failure
      --------------------------------------------------------------------------------
      
                      ********************************************************************************
                      scikit-build could not get a working generator for your system. Aborting build.
      
                      Building Linux wheels for Python 3.11 requires a compiler (e.g gcc).
      But scikit-build does *NOT* know how to install it on ubuntu
      
      To build compliant wheels, consider using the manylinux system described in PEP-513.
      Get it with "dockcross/manylinux-x64" docker image:
      
        https://github.com/dockcross/dockcross#readme
      
      For more details, please refer to scikit-build documentation:
      
        http://scikit-build.readthedocs.io/en/latest/generators.html#linux
      
                      ********************************************************************************
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects

**Comment by hanwsf** [comment]
> No CMAKE_CXX_COMPILER could be found.

install cmake

**Comment by williamsoo** [comment]
I have the same issue. Tried this but nothing works:

To install a C++ compiler on Windows 10/11, follow these steps:

    Install Visual Studio 2022.
    Make sure the following components are selected:
        Universal Windows Platform development
        C++ CMake tools for Windows
    Download the MinGW installer from the [MinGW website](https://sourceforge.net/projects/mingw/).
    Run the installer and select the gcc component.


**Will be good to get some advices. I am installing this on a Windows Laptop.

**Comment by jon2allen** [comment]
> I got the same issue, I just had to install gcc on Mac and ubuntu that solved my issues.
> 
> Look here how to install in mac using brew: https://discussions.apple.com/thread/8336714
> 
> And this one to install in ubuntu: sudo apt-get install build-essential -y


Same for FreeBSD - you have to have GCC and tools.  Use environment variable to change the default when doing the pip install.  

pkg install gcc12

CXX=g++ CC=gcc LD=g++

**Comment by uzziwizzle** [comment]
> https://github.com/ggerganov/llama.cpp#usage Finish the step of "Build"

I get this with make and cmake

[  6%] Building C object CMakeFiles/ggml.dir/ggml.c.o
/home/uzo/privateGPT/llama.cpp/ggml.c: In function ‘bytes_from_nibbles_32’:
/home/uzo/privateGPT/llama.cpp/ggml.c:534:27: warning: implicit declaration of function ‘_mm256_set_m128i’; did you mean ‘_mm256_set_epi8’? [-Wimplicit-function-declaration]
     const __m256i bytes = _mm256_set_m128i(_mm_srli_epi16(tmp, 4), tmp);
                           ^~~~~~~~~~~~~~~~
                           _mm256_set_epi8
/home/uzo/privateGPT/llama.cpp/ggml.c:534:27: error: incompatible types when initializing type ‘__m256i {aka const __vector(4) long long int}’ using type ‘int’

**Comment by uzziwizzle** [comment]
> o install in ubuntu: sudo apt-get install build-essential -y

I use ubuntu. gcc is installed still no luck

**Comment by uzziwizzle** [comment]
> es of output

I did. Same error

**Comment by ksejan** [comment]
> I get the error ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects
> 
> How do you suggest I fix? Ubuntu 18 python 3.11

I got the same error on Windows, installed Visual Studio and everything it told me but nothing fixed, so i switched to Linux and used a Ubuntu 22.04 machine and worked fine!

**Comment by tonaltti** [comment]
Windows users, install [C++ Build Tools](https://visualstudio.microsoft.com/visual-cpp-build-tools/) and tick "Visual C++ tools for CMake" in Individual components.

**Comment by mushafeel** [comment]
Windows 10 user... I was able to overcome the error by opening Visual Studio Installer and going to invidual components, then installating the latest Windows 10 SDK under SDKs, libraries, and frameworks.

**Comment by uzziwizzle** [comment]
I fixed this by upgrading to ubuntu 22.

**Comment by cadelina** [comment]
> Windows 10 user... I was able to overcome the error by opening Visual Studio Installer and going to invidual components, then installating the latest Windows 10 SDK under SDKs, libraries, and frameworks.

Thanks. 
This works in Windows 11. 
Within Visual Studio Installer go to Individual Components select and install all SDKs, Libraries, and frameworks.

![Screenshot 2023-06-12 131004](https://github.com/imartinez/privateGPT/assets/4171538/c6be0f89-ecd0-4a43-9ed7-5ffe0d3b5b14)

**Comment by ye-ye823** [comment]
Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [173 lines of output]


      --------------------------------------------------------------------------------
      -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is MSVC 19.36.32535.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: D:/applicationSoft/vs_BuildTools/vs/VC/Tools/MSVC/14.36.32532/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is MSVC 19.36.32535.0
      CMake Warning (dev) at C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-build-env-vjbi0lb3/overlay/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:168 (if):
        Policy CMP0054 is not set: Only interpret if() arguments as variables or
        keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
        details.  Use the cmake_policy command to set the policy and suppress this
        warning.

        Quoted variables like "MSVC" will no longer be dereferenced when the policy
        is set to NEW.  Since the policy is not set the OLD behavior will be used.
      Call Stack (most recent call first):
        CMakeLists.txt:4 (ENABLE_LANGUAGE)
      This warning is for project developers.  Use -Wno-dev to suppress it.

      CMake Warning (dev) at C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-build-env-vjbi0lb3/overlay/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:189 (elseif):
        Policy CMP0054 is not set: Only interpret if() arguments as variables or
        keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
        details.  Use the cmake_policy command to set the policy and suppress this
        warning.

        Quoted variables like "MSVC" will no longer be dereferenced when the policy
        is set to NEW.  Since the policy is not set the OLD behavior will be used.
      Call Stack (most recent call first):
        CMakeLists.txt:4 (ENABLE_LANGUAGE)
      This warning is for project developers.  Use -Wno-dev to suppress it.

      -- Detecting CXX compiler ABI info
      CMake Warning in C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-install-6m41_veo/llama-cpp-python_28c6c34830f34192b5e6669d19f1df6b/_cmake_test_compile/build/CMakeFiles/CMakeScratch/TryCompile-fc3sej/CMakeLists.txt:
        The object file directory

          C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-install-6m41_veo/llama-cpp-python_28c6c34830f34192b5e6669d19f1df6b/_cmake_test_compile/build/CMakeFiles/CMakeScratch/TryCompile-fc3sej/CMakeFiles/cmTC_ac727.dir/./

        has 225 characters.  The maximum full path to an object file is 250
        characters (see CMAKE_OBJECT_PATH_MAX).  Object file

          CMakeCXXCompilerABI.cpp.obj

        cannot be safely placed under this directory.  The build may not work
        correctly.


      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: D:/applicationSoft/vs_BuildTools/vs/VC/Tools/MSVC/14.36.32532/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (1.3s)
      -- Generating done (0.0s)
      -- Build files have been written to: C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-install-6m41_veo/llama-cpp-python_28c6c34830f34192b5e6669d19f1df6b/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator - success
      --------------------------------------------------------------------------------

      Configuring Project
        Working directory:
          C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-install-6m41_veo\llama-cpp-python_28c6c34830f34192b5e6669d19f1df6b\_skbuild\win-amd64-3.11\cmake-build
        Command:
          'C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-vjbi0lb3\overlay\Lib\site-packages\cmake\data\bin/cmake.exe' 'C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-install-6m41_veo\llama-cpp-python_28c6c34830f34192b5e6669d19f1df6b' -G Ninja '-DCMAKE_MAKE_PROGRAM:FILEPATH=C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-vjbi0lb3\overlay\Lib\site-packages\ninja\data\bin\ninja' -D_SKBUILD_FORCE_MSVC=1930 --no-warn-unused-cli '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-install-6m41_veo\llama-cpp-python_28c6c34830f34192b5e6669d19f1df6b\_skbuild\win-amd64-3.11\cmake-install' -DPYTHON_VERSION_STRING:STRING=3.11.4 -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-vjbi0lb3\overlay\Lib\site-packages\skbuild\resources\cmake' '-DPYTHON_EXECUTABLE:PATH=D:\applicationSoft\python3.11\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=D:\applicationSoft\python3.11\Include' '-DPYTHON_LIBRARY:PATH=D:\applicationSoft\python3.11\libs\python311.lib' '-DPython_EXECUTABLE:PATH=D:\applicationSoft\python3.11\python.exe' '-DPython_ROOT_DIR:PATH=D:\applicationSoft\python3.11' -DPython_FIND_REGISTRY:STRING=NEVER '-DPython_INCLUDE_DIR:PATH=D:\applicationSoft\python3.11\Include' '-DPython_LIBRARY:PATH=D:\applicationSoft\python3.11\libs\python311.lib' '-DPython3_EXECUTABLE:PATH=D:\applicationSoft\python3.11\python.exe' '-DPython3_ROOT_DIR:PATH=D:\applicationSoft\python3.11' -DPython3_FIND_REGISTRY:STRING=NEVER '-DPython3_INCLUDE_DIR:PATH=D:\applicationSoft\python3.11\Include' '-DPython3_LIBRARY:PATH=D:\applicationSoft\python3.11\libs\python311.lib' '-DCMAKE_MAKE_PROGRAM:FILEPATH=C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-vjbi0lb3\overlay\Lib\site-packages\ninja\data\bin\ninja' -DCMAKE_BUILD_TYPE:STRING=Release

      Not searching for unused variables given on the command line.
      -- The C compiler identification is MSVC 19.36.32535.0
      -- The CXX compiler identification is MSVC 19.36.32535.0
      -- Detecting C compiler ABI info
      CMake Warning in C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-install-6m41_veo/llama-cpp-python_28c6c34830f34192b5e6669d19f1df6b/_skbuild/win-amd64-3.11/cmake-build/CMakeFiles/CMakeScratch/TryCompile-gooqhk/CMakeLists.txt:
        The object file directory

          C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-install-6m41_veo/llama-cpp-python_28c6c34830f34192b5e6669d19f1df6b/_skbuild/win-amd64-3.11/cmake-build/CMakeFiles/CMakeScratch/TryCompile-gooqhk/CMakeFiles/cmTC_e1c94.dir/./

        has 235 characters.  The maximum full path to an object file is 250
        characters (see CMAKE_OBJECT_PATH_MAX).  Object file

          CMakeCCompilerABI.c.obj

        cannot be safely placed under this directory.  The build may not work
        correctly.


      -- Detecting C compiler ABI info - failed
      -- Check for working C compiler: D:/applicationSoft/vs_BuildTools/vs/VC/Tools/MSVC/14.36.32532/bin/Hostx86/x64/cl.exe
      CMake Warning in C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-install-6m41_veo/llama-cpp-python_28c6c34830f34192b5e6669d19f1df6b/_skbuild/win-amd64-3.11/cmake-build/CMakeFiles/CMakeScratch/TryCompile-a7ko0b/CMakeLists.txt:
        The object file directory

          C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-install-6m41_veo/llama-cpp-python_28c6c34830f34192b5e6669d19f1df6b/_skbuild/win-amd64-3.11/cmake-build/CMakeFiles/CMakeScratch/TryCompile-a7ko0b/CMakeFiles/cmTC_781fa.dir/./

        has 235 characters.  The maximum full path to an object file is 250
        characters (see CMAKE_OBJECT_PATH_MAX).  Object file

          testCCompiler.c.obj

        cannot be safely placed under this directory.  The build may not work
        correctly.


      -- Check for working C compiler: D:/applicationSoft/vs_BuildTools/vs/VC/Tools/MSVC/14.36.32532/bin/Hostx86/x64/cl.exe - broken
      CMake Error at C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-build-env-vjbi0lb3/overlay/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:67 (message):
        The C compiler

          "D:/applicationSoft/vs_BuildTools/vs/VC/Tools/MSVC/14.36.32532/bin/Hostx86/x64/cl.exe"

        is not able to compile a simple test program.

        It fails with the following output:

          Change Dir: C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-install-6m41_veo/llama-cpp-python_28c6c34830f34192b5e6669d19f1df6b/_skbuild/win-amd64-3.11/cmake-build/CMakeFiles/CMakeScratch/TryCompile-a7ko0b

          Run Build Command(s):C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-build-env-vjbi0lb3/overlay/Lib/site-packages/ninja/data/bin/ninja -v cmTC_781fa && [1/2] D:\applicationSoft\vs_BuildTools\vs\VC\Tools\MSVC\14.36.32532\bin\Hostx86\x64\cl.exe  /nologo   /DWIN32 /D_WINDOWS  /Zi /Ob0 /Od /RTC1 -MDd /showIncludes /FoCMakeFiles\cmTC_781fa.dir\testCCompiler.c.obj /FdCMakeFiles\cmTC_781fa.dir\ /FS -c C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-install-6m41_veo\llama-cpp-python_28c6c34830f34192b5e6669d19f1df6b\_skbuild\win-amd64-3.11\cmake-build\CMakeFiles\CMakeScratch\TryCompile-a7ko0b\testCCompiler.c
          [2/2] cmd.exe /C "cd . && C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-vjbi0lb3\overlay\Lib\site-packages\cmake\data\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_781fa.dir --rc=C:\PROGRA~2\WINDOW~1\10\bin\100203~1.0\x86\rc.exe --mt=C:\PROGRA~2\WINDOW~1\10\bin\100203~1.0\x86\mt.exe --manifests  -- D:\applicationSoft\vs_BuildTools\vs\VC\Tools\MSVC\14.36.32532\bin\Hostx86\x64\link.exe /nologo CMakeFiles\cmTC_781fa.dir\testCCompiler.c.obj  /out:cmTC_781fa.exe /implib:cmTC_781fa.lib /pdb:cmTC_781fa.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
          FAILED: cmTC_781fa.exe
          cmd.exe /C "cd . && C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-vjbi0lb3\overlay\Lib\site-packages\cmake\data\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_781fa.dir --rc=C:\PROGRA~2\WINDOW~1\10\bin\100203~1.0\x86\rc.exe --mt=C:\PROGRA~2\WINDOW~1\10\bin\100203~1.0\x86\mt.exe --manifests  -- D:\applicationSoft\vs_BuildTools\vs\VC\Tools\MSVC\14.36.32532\bin\Hostx86\x64\link.exe /nologo CMakeFiles\cmTC_781fa.dir\testCCompiler.c.obj  /out:cmTC_781fa.exe /implib:cmTC_781fa.lib /pdb:cmTC_781fa.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
          RC Pass 1: command "C:\PROGRA~2\WINDOW~1\10\bin\100203~1.0\x86\rc.exe /fo CMakeFiles\cmTC_781fa.dir/manifest.res CMakeFiles\cmTC_781fa.dir/manifest.rc" failed (exit code 2) with the following output:
          Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384


          Copyright (C) Microsoft Corporation.  All rights reserved.






          CMakeFiles\cmTC_781fa.dir/manifest.rc(3) : error RC2136 : missing '=' in EXSTYLE=<flags>


          ninja: build stopped: subcommand failed.





        CMake will not be able to correctly generate this project.
      Call Stack (most recent call first):
        CMakeLists.txt:3 (project)


      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-vjbi0lb3\overlay\Lib\site-packages\skbuild\setuptools_wrap.py", line 666, in setup
          env = cmkr.configure(
                ^^^^^^^^^^^^^^^
        File "C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-vjbi0lb3\overlay\Lib\site-packages\skbuild\cmaker.py", line 357, in configure
          raise SKBuildError(msg)

      An error occurred while configuring with CMake.
        Command:
          'C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-vjbi0lb3\overlay\Lib\site-packages\cmake\data\bin/cmake.exe' 'C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-install-6m41_veo\llama-cpp-python_28c6c34830f34192b5e6669d19f1df6b' -G Ninja '-DCMAKE_MAKE_PROGRAM:FILEPATH=C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-vjbi0lb3\overlay\Lib\site-packages\ninja\data\bin\ninja' -D_SKBUILD_FORCE_MSVC=1930 --no-warn-unused-cli '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-install-6m41_veo\llama-cpp-python_28c6c34830f34192b5e6669d19f1df6b\_skbuild\win-amd64-3.11\cmake-install' -DPYTHON_VERSION_STRING:STRING=3.11.4 -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-vjbi0lb3\overlay\Lib\site-packages\skbuild\resources\cmake' '-DPYTHON_EXECUTABLE:PATH=D:\applicationSoft\python3.11\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=D:\applicationSoft\python3.11\Include' '-DPYTHON_LIBRARY:PATH=D:\applicationSoft\python3.11\libs\python311.lib' '-DPython_EXECUTABLE:PATH=D:\applicationSoft\python3.11\python.exe' '-DPython_ROOT_DIR:PATH=D:\applicationSoft\python3.11' -DPython_FIND_REGISTRY:STRING=NEVER '-DPython_INCLUDE_DIR:PATH=D:\applicationSoft\python3.11\Include' '-DPython_LIBRARY:PATH=D:\applicationSoft\python3.11\libs\python311.lib' '-DPython3_EXECUTABLE:PATH=D:\applicationSoft\python3.11\python.exe' '-DPython3_ROOT_DIR:PATH=D:\applicationSoft\python3.11' -DPython3_FIND_REGISTRY:STRING=NEVER '-DPython3_INCLUDE_DIR:PATH=D:\applicationSoft\python3.11\Include' '-DPython3_LIBRARY:PATH=D:\applicationSoft\python3.11\libs\python311.lib' '-DCMAKE_MAKE_PROGRAM:FILEPATH=C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-vjbi0lb3\overlay\Lib\site-packages\ninja\data\bin\ninja' -DCMAKE_BUILD_TYPE:STRING=Release
        Source directory:
          C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-install-6m41_veo\llama-cpp-python_28c6c34830f34192b5e6669d19f1df6b
        Working directory:
          C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-install-6m41_veo\llama-cpp-python_28c6c34830f34192b5e6669d19f1df6b\_skbuild\win-amd64-3.11\cmake-build
      Please see CMake's output for more information.

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects

windows10

**Comment by csocha** [comment]
> cadelina

This fixed it for me. After hours and hours in VS.CODE terminal, CMD lines, going to the visual studio installer -> MS Build tools command prompt fixed it.

I noticed that when I do a c:\PATH, I get a totally different set of paths than if I do it in VS.CODE terminal, so clearly there is something there.
