### ISSUE TITLE
Sending data to posthog when trying to run offline

### ISSUE THREAD

**Issue by foosinn** [imartinez/privateGPT#34]
When running this in an offline container i noticed that it's trying to send requests to `app.posthog.com`

```
Enter a query: [2023-05-11 09:04:09,252] {_common.py:105} INFO - Backing off send_request(...) for 0.8s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='app.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8150e6b190>: Failed to resolve 'app.posthog.com' ([Errno -3] Temporary failure in name resolution)")))
```

Whats going on here?

**Comment by digitalw00t** [comment]
I'm not the author or affiliated with this package at all, just found out about it, but it's got to be coming from one of the packages it's using from a pip installed module.

**Comment by digitalw00t** [comment]
Looks like chroma is the culprit here.

chromadb-0.3.22.dist-info/RECORD:chromadb/telemetry/__pycache__/posthog.cpython-310.pyc,,
chromadb-0.3.22.dist-info/RECORD:chromadb/telemetry/posthog.py,sha256=-KD9HgV3H1gfg3blol9FhgmHuFA-jUY0h0NFkxqFt64,1041
chromadb-0.3.22.dist-info/METADATA:Requires-Dist: posthog (>=2.4.0)

**Comment by R-Y-M-R** [comment]
I will try to make a PR for this.

**Comment by imartinez** [comment]
Yes, it is ChromaDB telemetry anonymized data, but it can be disabled
https://github.com/chroma-core/chroma/blob/e62821f6d33ac02ccf379e60d232735d9dd7c00a/chromadb/__init__.py#L68

**Comment by digitalw00t** [comment]
To fix it, just turn off telemetry. 

Line 17:
    db = Chroma.from_documents(texts, llama, persist_directory=persist_directory, telemetry_enabled=False)

**Comment by digitalw00t** [comment]
That's from what I modified in the ingest.py.  I sent you a google chat request to talk about it if you wouldn't mind.
