### ISSUE TITLE
privateGPT.py fails with models/ggml-gpt4all-j-v1.3-groovy.bin not found!

### ISSUE THREAD

**Issue by GeeksikhSecurity** [imartinez/privateGPT#351]
Note: if you'd like to *ask a question* or *open a discussion*, head over to the [Discussions](https://github.com/imartinez/privateGPT/discussions) section and post it there.

**Describe the bug and how to reproduce it**
PrivateGPT.py fails with model not found. The ingest worked and created files in db folder.

Path not found issues for the model even when defined in the environment variable. Any suggestions would be appreciated:

C:\Users\geek\AppData\Roaming\Python\Python310\site-packages\langchain\llms\gpt4all.py", line 169, in validate_environment
    values["client"] = GPT4AllModel(
  File "C:\Users\geek\AppData\Roaming\Python\Python310\site-packages\pygpt4all\models\gpt4all_j.py", line 47, in init
    super(GPT4All_J, self).init(model_path=model_path,
  File "C:\Users\geek\AppData\Roaming\Python\Python310\site-packages\pygptj\model.py", line 58, in init
    raise Exception(f"File {model_path} not found!")
Exception: File models/ggml-gpt4all-j-v1.3-groovy.bin not found!
 GPT4All  dir

    Directory: C:\Users\geek\AppData\Local\nomic.ai\GPT4All

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        5/21/2023   4:35 PM                  cache
d-----        5/21/2023   9:21 PM                  db
-a----        5/21/2023   4:37 PM     3785248281   ggml-gpt4all-j-v1.3-groovy.bin
-a----        5/21/2023   6:32 PM     7955935232   incomplete-ggml-gpt4all-l13b-snoozy.bin
-a----        5/21/2023   4:35 PM              0   test_write.txt

 GPT4All  dir db

<PATH Abbreviated> ... C:\Users\geek\AppData\Local\nomic.ai\GPT4All;C:\Users\geek\AppData\Roaming\Python\Python310\Scripts 

**Expected behavior**
With path environment in place it should find the model and show the chat.

**Environment (please complete the following information):**
 - OS / hardware:  Windows 10 Home
 - Python version 
conda --version
conda 23.3.1

python --version
Python 3.10.9
- Other relevant information

**Additional context**

**Comment by mikedijkstra** [comment]
This is not a bug. As per the README:

> Then, download the LLM model and place it in a directory of your choice:

LLM: default to [ggml-gpt4all-j-v1.3-groovy.bin](https://gpt4all.io/models/ggml-gpt4all-j-v1.3-groovy.bin). If you prefer a different GPT4All-J compatible model, just download it and reference it in your .env file.

Download that file and put it in a new folder called `models`

**Comment by ravindraprasad75** [comment]
Create a folder called "models" and download [ggml-gpt4all-j-v1.3-groovy.bin](https://gpt4all.io/models/ggml-gpt4all-j-v1.3-groovy.bin) in to the folder

<img width="497" alt="image" src="https://github.com/imartinez/privateGPT/assets/14846630/d8740b89-c856-4d44-a703-042e24cf58f3">

**Comment by GeeksikhSecurity** [comment]
Thanks for the insight and your help!

 

 

Regards,

Gurvinder Singh

 

Linkedin: www.linkedin.com/in/gurvindersinghb <http://hwww.linkedin.com/in/gurvindersinghb> 

Twitter: twitter.com/gurvindersinghb <https://twitter.com/gurvindersinghb> 


------

The aim of life, according to the Sikh Gurus, is not to get salvation or a heavenly abode called Paradise, but to develop the best in us which is God.

Principal Teja Singh in his essay "Outline of Sikh Doctrines"

**Comment by chrisbvt** [comment]
This works so long as langchain is on langchain==0.0.306 or below just FYI
