### ISSUE TITLE
error in Chroma settings

### ISSUE THREAD

**Issue by ravindranantony** [imartinez/privateGPT#357]
C:\Users\rantonys\source\repos\privateGPT> python ingest.py
Traceback (most recent call last):
  File "C:\Users\xxxx\source\repos\privateGPT\ingest.py", line 27, in <module>
    from constants import CHROMA_SETTINGS
  File "C:\Users\rantonys\source\repos\privateGPT\constants.py", line 11, in <module>
    CHROMA_SETTINGS = Settings(
  File "pydantic\env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
persist_directory

**Describe the bug and how to reproduce it**
trying to use ingest..py but I am not sure what is 'duckdb+parquet' in the chroma settings.

CHROMA_SETTINGS = Settings(
        chroma_db_impl='duckdb+parquet',
        persist_directory=PERSIST_DIRECTORY,
        anonymized_telemetry=False
)

this is what my settings now 

**Expected behavior**
Should be possible to Ingest

**Environment (please complete the following information):**
 - OS / hardware: Windows 11
 -  - Python version 3.9.5

**Comment by monkeydust** [comment]
Same issue just now on fresh first time install:

(privategpt) C:\Users\admin\privateGPT>python ingest.py
Traceback (most recent call last):
  File "C:\Users\admin\privateGPT\ingest.py", line 27, in <module>
    from constants import CHROMA_SETTINGS
  File "C:\Users\admin\privateGPT\constants.py", line 11, in <module>
    CHROMA_SETTINGS = Settings(
  File "pydantic\env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
persist_directory
  none is not an allowed value (type=type_error.none.not_allowed)

**Comment by monkeydust** [comment]
Had same thing, its in the readme

- rename environment.env to .env 
- make sure you set a path for db e.g. on windows I have 'C:/temp'

works then

**Comment by ravindranantony** [comment]
super good, works now !!

**Comment by ravindranantony** [comment]
Downloading (…)_Pooling/config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 190/190 [00:00<00:00, 27.4kB/s]
Downloading (…)7e55de9125/README.md: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10.6k/10.6k [00:00<00:00, 2.66MB/s]
Downloading (…)55de9125/config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 612/612 [00:00<00:00, 301kB/s]
Downloading (…)ce_transformers.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 116/116 [00:00<00:00, 29.4kB/s]
Downloading (…)125/data_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 39.3k/39.3k [00:00<00:00, 367kB/s]
Downloading pytorch_model.bin: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 90.9M/90.9M [00:02<00:00, 30.5MB/s]
Downloading (…)nce_bert_config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 53.0/53.0 [00:00<00:00, 6.60kB/s]
Downloading (…)cial_tokens_map.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 112/112 [00:00<00:00, 22.6kB/s]
Downloading (…)e9125/tokenizer.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 466k/466k [00:00<00:00, 1.47MB/s]
Downloading (…)okenizer_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 350/350 [00:00<00:00, 175kB/s]
Downloading (…)9125/train_script.py: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13.2k/13.2k [00:00<00:00, 2.18MB/s]
Downloading (…)7e55de9125/vocab.txt: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 232k/232k [00:00<00:00, 887kB/s]
Downloading (…)5de9125/modules.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 349/349 [00:00<00:00, 168kB/s]
Creating new vectorstore
Loading documents from source_documents
Loading new documents: 100%|██████████████████████| 7/7 [00:03<00:00,  2.01it/s]
Loaded 7 new documents from source_documents
Split into 103 chunks of text (max. 500 tokens each)
Creating embeddings. May take some minutes...
Traceback (most recent call last):
  File "C:\Users\rantonys\source\repos\privateGPT\ingest.py", line 167, in <module>
    main()
  File "C:\Users\rantonys\source\repos\privateGPT\ingest.py", line 159, in main
    db = Chroma.from_documents(texts, embeddings, persist_directory=persist_directory, client_settings=CHROMA_SETTINGS)
  File "C:\Users\rantonys\AppData\Roaming\Python\Python39\site-packages\langchain\vectorstores\chroma.py", line 413, in from_documents
    return cls.from_texts(
  File "C:\Users\rantonys\AppData\Roaming\Python\Python39\site-packages\langchain\vectorstores\chroma.py", line 374, in from_texts
    chroma_collection = cls(
  File "C:\Users\rantonys\AppData\Roaming\Python\Python39\site-packages\langchain\vectorstores\chroma.py", line 88, in __init__
    self._client = chromadb.Client(self._client_settings)
  File "C:\Users\rantonys\AppData\Roaming\Python\Python39\site-packages\chromadb\__init__.py", line 91, in Client
    return chromadb.api.local.LocalAPI(settings, get_db(settings), telemetry_client)
  File "C:\Users\rantonys\AppData\Roaming\Python\Python39\site-packages\chromadb\__init__.py", line 58, in get_db
    raise ValueError(
ValueError: Expected chroma_db_impl to be one of clickhouse, duckdb, duckdb+parquet, got c:/temp

now I have this !!
