### ISSUE TITLE
Can't run ingest any more: none is not an allowed value (type=type_error.none.not_allowed)

### ISSUE THREAD

**Issue by ibardarov-fms** [imartinez/privateGPT#359]
I tried to run ingest in a new python environment but I got the following error.

```
12:02:11 ∴ ./ingest.py
Traceback (most recent call last):
  File "/home/g/projects/privateGPT/./ingest.py", line 167, in <module>
    main()
  File "/home/g/projects/privateGPT/./ingest.py", line 144, in main
    embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name)
  File "/home/g/.cache/pypoetry/virtualenvs/privategpt-FaFjlDWE-py3.10/lib/python3.10/site-packages/langchain/embeddings/huggingface.py", line 44, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for HuggingFaceEmbeddings
model_name
  none is not an allowed value (type=type_error.none.not_allowed)
```

**Environment (please complete the following information):**
Linux, tried with Python 10, and 11

.env
```
PERSIST_DIRECTORY=db
LLAMA_EMBEDDINGS_MODEL=/home/g/projects/privateGPT/models/ggml-model-q4_0.bin
MODEL_TYPE=GPT4All
MODEL_PATH=/home/g/projects/privateGPT/models/ggml-gpt4all-j-v1.3-groovy.bin
MODEL_N_CTX=1000
```

**Comment by PulpCattel** [comment]
You are using an old version of this repo, update to the latest version, re install the requirements and recreate your `.env`. It should look like this:

```
PERSIST_DIRECTORY=db
MODEL_TYPE=GPT4All
MODEL_PATH=models/ggml-gpt4all-j-v1.3-groovy.bin
EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
MODEL_N_CTX=1000
```

**Comment by vjrngn** [comment]
For those coming to issue, this is what worked for me (python noob here 😅)

1. `cp example.env .env`
2. `rm -rf db`
3. `python3 ingest.py`

Hope this helps 🙌🏻

**Comment by vtboyarc** [comment]
I can't seem to find the example.env in the first place...

**Comment by vtboyarc** [comment]
ok this seemed to fix my issue, in ui.py: 
`def build_history() -> list[ChatMessage]:
            history_messages: list[ChatMessage] = list(
        itertools.chain(
            *[
                [
                    ChatMessage(content=interaction[0], role=MessageRole.USER),
                    ChatMessage(
                        # Check if interaction[1] is not None before splitting
                        content=(interaction[1].split(SOURCES_SEPARATOR)[0] if interaction[1] is not None else None),
                        role=MessageRole.ASSISTANT,
                    ),
                ]
                for interaction in history
            ]
        )
    )


            # max 20 messages to try to avoid context overflow
            return history_messages[:20]`
