### ISSUE TITLE
ingest.py packages imports problems 

### ISSUE THREAD

**Issue by GuySarkinsky** [imartinez/privateGPT#360]
ingest.py file Import problems:

![image](https://github.com/imartinez/privateGPT/assets/46380994/7878426b-7441-427a-b595-5804bc4b3eac)

For example, tqdm already satisfied:

![image](https://github.com/imartinez/privateGPT/assets/46380994/79432991-2432-433a-b1bd-b9d56558f82c)

![image](https://github.com/imartinez/privateGPT/assets/46380994/20cd91cb-ca6a-4f7f-a56e-cb96176f7aab)

Device specifications:
![image](https://github.com/imartinez/privateGPT/assets/46380994/c3f7fc06-aab3-4443-b7f0-abe82039ab8d)

**Comment by PulpCattel** [comment]
The problem of requirements in visual studio seems related to your setup/configuration of visual studio itself. The script works so you clearly have them.

The `unknown token` is unrelated, see https://github.com/imartinez/privateGPT/issues/214 and many other duplicate issues.

**Comment by GuySarkinsky** [comment]
@PulpCattel 

You're right, I just didn't notice the process takes more than 15 minutes to create an answer.

How can results be improved? Can a GPU be integrated into the processing?
