### ISSUE TITLE
Failed to retrive model

### ISSUE THREAD

**Issue by ravindranantony** [imartinez/privateGPT#368]
Getting the Error after all the setup is done.

PS C:\Users\rantonys\source\repos\privateGPT> python privateGPT.py
Using embedded DuckDB with persistence: data will be stored in: C:\Users\rantonys\source\repos\privateGPT
Traceback (most recent call last):
  File "C:\Users\rantonys\source\repos\privateGPT\privateGPT.py", line 75, in <module>
    main()
  File "C:\Users\rantonys\source\repos\privateGPT\privateGPT.py", line 35, in main
    llm = GPT4All(model=model_path, n_ctx=model_n_ctx, backend='gptj', callbacks=callbacks, verbose=False)

          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GPT4All
__root__
  Failed to retrieve model (type=value_error)

**Describe the bug and how to reproduce it**
After all the setup, trying to run python privategpt.py in the vscode terminal

**Expected behavior**
should be running

**Environment (please complete the following information):**
 - OS / hardware: Windows 11
 - Python version 3.11.3
- Other relevant information

**Comment by ravindranantony** [comment]
I think the model was not downloaded properly

**Comment by bambang** [comment]
you should download the [ggml-gpt4all-j-v1.3-groovy.bin](https://gpt4all.io/models/ggml-gpt4all-j-v1.3-groovy.bin) file and put it in the model directory.
