### ISSUE TITLE
Output speed is increasingly slow more then 15 minuets for output.

### ISSUE THREAD

**Issue by GuySarkinsky** [imartinez/privateGPT#381]
### Discussed in https://github.com/imartinez/privateGPT/discussions/380

<div type='discussions-op-text'>

<sup>Originally posted by **GuySarkinsky** May 22, 2023</sup>
 How results can be improved to make sense for using privateGPT?

The model I use:  ggml-gpt4all-j-v1.3-groovy

Device specifications:

Device name	
Full device name	
Processor	Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz   2.11 GHz
Installed RAM	16.0 GB (15.9 GB usable)
Device ID	
Product ID	
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

* I understand that at the moment it is impossible to use GPU.

 
 </div>

**Comment by owenpmckenna** [comment]
You could also use a smaller model if you're willing to accept a possibly (probably somewhat) inferior response quality.
