### ISSUE TITLE
Stuck while running ingest.py process

### ISSUE THREAD

**Issue by d-bliss** [imartinez/privateGPT#388]
**The ingest process keep getting stuck at 86% (the last document) as below:**

🔥 /usr/local/bin/python3 /Users/MyName/Documents/programming-files/privateGPT-1/ingest.py
Creating new vectorstore
Loading documents from source_documents
Loading new documents:  86%|██████████████████▊   | 6/7 [00:06<00:00,  1.31it/s]

**Environment:**
 - OS / hardware: [e.g. macOS 13.3.1 / Intel]
 - Python version [Python 3.11.0]

**Additional context**
I've followed the steps as per the README. I have the requirements downloaded, and the ggml-gpt4all-j-v1.3-groovy.bin file in a models directory at the  same level as the project folder. The .env folder is renames as .env and set as below:

PERSIST_DIRECTORY=db
MODEL_TYPE=GPT4All
MODEL_PATH=models/ggml-gpt4all-j-v1.3-groovy.bin
EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
MODEL_N_CTX=1000

My source documents are seven PDF files. No idea why this is getting stuck on ingest. We don't need to download the all-MiniLM-L6-v2 seperatly? I assume that code is contained in the ggml-gpt4all-j-v1.3-groovy.bin file.

**Comment by maozdemir** [comment]
It's possible that the given document might be corrupted/could not be read by the respective module.
`all-MiniLM-L6-v2` is included in the `sentence-transformers` module.

**Comment by d-bliss** [comment]
Yes, I just sorted this thanks. I believe it may have been the documents.
