### ISSUE TITLE
Getting the following error when trying to run the ingest.py for the first time. 

### ISSUE THREAD

**Issue by ericflecher** [imartinez/privateGPT#393]
ingest.py
Traceback (most recent call last):
  File "/Users/ericflecher/Library/Mobile Documents/com~apple~CloudDocs/bckto/privateGPT/ingest.py", line 9, in <module>
    from langchain.document_loaders import (
ImportError: cannot import name 'UnstructuredODTLoader' from 'langchain.document_loaders' (/Users/ericflecher/Library/Python/3.9/lib/python/site-packages/langchain/document_loaders/__init__.py)

**Comment by maozdemir** [comment]
Python 3.10 is needed, you are using 3.9...

**Comment by ericflecher** [comment]
that was it thanks!

**Comment by albertcolmenero** [comment]
Hi there, I got the following error :
ImportError: cannot import name 'UnstructuredODTLoader' from 'langchain.document_loaders' (/Users/XXX/anaconda3/lib/python3.10/site-packages/langchain/document_loaders/__init__.py)

can someone help?

**Comment by mbaggnx** [comment]
> Python 3.10 is needed, you are using 3.9...

i am using 3.11... i should downgrade?

**Comment by maozdemir** [comment]
> > Python 3.10 is needed, you are using 3.9...
> 
> i am using 3.11... i should downgrade?

No, 3.10 or higher is fine.
