### ISSUE TITLE
Does it support languages rather than English?

### ISSUE THREAD

**Issue by buntouka** [imartinez/privateGPT#403]
Note: if you'd like to *ask a question* or *open a discussion*, head over to the [Discussions](https://github.com/imartinez/privateGPT/discussions) section and post it there.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by razem-io** [comment]
Yes, it does. privateGPT is at its current state a basic implementation of the following feature: https://python.langchain.com/en/latest/modules/chains/index_examples/vector_db_qa.html

This supports custom prompts. There you can add "answer in <language>". Example here: https://python.langchain.com/en/latest/modules/chains/index_examples/vector_db_qa.html#custom-prompts

**Comment by galdaka** [comment]
What modifications do I have to make in the prompt so that it answers me in Spanish?
