### ISSUE TITLE
Does anyone know which step takes most of the time to run? 

### ISSUE THREAD

**Issue by boboxuan** [imartinez/privateGPT#405]
It takes 10 mins for each query to run. Curious if anyone knows which step takes most of the time to run. The GPT4ALL model is not that slow, is because we need to  search in a large space of index?

**Comment by hatgit** [comment]
does that mean if a project is `Split into 152121 chunks of text (max. 500 tokens each)` that it will take 10 minutes for each chunk? or how do you define query?
