### ISSUE TITLE
 not enough space in the context's memory pool

### ISSUE THREAD

**Issue by keshavjha1** [imartinez/privateGPT#409]
**Describe the bug and how to reproduce it** 
Running more than 3-4 querys on model causing memory leaks exception
**Expected behavior**
Program should not crash 

**Environment (please complete the following information):**
 - OS / hardware: M1 and Linuc
 - Python version- miniconda
- Other relevant information

ggml_new_tensor_impl: not enough space in the context's memory pool (needed 9368316816, available 9347164208)
/Users/miniconda3/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by pseudotensor** [comment]
See: https://github.com/imartinez/privateGPT/issues/104#issuecomment-1559087435
