### ISSUE TITLE
Any models that support Chinese?

### ISSUE THREAD

**Issue by Nickwang2010** [imartinez/privateGPT#41]
I've download the two models. Can I exchange anyone of them to make it support Chinese? 
or  you can add the thrid model that can translate all the language

**Comment by alxspiker** [comment]
Figured it out! I use alpaca7b, which I assume is very similar to GPT4All.

To test this, I created a text document named "ai.txt" and inside added:

```
My name is Alx, and I am 26 years old.
```

Then I ran `python ingest.py source_documents/ai.txt` and changed the privateGPT.py to be like:
```
# Get the answer from the chain
res = qa(f"""The user has asked an AI: {query}. The response translated to Chinese is: """)    
answer, docs = res['result'], res['source_documents']
```

Tested:
`Enter a query: What is my name and my age?`

Output:
`你的名字和准eral 都是26岁。`

P.S. Writing in Chinese was very very slow compared to english. Also I am not chinese, but that did not seem very correct although maybe my name "Alx" in weird in chinese, could try messing with n_ctx maybe to get better results.

**Comment by Hel5ing** [comment]
same requirement

**Comment by zxjason** [comment]
can we set up a QQ group to discuss for Chinese issue?
my QQ is 84095749
