### ISSUE TITLE
Can not ingest

### ISSUE THREAD

**Issue by Edward7n15** [imartinez/privateGPT#417]
I tried to run ingest.py but this error pops up:

```
Traceback (most recent call last):
  File "/Users/usr_name/Downloads/prGPT/privateGPT-main/ingest.py", line 27, in <module>
    from constants import CHROMA_SETTINGS
  File "/Users/usr_name/Downloads/prGPT/privateGPT-main/constants.py", line 11, in <module>
    CHROMA_SETTINGS = Settings(
                      ^^^^^^^^^
  File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
persist_directory
  none is not an allowed value (type=type_error.none.not_allowed)
```

This is my .env
```
PERSIST_DIRECTORY=db
MODEL_TYPE=GPT4All
MODEL_PATH=/Users/usr_name/Downloads/prGPT/privateGPT-main/ggml-gpt4all-j-v1.3-groovy.bin
EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
MODEL_N_CTX=1000
```

**Environment (please complete the following information):**
 - OS / hardware: macOS 13.3.1 / Intel
 - Python version: 3

**Comment by pseudotensor** [comment]
Means `persist_directory` was not set, needs to be string.

Try out https://github.com/h2oai/h2ogpt for better handling of such things, including same CPU support as privateGPT but also full GUI and GPU support.  CPU mode tested on windows/mac.

**Comment by 808isonline** [comment]
I changed the my persist_directory to privateGPT folder path, but it is still not working. 

it gives me the following @pseudotensor. Can you help me understand what I need to do?

Traceback (most recent call last):
  File "/Users/mac300/Documents/GithubRepos/privategpt/privateGPT/ingest.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

**Comment by pseudotensor** [comment]
@808isonline Seems your env does not have dotenv installed, should have been from requirements via:
```
pip install -r requirements.txt
```

i.e. `python-dotenv==1.0.0` inside

**Comment by 808isonline** [comment]
@pseudotensor Hi! thank you for the quick reply! I really appreciate it! 

I did pip install -r requirements.txt in the beginning. 

I ran that command that again and tried python3 ingest.py, but still says:

Traceback (most recent call last):
  File "/Users/mac300/Documents/GithubRepos/privategpt/privateGPT/ingest.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

**Comment by pseudotensor** [comment]
Can you try just running python and see if that import works?


```python
from dotenv import load_dotenv
```

If it doesn't, problem has nothing to do with privateGPT.

**Comment by 808isonline** [comment]
@pseudotensor thank you for the quick reply again!

wait do i just run the following on the terminal?

> from dotenv import load_dotenv

If so I just tried it. And it gave me the following

from: can't read /var/mail/dotenv

**Comment by 808isonline** [comment]
@Edward7n15 

Thank you for the comment. I did that, and got the following

> Defaulting to user installation because normal site-packages is not writeable
> Requirement already satisfied: python-dotenv in /Users/mac300/Library/Python/3.9/lib/python/site-packages (1.0.0)

**Comment by Edward7n15** [comment]
@808isonline 
I did not meet such messages when I install packages. I am going to close the issue now since @pseudotensor has shown me a good direction to solve my problem. Hope you can find yours soon.

**Comment by FlipperUncle** [comment]
Hi @Edward7n15 How have you solved the issue, cause Im facing the same. Woudl I need to change the persist_directory? If yes to what?
