### ISSUE TITLE
Other embedding models?

### ISSUE THREAD

**Issue by dennydream** [imartinez/privateGPT#42]
Has anybody tried other embedding models such as those from Hugging Face?

Also, it can be finicky about certain things-- some unicode characters, size of chunks.  I've had it crash on me on the same file (not example file)

**Comment by Free-Radical** [comment]
I have tried _huggingface_, but whatever I try with **this repo** ends up crashing my Linux machine, although i can get _huggingface embeddings_  to work for other repo's.
