### ISSUE TITLE
GGML Assert error

### ISSUE THREAD

**Issue by ADXXI1590** [imartinez/privateGPT#428]
GGML_ASSERT: C:\Users\circleci.PACKER-64370BA5\project\gpt4all-backend\llama.cpp\ggml.c:4411: ctx->mem_buffer != NULL
not getting any prompt to enter the query?
instead getting the above assertion error? can anyone help with this?

**Comment by Om-GG** [comment]
I have the same issue.

**Comment by jhoughtelin** [comment]
Increase the amount of memory available.  I had the same issue trying to run the python binding of gpt4all. It worked after I provisioned a system with more than 16G of memory.
Slightly different but #90 is also suggesting that the system does not have enough memory.

**Comment by Om-GG** [comment]
Yep, I gave it 8 gb and it started moving, good to know that 16 may be a good number to aim for. It doesn't seem that 8gb would be anywhere near enough, as it moves quite slowly and takes a long time to reply to queries.

**Comment by rwcitek** [comment]
I had the same issue.

I was using a 2 GB cloud instance to build a Docker image with privateGPT.  The build worked.  Here's a link to the  Dockerfile:

https://github.com/rwcitek/privateGPT/blob/docker/docker/Dockerfile

However, when I tried to run `privateGPT.py` in the instance, it would core dump.  Changing the cloud instance to 16GB enabled the container to run.  This is the Docker run command that I used:

```bash
docker run --rm -it rwcitek/privategpt:2023-06-04 python3 privateGPT.py
```

I have not tried it on anything between 2 GB and 16 GB.

**Comment by selcukbeyhan** [comment]
same error. I saw multiple reports of this issue:
https://github.com/imartinez/privateGPT/issues/90
https://github.com/imartinez/privateGPT/issues/186

Is this something part of the model? or something related to this "circleci" user "C:\Users\circleci.PACKER-64370BA5\"?
