### ISSUE TITLE
 illegal hardware instruction  python privateGPT.py

### ISSUE THREAD

**Issue by GitUserForMaster01** [imartinez/privateGPT#430]
After I managed to install, and ingest PrivateGPT succesfully I wanted to start questioning. I'm so excited about this project, and I think the private AI capabilities will be huged. But for now, the following occured. 

Using embedded DuckDB with persistence: data will be stored in: db
Found model file.
gptj_model_load: loading model from 'models/ggml-gpt4all-j-v1.3-groovy.bin' - please wait ...
gptj_model_load: n_vocab = 50400
gptj_model_load: n_ctx   = 2048
gptj_model_load: n_embd  = 4096
gptj_model_load: n_head  = 16
gptj_model_load: n_layer = 28
gptj_model_load: n_rot   = 64
gptj_model_load: f16     = 2
zsh: illegal hardware instruction  python privateGPT.py

I installed privateGPT on Kali in a VM (Virtual Machine).

any help appreciated.

**Comment by apcameron** [comment]
See https://github.com/imartinez/privateGPT/issues/203
