### ISSUE TITLE
add JSON source-document support

### ISSUE THREAD

**Issue by mikee-gwu** [imartinez/privateGPT#433]
**Is your feature request related to a problem? Please describe.**
Its not always easy to convert json documents to csv (when there is nesting or arbitrary arrays of objects involved), so its not just a question of converting json data to csv. JSON to Markdown might work a little better but still seems dirty. Extracting data from the JSON model to upload as a simple text seems a crime since all the context and positional relationships are lost. It is actually a bit surprising the json format isn't natively supported and csv is. Hopefully not a huge lift.

**Describe the solution you'd like**
add the JSON file format as a natively/directly supported source-document.
(as documented in: https://github.com/imartinez/privateGPT#instructions-for-ingesting-your-own-dataset )

**Describe alternatives you've considered**
converting JSON to some other format like Markdown or CSV neither of which is super clean or possible.

**Additional context**

**Comment by sime2408** [comment]
Maybe you're referring to [a langchain agent](https://python.langchain.com/en/latest/modules/agents/toolkits/examples/json.html) who can read JSON?

**Comment by borel** [comment]
or maybe he is refering to
 https://python.langchain.com/en/latest/modules/indexes/document_loaders/examples/json.html
 
 you upload content and metadata quite easely

**Comment by mikee-gwu** [comment]
Hi guys, I was referring to this part of the documentation:

https://github.com/imartinez/privateGPT#instructions-for-ingesting-your-own-dataset

It supports several ways of important data from files including CSV, PDF, HTML, MD etc. but JSON is not on the list of documents that can be ingested. It seems JSON is missing from that list given that CSV and MD are supported and JSON is somewhat adjacent to those data formats. 

If not possible to ingest JSON data in this way, perhaps updating this section of the documentation (https://github.com/imartinez/privateGPT#instructions-for-ingesting-your-own-dataset ) with a "* to ingest JSON data utilize the langchain agent, or JSON document loader." note.

**Comment by sime2408** [comment]
@mikee-gwu try to experiment with these, maybe it helps

```python
from langchain.document_loaders import (
    DirectoryLoader, 
    TextLoader,
    JSONLoader,
)

def load_json():
    # loader = DirectoryLoader("source_documents", glob='**/*.json', show_progress=True, loader_cls=TextLoader)
    # or maybe with JSONLoader
    loader = DirectoryLoader(
        "source_documents", glob='**/*.json', show_progress=True, loader_cls = JSONLoader, 
                             loader_kwargs = {'jq_schema':'.content'}
    )
    
    documents = loader.load()
    print(f'document count: {len(documents)}')
    print(documents[0] if len(documents) > 0 else None)
```

**Comment by borel** [comment]
it's possible to do it quite easely :

```python
from langchain.document_loaders import (
    CSVLoader,
    JSONLoader,
``` 

and 

```python
LOADER_MAPPING = {
    ".csv": (CSVLoader, {}),
    # Add more mappings for other file extensions and loaders as needed
     ".json": (JSONLoader, {"jq_schema":".[].full_text"}),
}
``` 

you can also tune to have some metadata

**Comment by mikee-gwu** [comment]
thanks, I will experiment with these options as a way to import JSON data -- really appreciate the advice.


In terms of this ticket as an RFE request, does the following still hold? 

Describe the solution you'd like: 
add the JSON file format as a natively/directly supported source-document.
(as documented in: https://github.com/imartinez/privateGPT#instructions-for-ingesting-your-own-dataset )

**Comment by Anoupz** [comment]
@mikee-gwu did that work? Were you able to load the JSON data?

**Comment by Anoupz** [comment]
@borel, can you please share your code snippet?
