### ISSUE TITLE
Please provide OpenAI-compliant API

### ISSUE THREAD

**Issue by fishfree** [imartinez/privateGPT#434]
It will be much easier for re-use lots of codes projects which have integrated with OpenAI.

**Comment by pseudotensor** [comment]
I think his point is to allow API calls into the product with an OpenAI compliant API.

"Private" can mean many things.  E.g. private within a group, such as a company firewall, is still private.  So within that group still useful to be able to do API calls to the product.

@fishfree You can try https://github.com/h2oai/h2ogpt . We use gradio, which has a client-server API that we use and test.  We have an engineer working on OpenAI compliant API: https://github.com/h2oai/h2ogpt/pull/133 .

Lastly,  h2oGPT focuses on private open-source fully permissive models and code.  But you can choose to use OpenAI models and embeddings still.

**Comment by guyguy333** [comment]
Agree. Point here is not about OpenAI API endpoint but OpenAI API schema.

OpenAI API schema is becoming a "defacto standard" like AWS S3 API. It avoids fragmentation of tools with a single API schema.

It's also easy to use OpenAI API SDK with custom endpoint.

**Comment by 3x3cut0r** [comment]
Is there something new here?
Am I able to use an external llama-cpp-python server (api) in this project?
