### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by olinorwell** [imartinez/privateGPT#437]
**Describe the bug and how to reproduce it**
I followed the install steps as explained in the repo. I also looked for any additional steps that might be discussed in issues but aren't yet in the README section. I can install everything fine, but then when I run the ingest.py file I get a "Segmentation fault (core dumped)" error, right after it says "Using embedded DuckDB with persistence: data will be stored in: db".

**Expected behavior**
I assumed it will take a few seconds to complete ingesting the sample document, then return me to the command line to continue.

**Environment (please complete the following information):**
 - OS / hardware: Ryzen 3700, 32GB Ram, Radeon 5700XT (8GB), Arch Linux
 - Python version [e.g. 3.11.3] - 3.11.3
- Other relevant information: I have no problems running the Llama.cpp project for example, nor similar software such as Stable Diffusion. I tried both the suggested model (GPT4ALL) and also a Llama.cpp compatible model. The result is the same.

**Additional context**
I have plenty of free hard disk space (70GB), my RAM isn't filled up, nor is my VRAM. I even re-installed Linux and a day later have got the exact same result. The "Loading new documents" stage happens, and it says it'll be split into 90 chunks of text. All appears to be fine until the final step.

I have used faulthandler in Python to get more information - the issue is on "modeling_utils.py line 893 get_extended_attention_mask" - that appears to cause the seg fault.

**Comment by pseudotensor** [comment]
This happened to me when I used the naive langchain integration that fills prompt context with too many few shot examples that are not needed for instruct-tuned models.  You can try https://github.com/h2oai/h2ogpt -- which handles that better and has CPU mac/windows support as well as GPU support and a UI.

**Comment by ozzeruk** [comment]
Thanks, I'll give that a go no. To anyone else reading the above bug, I think it might be to do with the versions of things I have installed relevant to my Radeon card. Though, why it needs to do anything on the GPU isn't clear. I think forcing it to not touch the GPU would solve my problem.
