### ISSUE TITLE
ERROR: Could not build wheels for llama-cpp-python, hnswlib, lxml, which is required to install pyproject.toml-based project

### ISSUE THREAD

**Issue by mkam0012** [imartinez/privateGPT#445]
I am trying to install the requirements on an Apple M1 Pro in a Macbook Pro and getting errors for building three wheels, have absolutely no idea how to fix

**Comment by Angurajdin** [comment]
I'm also facing the face issue ( I tried with Ubuntu and Cent OS - both failed with the same error),

**Comment by jackfood** [comment]
download and install the "Microsoft C++ Build Tools" from the official Visual Studio website. Here are the steps you can take:

Visit the following URL: https://visualstudio.microsoft.com/visual-cpp-build-tools/.

On the webpage, you should see a "Download" button for the Visual Studio Build Tools. Click on it to initiate the download.

Once the download is complete, run the installer and follow the instructions to install the Microsoft C++ Build Tools.

During the installation process, make sure to select the necessary components for C++ development. This typically includes selecting the "C++ build tools" and any required packages or libraries.

After the installation is complete, try installing the hnswlib package again using pip.

**Comment by zhaolong1990ok** [comment]
I'm also facing the face issue ( I tried with CentOS 7.6 - both failed with the same error)
<img width="940" alt="image" src="https://github.com/imartinez/privateGPT/assets/3919124/33159ef4-f0b8-4e75-9ae2-8d97919ee68b">

**Comment by abdulfarhandevil** [comment]
![image](https://github.com/imartinez/privateGPT/assets/52881617/a7e3aad5-fbfd-4684-9a38-46ce6a0d27c1)
i installed Microsoft C++ Build Tools with "C++ build tools" as u mentioned but still getting this error

**Comment by Angurajdin** [comment]
Thanks @jackfood,I was able to install it on Windows (after using the Microsoft C++ Build Tools), but how do I do the same on Linux (Ubuntu, CentOS, or any other Linux environment) since we can not use the Microsoft C++ Build Tools in Linux?

**Comment by Angurajdin** [comment]
@abdulfarhandevil, Please share a screenshot of the Microsoft C++ Build Tools components that you installed

**Comment by abdulfarhandevil** [comment]
![image](https://github.com/imartinez/privateGPT/assets/52881617/30536833-73e2-4a12-8b77-ec9ce28c870d)
Is it correct?

**Comment by abdulfarhandevil** [comment]
![image](https://github.com/imartinez/privateGPT/assets/52881617/ad990274-8259-41cc-ae26-1883fe16bbb0)
The red marked are the Microsoft C++ Build Tools components that i have installed 
Can u pls check if i  missed anything

**Comment by taran11313** [comment]
I have found the solution for this  problem -
1) First install visual cpp build tools from this link -  https://visualstudio.microsoft.com/visual-cpp-build-tools/
2) Then install cython using the below command -
     py -m pip install cython
3) Set the following path in your PATH variable  -
    C:\Users\XXXXX\AppData\Local\Programs\Python\Python311\Scripts

**Comment by ppcmaverick** [comment]
Its not working, it says cannot build wheels for hnswlib. I tried with adding the build tools and every damn thing. Is there a real step by step for this. I have already tried 3 times now.

**Comment by ppcmaverick** [comment]
> 

Where to setup the Path Variable?

**Comment by jackfood** [comment]
@ppcmaverick

To set up Python in the PATH environment variable,

1. Determine the Python installation directory: 
   - If you are using the Python installed from python.org, the default installation location on Windows is typically `C:\PythonXX` (XX represents the version number).
   - If you are using Anaconda or Miniconda, the installation location is usually `C:\Users\YourUsername\Anaconda3` or `C:\Users\YourUsername\Miniconda3`, respectively.

2. Open the Control Panel:
   - Press the Windows key on your keyboard.
   - Type "Control Panel" and select it from the search results.

3. Go to System and Security:
   - In the Control Panel, click on "System and Security."

4. Click on "System":
   - Under the "System" section, click on "System" to open the system properties.

5. Click on "Advanced system settings":
   - On the left-hand side of the "System" window, click on "Advanced system settings" to open the System Properties dialog box.

6. Click on "Environment Variables":
   - In the System Properties dialog box, click on the "Environment Variables" button.

7. Edit the PATH variable:
   - In the "Environment Variables" dialog box, locate the "Path" variable under the "System variables" section and select it.
   - Click on the "Edit" button to modify the PATH variable.

8. Add Python to the PATH:
   - In the "Edit Environment Variable" dialog box, click on the "New" button.
   - Enter the path to the Python installation directory (step 1) by adding the following entry:
     - For Python from python.org: `C:\PythonXX` (replace XX with the version number).
     - For Anaconda or Miniconda: `C:\Users\YourUsername\Anaconda3` or `C:\Users\YourUsername\Miniconda3`, respectively.
   - Click "OK" to save the changes.

9. Close the dialog boxes:
   - Close all the dialog boxes by clicking "OK" or "Apply" until you return to the Control Panel.

10. Open a new command prompt:
    - Open a new command prompt or PowerShell window to verify that Python is correctly set up in the PATH.
    - Type `python` or `python --version` and press Enter.
    - If Python is set up correctly, you should see the Python version information printed on the screen without any errors.

**Comment by prezire** [comment]
I tried upgrading and installing wheel, langchain dependencies, c++ compilers. But still I still got the same error(s) using Ubuntu 22.04.

**Comment by Keith-Albright-Bose** [comment]
> https://visualstudio.microsoft.com/visual-cpp-build-tools/

This downloads a windows exe which is not for M1 Mac.  Mac has clang.  So this does not address the original poster's question.  I too have the same issue which is how I found this.

**Comment by albertas** [comment]
I was getting the same issue with Python3.10.x versions. However, I managed to solve them by upgrading to Python3.11.3.

All dependencies were installed successfully for Python3.11.3. I have used `pyenv` to install custom Python versions.

**Comment by qikongwanli** [comment]
> I'm also facing the face issue ( I tried with Ubuntu and Cent OS - both failed with the same error),

Hi, I have successfully installed this project in WSL2 (ubuntu 22.04). 
In order to install all requirements,  I run these codes:
$sudo apt update
$sudo apt install g++ gdb make ninja-build rsync zip
$pip3 install -r requirements.txt

**Comment by prezire** [comment]
Upgraded to latest gcc-11/g++-11, pip and python 3.11.3 via pyenv but still nothing works on Ubuntu 22.04.

**Comment by TianruiZhang** [comment]
You may find this useful: [(https://zhuanlan.zhihu.com/p/632202007)](url)

**Comment by aminlv** [comment]
> ![image](https://user-images.githubusercontent.com/52881617/240650157-ad990274-8259-41cc-ae26-1883fe16bbb0.png) The red marked are the Microsoft C++ Build Tools components that i have installed @Angurajdin Can u pls check if i missed anything or if its correct what should i do further to fix this issue

you also have to install cli 2 it use cli to compile it

**Comment by emreg00** [comment]
Had the same issue with Ubuntu 18.04.6 and I was able to make it work following the instructions to update  gcc-11 and g++-11 on [this post](https://github.com/oobabooga/text-generation-webui/issues/1534#issuecomment-1547025834).

**Comment by Naniyaking** [comment]
centos7
update cmake to  3.2.5 and update gcc to  12.3
create soft link 
ln -s  /install_dir/bin /usr/bin/gcc
ln -s /usr/bin/gcc /usr/bin/cc

**Comment by HN026** [comment]
I'm facing the same issue, I'm trying to develop this on Linux Fedora, can anyone help?

**Comment by cassina** [comment]
I solved the error by doing this:

```
pip3 uninstall -y -r requirements.txt
pip3 install --upgrade setuptools wheel
pip3 install -r requirements.txt
```

**Comment by elseifer** [comment]
> I solved the error by doing this:
> 
> ```
> pip3 uninstall -y -r requirements.txt
> pip3 install --upgrade setuptools wheel
> pip3 install -r requirements.txt
> ```

It works on my macos

**Comment by sanjana-sudo** [comment]
> I solved the error by doing this:
> 
> ```
> pip3 uninstall -y -r requirements.txt
> pip3 install --upgrade setuptools wheel
> pip3 install -r requirements.txt
> ```

Tried this on ubuntu, still not working...
here's the output for ref
`      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
  Building wheel for peft (pyproject.toml) ... done
  Created wheel for peft: filename=peft-0.5.0.dev0-py3-none-any.whl size=73122 sha256=d3fdf2edb73ba9cbda0feeca0ad8fdb89b54717d3b07536119f3c3856d74cee2
  Stored in directory: /home/unify/.cache/pip/wheels/ff/57/c1/a023c490307cd8ffa3b61c86c48d9767f0bb850053af18674b
  Building wheel for transformers (pyproject.toml) ... done
  Created wheel for transformers: filename=transformers-4.32.0.dev0-py3-none-any.whl size=7446865 sha256=bdb52dcd91380dd75626d7e7992706bb208aa34866a953b98a6acb8718162beb
  Stored in directory: /home/unify/.cache/pip/wheels/f6/48/92/9e4123ac1ebdcbfb22ad4c8490a4c2425b143314be3957af7b
Successfully built peft transformers
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects
`

**Comment by tkni2005** [comment]
I solved the issue on my WSL shown below.

on WSL1 Centos7:
`yum install centos-release-scl
yum install devtoolset-9-gcc-c++
scl enable devtoolset-9 bash
pip3 install -r requirements.txt
`

on WSL2 Ubuntu 22.04.2 LTS:
`
sudo apt-get install python3.10-dev
pip3 install -r requirements.txt
`

**Comment by sanjana-sudo** [comment]
> I solved the issue on my WSL shown below.
> 
> on WSL1 Centos7:
> 
> ```
> yum install centos-release-scl
> yum install devtoolset-9-gcc-c++
> scl enable devtoolset-9 bash
> pip3 install -r requirements.txt
> ```
> 
> on WSL2 Ubuntu 22.04.2 LTS:
> 
> ```
> sudo apt-get install python3.10-dev
> pip3 install -r requirements.txt
> ```

Tried it in Ubuntu 22.04.3 LTS. Still facing the same error

**Comment by JiaYingLii** [comment]
This is all because of gcc/c++ version is too low. 

I fixed by running as below

`sudo apt update
sudo apt upgrade
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt update
sudo apt install gcc-11 g++-11
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 60 --slave /usr/bin/g++ g++ /usr/bin/g++-11
`

(Ubuntu 18.04)

And make sure your python version is 3.11+.

**Comment by jarciniegas20** [comment]
I also faced the same issue when trying to install "llama-cpp-python" on my Mac. Ultimately, what **solved** the issue was running `xcode-select --install` on my terminal. This should open up a separate installer window. This installs the Xcode Command Line Tools on a Mac, which include the compilers needed for c and c++. After installing it, I checked the g++ was working with `g++ --version` You should now see the version, and running `pip install llama-cpp-python` should work.

**Comment by rpuls** [comment]
Anyone that managed to fix this issue on windows 11?
I installed visual studio 2022 and the c++ build tools. restarted machine
Still get same error.

**Comment by prateekrana17** [comment]
I have managed to fix this issue on Windows 11.
1)Uninstall Visual Studio, C++ build tools, Virtual C++ Redist, Windows SDK etc. (basically all C++ related Micrsooft Components)
2) Restart the PC
3) Install C++ build tools using Visual Studio and select all C++ options
4) Then install cython using the below command -
    py -m pip install cython
5) Set the following path in your PATH variable -
    C:\Users\XXXXX\AppData\Local\Programs\Python\Python311\Scripts
6) pip3 install -r requirements.txt

**Comment by abdulkarim20-ui** [comment]
i full install and successful done . after ingest i run the privategpt but it cant give query answer? why? i fully provide file in souce diecrtory.
![Screenshot 2023-09-09 024735](https://github.com/imartinez/privateGPT/assets/144487522/a529ab99-ba3b-4de8-bc52-4eb7008ec4b4)

**Comment by ashokpoojary24** [comment]
![Screenshot (195)](https://github.com/imartinez/privateGPT/assets/136725971/7eedc2a4-040c-4d68-b515-6ca89369a5d4)
what is the solution for this in windows

**Comment by EmmaWebGH** [comment]
Help please
I can't make the command 
$env:CMAKE_ARGS='-DLLAMA_CUBLAS=on'; poetry run pip install --force-reinstall --no-cache-dir llama-cpp-python
work!

```
-- Configuring incomplete, errors occurred!

      *** CMake configuration failed
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects
```

I have already installed (and double checked) visual studio 2022, also 
pip install torch==2.0.0+cu118 --index-url https://download.pytorch.org/whl/cu118
also
py -m pip install cython
also
MiniGW and gcc components.

WHAT am I missing here? I don't understand how people make youtube tutorials where they start with a clean environment, then just copy paste the commands and it all magically works. Every time I try some new app, there's something that fails or something that's missing. If someone is going to release a tool like PrivateGPT can you make an installer .bat that will setup a venv, check for things already installed, install what is needed, detect CUDA, and set that up too. Jesus Christ.

**Comment by Choppra** [comment]
I couldnt agree with you more.  I pride myself on understanding dependencies and building with docker and python.  This is a soup of randomness.

**Comment by naveenfaclon** [comment]
ERROR: Command errored out with exit status 1:
   command: /home/ubuntu/Mistral/new/bin/python3 /tmp/tmp9i_wnj9h build_wheel /tmp/tmpzxxqrw16
       cwd: /tmp/pip-install-mg67x6c9/llama-cpp-python
  Complete output (23 lines):
  *** scikit-build-core 0.8.2 using CMake 3.28.3 (wheel)
  *** Configuring CMake...
  2024-03-04 17:06:47,283 - scikit_build_core - WARNING - libdir/ldlibrary: /usr/lib/x86_64-linux-gnu/libpython3.8.so is not a real file!
  2024-03-04 17:06:47,283 - scikit_build_core - WARNING - Can't find a Python library, got libdir=/usr/lib/x86_64-linux-gnu, ldlibrary=libpython3.8.so, multiarch=x86_64-linux-gnu, masd=x86_64-linux-gnu
  loading initial cache file /tmp/tmp5mfr_ixs/build/CMakeInit.txt
  -- The C compiler identification is GNU 9.4.0
  -- The CXX compiler identification is unknown
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  CMake Error at CMakeLists.txt:3 (project):
    No CMAKE_CXX_COMPILER could be found.
  
    Tell CMake where to find the compiler by setting either the environment
    variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
    to the compiler, or to the compiler name if it is in the PATH.
  
  
  -- Configuring incomplete, errors occurred!
  
  *** CMake configuration failed
  ----------------------------------------
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python which use PEP 517 and cannot be installed directly

i am getting this error

**Comment by naveenfaclon** [comment]
I a trying to install llama.cpp i am facing this issue
Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      *** scikit-build-core 0.8.2 using CMake 3.28.3 (wheel)
      *** Configuring CMake...
      2024-03-17 09:10:11,345 - scikit_build_core - WARNING - libdir/ldlibrary: /usr/lib/x86_64-linux-gnu/libpython3.8.so is not a real file!
      2024-03-17 09:10:11,346 - scikit_build_core - WARNING - Can't find a Python library, got libdir=/usr/lib/x86_64-linux-gnu, ldlibrary=libpython3.8.so, multiarch=x86_64-linux-gnu, masd=x86_64-linux-gnu
      loading initial cache file /tmp/tmpe1qdt55w/build/CMakeInit.txt
      -- The C compiler identification is GNU 9.4.0
      -- The CXX compiler identification is unknown
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      CMake Error at CMakeLists.txt:3 (project):
        No CMAKE_CXX_COMPILER could be found.
      
        Tell CMake where to find the compiler by setting either the environment
        variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
        to the compiler, or to the compiler name if it is in the PATH.
      
      
      -- Configuring incomplete, errors occurred!
      
      *** CMake configuration failed
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects
``

**Comment by pypdeveloper** [comment]
Is there any solution for this problem on Apple Silicon? I have tried updating the software, I have tried everything else mentioned in this thread, is there something I am missing or is there some bug?

**Comment by wonbeom12** [comment]
윈도우

python -m pip install llama-cpp-python --prefer-binary --no-cache-dir --extra-index-url=https://jllllll.github.io/llama-cpp-python-cuBLAS-wheels/AVX2/cu122
