### ISSUE TITLE
ingest.py extracts only the first row from the CSV files

### ISSUE THREAD

**Issue by GuySarkinsky** [imartinez/privateGPT#448]
My suggestion for fixing the bug:

1. Modify the load_single_document function as follows:

def load_single_document(file_path: str) -> List[Document]:
    ext = "." + file_path.rsplit(".", 1)[-1]
    if ext in LOADER_MAPPING:
        loader_class, loader_args = LOADER_MAPPING[ext]
        loader = loader_class(file_path, **loader_args)
        return loader.load()

    raise ValueError(f"Unsupported file extension '{ext}'")
    
2. Modify the load_documents function as follows:    
 
 def load_documents(source_dir: str, ignored_files: List[str] = []) -> List[Document]:
    """
    Loads all documents from the source documents directory, ignoring specified files
    """
    all_files = []
    for ext in LOADER_MAPPING:
        all_files.extend(
            glob.glob(os.path.join(source_dir, f"**/*{ext}"), recursive=True)
        )
    filtered_files = [file_path for file_path in all_files if file_path not in ignored_files]

    with Pool(processes=os.cpu_count()) as pool:
        results = []
        with tqdm(total=len(filtered_files), desc='Loading new documents', ncols=80) as pbar:
            for i, docs in enumerate(pool.imap_unordered(load_single_document, filtered_files)):
                results.extend(docs)
                pbar.update()

    return results

**Comment by morsamatias** [comment]
Could you please do a PR with that changes? [https://opensource.guide/how-to-contribute/](https://opensource.guide/how-to-contribute/)

Thank you!

**Comment by tylorschafer** [comment]
I just noticed this csv issue this morning. Just tested this fix and confirmed it works. Would be great to have a PR for this. I can probably put it up early next week if no one else does.

**Comment by pachgadehardik** [comment]
If you load multiple files (.CSV or .txt), it will provide an error as the documents will be stored as lost of Document tuples and further splitting of Documents won't be happening

**Comment by GuySarkinsky** [comment]
> If you load multiple files (.CSV or .txt), it will provide an error as the documents will be stored as lost of Document tuples and further splitting of Documents won't be happening 

@pachgadehardik 

Thank, for your cooperation,
I will try to resolve it at the beginning of next week.

**Comment by ravindraprasad75** [comment]
> > If you load multiple files (.CSV or .txt), it will provide an error as the documents will be stored as lost of Document tuples and further splitting of Documents won't be happening
> 
> @pachgadehardik
> 
> Thank, for your cooperation, I will try to resolve it at the beginning of next week.

Are you ok if do PR for this?

**Comment by gugaiz** [comment]
I saw there was a merge to fix the issue, but the issue is still happening right?
