### ISSUE TITLE
In the background, what happens if I ask for a summary?

### ISSUE THREAD

**Issue by RonanKMcGovern** [imartinez/privateGPT#45]
If I ask for a summary of the document, how are the right parts of the embeddings being selected in order to summarise?

If I understand correctly, an embedding of the question is compared with the embeddings in the document to pull out relevant phrases.

What are some ways I could improve summarisation? Thanks

**Comment by alxspiker** [comment]
You can add summarization: https://python.langchain.com/en/latest/use_cases/summarization.html

**Comment by imartinez** [comment]
As @alxspiker pointed, summarization is a different process. You don't need stored embeddings for that. You could just use the right type of chain supported by GPT4All LLM and pass in the docs loaded through any of the available document loaders in Langchain.
