### ISSUE TITLE
Add support/mapping for Images, URLs and JSON

### ISSUE THREAD

**Issue by robertgro** [imartinez/privateGPT#451]
As an enhancement, leveraging the full power of the [Unstructured package](https://github.com/Unstructured-IO/unstructured), I would like to see a mapping for images, JSON and URLS.

What you need to implement specifically is the [UnstructuredImageLoader](https://python.langchain.com/en/latest/modules/indexes/document_loaders/examples/image.html), [UnstructuredURLLoader](https://python.langchain.com/en/latest/modules/indexes/document_loaders/examples/url.html) and the [JSONLoader](https://python.langchain.com/en/latest/modules/indexes/document_loaders/examples/json.html).

As support for multiple file types grows, I would also suggest replacing the different mappings with a more generic approach, using the [DirectoryLoader](https://python.langchain.com/en/latest/modules/indexes/document_loaders/examples/file_directory.html) or [UnstructuredFileLoader](https://python.langchain.com/en/latest/modules/indexes/document_loaders/examples/unstructured_file.html) directly.

**Comment by maozdemir** [comment]
I'd not rely on OCR, any OCR output should be supervised. The rest sounds good, though.

**Comment by pseudotensor** [comment]
@robertgro you can try https://github.com/h2oai/h2ogpt or borrow code  from there for prviateGPT.  It has blip/blip2 for captioning and OCR recognition.  Also support URLs.
