### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte

### ISSUE THREAD

**Issue by candre23** [imartinez/privateGPT#453]
Tried individually ingesting about a dozen longish (200k-800k) text files and a handful of similarly sized HTML files.  A couple successfully loaded, but most of them failed with this "UnicodeDecodeError".  The exact byte and position changed based on the file, but this is an example of the full error:

```
Appending to existing vectorstore at db
Using embedded DuckDB with persistence: data will be stored in: db
Loading documents from source_documents
Loading new documents:   0%|                              | 0/1 [00:02<?, ?it/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\langchain\document_loaders\text.py", line 41, in load
    text = f.read()
  File "C:\Python310\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x97 in position 1183: invalid start byte

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python310\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\ai\privateGPT\ingest.py", line 89, in load_single_document
    return loader.load()[0]
  File "C:\Python310\lib\site-packages\langchain\document_loaders\text.py", line 54, in load
    raise RuntimeError(f"Error loading {self.file_path}") from e
RuntimeError: Error loading source_documents\The Science of Discworld by Ter - Unknown.txt
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ai\privateGPT\ingest.py", line 167, in <module>
    main()
  File "C:\ai\privateGPT\ingest.py", line 151, in main
    texts = process_documents([metadata['source'] for metadata in collection['metadatas']])
  File "C:\ai\privateGPT\ingest.py", line 119, in process_documents
    documents = load_documents(source_directory, ignored_files)
  File "C:\ai\privateGPT\ingest.py", line 108, in load_documents
    for i, doc in enumerate(pool.imap_unordered(load_single_document, filtered_files)):
  File "C:\Python310\lib\multiprocessing\pool.py", line 873, in next
    raise value
RuntimeError: Error loading source_documents\The Science of Discworld by Ter - Unknown.txt
```
If it was just one or two weird files causing errors that would be understandable, but successful ingestion seems to be the exception, not the rule.  _Most_ text files fail with this error.

**Comment by lukaszliniewicz** [comment]
Hope this gets fixed soon! Many thanks to all contributors :)

**Comment by yaziciali** [comment]
Hi,
I write a fix for this error:
File: privateGPT/private_gpt/server/ingest/ingest_service.py
Code: 
if isinstance(file_data, Path):
                **with open(file_data, 'rb') as f2:
                    result2 = chardet.detect(f2.read())**
                text = file_data.read_text(**encoding=result2['encoding']**)
                # text = file_data.read_text()


Can I edit the file in this repository?

**Comment by MSpriv** [comment]
I am using the new 0.2.0 version and doing bulk ingest and get the same error:
make ingest /Users/my/folder -- --watch --log-file /User/user/privateGPT/log/file.log

'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte

the major problem is, that it seems 
1. to stop the whole ingest. (=> I had a encrypted pdf file in the batch and expected an  error "cryptography>=3.1 is required for AES algorithm", which did not show)
2. the log does not show the result. all files of the folder are listed.

I searched the privategpt installation and was unable to detect ingest.py or any other file specifying: TextLoader=

Question:
1. where to update the TextLoader?
2. is there a mechanism to continue the ingest and report failed files only?
