### ISSUE TITLE
Number of Thread used for pirvategpt.py

### ISSUE THREAD

**Issue by jackfood** [imartinez/privateGPT#455]
What is the thread usage when running ggml? Can i add number of thread to use when running privategpt.py?

**Comment by TopNotchSushi** [comment]
yes, in the llm lines, for either LLamaCPP or GPT4All, add `, n_threads=(number of threads)`

**Comment by jackfood** [comment]
Thank you. managed to work.

**Comment by haakonnessjoen** [comment]
Seems like this now only works for llamacpp. I tried with 64 threads on a big server, and it worked fine. But with gpt4all it is always limited to 4 threads. And never goes over 400% usage.

**Comment by abalib** [comment]
> n_threads=(number of threads)

same here.  llm.n_threads = 1 or 8 or else makes no difference to the thread count.

**Comment by JasonMaggard** [comment]
Update to the latest version of langchain (0.193) and the n_threads works for GPT4all.
