### ISSUE TITLE
Error running privateGTP.py

### ISSUE THREAD

**Issue by araujofrancisco** [imartinez/privateGPT#457]
Using embedded DuckDB with persistence: data will be stored in: db
    Found model file.
    gptj_model_load: loading model from 'models/ggml-gpt4all-j-v1.3-groovy.bin' - please wait ...
    gptj_model_load: n_vocab = 50400
    gptj_model_load: n_ctx = 2048
    gptj_model_load: n_embd = 4096
    gptj_model_load: n_head = 16
    gptj_model_load: n_layer = 28
    gptj_model_load: n_rot = 64
    gptj_model_load: f16 = 2
    [1] 382794 illegal hardware instruction python privateGPT.py

OS: Ubuntu 22.04.2 LTS
Python: 3.10.6

**Comment by araujofrancisco** [comment]
It seems the issue is related to AVX/AVX2 instructions missing on my cpu: https://github.com/nomic-ai/gpt4all-chat/issues/32#issuecomment-1509549739

**Comment by RGGH** [comment]
> It seems the issue is related to AVX/AVX2 instructions missing on my cpu: [nomic-ai/gpt4all-chat#32 (comment)](https://github.com/nomic-ai/gpt4all-chat/issues/32#issuecomment-1509549739)

I have avx and still get same error :

python3 privateGPT.py
Using embedded DuckDB with persistence: data will be stored in: db
Found model file.
gptj_model_load: loading model from 'models/ggml-gpt4all-j-v1.3-groovy.bin' - please wait ...
gptj_model_load: n_vocab = 50400
gptj_model_load: n_ctx   = 2048
gptj_model_load: n_embd  = 4096
gptj_model_load: n_head  = 16
gptj_model_load: n_layer = 28
gptj_model_load: n_rot   = 64
gptj_model_load: f16     = 2
gptj_model_load: ggml ctx size = 5401.45 MB
Illegal instruction

Linux gpt 5.15.0-50-generic #56~20.04.1-Ubuntu SMP Tue Sep 27 15:51:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Python 3.10.6

**Comment by csharpdeb** [comment]
I am receiving the same message. 
python3 privateGPT.py
Using embedded DuckDB with persistence: data will be stored in: db
Found model file.
gptj_model_load: loading model from 'models/ggml-gpt4all-j-v1.3-groovy.bin' - please wait ...
gptj_model_load: n_vocab = 50400
gptj_model_load: n_ctx   = 2048
gptj_model_load: n_embd  = 4096
gptj_model_load: n_head  = 16
gptj_model_load: n_layer = 28
gptj_model_load: n_rot   = 64
gptj_model_load: f16     = 2
gptj_model_load: ggml ctx size = 5401.45 MB
Illegal instruction (core dumped)

I have the crash log if that helps. Its 343MB compressed, so not sure how to share it.

**Comment by araujofrancisco** [comment]
On my case I found that the issue is related to the pyllamacpp.model. To reproduce the issue using python console:

```
Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyllamacpp.model import Model
[1]    109726 illegal hardware instruction  python

```

**Comment by araujofrancisco** [comment]
It seems to be possible to build pyllamacpp disabling AVX/AVX2 instructions support per discussion [https://github.com/ParisNeo/gpt4all-ui/issues/74#issuecomment-1508365776](https://github.com/ParisNeo/gpt4all-ui/issues/74#issuecomment-1508365776).
