### ISSUE TITLE
Ingest estimate

### ISSUE THREAD

**Issue by syco** [imartinez/privateGPT#458]
Hi,

Is there a way to estimate the ingest time?

I'm trying to ingest 7028 csv files, total size 205M, total lines 421774.

The server I'm using doesn't have a gpu, the cpu is a Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz

It's running at 8/8/8 load for the last 7 days and 17 hours straight.

I see these lines going by:
```txt
llama_print_timings:        load time =   950.39 ms
llama_print_timings:      sample time =     0.00 ms /     1 runs   (    0.00 ms per run)
llama_print_timings: prompt eval time = 16863.50 ms /   158 tokens (  106.73 ms per token)
llama_print_timings:        eval time =     0.00 ms /     1 runs   (    0.00 ms per run)
llama_print_timings:       total time = 16927.24 ms
```

but how long before it will be done?

Thanks

**Comment by PulpCattel** [comment]
It's not currently in the code, but if you search for this line in `ingest.py`:

```python3
embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name)
```

and turned it into:

```python3
embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name, encode_kwargs={'show_progress_bar': True})
```

You'll have a progress bar for the ingestion.

**Comment by syco** [comment]
Thanks, but is there no way to understand it from that output?
I didn't want to lose a week of progress.

**Comment by PulpCattel** [comment]
Oh wait, are you using an old version of this software (if you don't have `EMBEDDINGS_MODEL_NAME` in your `.env` it's the old version)? You should update to the latest version and recreate your `.env` file. The old version uses an infinitely slower ingestion model.

Yes, you may have to stop and restart. I have no idea how long it would take with the old model (maybe forever?).

**Comment by morsamatias** [comment]
@syco Did you have a good performance with csv? In that case could you please tell the model and embeddings that you had used?

**Comment by syco** [comment]
> embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name, encode_kwargs={'show_progress_bar': True})
Maybe this could be in the env file, I feel it would be useful to many beginners.

@morsamatias, I have no idea where I'm going with this. I'm a total beginner. I used the ggml-model-q4_0.bin and ggml-gpt4all-j-v1.3-groovy.bin and it actually completed ingesting a few minutes ago, after 7 days. And it's not answering any question. So I'm starting again.

Does anyone have a good combination of MODEL_PATH and LLAMA_EMBEDDINGS_MODEL that works for Italian?

**Comment by PulpCattel** [comment]
> Maybe this could be in the env file, I feel it would be useful to many beginners.

I think it will be added shortly.

> Does anyone have a good combination of MODEL_PATH and LLAMA_EMBEDDINGS_MODEL that works for Italian?

Just to be clear, `LLAMA_EMBEDDINGS_MODEL` this doesn't work with this repo anymore, and it's much much slower, you should consider upgrading.

**Comment by syco** [comment]
yes, I meant these 2 variables
```txt
MODEL_PATH=models/ggml-gpt4all-j-v1.3-groovy.bin
EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
```

Anyway, I'll close this as it was a performance request that's turning into a full support conversation.
The performance issue has been resolved. So I'll continue my testing offline.
Thanks all for the support.
