### ISSUE TITLE
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__ pydantic.error_wrappers.ValidationError: 1 validation error for LlamaCppEmbeddings

### ISSUE THREAD

**Issue by sandyrs9421** [imartinez/privateGPT#461]
i am seeing below error when i run the ingest.py. any thoughts on how i can resolve it ? kindly advise 

Error - 
error loading model: this format is no longer supported (see https://github.com/ggerganov/llama.cpp/pull/1305)
llama_init_from_file: failed to load model
Traceback (most recent call last):
  File "/Users/FBT/Desktop/Projects/privategpt/privateGPT/ingest.py", line 39, in <module>
    main()
  File "/Users/FBT/Desktop/Projects/privategpt/privateGPT/ingest.py", line 30, in main
    llama = LlamaCppEmbeddings(model_path="./models/ggml-model-q4_0.bin")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LlamaCppEmbeddings
__root__
  Could not load Llama model from path: ./models/ggml-model-q4_0.bin. Received error  (type=value_error)

My ENV file - 
PERSIST_DIRECTORY=db
MODEL_TYPE=GPT4All
MODEL_PATH=models/ggml-gpt4all-j-v1.3-groovy.bin
EMBEDDINGS_MODEL_NAME=/Users/FBT/Desktop/Projects/privategpt/privateGPT/models/ggml-model-q4_0.bin
MODEL_N_CTX=1000

**Comment by christopherpickering** [comment]
Did you download and add a model?

**Comment by gvilarino** [comment]
@sandyrs: [as stated in the `README.md`](https://github.com/imartinez/privateGPT/blob/main/README.md?plain=1#L15-L16) you should first [download the model file](https://gpt4all.io/models/ggml-gpt4all-j-v1.3-groovy.bin) into a `models` directory in the project root.  I encountered your same issue and this worked.

**Comment by oyvindhagen2** [comment]
I'm getting the same error, i have downloaded a model and the env file points to the right path

PERSIST_DIRECTORY=db
MODEL_TYPE=GPT4All
MODEL_PATH=/workspaces/privateGPT/models/ggml-gpt4all-j-v1.3-groovy (1).bin
EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
MODEL_N_CTX=1000
TARGET_SOURCE_CHUNKS=4

**Comment by sandyrs9421** [comment]
yes i have downloaded the models and mentioned the same path in env file but still seeing the issue.
<img width="756" alt="Screenshot 2023-05-26 at 12 07 20 PM" src="https://github.com/imartinez/privateGPT/assets/89383080/8ff042ff-f9df-410b-be77-9f39a2368442">

can you please help me on how i can resolve thie error ?
@christopherpickering / @gvilarino

**Comment by albertas** [comment]
Had the same issue. Moving downloaded models into `models` directory resolved it.

I see that you have `MODEL_PATH=models/ggml-gpt4all-j-v1.3-groovy.bin` in your .env file, so its likely that the issue is the same for you. Just create `models` directory and move your downloaded models into it.

**Comment by sandyrs9421** [comment]
@albertas - thanks for the reply i tried the recommended steps and seeing similar error.
i am seeing this error when i run the privategpt.py file. Data ingestion was successful.

My ENV File -
PERSIST_DIRECTORY=db
MODEL_TYPE=GPT4All
MODEL_PATH=models/ggml-gpt4all-j-v1.3-groovy.bin
EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
MODEL_N_CTX=1000
TARGET_SOURCE_CHUNKS=4

<img width="788" alt="Screenshot 2023-05-29 at 12 25 06 PM" src="https://github.com/imartinez/privateGPT/assets/89383080/967153e6-5514-464f-8c81-2beeb069f36b">

**Comment by agentmith** [comment]
Similar issue, tried with both putting the model in the .\models subfolder and its own folder inside the .\models subdirectory. The only way I can get it to work is by using the originally listed model, which I'd rather not do as I have a 3090. It's most likely a configuration issue in the .env file, but I'm not 100% sure what all to change if you switch to a different model.

**Comment by ayteakkaya536** [comment]
I had encounter with same problem. I used absolute path for the model path, it resolved the issue.

**Comment by Rasmus-Riis** [comment]
> I had encounter with same problem. I used absolute path for the model path, it resolved the issue.

Thanks. That fixed it for me :-)

**Comment by Yousef-Mush** [comment]
For me I used absolute path in "privateGPT.py"
previously it was 
`model_path = os.environ.get('MODEL_PATH')`
I changed it to 
`model_path = "C:/Users/YM/Desktop/PrivateGPT/privateGPT/models/ggml-gpt4all-j-v1.3-groovy.bin"`

in .env here is my config:

_PERSIST_DIRECTORY=db
MODEL_TYPE=GPT4All
MODEL_PATH=models/ggml-gpt4all-j-v1.3-groovy.bin
EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
MODEL_N_CTX=1000
TARGET_SOURCE_CHUNKS=4_

**Comment by tosundar40** [comment]
Changing the path in the  privateGPT.py also does not fix the issue . Please help

**Comment by ciathyza** [comment]
Any solution found to this yet?
Using absolute path (on MacOS) does not fix it for me.

**Comment by abcnow** [comment]
same here with the same problem.. using the absolute path didn't fix the problem

**Comment by danielmiranda** [comment]
If you set model path correctly mentioned in .env file and remove the extra argument n_ctx=1000, Its working as expected.
