### ISSUE TITLE
Are there any other GPT4All-J compatible models of which MODEL_N_CTX is greater than 2048?

### ISSUE THREAD

**Issue by fishfree** [imartinez/privateGPT#463]
I tried ggml-mpt-7b-instruct.bin of which MODEL_N_CTX  is 4096. But error occured when loading:
```
gptj_model_load: loading model from 'models/ggml-mpt-7b-instruct.bin' - please wait ...
gptj_model_load: invalid model file 'models/ggml-mpt-7b-instruct.bin' (bad magic)
GPT-J ERROR: failed to load model from models/ggml-mpt-7b-instruct.bin
```

**Comment by darrinh** [comment]
Have been getting similar errors:

`gptj_model_load: invalid model file 'models/mpt-7b-instruct.ggmlv3.q8_0.bin' (bad vocab size 2007 != 4096)`

**Comment by ProxyAyush** [comment]
yeah so in privateGPT on line 36 change " backend='gptj' " to " backend='mpt' "
