### ISSUE TITLE
ERROR: The prompt size exceeds the context window size and cannot be processed.GPT-J

### ISSUE THREAD

**Issue by fishfree** [imartinez/privateGPT#466]
I ask a question in Chinese, it shows error as below:
![image](https://github.com/imartinez/privateGPT/assets/1741341/2a9b8837-20ac-4a04-92cf-1e294ea173cd)

I can totally confirm that there is only one PDF file in the source_documents folder, the file contains only 889 Chinese characters. Cumbersomely, the answer is related to my question, and output Chinese correctly.

My .env file is as below:
```
PERSIST_DIRECTORY=db
MODEL_TYPE=GPT4All
MODEL_PATH=models/ggml-gpt4all-j-v1.3-groovy.bin
#EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
EMBEDDINGS_MODEL_NAME=GanymedeNil/text2vec-large-chinese
MODEL_N_CTX=20480
```

**Comment by imartinez** [comment]
Try reducing the in your .env file:

`MODEL_N_CTX=20480`

Make it 1000 an try again

**Comment by fishfree** [comment]
@imartinez Thank you! However, the problem still exists as it was after changing `MODEL_N_CTX=1000`.

**Comment by sliontc** [comment]
> @imartinez Thank you! However, the problem still exists as it was after changing `MODEL_N_CTX=1000`.

Same error, have you found the solution?

**Comment by cutd** [comment]
Same error, is there any solution?

**Comment by linzhihui7** [comment]
It seems to be a file specific problem, privateGPT works fine for other files, but throws the above error only for specifc file.

**Comment by sliontc** [comment]
> It seems to be a file specific problem, privateGPT works fine for other files, but throws the above error only for specifc file.

What specifi file do you mean?

**Comment by simonqian** [comment]
try:
TARGET_SOURCE_CHUNKS=2

**Comment by cutd** [comment]
> try: TARGET_SOURCE_CHUNKS=2

@simonqian config it in .env ?

**Comment by FPWS** [comment]
I have the same issue. I'm working within an Jupyter Notebook. I don't read the .env file. Is it also possible to set the TARGET_SOURCE_CHUNKS=2 in the Notebook directly? 
Moreover: It doesn't work for me.

**Comment by ye-ye823** [comment]
Same error, is there any solution?

**Comment by sun8134** [comment]
Same error, is there any solution?
