### ISSUE TITLE
Dimensionality of (384) does not match index dimensionality (4096)

### ISSUE THREAD

**Issue by sandyrs9421** [imartinez/privateGPT#468]
when i run privategpt.py file
please help on how i can resolve this error.
error -
Dimensionality of (384) does not match index dimensionality (4096)

ptj_model_load: loading model from 'models/ggml-gpt4all-j-v1.3-groovy.bin' - please wait ...
gptj_model_load: n_vocab = 50400
gptj_model_load: n_ctx   = 2048
gptj_model_load: n_embd  = 4096
gptj_model_load: n_head  = 16
gptj_model_load: n_layer = 28
gptj_model_load: n_rot   = 64
gptj_model_load: f16     = 2
gptj_model_load: ggml ctx size = 5401.45 MB
gptj_model_load: kv self size  =  896.00 MB
gptj_model_load: ................................... done
gptj_model_load: model size =  3609.38 MB / num tensors = 285

and my .env file -
PERSIST_DIRECTORY=db
MODEL_TYPE=GPT4All
MODEL_PATH=models/ggml-gpt4all-j-v1.3-groovy.bin
EMBEDDINGS_MODEL_NAME='sentence-transformers/all-MiniLM-L6-v2'
MODEL_N_CTX=1000

**Comment by imartinez** [comment]
You most probably had a database created with a previous version of ingest.py, using a different embeddings model. 

Delete your `db` folder, re-run ingest.py, and that will solve the issue

**Comment by amr-cloudforce** [comment]
This error seems to occur when there are documents in the local cache and you have changed the settings (profile). The solution that worked for me was to delete the cache in the local_data folder and restart the server.
