### ISSUE TITLE
Using the nomic-ai models from Hugging Face ( 2 .bin files )

### ISSUE THREAD

**Issue by hvina** [imartinez/privateGPT#469]
I have downloaded the gpt4all-j models from HuggingFace ( HF ). This has two model files . 
Should I combine both the files into a single .bin file as required by the MODEL_PATH in the .env file 
Can the original directory be used as is ?

**Comment by jackfood** [comment]
There suppose to have one bin file. Try to use gpt4all (one click installer) and download the model, at least that model from gpt4all works for me.

**Comment by meherhendi** [comment]
You can find the bin files used by gpt4all under this directory 
[https://github.com/nomic-ai/gpt4all/tree/main/gpt4all-chat](url)
