### ISSUE TITLE
Capital letter on file formats not supported

### ISSUE THREAD

**Issue by mariustk** [imartinez/privateGPT#478]
**Describe the bug and how to reproduce it**
By having documents ending with for instance ".PDF" ValueError is raised. I have a large chunk of documents ending with capital ".PDF" i have t rename them before ingest can be run.

**Expected behavior**
The module should be able to handle capital letter file extensions.

**Environment (please complete the following information):**
 - OS / hardware: Windows 10
 - Python version 3.9

**Comment by 66north** [comment]
I'm not getting the error on my macOS, but I tried the .PDF (in uppercase) files and they are simply ignored when ingesting.
