### ISSUE TITLE
After 2 questions the program crashes due to memory issues

### ISSUE THREAD

**Issue by skuma307** [imartinez/privateGPT#480]
Thank you so much for a great starting point to build solutions using Open source LLMs. The program crashes after a couple of queries. 

**Expected behavior**
Can we add some kind of controls to manage the memory? How can we fix this memory issue programmatically?

**Environment (please complete the following information):**
 - OS/hardware: N-series Azure VM with 8 CPUs
 - Python version: 3.10
- The VM has good enough space as well.

Thanks in advance.

**Comment by 66north** [comment]
How much ram do you have allocated to that VM? When the model is running it will probably put a lot of stuff to memory, I do not see this issue running it on a M1 MacBook Air with 16Gb of Ram
