### ISSUE TITLE
please allow or add feature for connect to other vector databases like Pinecone

### ISSUE THREAD

**Issue by ArRashid** [imartinez/privateGPT#488]
**Describe the solution you'd like**
where any one can change the .env file to switch the database

**Comment by sime2408** [comment]
It's a matter of adding few lines, you can do this yourself I guess:

`pip3 -q install pinecone-client`

```python
# Initialize Pinecone
pinecone.init(
    api_key = os.environ.get('PINECONE_API_KEY'),
    environment = os.environ.get('PINECONE_API_ENV')

index_dimensions = 5120 # OpenAI = 1536
index_name = os.environ.get('PINECONE_INDEX')

if index_name not in pinecone.list_indexes():
    pinecone.create_index(
        index_name, dimension=index_dimensions, metric="cosine", pod_type="p1"
    )

index = pinecone.Index(index_name)

db = Pinecone.from_documents(documents=docs, embedding=embeddings, index_name=index_name, namespace='privateGPT')
```

**Comment by darksheer** [comment]
Correct me if I'm wrong, thats the code to ingest the documents into pinecone.  There would still need to be the addition of the db = for searching pinecone vectors: `db = Pinecone.from_existing_index(index_name, embeddings)` ?
