### ISSUE TITLE
Spanish support

### ISSUE THREAD

**Issue by alejandrofdzllorente** [imartinez/privateGPT#492]
First of all, thanks for your repo, it works great and power the open source movement.

Could we work to adding some  spanish language model like Bertin or a Llama finetunned? It would be a great feature!

Thanks any support.

**Comment by PeterPirog** [comment]
Is possible to add any other languages?

**Comment by dadanrhem** [comment]
Im completly noob but i think  we must use models from huggingface that support other language and gpt-j .

**Comment by adantart** [comment]
Just change the model embedding to other prepared for multilingual support, as e5-multilingual-base

**Comment by alejandrofdzllorente** [comment]
> Just change the model embedding to other prepared for multilingual support, as e5-multilingual-base

That's not enough. Changing the current embedding for multilingual fixes the embedding part, not the model part. You need also a multilingual model and, for now, there is no multilingual model supported here.

**Comment by adantart** [comment]
> That's not enough. Changing the current embedding for multilingual fixes the embedding part, not the model part. You need also a multilingual model and, for now, there is no multilingual model supported here.

You can use some spanish models (BERTIN), or create one with tons of spanish corpora https://github.com/dav009/awesome-spanish-nlp

**Comment by PeterPirog** [comment]
@adantart How to practically change the model? I would like to use in privateGPT polish language model [https://huggingface.co/mmosiolek/polpaca-lora-7b](https://huggingface.co/mmosiolek/polpaca-lora-7b) .  How to configure settings.yaml file? Should I modify more  settings files?

```
local:
  llm_hf_repo_id: <Your-Model-Repo-ID>
  llm_hf_model_file: <Your-Model-File>
  embedding_hf_model_name: BAAI/bge-base-en-v1.5
```
Should I download the model or it will be downloaded automatically?
