### ISSUE TITLE
Allow multiple instances or threading 

### ISSUE THREAD

**Issue by emmanero90** [imartinez/privateGPT#503]
For this application to be realistic, it definitely requires multiple users queries at the same time. I tried running two instances, but the other get killed. Also cannot be run as a thread. 

I will be very great if this is considered

**Comment by manishshanker** [comment]
Any update on this?

**Comment by vidyaprasanna77** [comment]
Hi I am facing the same issue . Any solutions

**Comment by soualid** [comment]
+1

**Comment by balamuthu1** [comment]
Hi, i see this as completed. Is it in any release version? Is there a documentation on this? This will be really very helpful thanks !

**Comment by guillesotelo** [comment]
+1
