### ISSUE TITLE
installing requirements llama-cpp-python error

### ISSUE THREAD

**Issue by Vector-9974** [imartinez/privateGPT#504]
**Describe the bug and how to reproduce it**
While installing the requirements for the library via the requirements file, the llama-cpp-python library is throwing an error and it is not being able to be built as this is the error that is occuring 

 C:\Users\Work\AppData\Local\Temp\pip-install-vc40mq09\llama-cpp-python_750867ce395148aeb5905d4aa919a0ee\vendor\llama.cpp\ggml.c(895): error C2146: syntax error: missing ')' before identifier 'x'
      C:\Users\Work\AppData\Local\Temp\pip-install-vc40mq09\llama-cpp-python_750867ce395148aeb5905d4aa919a0ee\vendor\llama.cpp\ggml.c(895): error C2061: syntax error: identifier 'x'
      C:\Users\Work\AppData\Local\Temp\pip-install-vc40mq09\llama-cpp-python_750867ce395148aeb5905d4aa919a0ee\vendor\llama.cpp\ggml.c(895): error C2059: syntax error: ';'
      C:\Users\Work\AppData\Local\Temp\pip-install-vc40mq09\llama-cpp-python_750867ce395148aeb5905d4aa919a0ee\vendor\llama.cpp\ggml.c(895): error C2059: syntax error: ','
      C:\Users\Work\AppData\Local\Temp\pip-install-vc40mq09\llama-cpp-python_750867ce395148aeb5905d4aa919a0ee\vendor\llama.cpp\ggml.c(895): error C2059: syntax error: ')'

**Environment (please complete the following information):**
 - OS / hardware: Windows 11
 - Python version 3.11.3

How should I go about rectifying this error

**Comment by weasel4o** [comment]
@Vector-9974  - try installing Visual Studio (not VS Code, but Visual studio) - it appears that you are lacking a C++ compiler on your PC. During the installation, make sure to add the C++ build tools in the installer selection options. Then run the pip install of the package again.

**Comment by hakhok** [comment]
If using python 3.11, downgrade to python 3.10
https://github.com/chroma-core/chroma/issues/163#issue-1595123129

**Comment by nyoma-diamond** [comment]
I get this error on python 3.10.11
