### ISSUE TITLE
UnicodedecodeError

### ISSUE THREAD

**Issue by jackfood** [imartinez/privateGPT#509]
I ingested a few txt. When i query using the default gpt4all model groovy.bin, it is able to generate the front part. however, during the generation, this error appears.

Exception ignored on calling ctypes callback function: <function LLModel._response_callback at 0x00000250F76E7A30>
Traceback (most recent call last):
  File "D:\Python\Pgpt1\lib\site-packages\gpt4all\pyllmodel.py", line 241, in _response_callback
    print(response.decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 0-1: unexpected end of data

Not sure is this cause by ingestion.py or the model used.

**Comment by MikeColeGuru** [comment]
I am getting this also on some but not all response generation.

**Comment by Thinkharder** [comment]
Same here. Example:

Enter a query: _How should a husband treat his wife?_

 A helpful answer from our expert guide would be the following - When talking about any topic or issue with her spouse / girlfriend/ family members, it is essential that you always express yourself in an empathic way as they can relate to your emotions and share similar experiences. It**Exception ignored on calling ctypes callback function: <function LLModel._response_callback at 0x00000247D9DF3740>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gpt4all\pyllmodel.py", line 241, in _response_callback       
    print(response.decode('utf-8'))
          ^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 0-1: unexpected end of data**

**Comment by ianhill60** [comment]
I'm also receiving this issue - commenting to stay updated.

**Comment by ahlongxp** [comment]
same issue~~
