### ISSUE TITLE
Hallucination: Answers are not from the docs but from the model's own knowledge base

### ISSUE THREAD

**Issue by skuma307** [imartinez/privateGPT#517]
**Describe the bug and how to reproduce it**
The code base works completely fine. Fantastic work! I have tried different LLMs. Even after creating embeddings on multiple docs, the answers to my questions are always from the model's knowledge base. It is not returning the answers from the documents. I have defined a prompt template too but that doesn't work either. The source document is something that the model has used in the training part.

**Expected behavior**
If embeddings are created for docs, LLMs should return the answers from those only and if it can't answer, it must not return. It hallucinates like anything. How can I achieve the results only from the documents that I have created the embedding for?

**Additional context**
I have tried MPT-7B, GPT4ALL, LLaMA, etc. I have tried different chains in Langchain but nothing works.

**Comment by 8bitaby** [comment]
I asked a question out the context of  state_of_the_union.txt :

> Question:
what is an apple?

> Answer:
 An Apple refers to a company that specializes in producing high-quality personal computers with user interface designs based on those used by Steve Jobs for his first Macintosh computer released in 1984 as part of the "1984" novel written and illustrated by George Orwell which portrayed totalitarianism.

> source_documents/state_of_the_union.txt:
GM is making the largest investment in its history—$7 billion to build electric vehicles, creating 4,000 jobs in Michigan. 
All told, we created 369,000 new manufacturing jobs in America just last year. 
\Powered by people I’ve met like JoJo Burgess, from generations of union steelworkers from Pittsburgh, who’s here with us tonight. As Ohio Senator Sherrod Brown says, “It’s time to bury the label “Rust Belt.” It’s time.

> source_documents/state_of_the_union.txt:
This is where Intel, the American company that helped build Silicon Valley, is going to build its $20 billion semiconductor “mega site”. Up to eight state-of-the-art factories in one place. 10,000 new good-paying jobs. Some of the most sophisticated manufacturing in the world to make computer chips the size of a fingertip that power the world and our everyday lives.
Smartphones. The Internet. Technology we have yet to invent. 
But that’s just the beginning.

This sure shows that the model returns the answers outside the source document.

**Comment by skuma307** [comment]
I agree with you so how can we fix that? I need the answer only from embeddings (on top of my docs), I don't want LLM to return the answer from the base knowledge.

**Comment by AleksandrovEugen** [comment]
I also encountered this problem, that the answer was generated not on the basis of an indexed document, but from the knowledge base on which the model was trained.

How can I fix this so that answers are generated only on the basis of indexed documents?

**Comment by skuma307** [comment]
Can anyone from the community help here? Maybe the creator or co-creators of the PrivateGPT?

**Comment by Guillaume-Fgt** [comment]
One possible way is to use a [custom prompt](https://python.langchain.com/en/latest/modules/chains/index_examples/vector_db_qa.html). You have to modify the ```privateGPT.py``` file.

At the top of the file, add ```from langchain import PromptTemplate```. And then replace the part with ```RetrievalQA.from_chain_type``` with this:

```
    prompt_template = """Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.

    {context}

    Question: {question}
    Answer:
    """
    PROMPT = PromptTemplate(
        template=prompt_template, input_variables=["context", "question"]
    )
    chain_type_kwargs = {"prompt": PROMPT}
    qa = RetrievalQA.from_chain_type(
        llm=llm,
        chain_type="stuff",
        retriever=retriever,
        return_source_documents=not args.hide_source,
        chain_type_kwargs=chain_type_kwargs,
    )
```

Using ```ggml-vic13b-uncensored-q5_1.bin```, with the question "What is an apple?":

**Before**
>  An apple is a type of fruit that belongs to the genus Malus and the family Rosaceae. It is typically red-green in color with white spots on its skin, and it has seeds in its core. Apples are often eaten raw or used as an ingredient in various recipes. They are also commonly used for making apple juice and cider.

**After**
> 1. Apple is a type of fruit that is commonly used in various dishes such as salads, desserts, and main courses.
>     2. Apple can also refer to a technology company that designs, manufactures, and markets smartphones, computers, tablets, smartwatches, and other electronic devices.
>     3. In the context of the given text, it is not clear which meaning of "apple" is intended.

**Comment by skuma307** [comment]
Thanks for your comment @Guillaume-Fgt , I appreciate that but even in the case of a custom prompt.... It doesn't work in the case of the MPT7B model and the default models shared in the repository. I have used. Let me try out the model you are suggesting. Can you share the model link so I can download it?

**Comment by AndreasKunar** [comment]
> Sure,[ here](https://huggingface.co/vicuna/ggml-vicuna-13b-1.1) is the link.

Seems to be the problem with llama.cpp recently changing file-formats. See https://github.com/imartinez/privateGPT/issues/567#issuecomment-1569991256 wich might help

**Comment by sleeplessinva** [comment]
I ingested the state of the union text file along with my 2022 tax return in pdf format and when I asked "how long is the state of the union" it responded by returning with all the various numerical values it found from my 1040 form, from both the federal and the state.

So yeah... something is definitely broken.

**Comment by ErfolgreichCharismatisch** [comment]
For me, there is hallucination even after using what @Guillaume-Fgt wrote.
To do some debugging, I changed the prompt to "Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer. Reply in German.".
The answer was in english.
I suspect that the prompt is being ignored.

**Comment by 4ck4t4ny** [comment]
Same here. - Truly hope this is part of a fix in the near future..

Queries to _list the contents or chapters of a book_ do not faithfully render the original text.
Proof is as easy as opening the original PDF and looking at the contents page(s).

A query like
"List the contents of the book XYZ"
or
"List the chapters of book XYZ"

will produce freely invented results every single time.

---
For what it's worth, here are my
**System settings:**

Ubuntu Server 22.04 LTS
20GB RAM
Branch: HEAD
PGPT_PROFILES=local make run

**INGESTION LOG - no errors:** 
[2023-12-21 17:49:07.277] [INFO] Completed ingesting ../import_pdf/BookXYZ.pdf
[2023-12-21 17:49:07.277] [INFO] Watching ../import_pdf for changes, press Ctrl+C to stop...

**settings.yaml**
llm_hf_model_file: mistral-7b-instruct-v0.1.Q4_K_M.gguf
ingest_mode: parallel # (also tried batch)

**Comment by jnogol** [comment]
Hey folks, first of all, I just want to say thank you for such a fantastic project.

I'm still having this issue 😟 . In my case, I have added the documentation (in MarkDown) of an internal project related to platform engineering (so Kubernetes, GitHub Actions, Terraform and the likes) and while adjusting parameters (I've found what works best for me is `top_k=1`, `top_p=0.1`, `temperature=0.01`) has helped getting better results, it still gets information from the model base, specially when it tries to provide an example. 

For instance, when asked how can we push an image to a repository (which the answer is using a provided, internal, GitHub action), the example it provides includes an action that [doesn't exist (docker/docker)](https://github.com/marketplace?category=&query=docker%2Fdocker+sort%3Amatch-desc&type=actions&verification=)

``` yaml
info: Image Replication

  on:
    push:
      branches:
        - main

  jobs:
    build-and-push:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Build and push image
          uses: docker/docker@v2
          with:
            dockerfile: Dockerfile
            push: true
            registry: ecr
            username: <your-username>
            password: <your-password>
```

My system chat and query prompts are [the defaults](https://github.com/zylon-ai/private-gpt/blob/347be643f7929c56382a77c3f45f0867605e0e0a/settings.yaml#L25-L33), so I'm not sure why is not complying to them.

I'm fairly new to all this ecosystem but I'm more than happy to try and spend time debugging and testing.

### Additional context
config

``` yaml
llm:
  mode: ollama
  max_new_tokens: 512
  context_window: 3900
  temperature: 0.01 
(...)
ollama:
  llm_model: llama2
  embedding_model: mxbai-embed-large
  keep_alive: 5m
  tfs_z: 1.0
  top_k: 1
  top_p: 0.1
  repeat_last_n: 64       
  repeat_penalty: 0.9    
```
It was happening as well using mistral as the LLM model and `nomic-embed-text` as the embedding model.

**Comment by anamariaUIC** [comment]
> Hey folks, first of all, I just want to say thank you for such a fantastic project.
> 
> I'm still having this issue 😟 . In my case, I have added the documentation (in MarkDown) of an internal project related to platform engineering (so Kubernetes, GitHub Actions, Terraform and the likes) and while adjusting parameters (I've found what works best for me is `top_k=1`, `top_p=0.1`, `temperature=0.01`) has helped getting better results, it still gets information from the model base, specially when it tries to provide an example.
> 
> For instance, when asked how can we push an image to a repository (which the answer is using a provided, internal, GitHub action), the example it provides includes an action that [doesn't exist (docker/docker)](https://github.com/marketplace?category=&query=docker%2Fdocker+sort%3Amatch-desc&type=actions&verification=)
> 
> ```yaml
> info: Image Replication
> 
>   on:
>     push:
>       branches:
>         - main
> 
>   jobs:
>     build-and-push:
>       runs-on: ubuntu-latest
>       steps:
>         - name: Checkout code
>           uses: actions/checkout@v2
> 
>         - name: Build and push image
>           uses: docker/docker@v2
>           with:
>             dockerfile: Dockerfile
>             push: true
>             registry: ecr
>             username: <your-username>
>             password: <your-password>
> ```
> 
> My system chat and query prompts are [the defaults](https://github.com/zylon-ai/private-gpt/blob/347be643f7929c56382a77c3f45f0867605e0e0a/settings.yaml#L25-L33), so I'm not sure why is not complying to them.
> 
> I'm fairly new to all this ecosystem but I'm more than happy to try and spend time debugging and testing.
> ### Additional context
> 
> config
> 
> ```yaml
> llm:
>   mode: ollama
>   max_new_tokens: 512
>   context_window: 3900
>   temperature: 0.01 
> (...)
> ollama:
>   llm_model: llama2
>   embedding_model: mxbai-embed-large
>   keep_alive: 5m
>   tfs_z: 1.0
>   top_k: 1
>   top_p: 0.1
>   repeat_last_n: 64       
>   repeat_penalty: 0.9    
> ```
> 
> It was happening as well using mistral as the LLM model and `nomic-embed-text` as the embedding model.

Hi @jnogol did you ever resolve this issue and if yes can you please share how?
