### ISSUE TITLE
Which model powers privateGPT?

### ISSUE THREAD

**Issue by pradeepdev-1995** [imartinez/privateGPT#519]
You are claiming that privateGPT not using any openai interface and can work without an internet connection. May I know which LLM model is using inside privateGPT for inference purpose?

**Comment by 8bitaby** [comment]
LLM: default to [ggml-gpt4all-j-v1.3-groovy.bin](https://gpt4all.io/models/ggml-gpt4all-j-v1.3-groovy.bin).
If you prefer a different GPT4All-J compatible model, just download it and reference it in your .env file.
[ggml-vicuna-13b-1.1](https://huggingface.co/vicuna/ggml-vicuna-13b-1.1/blob/main/ggml-vic13b-q5_1.bin) and [koala-7B-GGML](https://huggingface.co/TheBloke/koala-7B-GGML/blob/main/koala-7B.ggmlv3.q4_0.bin) are some of the different models that you can try out other than the default mentioned.

**Comment by pradeepdev-1995** [comment]
@8bitaby is this model already embedded with the repo? when I download the repo shall I get this model.bin file?
