### ISSUE TITLE
Unable to even run ingest.py

### ISSUE THREAD

**Issue by cyonghui81** [imartinez/privateGPT#522]
I am running windows 10, have installed the necessary cmake and gnu that the git mentioned
Python 3.11 version

However i am facing tons of issue installing privateGPT

I tried installing in a virtual environment with pip install -r requirements.txt

However when it try to run ingest.py, it gives me this error 

C:\Users\User\Documents\Learning\privateGPT>python ingest.py
Traceback (most recent call last):
  File "C:\Users\User\Documents\Learning\privateGPT\ingest.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

**Comment by aviggithub** [comment]
pip install python-dotenv

**Comment by bstawy** [comment]
i try "C:\Users\User\Documents\Learning\privateGPT>pip install python-dotenv" and i get
Requirement already satisfied: python-dotenv in c:\users\basta\appdata\local\programs\python\python311\lib\site-packages (1.0.0)
when i try run ingest.py i get the same error
File "C:\Users\basta\GPT\privateGPT\ingest.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

**Comment by johnbrisbin** [comment]
You must always do your installs within the virtual environment or they will not be seen when you run the code later.
So, you must be within the venv when you initially install the project, the requirements and the things missing from the requirements and when you execute either ingest.py or privategpt.py.

**Comment by Matus1976** [comment]
> You must always do your installs within the virtual environment or they will not be seen when you run the code later. So, you must be within the venv when you initially install the project, the requirements and the things missing from the requirements and when you execute either ingest.py or privategpt.py.

Can you elaborate on this?

**Comment by JasonMaggard** [comment]
> > You must always do your installs within the virtual environment or they will not be seen when you run the code later. So, you must be within the venv when you initially install the project, the requirements and the things missing from the requirements and when you execute either ingest.py or privategpt.py.
> 
> Can you elaborate on this?

You create a python virtual env. Then activate that virtual env. Then run your pip install.

`python -m venv {name}`
`source {name}/bin/activate`

Now, run `which python` and you should be pointed to your virtual environment. Now you can `pip install` and the virtual environment will be updated.
