### ISSUE TITLE
privateGPT doesn't respond. 

### ISSUE THREAD

**Issue by anggoro-yn** [imartinez/privateGPT#529]
Hi,

I have managed to install privateGPT and ingest the documents.

When i run privateGPT.py, the program asked me to submit a query but after that no responses come out form the program. What might have gone wrong?

"Enter a query: please summarize the state of union?"

after I hit ENTER, nothing happens for two hours.

Thank you.

**Comment by anggoro-yn** [comment]
![image](https://github.com/imartinez/privateGPT/assets/70189451/eea60a89-52dd-41b0-8415-9a95c6143c33)

**Comment by newmedicine** [comment]
A response is likely to take several hours depending on your hardware, the ingested docs and the query

**Comment by newmedicine** [comment]
... although "summarise the constitution" only took a few minutes on Intel(R) Core(TM) i5-6600T CPU @ 2.70GHz with 16GB RAM. YMMV as they say!

**Comment by anggoro-yn** [comment]
The ingestion of data is fine. It is a long time but not very long. But just one query of summarize the state of the union text took more than two hours .... I kill the process after two hours of no response. 

My laptop is AMD Ryzen 3250 with 8 GB of memory. During the process I notice that it took 50% of CPU time.

Is there minimum requirement?

**Comment by Jeru2023** [comment]
Only 2 hours? Just wait for few more days it might work

**Comment by AdityaSher** [comment]
for me it worked when i pressed ctrl+c gave response instantly mac m1
