### ISSUE TITLE
Incomplete dependency list

### ISSUE THREAD

**Issue by msidqi** [imartinez/privateGPT#530]
`pip3 install -r dependencies.txt`

Installation process fails due to missing dependencies.
I had to manually install the following packages to complete the build/installation:
- scikit-build
- pybind11
- numpy

Environment:
 - MacOS/M1
 - Python version 3

**Comment by ChristiaanSl** [comment]
Did you get it working on an MacOS M1? I can't seem to get it working on my M1 with ARM on Python 3.10 or higher (which is required).
