### ISSUE TITLE
Web server for private GPT

### ISSUE THREAD

**Issue by PeterPirog** [imartinez/privateGPT#531]
I think that interesting option can be  creating private GPT web server with interface.
Web interface needs:
-text field  for question
-text ield for output answer
-button to select propoer model
-button to add model
-button to select/add new text document
-button to confir querry

application can be runing as docker container with mounting directories for models and documents

**Comment by ijasonwhite** [comment]
Great idea but drop the docker bit ;)

**Comment by oktaborg** [comment]
I like to try a docker version of this. I have done similar stuff but in many different containers talking to each other. Like the try this solution with just one container with web interface. 

Also, do you need a paid api?

**Comment by ebisuinfosoft** [comment]
Check this out. It's already implemented.

https://github.com/SamurAIGPT/privateGPT

**Comment by pseudotensor** [comment]
Ya same here for web UI with all document related controls: https://github.com/h2oai/h2ogpt   Has client API as well if that is your thing.

**Comment by PeterPirog** [comment]
@ebisuinfosoft @pseudotensor  Thank You for the answer :)

**Comment by paul-asvb** [comment]
https://github.com/SamurAIGPT/privateGPT forwards me to a different project. Not sure if this is relevant anymore.
