### ISSUE TITLE
Set n_threads drastically slow down privateGPT

### ISSUE THREAD

**Issue by mehrdad2000** [imartinez/privateGPT#538]
Hi
set n_threads=40 in this file privateGPT.py to use all cpu cores it will slow down while answer.

set n_threads=1 in this file privateGPT.py to use 1 cpu core it will slow down while answer.

remove n_threads in this file privateGPT.py, it will answer as usual!

How can increase speed of answering?

FYI:i have no GPU

any idea?
Thanks

**Comment by sime2408** [comment]
`n_threads=psutil.cpu_count(logical=False),`

**Comment by mehrdad2000** [comment]
@sime2408 what does it? Any description?

Thanks

**Comment by sime2408** [comment]
The psutil.cpu_count(logical=False) function call is used to get the number of physical cores on your machine.

The psutil.cpu_count() function is a part of the psutil library in Python, which is used for retrieving information on running processes and system utilization (CPU, memory, disks, network, sensors) in Python. The cpu_count() function specifically returns the number of CPUs in the system.

If you call psutil.cpu_count() without any arguments, it returns the number of logical cores, which includes the cores created by hyper-threading. If hyper-threading is enabled, each physical core will appear as two cores to the operating system, which can be beneficial for certain types of tasks.

However, if you call psutil.cpu_count(logical=False), it will return the number of physical cores, not including the cores from hyper-threading.

So, in the context of n_threads=psutil.cpu_count(logical=False), the code is setting the number of threads for a certain operation or process to the number of physical cores on the machine. This is often done to maximize the usage of CPU resources.

**Comment by mehrdad2000** [comment]
@sime2408 try that it utilizes all cpu cores and still so slow, when i remove it, answer speed increase but not use all cores.

seems it doesn’t related to number of cores. Even when i assign all cores during answer questions it utilizes all cores but answering drastically slow down!

any idea?
Thanks

**Comment by sime2408** [comment]
> any idea? Thanks

@mehrdad2000 That's due to embeddings I guess and vector search, will try to figure out how to speed this up and will update you
