### ISSUE TITLE
[ No new documents to load ] after running ingest.py

### ISSUE THREAD

**Issue by MichaelSebero** [imartinez/privateGPT#548]
**Describe the bug and how to reproduce it**
I placed a total of 5 pdfs and a couple txt files in [ source_documents ] but it doesn't ingest new documents, it only ingested the original sample material. I've tried adding one pdf or txt file at a time and it still doesn't recognize the contents. I get the console response of...

Creating new vectorstore
Loading documents from source_documents
Loading new documents: 0it [00:00, ?it/s]
No new documents to load

**Expected behavior**
I expected for all of the files in [ source_documents ] to be ingested by privateGPT.

**Environment (please complete the following information):**
 - Hardware: Nvidia GTX 1660
 - OS: Linux
 - Python: 3.11

**Comment by MichaelSebero** [comment]
Fixed the issue, it's solved with my fork of privateGPT

**Comment by Vignesh1489** [comment]
I am also facing the same error. i have placed some new files but its not picking. someone please help on it.

**Comment by ekonlab** [comment]
I basically re-installed the whole thing and place the new documents in the source_documents folder before running ingest.py. It worked.

**Comment by MichaelSebero** [comment]
Re-installing it still gives me the same issue.

**Comment by DuarteBarbosaPT** [comment]
> Re-installing it still gives me the same issue.

Hi,
The problem you're facing is because you haven't run the "python3 ingest.py" command in the same folder as the file. Just go to that folder using the "cd" command in your terminal or command prompt. Then, run the "python3 ingest.py" command, and it should work.

**Comment by Schaekermann** [comment]
> 

I had the same problem because I use several Versions of Python in parallel on my Laptop. I had to open cmd, then cd to the folder of privatGPT. I then had do call python.exe including its path like:

C:\Users\Donald\Desktop\privateGPT>C:\Python311\python ingest.py      This worked for me

My original attempt didn't work:

C:\Python311>python C:\Users\Donald\Desktop\privateGPT\ingest.py      This did not work !!!

Just in case it's usefull for anyone elese:
In my special case i always opened cmd as admin to follow the install instructions and get everything working.

**Comment by MichaelSebero** [comment]
> > Re-installing it still gives me the same issue.
> 
> Hi, The problem you're facing is because you haven't run the "python3 ingest.py" command in the same folder as the file. Just go to that folder using the "cd" command in your terminal or command prompt. Then, run the "python3 ingest.py" command, and it should work.

This is what I've been doing the whole time.

**Comment by DuarteBarbosaPT** [comment]
> /home/$USER/privateGPT/

You can try to use the gysoks solution or can you try
'cd /home/$USER/privateGPT/' and then 'python3 ingest.py'?

**Comment by MichaelSebero** [comment]
> > /home/$USER/privateGPT/
> 
> You can try to use the gysoks solution or can you try 'cd /home/$USER/privateGPT/' and then 'python3 ingest.py'?

I've done this before too, neither way works.

**Comment by MichaelSebero** [comment]
With the new version of [ ingest.py ] it doesn't consume the original [ source_documents ] it still gives the error message.

Creating new vectorstore
Loading documents from source_documents
Loading new documents: 0it [00:00, ?it/s]
No new documents to load

**Steps to reproduce**
. cd /home/$USER/privateGPT/ && python3 ingest.py
or 
. python3 /home/$USER/privateGPT/ingest.py

**Comment by MichaelSebero** [comment]
This issue still persists after new updates to ingest.py.
