### ISSUE TITLE
sample csv file that privateGPT work with it correctly

### ISSUE THREAD

**Issue by mehrdad2000** [imartinez/privateGPT#551]
Hi
I try to ingest different type csv file to privateGPT but when i ask about that don't answer correctly!

is there any sample or template that privateGPT work with that correctly?

FYI: same issue occurs when i feed other extension like pdf, docx,...

Any idea?
Thanks

**Comment by ravindraprasad75** [comment]
This is a known issue #448

**Comment by ravindraprasad75** [comment]
Let me test this

**Comment by ravindraprasad75** [comment]
> Error Description
> 001 Server fail
> 002 Client fail

This is a bug. Model is reading just first record just like in the case of CSV file

**Comment by mehrdad2000** [comment]
@ravindraprasad75 seems it has issue with text file too!

**Comment by mehrdad2000** [comment]
@avizuber my .env same as you and we have same issue!

**Comment by ravindraprasad75** [comment]
> @avizuber my .env same as you and we have same issue!

This error is nothing to do with .env file. There is a bug in the code

**Comment by QuickBenx** [comment]
yea getting the same :
Q: Let s(v) = -10v**2 + 3v + 4. Let k be s(-2). Suppose 5q - 16 = -kq. Solve q*l = -l for l.

is this supposed to be code for something specific ?

**Comment by Akilesh3** [comment]
I have the same problem with the CSV files.
Question: Let k = 10 - 6. Suppose 2z + 3z = -ky + 4, 5z = 3y - 15. Solve 0 = -2n - y*n for n.
Answer: 0
Why does it asks itself a question and answer it?

**Comment by rolender2** [comment]
I have the same issue.  here is the output:  Question: Let r(l) = -2l**3 + 14l*2 - 6l + 5. Let i be r(7). Suppose 0 = 3q - 2q - i. What is the units digit of q?
Answer: 9  

I used the walmart sales dataset csv from kaggle.
