### ISSUE TITLE
When i run privateGPT.py I got an error that says: cannot access local variable 'llm' where it is not associated with a value

### ISSUE THREAD

**Issue by busyneuron** [imartinez/privateGPT#559]
Error running the privateGPT.py file on cmd. Here is the full error:

____________________________________________________________________
Using embedded DuckDB with persistence: data will be stored in: db
Model GPT4ALL not supported!
Traceback (most recent call last):
  File "C:\Users\soyel\Desktop\privateGpt\privateGPT.py", line 77, in <module>
    main()
  File "C:\Users\soyel\Desktop\privateGpt\privateGPT.py", line 41, in main
    qa = RetrievalQA.from_chain_type(llm=llm, chain_type="stuff", retriever=retriever, return_source_documents= not args.hide_source)
                                         ^^^
UnboundLocalError: cannot access local variable 'llm' where it is not associated with a value
___________________________________________________________________________

I think it should load everything fine.

 - Windows 10
 - Python 3.11.3

**Comment by GianlucaMattei** [comment]
It can not retrieve your model. 
You should add to your comment the .env file to understand what is happening. Anyway I can say there is at least one error. The model is called GTP4All not GTP4ALL. Try to edit this in your .env file first of all

**Comment by busyneuron** [comment]
PERSIST_DIRECTORY=db
MODEL_TYPE=GPT4All
MODEL_PATH=models/ggml-gpt4all-j-v1.3-groovy.bin
EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
MODEL_N_CTX=1000
TARGET_SOURCE_CHUNKS=4

**Comment by busyneuron** [comment]
Okay it is solved, now i can enter a query, but it lasts too long to answer, is it because of my computer's performance?

**Comment by GianlucaMattei** [comment]
> Okay it is solved, now i can enter a query, but it lasts too long to answer, is it because of my computer's performance?

Don't know, I have a 3060m and it takes a lot to answer. I was wondering your same question since I pretty new to these things

**Comment by johnbrisbin** [comment]
Currently, the computer's CPU is the only resource used. GPU support is on the way, but getting it installed is tricky. It helps greatly with the ingest, but I have not yet seen improvement on the same scale with the query side, but the installed GPU only has about 5.5GB free for model layers.

**Comment by GianlucaMattei** [comment]
> Currently, the computer's CPU is the only resource used. GPU support is on the way, but getting it installed is tricky. It helps greatly with the ingest, but I have not yet seen improvement on the same scale with the query side, but the installed GPU only has about 5.5GB free for model layers.

I thought each model uses the GPU
Thus the *.bin models use the CPU? Or which type of models use it?
