### ISSUE TITLE
it looks it is not compatible with other models downloaded from the same source (https://gpt4all.io/index.html)

### ISSUE THREAD

**Issue by 77bgh** [imartinez/privateGPT#565]
Hello, I just replaced the model path to use a different one, downloaded from https://gpt4all.io/index.html
please note this model is in the same folder 'models' as ggml-gpt4all-j-v1.3-groovy.bin however with groovy (downloaded from https://gpt4all.io/index.html ) it works, as well all dependencies are installed accordingly with the required version

this is my .env,

PERSIST_DIRECTORY=db
MODEL_TYPE=GPT4All
MODEL_PATH=models/ggml-gpt4all-l13b-snoozy.bin
EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
MODEL_N_CTX=1000
TARGET_SOURCE_CHUNKS=4

I tried as well with other models downloaded from the same source, the same error:

_Using embedded DuckDB with persistence: data will be stored in: db
Found model file.
gptj_model_load: loading model from 'models/ggml-gpt4all-l13b-snoozy.bin' - please wait ...
gptj_model_load: invalid model file 'models/ggml-gpt4all-l13b-snoozy.bin' (bad magic)
GPT-J ERROR: failed to load model from models/ggml-gpt4all-l13b-snoozy.bin
Enter a query:_

**Comment by ProxyAyush** [comment]
got the same problem

**Comment by pseudotensor** [comment]
FYI Bad magic means different quantization version.  I recommend, like localGPT and h2oGPT (https://github.com/h2oai/h2ogpt), using only latest llama.cpp based models, not GPT4All that are still on quantization 2.  E.g. wizardlm or vicuna llama.cpp models are much better than gpt4all gpt-j etc.

**Comment by ProxyAyush** [comment]
> FYI Bad magic means different quantization version. I recommend, like localGPT and h2oGPT (https://github.com/h2oai/h2ogpt), using only latest llama.cpp based models, not GPT4All that are still on quantization 2. E.g. wizardlm or vicuna llama.cpp models are much better than gpt4all gpt-j etc.

I checked my file even if i change my .env values the privateGPT script loads the older .env values, why is this happening?

**Comment by grigio** [comment]
@pseudotensor Which WizardLM did you try ?
I tried with `Wizard-Vicuna-7B-Uncensored.ggmlv3.q4_0.bin` but I get Bad Magic
