### ISSUE TITLE
Not Enough Space on every Inquiry

### ISSUE THREAD

**Issue by AsaTyr2018** [imartinez/privateGPT#566]
**Describe the bug and how to reproduce it**
Loading up 7 Documents (Small PDF Files with less then 5mb)
Indexed with Ingest -> No Problem

Starting PrivatGPT:
Using embedded DuckDB with persistence: data will be stored in: db
gptj_model_load: loading model from 'models/ggml-gpt4all-j-v1.3-groovy.bin' - please wait ...
gptj_model_load: n_vocab = 50400
gptj_model_load: n_ctx   = 2048
gptj_model_load: n_embd  = 4096
gptj_model_load: n_head  = 16
gptj_model_load: n_layer = 28
gptj_model_load: n_rot   = 64
gptj_model_load: f16     = 2
gptj_model_load: ggml ctx size = 4505.45 MB
gptj_model_load: memory_size =   896.00 MB, n_mem = 57344
gptj_model_load: ................................... done
gptj_model_load: model size =  3609.38 MB / num tensors = 285

Started the Inquiry "List up the Flight Tickets"
Output:
gpt_tokenize: unknown token '├'
gpt_tokenize: unknown token '£'
ggml_new_tensor_impl: not enough space in the context's memory pool (needed 15472003040, available 15459426400)

**Expected behavior**
Output 3 Tickets 

**Environment (please complete the following information):**
I use a Computer with 64gb RAM and an RTC 3090 24gb VRAM.
PrivatGPT is stored on a m.2 with 1tb storage.
I´m Running windows 11 Enterprise.
Python 3.10.9

**Additional context**
i can´t point out where its getting the 15,46gb from. my system has definitly more memory availible. but regardless of that memory. its just 7 pdf files with less then 5mb.

**Comment by pseudotensor** [comment]
The context is just overflowing because of how privateGPT has no protections for various issues.  You can  try https://github.com/h2oai/h2ogpt or use the code there and put into privateGPT.

**Comment by pseudotensor** [comment]
Our GPT4All parent class: https://github.com/h2oai/h2ogpt/blob/c4acb23ed257e0e92015df98edfb7632c79cd8aa/gpt4all_llm.py#L169-L180

Our LLaMa parent class: https://github.com/h2oai/h2ogpt/blob/c4acb23ed257e0e92015df98edfb7632c79cd8aa/gpt4all_llm.py#L234-L255

For gpt4all there just has a hard cut-off so doesn't fail, but the llama way is best and can be done in general  Basically one tokenizes (fast) the prompt, and if goes beyond max, then truncates text input with conservative bound.
