### ISSUE TITLE
THIS REPO NEEDS A STABLE RELEASE

### ISSUE THREAD

**Issue by TheSnowGuru** [imartinez/privateGPT#579]
THIS REPO NEEDS A STABLE RELEASE

**Comment by imartinez** [comment]
Totally agree! Will introduce versioning in the coming days

**Comment by alekssadowski95** [comment]
Yes please, I tried installing it on Windows 10 and Ubuntu 20.04 and both would not work. I am a little dissapointed.

**Comment by pseudotensor** [comment]
h2oGPT (https://github.com/h2oai/h2ogpt) has like 70 tests to ensure we don't break anything.  This repo should do the same.  Some of our tests are still manual, but once jenkins CI comes online I'll add more.  We also need more than linux testing, with windows/macos in CI, but we don't have that yet either.   Those are manually tested.  We'll also have pypi release soon, like DB-GPT.
