### ISSUE TITLE
main issue

### ISSUE THREAD

**Issue by 0x240x23elu** [imartinez/privateGPT#584]
[Note: if you'd like to *ask a question* or *open a discussion*, head over to the [Discussions](https://github.com/imartinez/privateGPT/discussions) section and post it there.

**Describe the bug and how to reproduce it**
A clear and concise description of what the bug is and the steps to reproduce the behavior.

**Expected behavior**

**Environment (please complete the following information):**
 - OS / hardware: [e.g. macOS 12.6 / M1]
 - Python version [e.g. 3.11.3]
- Other relevant information

**Additional context**
](https://github.com/imartinez/privateGPT)

**Comment by 0x240x23elu** [comment]
OS / hardware: Windows 10
Python version [3.10)

**Comment by imartinez** [comment]
What is the issue?

**Comment by 0x240x23elu** [comment]
G:\gpt\privategpt\privateGPT>python privateGPT.py
Using embedded DuckDB with persistence: data will be stored in: db
Traceback (most recent call last):
  File "G:\gpt\privategpt\privateGPT\privateGPT.py", line 76, in <module>
    main()
  File "G:\gpt\privategpt\privateGPT\privateGPT.py", line 36, in main
    llm = GPT4All(model=model_path, n_ctx=model_n_ctx, backend='gptj', callbacks=callbacks, verbose=False)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GPT4All
__root__
  Invalid model directory (type=value_error)

**Comment by melroy89** [comment]
Dup: https://github.com/imartinez/privateGPT/issues/459 &
