### ISSUE TITLE
How to solve garbled characters：B/A,$9*)E;319B+.>H=;5D9C5?GF":(B7'1-E7)

### ISSUE THREAD

**Issue by RD-Man** [imartinez/privateGPT#587]
> Question:
what is the nato

> Answer:
"B/A,$9*)E;319B+.>H=;5D9C5?GF":(B7'1-E7)(':;$'F%=7?3F942!G?H1;GB(/")::(&A8)(4;)!4-<3'C('7.;?#C2#;4D=D71.=,6">7HH7)6=/818D#1:9!-EH?>2E81'12-F=6B/-8#F/$&1954.4E2/;>%724GB1)HB++/2!;9B,8&?#*B%%/DH-C5A6D8.2B5!&/*#<+;.H%!<1*GA.,=83/*=H-%?1-*+-%C)/3:16D.*E%$%<=E6

**Comment by phasedistorter** [comment]
Make sure the model you are using is fully downloaded.
