### ISSUE TITLE
PrivateGPT is not giving an answer

### ISSUE THREAD

**Issue by autumnalblues** [imartinez/privateGPT#591]
Hello there!

Followed the instructions and installed the dependencies but I'm not getting any answers to any of my queries. Please find the attached screenshot. What could be the problem?
<img width="731" alt="PrivateGPT Error" src="https://github.com/imartinez/privateGPT/assets/129698237/d4e73053-6d66-4c8c-8bf5-58188fcd3505">

**Comment by pseudotensor** [comment]
Is the CPU running in background?  i.e. Will be slow for the demo that has large context use.

**Comment by autumnalblues** [comment]
HI @pseudotensor: Apparently, I got an answer after more than 10 minutes. It just took a lot of time! Thanks so much for the assistance! :)
