### ISSUE TITLE
Getting this error : 1 validation error for GPT4All . Invalid model directory (type=value_error)

### ISSUE THREAD

**Issue by ar-ohi-srivastav** [imartinez/privateGPT#603]

**Comment by ar-ohi-srivastav** [comment]
My .env file 
PERSIST_DIRECTORY=db
MODEL_TYPE=GPT4All
MODEL_PATH=Downloads/ggml-gpt4all-j-v1.3-groovy.bin
EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
MODEL_N_CTX=1000
TARGET_SOURCE_CHUNKS=4

**Comment by dnordgren** [comment]
Did you download the model into `models`? See this: https://github.com/imartinez/privateGPT/issues/78#issuecomment-1546545092

I had this error too but then followed that comment to download the models and now working. Downloading the model would be a small improvement to the README that I glossed over.

**Comment by arnaupool** [comment]
> Did you download the model into `models`? See this: [#78 (comment)](https://github.com/imartinez/privateGPT/issues/78#issuecomment-1546545092)

That seems to do it, they should update the README.

**Comment by harsiddhdave44** [comment]
> Did you download the model into `models`? See this: [#78 (comment)](https://github.com/imartinez/privateGPT/issues/78#issuecomment-1546545092)
> 
> I had this error too but then followed that comment to download the models and now working. Downloading the model would be a small improvement to the README that I glossed over.

The comment mentions two models to be downloaded. Is it using two models or just one?

**Comment by arnaupool** [comment]
> > Did you download the model into `models`? See this: [#78 (comment)](https://github.com/imartinez/privateGPT/issues/78#issuecomment-1546545092)
> > I had this error too but then followed that comment to download the models and now working. Downloading the model would be a small improvement to the README that I glossed over.
> 
> The comment mentions two models to be downloaded. Is it using two models or just one?

Just the one provided.

**Comment by maozdemir** [comment]
The model path is relative, you have to provide the full path or relative path. I have no idea how to explain the concept.

**Comment by ar-ohi-srivastav** [comment]
@dnordgren  thanks it worked
