### ISSUE TITLE
Small Bug - repeating answer

### ISSUE THREAD

**Issue by phsheth** [imartinez/privateGPT#609]
**Describe the bug and how to reproduce it**
When the answer starts - it is printed twice after the prompt. Example:

=====
Enter a query: What year is this?
2023
2023
=====

**Expected behavior**
It should answer only once.

**Environment (please complete the following information):**
 - OS / hardware: Windows 11 - Dell Laptop 64bit
 - Python version  3.10.9

**Comment by melroy89** [comment]
Just accept that the year is 2023 ;)
