### ISSUE TITLE
Syntax error model type 

### ISSUE THREAD

**Issue by Joaov41** [imartinez/privateGPT#615]
Running macOS Ventura getting this error 
match model_type:
          ^
SyntaxError: invalid syntax

**Comment by tehruhn** [comment]
Ah I just ran it and had the same error. macOS Ventura as well

**Comment by Joaov41** [comment]
Downgrading to python 3.10.1 now get a different error 

from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

**Comment by ProxyAyush** [comment]
> Downgrading to python 3.10.1 now get a different error
> 
> from dotenv import load_dotenv ModuleNotFoundError: No module named 'dotenv'

use 'python -m pip install python-dotenv'

**Comment by ProxyAyush** [comment]
> Running macOS Ventura getting this error match model_type: ^ SyntaxError: invalid syntax

you must use python 3.11 or newer versions, your python version must be older

**Comment by Joaov41** [comment]
> > Downgrading to python 3.10.1 now get a different error
> > from dotenv import load_dotenv ModuleNotFoundError: No module named 'dotenv'
> 
> use 'python -m pip install python-dotenv'

Requirement already satisfied

**Comment by Joaov41** [comment]
> > Running macOS Ventura getting this error match model_type: ^ SyntaxError: invalid syntax
> 
> you must use python 3.11 or newer versions, your python version must be older

Just upgraded to 3.11.1 and still no module dotenv error

**Comment by ProxyAyush** [comment]
> > > Running macOS Ventura getting this error match model_type: ^ SyntaxError: invalid syntax
> > 
> > 
> > you must use python 3.11 or newer versions, your python version must be older
> 
> Just upgraded to 3.11.1 and now the error is other. No module langchain

then use `python -m pip install langchain` exactly and paste it in terminal

**Comment by CooleMuetze** [comment]
I got the same Error but was able to go around it. The match model_type is simply a switch statement which is looking for your model type. By commenting out the match statement and just writing the code for the specific model you use, the error can be bypassed.

When using the default model:
`#    match model_type:
#        case "LlamaCpp":
#            llm = LlamaCpp(model_path=model_path, n_ctx=model_n_ctx, callbacks=callbacks, verbose=False)
#        case "GPT4All":
#            llm = GPT4All(model=model_path, n_ctx=model_n_ctx, backend='gptj', callbacks=callbacks, verbose=False)
#        case _default:
#            print(f"Model {model_type} not supported!")
#            exit;
    
    llm = GPT4All(model=model_path, n_ctx=model_n_ctx, backend='gptj', callbacks=callbacks, verbose=False)`

**Comment by alexfilothodoros** [comment]
> > Running macOS Ventura getting this error match model_type: ^ SyntaxError: invalid syntax
> 
> you must use python 3.11 or newer versions, your python version must be older

I am using 3.11.2 and I get this error.
