### ISSUE TITLE
Can I use my database to directly query it?

### ISSUE THREAD

**Issue by asoral** [imartinez/privateGPT#616]
I use MariaDB for my app and saw this library and want to use it. I am trying to figure out a way to use this directly off my database tables, rather than exporting them into text or any other format and running the model on the data.
Is it even possible? How?

**Comment by maozdemir** [comment]
MariaDB is a fork of MySQL. See https://python.langchain.com/en/latest/modules/chains/examples/sqlite.html

**Comment by Cornatul** [comment]
> I use MariaDB for my app and saw this library and want to use it. I am trying to figure out a way to use this directly off my database tables, rather than exporting them into text or any other format and running the model on the data. Is it even possible? How?
I guess you could have a look to the document processor and see if there is any

**Comment by asoral** [comment]
> MariaDB is a fork of MySQL. See https://python.langchain.com/en/latest/modules/chains/examples/sqlite.html

This works. I will try and open another issue if required. Thanks for the support
