### ISSUE TITLE
gptj_model_load: invalid model file 'models/pytorch_model.bin' (bad magic)

### ISSUE THREAD

**Issue by mehrdad2000** [imartinez/privateGPT#628]
Hi
Can’t load custom model of llm that exist on huggingface in privategpt!

got this error:
gptj_model_load: invalid model file 'models/pytorch_model.bin' (bad magic)

Any idea?
Thanks

**Comment by sime2408** [comment]
If you go to FIle and the version tab your model must have `pytorch_model.bin` files, [ like this repo for example](https://huggingface.co/tiiuae/falcon-40b-instruct/tree/main)

**Comment by mehrdad2000** [comment]
@sime2408 bin files download correctly and i put in “models” directory and change .env to load custom model but got this error:
gptj_model_load: invalid model file 'models/pytorch_model.bin' (bad magic)

Any other idea? 
Thanks
