### ISSUE TITLE
Love this project - what's the path to production?

### ISSUE THREAD

**Issue by shihzy** [imartinez/privateGPT#636]
Hi all - love this project and the simplicity to creating a private LLM.  Especially for folks like myself who are tinkering but are not that deep technically (I'm just an ole' PM)

With that - I'm curious what the path to production might look like? It seems like the user persona here is really a semi-technical engineer who has expertise in other areas (i.e. front end) but doesn't want to deal with the LLM side of it.  And also needs to privacy piece as a core tenant of the product.

As someone just running it locally on a Mac (and not terribly technical), its def a bit slow.  Some of the responses are a bit "interesting".

Curious what others in the community think.

**Comment by melroy89** [comment]
Please, make a topic on the discussion instead about this: https://github.com/imartinez/privateGPT/discussions. Issues should be used for.. Issues.. Ideally.

**Comment by shihzy** [comment]
ah good call.  i didn't see the discussions tab.  will close

**Comment by melroy89** [comment]
No problem!
