### ISSUE TITLE
Duplicates Responses When Running privateGPT

### ISSUE THREAD

**Issue by GLM9** [imartinez/privateGPT#641]
---
name: Bug report
about: Create a report to help us improve
title: 'Duplicates Responses When Running privateGPT'
labels: bug
assignees: 'GLM9'

---

**Describe the bug and how to reproduce it**
During the execution of the privateGPT script (privateGPT.py), a repeated block of output appears that seems to be duplicate responses generated by the LangChain framework. This duplication occurs for every user query entered.

Run the privateGPT.py script in the Python environment.
Enter a user query.
Observe the output. There is duplicated text within the same answer.

**Expected behavior**
The expected behavior is a unique response to the user's query without any duplicated content. The script has been modified to remove duplicated sentences from the generated responses, but the output from the LangChain framework still appears to be duplicated.

**Environment**
 - OS / hardware:   Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz   3.60 GHz
                    16.0 GB
                    64-bit operating system, x64-based processor
                    Windows 10 Home
                    22H2

 - Python 3.11.3
- Other relevant information: The script was executed within an Anaconda environment.

**Additional context**
The script has been adjusted to remove duplicate sentences from the generated response. The function correctly removes duplicates when tested separately, but it does not seem to affect the duplicated output from the LangChain framework. This issue may stem from how LangChain is handling or returning its responses.

**Comment by laSonde** [comment]
Same as you, tested yersterday and I identified this behavior as well.

**Comment by SH1436** [comment]
Identical issue to what GLM9 describes.

**Comment by seangrant82** [comment]
have you tried running with the hide source arg?:

`python privateGPT.py --hide-source`

**Comment by SH1436** [comment]
> have you tried running with the hide source arg?:
> 
> `python privateGPT.py --hide-source`
> 
> that cleaned things up for me

Thanks, Sean that worked very well :)

I also found that changing line 69 in PrivateGPT.py as below makes the change permanent.
    parser.add_argument("--hide-source", "-S", action='store_**false**',
                        help='Use this flag to disable printing of source documents used for answers.')
