### ISSUE TITLE
For those who use centos and can't install llama-cpp-python

### ISSUE THREAD

**Issue by StartAgainJ** [imartinez/privateGPT#644]
What you need is to upgrade you gcc version to 11, do as follows:
1. remove old gcc
yum remove gcc yum remove gdb
2. install scl-utils
sudo yum install scl-utils sudo yum install centos-release-scl
3. find devtoolset-11
yum list all --enablerepo='centos-sclo-rh' | grep "devtoolset"
4. install devtoolset-11-toolchain
yum install -y devtoolset-11-toolchain
5. add gcc 11 to PATH by adding following script to /etc/profile
PATH=$PATH::/opt/rh/devtoolset-11/root/usr/bin export PATH sudo scl enable devtoolset-11 bash
6. show gcc version and gcc11 is installed successfully.
gcc --version
7. pip install llama-cpp-python==0.1.50

**Comment by naimavahab** [comment]
Still its not working for me .. my system is centos 7..x86_64 and GCC is gcc (GCC) 11.2.1 20220127 (Red Hat 11.2.1-9)
for python 3.10 env, pip install llama-cpp-python is still throwing following error
Collecting llama-cpp-python==0.1.50
  Using cached llama_cpp_python-0.1.50.tar.gz (1.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: typing-extensions>=4.5.0 in /root/anaconda3/envs/gpt4all/lib/python3.10/site-packages (from llama-cpp-python==0.1.50) (4.5.0)
Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "/tmp/pip-build-env-8v43xb13/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 645, in setup
          cmkr = cmaker.CMaker(cmake_executable)
        File "/tmp/pip-build-env-8v43xb13/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 148, in __init__
          self.cmake_version = get_cmake_version(self.cmake_executable)
        File "/tmp/pip-build-env-8v43xb13/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 105, in get_cmake_version
          raise SKBuildError(msg) from err

      Problem with the CMake installation, aborting build. CMake executable is /tmp/pip-build-env-8v43xb13/overlay/lib/python3.10/site-packages/cmake/data/bin/cmake
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects

**Comment by vual** [comment]
> 7\. pip install llama-cpp-python==0.1.50

the same error，have you resolve it？

**Comment by vual** [comment]
> Still its not working for me .. my system is centos 7..x86_64 and GCC is gcc (GCC) 11.2.1 20220127 (Red Hat 11.2.1-9) for python 3.10 env, pip install llama-cpp-python is still throwing following error Collecting llama-cpp-python==0.1.50 Using cached llama_cpp_python-0.1.50.tar.gz (1.2 MB) Installing build dependencies ... done Getting requirements to build wheel ... done Preparing metadata (pyproject.toml) ... done Requirement already satisfied: typing-extensions>=4.5.0 in /root/anaconda3/envs/gpt4all/lib/python3.10/site-packages (from llama-cpp-python==0.1.50) (4.5.0) Building wheels for collected packages: llama-cpp-python Building wheel for llama-cpp-python (pyproject.toml) ... error error: subprocess-exited-with-error
> 
> × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully. │ exit code: 1 ╰─> [9 lines of output] Traceback (most recent call last): File "/tmp/pip-build-env-8v43xb13/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 645, in setup cmkr = cmaker.CMaker(cmake_executable) File "/tmp/pip-build-env-8v43xb13/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 148, in **init** self.cmake_version = get_cmake_version(self.cmake_executable) File "/tmp/pip-build-env-8v43xb13/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 105, in get_cmake_version raise SKBuildError(msg) from err
> 
> ```
>   Problem with the CMake installation, aborting build. CMake executable is /tmp/pip-build-env-8v43xb13/overlay/lib/python3.10/site-packages/cmake/data/bin/cmake
>   [end of output]
> ```
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for llama-cpp-python Failed to build llama-cpp-python ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects

the same error，have you resolve it？

**Comment by vual** [comment]
> What you need is to upgrade you gcc version to 11, do as follows:
> 
> 1. remove old gcc
>    yum remove gcc yum remove gdb
> 2. install scl-utils
>    sudo yum install scl-utils sudo yum install centos-release-scl
> 3. find devtoolset-11
>    yum list all --enablerepo='centos-sclo-rh' | grep "devtoolset"
> 4. install devtoolset-11-toolchain
>    yum install -y devtoolset-11-toolchain
> 5. add gcc 11 to PATH by adding following script to /etc/profile
>    PATH=$PATH::/opt/rh/devtoolset-11/root/usr/bin export PATH sudo scl enable devtoolset-11 bash
> 6. show gcc version and gcc11 is installed successfully.
>    gcc --version
> 7. pip install llama-cpp-python==0.1.50

no useable,

**Comment by nguyen-viet-hung** [comment]
For whom faces this issue, the steps here:
- Install devtoolset-11 as above
- Run follow command: `CMAKE_ARGS="-DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++" pip install llama-cpp-python`
- And check your results

**Comment by lastYoueven** [comment]
``> For whom faces this issue, the steps here:
> 
> * Install devtoolset-11 as above
> * Run follow command: `CMAKE_ARGS="-DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++" pip install llama-cpp-python`
> * And check your results

not work for me:

```
(venv) PS E:\stable-diffusion-webui\extensions\ComfyUI_windows_portable\ComfyUI> pip install llama-cpp-python 
Collecting llama-cpp-python
  Using cached llama_cpp_python-0.2.79.tar.gz (50.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: typing-extensions>=4.5.0 in e:\stable-diffusion-webui\extensions\comfyui_windows_portable\comfyui\venv\lib\site-packages (from llama-cpp-python) (4.12.2)
Requirement already satisfied: numpy>=1.20.0 in e:\stable-diffusion-webui\extensions\comfyui_windows_portable\comfyui\venv\lib\site-packages (from llama-cpp-python) (1.26.4)
Collecting diskcache>=5.6.1 (from llama-cpp-python)
  Using cached diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: jinja2>=2.11.3 in e:\stable-diffusion-webui\extensions\comfyui_windows_portable\comfyui\venv\lib\site-packages (from llama-cpp-python) (3.1.4)
Requirement already satisfied: MarkupSafe>=2.0 in e:\stable-diffusion-webui\extensions\comfyui_windows_portable\comfyui\venv\lib\site-packages (from jinja2>=2.11.3->llama-cpp-python) (2.1.5)
Using cached diskcache-5.6.3-py3-none-any.whl (45 kB)
Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      *** scikit-build-core 0.9.6 using CMake 3.28.1 (wheel)
      *** Configuring CMake...
      2024-06-20 11:43:27,603 - scikit_build_core - WARNING - Can't find a Python library, got libdir=None, ldlibrary=None, multiarch=None, masd=None
      loading initial cache file C:\Users\mfker\AppData\Local\Temp\tmpi6ueec5o\build\CMakeInit.txt
      -- Building for: NMake Makefiles
      CMake Error at CMakeLists.txt:3 (project):
        Running

         'nmake' '-?'

        failed with:

         no such file or directory


      CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!

      *** CMake configuration failed
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects
```

**Comment by nguyen-viet-hung** [comment]
@lastYoueven 

Your issue is not similar to the above. The above issue is for CentOS OS while your OS is Windows. As you can see, you lack python library also C/C++ compiler. You should find how to use Visual Studio Build Tools Set to build llama-cpp-python on Windows.

**Comment by lastYoueven** [comment]
> @lastYoueven
> 
> Your issue is not similar to the above. The above issue is for CentOS OS while your OS is Windows. As you can see, you lack python library also C/C++ compiler. You should find how to use Visual Studio Build Tools Set to build llama-cpp-python on Windows.

thanks， i got this issue about gcc of window os, i make it worked with `set CMAKE_ARGS="-DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++" && pip install llama-cpp-python
`, thanks agent.

**Comment by lastYoueven** [comment]
> > @lastYoueven
> > Your issue is not similar to the above. The above issue is for CentOS OS while your OS is Windows. As you can see, you lack python library also C/C++ compiler. You should find how to use Visual Studio Build Tools Set to build llama-cpp-python on Windows.
> 
> thanks， i got this issue about gcc of window os, i make it worked with `set CMAKE_ARGS="-DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++" && pip install llama-cpp-python ` with linux in docker, thanks agent.

last word, i retry pip install llama-cpp-python sussecc with this command `# Windows
$env:CMAKE_ARGS = "-DLLAMA_BLAS=ON -DLLAMA_BLAS_VENDOR=OpenBLAS"
pip install llama-cpp-python` on window11 from https://github.com/abetlen/llama-cpp-python readme.md
