### ISSUE TITLE
chromadb.errors.NoIndexException: Index not found, please create an instance before querying

### ISSUE THREAD

**Issue by hktalent** [imartinez/privateGPT#65]
···
$ python privateGPT.py
llama.cpp: loading model from models/ggml-model-q4_0.bin
llama.cpp: can't use mmap because tensors are not aligned; convert to new format to avoid this
llama_model_load_internal: format     = 'ggml' (old version with low tokenizer quality and no mmap support)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 1000
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size = 4113748.20 KB
llama_model_load_internal: mem required  = 5809.33 MB (+ 2052.00 MB per state)
...................................................................................................
.
llama_init_from_file: kv self size  = 1000.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 1 | AVX512_VNNI = 1 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 | 
Using embedded DuckDB with persistence: data will be stored in: db
gptj_model_load: loading model from 'models/ggml-gpt4all-j-v1.3-groovy.bin' - please wait ...
gptj_model_load: n_vocab = 50400
gptj_model_load: n_ctx   = 2048
gptj_model_load: n_embd  = 4096
gptj_model_load: n_head  = 16
gptj_model_load: n_layer = 28
gptj_model_load: n_rot   = 64
gptj_model_load: f16     = 2
gptj_model_load: ggml ctx size = 4505.45 MB
gptj_model_load: memory_size =   896.00 MB, n_mem = 57344
gptj_model_load: ................................... done
gptj_model_load: model size =  3609.38 MB / num tensors = 285

Enter a query: 
The RTCPeerConnection.connectionState state in webrtc should be 'connected' or 'connected' in order to start creating a createDataChannel
···

error
···
lama_print_timings:        load time =  1395.38 ms
llama_print_timings:      sample time =     0.00 ms /     1 runs   (    0.00 ms per run)
llama_print_timings: prompt eval time =  4648.07 ms /    32 tokens (  145.25 ms per token)
llama_print_timings:        eval time =   170.89 ms /     1 runs   (  170.89 ms per run)
llama_print_timings:       total time =  4834.98 ms
Traceback (most recent call last):
  File "/Users/51pwn/MyWork/privateGPT/privateGPT.py", line 57, in <module>
    main()
  File "/Users/51pwn/MyWork/privateGPT/privateGPT.py", line 42, in main
    res = qa(query)    
  File "/Users/51pwn/anaconda3/envs/privateGPT/lib/python3.10/site-packages/langchain/chains/base.py", line 140, in __call__
    raise e
  File "/Users/51pwn/anaconda3/envs/privateGPT/lib/python3.10/site-packages/langchain/chains/base.py", line 134, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/Users/51pwn/anaconda3/envs/privateGPT/lib/python3.10/site-packages/langchain/chains/retrieval_qa/base.py", line 119, in _call
    docs = self._get_docs(question)
  File "/Users/51pwn/anaconda3/envs/privateGPT/lib/python3.10/site-packages/langchain/chains/retrieval_qa/base.py", line 181, in _get_docs
    return self.retriever.get_relevant_documents(question)
  File "/Users/51pwn/anaconda3/envs/privateGPT/lib/python3.10/site-packages/langchain/vectorstores/base.py", line 366, in get_relevant_documents
    docs = self.vectorstore.similarity_search(query, **self.search_kwargs)
  File "/Users/51pwn/anaconda3/envs/privateGPT/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 181, in similarity_search
    docs_and_scores = self.similarity_search_with_score(query, k, filter=filter)
  File "/Users/51pwn/anaconda3/envs/privateGPT/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 228, in similarity_search_with_score
    results = self.__query_collection(
  File "/Users/51pwn/anaconda3/envs/privateGPT/lib/python3.10/site-packages/langchain/utils.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/Users/51pwn/anaconda3/envs/privateGPT/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 120, in __query_collection
    return self._collection.query(
  File "/Users/51pwn/anaconda3/envs/privateGPT/lib/python3.10/site-packages/chromadb/api/models/Collection.py", line 219, in query
    return self._client._query(
  File "/Users/51pwn/anaconda3/envs/privateGPT/lib/python3.10/site-packages/chromadb/api/local.py", line 408, in _query
    uuids, distances = self._db.get_nearest_neighbors(
  File "/Users/51pwn/anaconda3/envs/privateGPT/lib/python3.10/site-packages/chromadb/db/clickhouse.py", line 583, in get_nearest_neighbors
    uuids, distances = index.get_nearest_neighbors(embeddings, n_results, ids)
  File "/Users/51pwn/anaconda3/envs/privateGPT/lib/python3.10/site-packages/chromadb/db/index/hnswlib.py", line 230, in get_nearest_neighbors
    raise NoIndexException(
chromadb.errors.NoIndexException: Index not found, please create an instance before querying
···

**Comment by imartinez** [comment]
You probably didn't go through the "ingest" step, or the ingest didn't finish correctly. Run the ingest again and make sure a db folder with a subfolder and contents is created by that process. Then you can run privateGPT.py

**Comment by ottlinger** [comment]
Thanks, I repeated the ingestion and this fixed the issue for me. Same with you @hktalent ?

**Comment by hktalent** [comment]
try:
```
python ingest.py
$ find db
db
db/chroma-embeddings.parquet
db/index
db/index/uuid_to_id_48798f7b-74a2-43d8-8e33-6e52bf3952ce.pkl
db/index/id_to_uuid_48798f7b-74a2-43d8-8e33-6e52bf3952ce.pkl
db/index/index_48798f7b-74a2-43d8-8e33-6e52bf3952ce.bin
db/index/index_metadata_48798f7b-74a2-43d8-8e33-6e52bf3952ce.pkl
db/chroma-collections.parquet
```
now
```
llama_print_timings:        load time =  2760.40 ms
llama_print_timings:      sample time =     0.00 ms /     1 runs   (    0.00 ms per run)
llama_print_timings: prompt eval time =  5753.98 ms /    32 tokens (  179.81 ms per token)
llama_print_timings:        eval time =   130.25 ms /     1 runs   (  130.25 ms per run)
llama_print_timings:       total time =  5899.54 ms
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'
gpt_tokenize: unknown token '�'

 I do not know the answer as I am a machine learning model and do not have the capability to process human language or emotions. I am a language model trained on a vast amount of text data, and I am designed to provide general information, factual, or general knowledge based on my programming and data. If you need specific assistance with a human task or want a real person to talk to, I suggest contacting a live customer service representative for further assistance.

```

**Comment by dennydream** [comment]
I ran into the same problem after trying a few things.  Loaded 2 SEC filings-- had issues answering questions.  Then tried loading Alice in Wonderland from the Gutenberg site.  Loaded fine, asked a few questions.  Then one question it appeared to run out of memory.  closed down a few kernels in jupyter, then ran command line again and got this error.

**Comment by hktalent** [comment]
Give up decisively, don't waste your life
