### ISSUE TITLE
 pip install error

### ISSUE THREAD

**Issue by lvlongtao** [imartinez/privateGPT#650]
cmd:ARCHFLAGS="-arch x86_64" pip install -r requirements.txt

Installing collected packages: typing-inspect, scipy, rich, pytz-deprecation-shim, python-dateutil, pydantic, pandoc, numexpr, msg-parser, marshmallow, lxml, llama-cpp-python, joblib, jinja2, imapclient, idna, httptools, hnswlib, h11, greenlet, fsspec, frozenlist, filelock, et-xmlfile, deprecated, colorclass, click, charset-normalizer, chardet, cffi, certifi, beautifulsoup4, backoff, attrs, async-timeout, yarl, uvicorn, tzlocal, typer, torch, SQLAlchemy, scikit-learn, requests, python-pptx, python-docx, pandas, openpyxl, openapi-schema-pydantic, nltk, marshmallow-enum, cryptography, clickhouse-connect, anyio, aiosignal, watchfiles, torchvision, starlette, posthog, pdfminer.six, msoffcrypto-tool, huggingface-hub, httpcore, gpt4all, dataclasses-json, aiohttp, transformers, langchain, httpx, fastapi, sentence-transformers, argilla, unstructured, chromadb, pcodedmp, oletools, RTFDE, extract-msg
  DEPRECATION: pandoc is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for pandoc ... done
  DEPRECATION: lxml is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for lxml ... error
  error: subprocess-exited-with-error

  × Running setup.py install for lxml did not run successfully.
  │ exit code: 1
  ╰─> [123 lines of output]
      Building lxml version 4.9.2.
      Building without Cython.
      Building against libxml2 2.9.4 and libxslt 1.1.29
      running install
      /Users/lvlongtao/github/privateGPT/venv/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.15-x86_64-cpython-311
      creating build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/_elementpath.py -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/sax.py -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/pyclasslookup.py -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/__init__.py -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/builder.py -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/doctestcompare.py -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/usedoctest.py -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/cssselect.py -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/ElementInclude.py -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      creating build/lib.macosx-10.15-x86_64-cpython-311/lxml/includes
      copying src/lxml/includes/__init__.py -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/includes
      creating build/lib.macosx-10.15-x86_64-cpython-311/lxml/html
      copying src/lxml/html/soupparser.py -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/html
      copying src/lxml/html/defs.py -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/html
      copying src/lxml/html/_setmixin.py -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/html
      copying src/lxml/html/clean.py -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/html
      copying src/lxml/html/_diffcommand.py -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/html
      copying src/lxml/html/html5parser.py -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/html
      copying src/lxml/html/__init__.py -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/html
      copying src/lxml/html/formfill.py -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/html
      copying src/lxml/html/builder.py -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/html
      copying src/lxml/html/ElementSoup.py -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/html
      copying src/lxml/html/_html5builder.py -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/html
      copying src/lxml/html/usedoctest.py -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/html
      copying src/lxml/html/diff.py -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/html
      creating build/lib.macosx-10.15-x86_64-cpython-311/lxml/isoschematron
      copying src/lxml/isoschematron/__init__.py -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/isoschematron
      copying src/lxml/etree.h -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/etree_api.h -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/lxml.etree.h -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/lxml.etree_api.h -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/objectify.pyx -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/etree.pyx -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/public-api.pxi -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/xmlid.pxi -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/cleanup.pxi -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/xslt.pxi -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/xpath.pxi -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/debug.pxi -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/serializer.pxi -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/classlookup.pxi -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/saxparser.pxi -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/objectpath.pxi -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/relaxng.pxi -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/xinclude.pxi -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/iterparse.pxi -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/parser.pxi -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/dtd.pxi -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/apihelpers.pxi -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/xmlerror.pxi -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/readonlytree.pxi -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/extensions.pxi -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/xmlschema.pxi -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/schematron.pxi -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/docloader.pxi -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/nsclasses.pxi -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/parsertarget.pxi -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/xsltext.pxi -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/proxy.pxi -> build/lib.macosx-10.15-x86_64-cpython-311/lxml
      copying src/lxml/includes/xmlerror.pxd -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/includes
      copying src/lxml/includes/c14n.pxd -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/includes
      copying src/lxml/includes/xmlschema.pxd -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/includes
      copying src/lxml/includes/__init__.pxd -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/includes
      copying src/lxml/includes/schematron.pxd -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/includes
      copying src/lxml/includes/tree.pxd -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/includes
      copying src/lxml/includes/uri.pxd -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/includes
      copying src/lxml/includes/etreepublic.pxd -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/includes
      copying src/lxml/includes/xpath.pxd -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/includes
      copying src/lxml/includes/htmlparser.pxd -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/includes
      copying src/lxml/includes/xslt.pxd -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/includes
      copying src/lxml/includes/config.pxd -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/includes
      copying src/lxml/includes/xmlparser.pxd -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/includes
      copying src/lxml/includes/xinclude.pxd -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/includes
      copying src/lxml/includes/dtdvalid.pxd -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/includes
      copying src/lxml/includes/relaxng.pxd -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/includes
      copying src/lxml/includes/lxml-version.h -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/includes
      copying src/lxml/includes/etree_defs.h -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/includes
      creating build/lib.macosx-10.15-x86_64-cpython-311/lxml/isoschematron/resources
      creating build/lib.macosx-10.15-x86_64-cpython-311/lxml/isoschematron/resources/rng
      copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/isoschematron/resources/rng
      creating build/lib.macosx-10.15-x86_64-cpython-311/lxml/isoschematron/resources/xsl
      copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/isoschematron/resources/xsl
      copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/isoschematron/resources/xsl
      creating build/lib.macosx-10.15-x86_64-cpython-311/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.macosx-10.15-x86_64-cpython-311/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      running build_ext
      building 'lxml.etree' extension
      creating build/temp.macosx-10.15-x86_64-cpython-311
      creating build/temp.macosx-10.15-x86_64-cpython-311/src
      creating build/temp.macosx-10.15-x86_64-cpython-311/src/lxml
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -arch x86_64 -DCYTHON_CLINE_IN_TRACEBACK=0 -I/usr/include/libxml2 -Isrc -Isrc/lxml/includes -I/Users/lvlongtao/github/privateGPT/venv/include -I/usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c src/lxml/etree.c -o build/temp.macosx-10.15-x86_64-cpython-311/src/lxml/etree.o -w -flat_namespace
      src/lxml/etree.c:192174:60: error: incompatible function pointer types passing 'void (void *, void *, const xmlChar *)' (aka 'void (void *, void *, const unsigned char *)') to parameter of type 'xmlHashScanner' (aka 'void (*)(void *, void *, unsigned char *)') [-Wincompatible-function-pointer-types]
        xmlHashScan(__pyx_v_self->__pyx_base._xpathCtxt->nsHash, __pyx_f_4lxml_5etree__registerExsltFunctionsForNamespaces, __pyx_v_self->__pyx_base._xpathCtxt);
                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/libxml/hash.h:210:22: note: passing argument to parameter 'f' here
                                               xmlHashScanner f,
                                                              ^
      1 error generated.
      Compile failed: command '/usr/local/opt/llvm/bin/clang' failed with exit code 1
      creating var
      creating var/folders
      creating var/folders/0s
      creating var/folders/0s/dcn9v03s031f6qs6t5whb7c80000gp
      creating var/folders/0s/dcn9v03s031f6qs6t5whb7c80000gp/T
      cc -arch x86_64 -I/usr/include/libxml2 -I/usr/include/libxml2 -c /var/folders/0s/dcn9v03s031f6qs6t5whb7c80000gp/T/xmlXPathInitp8sr00yd.c -o var/folders/0s/dcn9v03s031f6qs6t5whb7c80000gp/T/xmlXPathInitp8sr00yd.o
      cc -arch x86_64 var/folders/0s/dcn9v03s031f6qs6t5whb7c80000gp/T/xmlXPathInitp8sr00yd.o -lxml2 -o a.out
      error: command '/usr/local/opt/llvm/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lxml

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip

Note: if you'd like to *ask a question* or *open a discussion*, head over to the [Discussions](https://github.com/imartinez/privateGPT/discussions) section and post it there.

**Describe the bug and how to reproduce it**
A clear and concise description of what the bug is and the steps to reproduce the behavior.

**Expected behavior**

**Environment (please complete the following information):**
 - OS / hardware: [e.g. macOS 12.6 / M1]
 - Python version [e.g. 3.11.3]
- Other relevant information

**Additional context**

**Comment by lvlongtao** [comment]
STATIC_DEPS=true sudo pip install lxml

solved

**Comment by FuckReally** [comment]
> 
I ran it get a new error:PermissionError: [Errno 1] Operation not permitted
