### ISSUE TITLE
no output for me after asking question 

### ISSUE THREAD

**Issue by ghost** [imartinez/privateGPT#652]
> Enter a query:
explain me about the docs talk?

and after that it look like its freezen, no ouput i waited for more then 5 minute and nothing

**Comment by SharinganKazekage** [comment]
now i got killed after 10 minute of wait

**Comment by twjjack** [comment]
I got the same issue. 

This is my value in .env
!sed -i 's/n_gpu_layers=10' /content/privateGPT/.env 
!sed -i 's/MODEL_TYPE=GPT4All' /content/privateGPT/.env 
!sed -i 's/ggml-gpt4all-j-v1.3-groovy.bin' /content/privateGPT/.env 

This is my GPU setting in Colab. 
![image](https://github.com/maozdemir/privateGPT-colab/assets/30719970/409eb7b8-b6c3-4a38-bd1f-d5121bf88bce)

**Comment by sazdg** [comment]
Same issue!
