### ISSUE TITLE
Can I change the source_documents location

### ISSUE THREAD

**Issue by ChapmanKU** [imartinez/privateGPT#655]
Is it possible to change the source documents location, to, for example a NAS folder containing all my PDFs?

**Comment by diamondbarcode** [comment]
i was wondering too there trick to link folder not sure if that work i do not test .. but i know if your documents using unicode it give error .. so far it does not understand other language well English seem only thing it know

**Comment by melroy89** [comment]
Lol.. That might be not ideal.. The whole point of a environment variable, is to actually use this variable in the terminal.

You can set this variable using Bash using: 

```
export SOURCE_DIRECTORY=/some/folder/path
```

After which you can try to execute the python script, without the need to change the code..... 

Depending on your operating system and your NAS solution, you might need to mount this remote locally first. So you can provide the `SOURCE_DIRECTORY` variable a path to an actual folder on your local system.

**Comment by DjToMeK30** [comment]
Yes, that is why I said he can change system env first...
But sometimes you don't want to do that or don't need it if you want to quickly check if it works and then set env variable when you are actually sure
