### ISSUE TITLE
Mac M1芯片 ，安装依赖时候报错RROR: Failed building wheel for grpcio

### ISSUE THREAD

**Issue by denganhui** [imartinez/privateGPT#656]
Note: if you'd like to *ask a question* or *open a discussion*, head over to the [Discussions](https://github.com/imartinez/privateGPT/discussions) section and post it there.

**Describe the bug and how to reproduce it**
A clear and concise description of what the bug is and the steps to reproduce the behavior.

**Expected behavior**

**Environment (please complete the following information):**
 - OS / hardware: [e.g. macOS 1  M1]
 - Python version [e.g. 3.10]
- Other relevant information

**Additional context**
安装依赖时候报错RROR: Failed building wheel for grpcio

后来调整为，1.54.0 ，OK
pip3 install  grpcio==1.54.0

**Comment by yudidi** [comment]
Does mac m1 16g can run this repo?
