### ISSUE TITLE
我想让他回答中文 但是字符长度限制了他 我该如何解决 这个字符长度限制问题 

### ISSUE THREAD

**Issue by TopZxx** [imartinez/privateGPT#670]
> Question:
铜便士

> Answer:
ERROR: The prompt size exceeds the context window size and cannot be processed.

**Comment by TopZxx** [comment]
I want him to answer Chinese but the character length limits him, how do I solve this character length limit problem?

**Comment by TopZxx** [comment]
gptj_model_load: loading model from 'models/ggml-gpt4all-j-v1.3-groovy.bin' - please wait ...
gptj_model_load: n_vocab = 50400
gptj_model_load: n_ctx   = 2048
gptj_model_load: n_embd  = 4096
gptj_model_load: n_head  = 16
gptj_model_load: n_layer = 28
gptj_model_load: n_rot   = 64
gptj_model_load: f16     = 2
gptj_model_load: ggml ctx size = 5401.45 MB
gptj_model_load: kv self size  =  896.00 MB
gptj_model_load: ................................... done
gptj_model_load: model size =  3609.38 MB / num tensors = 285

Enter a query: 铜便士
ERROR: The prompt size exceeds the context window size and cannot be processed.GPT-J ERROR: The prompt is4568tokens and the context window is2048!

ERROR: The prompt size exceeds the context window size and cannot be processed.

> Question:
铜便士

> Answer:
ERROR: The prompt size exceeds the context window size and cannot be processed.

**Comment by TopZxx** [comment]
gptj_model_load: loading model from 'models/ggml-gpt4all-j-v1.3-groovy.bin' - please wait ...
gptj_model_load: n_vocab = 50400
gptj_model_load: n_ctx   = 2048
gptj_model_load: n_embd  = 4096
gptj_model_load: n_head  = 16
gptj_model_load: n_layer = 28
gptj_model_load: n_rot   = 64
gptj_model_load: f16     = 2
gptj_model_load: ggml ctx size = 5401.45 MB
gptj_model_load: kv self size  =  896.00 MB
gptj_model_load: ................................... done
gptj_model_load: model size =  3609.38 MB / num tensors = 285

Enter a query: 铜便士
ERROR: The prompt size exceeds the context window size and cannot be processed.GPT-J ERROR: The prompt is4568tokens and the context window is2048!

ERROR: The prompt size exceeds the context window size and cannot be processed.

> Question:
铜便士

> Answer:
ERROR: The prompt size exceeds the context window size and cannot be processed.

**Comment by jarryidle** [comment]
It doesn't support Chinese.

**Comment by TopZxx** [comment]
think you very much&nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "imartinez/privateGPT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月12日(星期一) 上午8:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [imartinez/privateGPT] 我想让他回答中文 但是字符长度限制了他 我该如何解决 这个字符长度限制问题  (Issue #670)





 
It doesn't support Chinese.
