### ISSUE TITLE
Speed issues on prompt - what can be done to improve this?

### ISSUE THREAD

**Issue by InfamyStudio** [imartinez/privateGPT#673]
Hi all,

Just to get started I love the project and it is a great starting point for me in my journey of utilising LLM's. We are looking to integrate this sort of system in an environment with around 1TB data at any running instance, and just from initial testing on my main desktop which is running Windows 10 with an I7 and 32GB RAM. I am noticing that ingest times are not too bad and would be expected to take a while, but this is not the case. Upon actually writing a prompt the generation time is around 2-3 minutes depending on the query and this is just deathly slow.

What can be done to speed up this process, does the code need rewriting for better optimization? The different models used? Or what are the recommended hardware specs, at my org we can spin up any sort of machine with any specs so what would be ideal to reach around a 10-second prompt response time?

**Comment by StephenDWright** [comment]
You can get faster inference using GPU offloading. llama.cpp now supports a mix of using CPU and GPU. Even langchain mentions it. That will significantly speed up inference.

**Comment by InfamyStudio** [comment]
> You can get faster inference using GPU offloading. llama.cpp now supports a mix of using CPU and GPU. Even langchain mentions it. That will significantly speed up inference.

Are there any pull requests showcasing this, or anymore information you can provide on implementing this. I have seen a few comments about changing the backend used with your model.

**Comment by StephenDWright** [comment]
> > You can get faster inference using GPU offloading. llama.cpp now supports a mix of using CPU and GPU. Even langchain mentions it. That will significantly speed up inference.
> 
> Are there any pull requests showcasing this, or anymore information you can provide on implementing this. I have seen a few comments about changing the backend used with your model.

There is a pull request in this repo regarding using GPU and this is where similar information is referenced in the langchain docs. 

https://python.langchain.com/en/latest/modules/models/llms/integrations/llamacpp.html
