### ISSUE TITLE
Not understandable responses with n_gpu_layers

### ISSUE THREAD

**Issue by jonyeecoder** [imartinez/privateGPT#674]
i was able to get proper understandable english responses in its original state
after enabling privategpt with gpu acceleration, i got response that was not understandable in english when using n_gpu_layers

anyhow encountered this issue before?
will be great to know the solution

Thanks.

**Comment by SH1436** [comment]
I could try to replicate your issue and explore possible solutions.
How did you implement the use of GPU?
