### ISSUE TITLE
Not getting response in english

### ISSUE THREAD

**Issue by VikashChauhan51** [imartinez/privateGPT#676]
Note: if you'd like to *ask a question* or *open a discussion*, head over to the [Discussions](https://github.com/imartinez/privateGPT/discussions) section and post it there.

**Describe the bug and how to reproduce it**
The privateGPT returns characters combination response like strong password instead of actual content in English. Please refer attached screenshot from more information.

**Expected behavior**
The privateGPT should return response in English.

**Environment (please complete the following information):**
 - OS / hardware: [e.g. window 11 / 16 GM RAM 2.42 GHz]
 - Python version [e.g. 3.10.4]
- Other relevant information

**Additional context**
Please check this output console window screenshot:
![image](https://github.com/imartinez/privateGPT/assets/14816038/97ded7a9-59f8-4069-bc1d-2b759304b85f)

**Comment by zibberzoo** [comment]
Same problem here.  The output is a stream of characters.  Oddly, the stream is limited to the characters following the colon:    C G ; 7 +
