### ISSUE TITLE
ERROR: No matching distribution found for gpt4all==0.2.3

### ISSUE THREAD

**Issue by sucat1997** [imartinez/privateGPT#680]
Note: if you'd like to *ask a question* or *open a discussion*, head over to the [Discussions](https://github.com/imartinez/privateGPT/discussions) section and post it there.

**Describe the bug and how to reproduce it**
pip3 install bug, no matching distribution found for gpt4all==0.2.3 

**Expected behavior**
X:\project_work_space\privateGPT-main\privateGPT-base>pip3 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting langchain==0.0.177 (from -r requirements.txt (line 1))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/e6/2a/b108911383cbebe658208e771de45663d7ce0b851315d9825bd73e816550/langchain-0.0.177-py3-none-any.whl (877 kB)
     ---------------------------------------- 877.7/877.7 kB 3.7 MB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement gpt4all==0.2.3 (from versions: 0.1.5, 0.1.6, 0.1.7)
ERROR: No matching distribution found for gpt4all==0.2.3

And then pip3 install is stop

**Environment (please complete the following information):**
 - OS / hardware: [e.g. win10 / i7-11700]
 - Python version [e.g. 3.10.10]
- Other relevant information

**Additional context**

**Comment by sucat1997** [comment]
sorry, but just can't download it.
![UC2TRN2_@NK$D~DP30MG5(8](https://github.com/imartinez/privateGPT/assets/45302883/8a8849ca-1169-4206-acd4-0ef6689c084f)
![H%%W49MRS@L98OWMQUNDUIT](https://github.com/imartinez/privateGPT/assets/45302883/55a4a60f-a034-431b-8560-8916503fb8a6)

**Comment by sucat1997** [comment]
INFO: pip is looking at multiple versions of sentence-transformers to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement torch>=1.6.0 (from sentence-transformers) (from versions: none)
ERROR: No matching distribution found for torch>=1.6.0

我从网上了解到这个问题需要降低python版本至3.8来解决，而privateGPT.py中有一个写法是3.10的，呃呃
I learned online that this issue needs to be resolved by lowering the Python version to 3.8, and there is a writing method in privateGPT.py that is 3.10, emmm....

**Comment by thanhtantran** [comment]
It seems that you are running on an ARM machine, with ARM the gpt4all cannot be greater than 0.17

Use X86 machine instead

**Comment by thanhtantran** [comment]
Upgrade your python to 3.10 and pip

**Comment by sucat1997** [comment]
This problem was resolved after I discovered that my Python 10.10 is 32-bit

My fault
