### ISSUE TITLE
Support custom sentence-transformer models

### ISSUE THREAD

**Issue by underlines** [imartinez/privateGPT#681]
According to the Massive Text Embedding Benchmark (MTEB) Leaderboard there are many better sentence-transformers models available:

https://huggingface.co/spaces/mteb/leaderboard

It would be great to have support for bring your own sentence-transformer. Some great SOTA models currently are:

https://huggingface.co/embaas/sentence-transformers-e5-large-v2
https://huggingface.co/sentence-transformers/sentence-t5-xxl
https://huggingface.co/embaas/sentence-transformers-multilingual-e5-base

And support to load them automatically within the sentence-transformer library as simple as:
```
from sentence_transformers import SentenceTransformer
sentences = ["This is an example sentence", "Each sentence is converted"]

model = SentenceTransformer('sentence-transformers/sentence-t5-xxl')
embeddings = model.encode(sentences)
print(embeddings)
```

**Comment by darksheer** [comment]
+1 to this.  Testing with different embeddings would be a nice feature to have.
