### ISSUE TITLE
ingest.py fails due to a server timeout

### ISSUE THREAD

**Issue by luciph0r** [imartinez/privateGPT#689]
**Describe the bug and how to reproduce it**
Script fails trying to connect to cdn-lfs.huggingface.co. 

**Environment (please complete the following information):**
 - OS / hardware: Linux Mint 21.1
 - Python version 3.10.6
  ```
for chunk in r.iter_content(chunk_size=10 * 1024 * 1024):
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 822, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.
```

**Comment by kyxap** [comment]
I don't think people from this repo managing that host (but could be wrong). Anyway just configured locally and everything was fine so could be issue on your end (slow connection) or issue is resolved, try again.

**Comment by saravr** [comment]
Must be a client side issue. After disconnecting VPN it worked for me.
