### ISSUE TITLE
ingest.py and privateGPT.py does nothing

### ISSUE THREAD

**Issue by miroworks** [imartinez/privateGPT#694]
Hi there,
i use a vps for privateGPT (8 vcores, 32gb ram) but if i start the ingest.py or privateGPT.py there is nothing. No message, just nothing. All i can do is to stop the script with CTRL+X. 

I installed everything like it should (pip3 requirements + models folder with .bin file + .env). Its scary cause the script keeps running and just nothing happen. 

Can someone help me? Thanks alot!

**Comment by supmind** [comment]
me too， get nothing output

**Comment by supmind** [comment]
> i found out that this line of code runs forever:
> 
> embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name)
> 
> embeddings_model_name is all-MiniLM-L6-v2

seams  like cant download file from HuggingFace
