### ISSUE TITLE
Giving responses on general queries also from internet. Why it wont be restricted towards the PDF I have provided?

### ISSUE THREAD

**Issue by akashlinux10may** [imartinez/privateGPT#696]
Giving responses on general queries also from internet. Why it wont be restricted towards the PDF I have provided?

DB folder contain the index but it will also answer out of the knowledge base queries. How it would get restricted towards only the knowledge base?

**Comment by darrinh** [comment]
I've noticed this as well, hallucinations when I guess there is not enough context. For example, I have added some docs and asked about somebody in the docs, out of the four document references it provided, the first one was talking about a character from The Sims, which has a similar name to my query but not the same. I think its import to also frame the question in a way to help provide context.

**Comment by boral** [comment]
I think it is not from internet but from trained model. Even if you cut off internet, you will get same response.
