### ISSUE TITLE
How to fix this error after tried to embed my text file? Traceback (most recent call last):   File "privateGPT\ingest.py", line 22, in <module>

### ISSUE THREAD

**Issue by stevevaius2015** [imartinez/privateGPT#7]
I received this error after trying to embed my text data which is [[here](https://file.io/T5HskeMm6PjH)](url)
Error here [https://pastebin.com/BjaW6XpN](url)

How can I fix this error?

**Comment by imartinez** [comment]
Apparently `CharacterTextSplitter` is creating the issue, according to this comment https://github.com/imartinez/privateGPT/commit/92244a90b4ef094481ffcefb2e8a1ebdbbcd110d#commitcomment-112336983

You can try to change it to `RecursiveCharacterTextSplitter`. If it works for you, please feel free to open a PR. Thanks!

**Comment by imartinez** [comment]
Fixed in https://github.com/imartinez/privateGPT/commit/026b9f895cfb727da523a20c59773146801236ba

**Comment by stevevaius2015** [comment]
Thanks its working now but takes too much time.
