### ISSUE TITLE
 [Errno 2] No such file or directory: 'D:\\AI\\PrivateGPT\\privateGPT\\pydantic\\main.py'

### ISSUE THREAD

**Issue by Saahil-exe** [imartinez/privateGPT#703]
How to solve this?

Using embedded DuckDB with persistence: data will be stored in: db
Found model file at  models/ggml-gpt4all-j-v1.3-groovy (2).bin
Invalid model file
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ d:\AI\PrivateGPT\privateGPT\privateGPT.py:82 in <module>                                         │
│                                                                                                  │
│   79                                                                                             │
│   80                                                                                             │
│   81 if __name__ == "__main__":                                                                  │
│ ❱ 82 │   main()                                                                                  │
│   83                                                                                             │
│                                                                                                  │
│ d:\AI\PrivateGPT\privateGPT\privateGPT.py:38 in main                                             │
│                                                                                                  │
│   35 │   │   case "LlamaCpp":                                                                    │
│   36 │   │   │   llm = LlamaCpp(model_path=model_path, n_ctx=model_n_ctx, n_batch=model_n_bat    │
│   37 │   │   case "GPT4All":                                                                     │
│ ❱ 38 │   │   │   llm = GPT4All(model=model_path, n_ctx=model_n_ctx, backend='gptj', n_batch=m    │
│   39 │   │   case _default:                                                                      │
│   40 │   │   │   print(f"Model {model_type} not supported!")                                     │
│   41 │   │   │   exit;                                                                           │
│                                                                                                  │
│ D:\AI\PrivateGPT\privateGPT\pydantic\main.py:341 in pydantic.main.BaseModel.__init__             │
│                                                                                                  │
│ [Errno 2] No such file or directory: 'D:\\AI\\PrivateGPT\\privateGPT\\pydantic\\main.py'         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValidationError: 1 validation error for GPT4All
__root__
  Unable to instantiate model (type=value_error)

**Comment by Galigator** [comment]
I think the true error is the message bellow this one. Maybe you should configure the model path in example.env .
