### ISSUE TITLE
Update to allow a change in the number of threads available for use.

### ISSUE THREAD

**Issue by FearTheBadger** [imartinez/privateGPT#710]
**Is your feature request related to a problem? Please describe.**
I have more than the default number of threads (4) available for processing. I'd like to be able to use those extra threads.

**Describe the solution you'd like**
Add `n_threads` to the `llm` variable.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by TahirAhmadov** [comment]
I second this. The query response time is way too long and I could see that most of the cores are idle except for a few.
