### ISSUE TITLE
JSON Support

### ISSUE THREAD

**Issue by ekomsctr** [imartinez/privateGPT#713]
Hello there,

first of all great project! It has serious potential into business application development in my opinion!

I was wondering if this has support (or even the potential) to elaborate .json documents, and if yes, would we able to do "querying" with natural language on records (e.g. 1 source file = 1 record) based on the json object metadata? I'm asking this because i'm still kinda new to the AI world (so any explanation is very welcome).

Very much thanks in advance :)

**Comment by AISIS7** [comment]
I want to know the same.
