### ISSUE TITLE
source docs don't seem to correspond to answer

### ISSUE THREAD

**Issue by vnevoa** [imartinez/privateGPT#716]
**Describe the bug and how to reproduce it**
Ingested 1047 different PDF files (4GB). The db folder occupies around 700MB.
Made several unrelated queries, with subjects exclusive to different source files.
The answers seem ok, but **it always exhibits the same sources for every query**, even when those sources have zero relation to the query context.

**Expected behavior**
I'd expect to get the source document and chunk/page that is related to the content that was used to build the reply to the query.

**Environment (please complete the following information):**
 - OS / hardware: Ubuntu 22.04 / Ryzen 5700G 32GB
 - Python version 3.10.6

**Additional context**

.env file:
PERSIST_DIRECTORY=db
MODEL_TYPE=GPT4All
MODEL_PATH=models/ggml-gpt4all-j-v1.3-groovy.bin
EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
MODEL_N_CTX=1000
MODEL_N_BATCH=8
TARGET_SOURCE_CHUNKS=10

The default value of TARGET_SOURCE_CHUNKS also exhibits the same behavior.
The ingest process was repeated multiple times over the same PDF set, due to process exceptions.
Some of the PDFs (6 of them) are image-only scans, resulting in empty chunks of text.

**Comment by annetre** [comment]
I have the same behavior.
