### ISSUE TITLE
Feature Request: Support for Chinese Language

### ISSUE THREAD

**Issue by WingkitChou** [imartinez/privateGPT#717]
I am enjoying the functionality of this program, however, as a native Chinese speaker, I am limited to asking questions and inputting documents in English. This presents a challenge for me, as I have a number of Chinese documents I'd like to ingest and questions I'd like to ask in Chinese.

**Comment by FearTheBadger** [comment]
I don't think this program would have any way of fulfilling your request. I could be wrong but I assume that the language accepted is based on the model used to parse the data. All this does is take a model you download and apply it to your defined set of documents. You'd have to find a model that understands the language you are giving it.

**Comment by Dragon1573** [comment]
I don't have enough physical memory launching `privateGPT.py`, but I successfully ingested Simplified Chinese `*.pdf` documents on my device.

I think it might be similar to ChatPDF? You can ingest non-English documents on ChatPDF, sometimes ask questions in Simplified Chinese, but receive responses only in English.
