### ISSUE TITLE
Not reading eml files

### ISSUE THREAD

**Issue by peterchanws** [imartinez/privateGPT#721]
**Describe the bug and how to reproduce it**
I put 16 eml files in the source_documents folder.  execute python ingest.py. errors appear:
Traceback (most recent call last):
  File "/Users/pchan3/Desktop/privateGPT/ingest.py", line 49, in load
    doc = UnstructuredEmailLoader.load(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pchan3/miniconda3/lib/python3.11/site-packages/langchain/document_loaders/unstructured.py", line 70, in load
    elements = self._get_elements()
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/pchan3/miniconda3/lib/python3.11/site-packages/langchain/document_loaders/email.py", line 24, in _get_elements
    return partition_email(filename=self.file_path, **self.unstructured_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pchan3/miniconda3/lib/python3.11/site-packages/unstructured/partition/email.py", line 249, in partition_email
    raise ValueError(f"{content_source} content not found in email")
ValueError: text/html content not found in email
  

**Expected behavior**
Expect splitting the eml files

**Environment (please complete the following information):**
 - OS / hardware: [macOS 12.6.6 / Xeon E5]
 - Python version [3.11.3]
- Other relevant information

**Additional context**
Content of 1 eml file:

Status: R
Subject: RE:
From: "Jeb Bush" <jeb@jeb.org>
Date: Mon, 08 Nov 1999 18:16:32 -0800
To: "'Dana, Pamella'" <danap@eog.state.fl.us>
Message-ID: <118b72a4a32586c8015f3bb3096258d8@converter.generated.id>
In-Reply-To: <32F64A7C8687D3118A100004ACE6E2D215C9D9@govexch.eog.state.fl.us>
X-Priority: 3 (Normal)
Importance: Normal
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: binary
X-Converted-By: Emailchemy 11.3.5 Forensic Edition; licensedTo="Stanford University Libraries"

xxxxxxxxxxxxxx

 -----Original Message-----
From: 	Dana, Pamella [mailto:DanaP@eog.state.fl.us] 
Sent:	Monday, November 08, 1999 4:39 PM
To:	'jeb@jeb.org'
Subject:	

 << File: Eglinhanger.doc >> <<Eglinhanger.doc>> 

xxxxxxxxxxxxxxx

**Comment by unalignedcoder** [comment]
better delete that email body. none of our business who you were exchanging emails with.

**Comment by peterchanws** [comment]
email content deleted as per your request
