### ISSUE TITLE
warning: Unable to connect optimized C data functions [No module named '_testbuffer'], falling back to pure Python

### ISSUE THREAD

**Issue by aaronmarkham** [imartinez/privateGPT#723]
**Describe the bug and how to reproduce it**
I get this warning both during embeddings creation and running the model. 
```
Unable to connect optimized C data functions [No module named '_testbuffer'], falling back to pure Python
```

**Expected behavior**
Maybe things would run faster if it could find what it is looking for.

**Environment (please complete the following information):**
 - OS / hardware: Windows 10 Home
 - Python version: 3.11

Already had MinGW installed and gcc is selected (mingw32-gcc-bin). Assuming this is what the readme is referring to.

**Comment by gtdas** [comment]
I am getting this error while running the model python privateGPT.py. Anyone find a solution please let me know. thanks

**Comment by arkhub** [comment]
> Had similar issue, found that downgrading the clickhouse-connect package version solved it for me. `pip install --upgrade clickhouse-connect==0.5.22`

this one solves the issues for me in windows, thanks.

**Comment by rdyers** [comment]
Excellent. Thank you. `pip install --upgrade clickhouse-connect==0.5.22`
worked for me too.

**Comment by catbears** [comment]
Seems like clickhouse-connect got fixed. Using the latest version fixed it for me.

**Comment by jogi1004** [comment]
> Had similar issue, found that downgrading the clickhouse-connect package version solved it for me. `pip install --upgrade clickhouse-connect==0.5.22`

Had to add "--user" because of restrictions but it worked for me. Thanks!

**Comment by cosinus90** [comment]
Ubuntu 18.04.6 LTS
Python 3.7.5
clickhouse_connect Version: 0.5.22 and Version: 0.6.23


Still getting

`
Unable to connect optimized C data functions [No module named 'clickhouse_connect.driverc.buffer'], falling back to pure Python
Unable to connect ClickHouse Connect C to Numpy API [No module named 'clickhouse_connect.driverc.npconv'], falling back to pure Python
Traceback (most recent call last):
  File "sync-subscriptions.py", line 1, in <module>
    import clickhouse_connect
  File "/usr/local/lib/python3.8/dist-packages/clickhouse_connect/__init__.py", line 1, in <module>
    from clickhouse_connect.driver import create_client
  File "/usr/local/lib/python3.8/dist-packages/clickhouse_connect/driver/__init__.py", line 9, in <module>
    from clickhouse_connect.driver.httpclient import HttpClient
  File "/usr/local/lib/python3.8/dist-packages/clickhouse_connect/driver/httpclient.py", line 20, in <module>
    from clickhouse_connect.driver.compression import available_compression
  File "/usr/local/lib/python3.8/dist-packages/clickhouse_connect/driver/compression.py", line 5, in <module>
    import lz4
  File "/usr/local/lib/python3.8/dist-packages/lz4/__init__.py", line 14, in <module>
    from ._version import (  # noqa: F401
ModuleNotFoundError: No module named 'lz4._version'
`
