### ISSUE TITLE
【Invalid model file】gpt4all upgraded to 0.3.4, but the problem still exists

### ISSUE THREAD

**Issue by watchmen1992** [imartinez/privateGPT#724]
![image](https://github.com/imartinez/privateGPT/assets/28006018/6080a011-7554-47a9-97f5-1fd72ee276b5)
gpt4all upgraded to 0.3.4, but the problem still exists

OS：debian 10.3
python：3.10.10

This is the configuration of the. env file
![image](https://github.com/imartinez/privateGPT/assets/28006018/df15e4f6-941d-4ac8-a98e-c898632b578f)

**Comment by watchmen1992** [comment]
<img width="593" alt="image" src="https://github.com/imartinez/privateGPT/assets/28006018/3f24cc1e-cf0f-48dc-a7ad-dd33425baf66">

**Comment by watchmen1992** [comment]
@imartinez @ivan-ontruck

**Comment by lemig** [comment]
This is currently an open issue in gpt4all see: https://github.com/nomic-ai/gpt4all/issues/866
