### ISSUE TITLE
No matching distribution found for gpt4all==0.3.4

### ISSUE THREAD

**Issue by wsimon98** [imartinez/privateGPT#729]
Note: if you'd like to *ask a question* or *open a discussion*, head over to the [Discussions](https://github.com/imartinez/privateGPT/discussions) section and post it there.

**Describe the bug and how to reproduce it**
Cannot run the pip3 install -r requirements.txt

**Expected behavior**
get error regarding GPT4ALL:

ERROR: Could not find a version that satisfies the requirement gpt4all==0.3.4 (from versions: 0.1.5, 0.1.6, 0.1.7)
ERROR: No matching distribution found for gpt4all==0.3.4

**Environment (please complete the following information):**
 - OS / hardware:Windows 2019
 - Python version pip 23.1.2 from C:\Program Files (x86)\Python310-32\lib\site-packages\pip (python 3.10)

**Comment by Pipeliner** [comment]
It seems that gpt4all==0.3.4 is not available for aarch64 Linux (wheels are not built). 0.1.7 installs fine but I'm not sure yet if it works.

**Comment by Pipeliner** [comment]
gpt4all can be built locally: https://github.com/nomic-ai/gpt4all/blob/main/gpt4all-bindings/python/README.md
I get `pydantic.error_wrappers.ValidationError: 1 validation error for GPT4All` though this seems to be a known issue.

**Comment by leandro-jm** [comment]
Same problem when running the command:

```
~/privateGPT# pip install -r requirements.txt
Collecting langchain==0.0.197
  Using cached langchain-0.0.197-py3-none-any.whl (1.0 MB)
ERROR: Could not find a version that satisfies the requirement gpt4all==0.3.4 (from versions: 0.1.5, 0.1.6, 0.1.7)
ERROR: No matching distribution found for gpt4all==0.3.4
```

Below my setup. 

MacBook Air M2 
- MacOS Ventura 13.0.1 

Docker version 23.0.5:
- Ubuntu 22.04.2 LTS  (Jammy Jellyfish)
- Python 3.10.6
- pip 22.0.2

Obs: I used as guide the article: https://github.com/imartinez/privateGPT

**Comment by M0E-lnx** [comment]
I'm getting this error on AMD64 also when running ``pip3 install -r requirements.txt``

``No matching distribution found for gpt4all==0.3.4``

**Comment by billybahlah1976** [comment]
I managed to build my own, hope it helps

https://documentingthings.wordpress.com/2023/07/10/chatgpt-x-raspberry-pi/
