### ISSUE TITLE
Source documents

### ISSUE THREAD

**Issue by pitosalas** [imartinez/privateGPT#741]
What happens if I put a file in source_documents which doesn't have any of the supported file extensions?

Is there a way to tell the model to "forget" a file that it has ingested?

Right now the model is generating gibberish:

<img width="328" alt="Screenshot 2023-06-19 at 11 02 10 AM" src="https://github.com/imartinez/privateGPT/assets/44681/83d2ff0a-3a47-4fe5-a995-cee35d767891">

**Comment by lystrata** [comment]
I found the removing the db directory (and its contents) and recreating it -- will get you back to a blank canvas. The db directory contents are created dynamically on the ingest.

**Comment by nednones** [comment]
I have a similiar problem. I built an API to add documents dynamically and to call the ingest main function which processes new added documents but does not seem to correspond when running the prompt script to query the information inside
