### ISSUE TITLE
How to increase the output length?

### ISSUE THREAD

**Issue by samarthsarin** [imartinez/privateGPT#746]
Hi,

Thank you for this repo. I just wanted to check that I was able to successfully run the complete code. However I wanted to understand how can I increase the output length of the answer as currently it is not fixed and sometimes the output is too short (70-80 words) and sometimes it is too long (500-600 words). How can I fix the max length or minimum length of the output answer? Is there any parameter I can play with while inferencing?

Thank you

**Comment by silvernailj** [comment]
Same question.  It would also be nice if the prompt, answers, or references were in a different color so that they be easily distinguished.

**Comment by selecta-ufuk** [comment]
https://github.com/imartinez/privateGPT/issues/1243#issuecomment-1819942062
