### ISSUE TITLE
Reached end of context

### ISSUE THREAD

**Issue by Devangkaruskar** [imartinez/privateGPT#748]
when i asked query sometimes it shows like below:

**Enter a query:** can you explain me about Measuring in JOG?
**GPT-J: reached the end of the context window so resizing**

can you please me to understand why this happen?

**Comment by rekab72** [comment]
Same response after several test queries using State of the Union example.
`GPT-J: reached the end of the context window so resizing`
Memory 8.0 GiB
Processor 11th Gen Intel® Core™ i5-1135G7 @ 2.40GHz × 8
Graphics Mesa Intel® Xe Graphics (TGL GT2)
Disk Capacity 768.2 GB
OS Ubuntu 22.04.2 LTS

**Comment by PetreVane** [comment]
@rekab72  you also need to add the serial number from your motherboard, the one starting with CX… because this is essential when solving this bug. If your motherboard serial number does not start with CX … it might be that your computer is incompatible with this program 😐

**Comment by goodpilotfish** [comment]
Same behavior after several queries. 

Running model locally on a MacBook Pro (13-inch, M1, 2020) and the message shows up both for GPT4All and Lama models.

**Comment by samanemami** [comment]
Hi @goodpilotfish 

Could you please share your experience of how you implemented llama please?
It would be so helpful for the community
