### ISSUE TITLE
unable to run ingest.py

### ISSUE THREAD

**Issue by WestB-DEV** [imartinez/privateGPT#750]
As with many interested in this project, I have been following the tutorial here (https://www.youtube.com/watch?v=jxSPx1bfl2M) by Matthew Berman

after running "ingest.py" I keep getting this error

"(privateGPT) (base) thismac@MacBook-Pro privateGPT % /usr/local/bin/python3 /Users/thismac/Desktop/privateGP
T/ingest.py
Traceback (most recent call last):
  File "/Users/thismac/Desktop/privateGPT/ingest.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
(privateGPT) (base) thismac@MacBook-Pro privateGPT % "

been working at this for 2 days now (in between work of course) 

I manually selected python version 3.11 in VS code but it still shows python 3.9 in the terminal occasionally (example "Requirement already satisfied: pip in ./privateGPT/lib/python3.9/site-packages (22.0.4)")

I am runing a Macbook pro M1 Max with 64 GB

**Comment by PetreVane** [comment]
This is not a bug.
The error message indicates that the module named 'dotenv' is not installed in your Python environment. The 'dotenv' module is used to load environment variables from a file, and it seems to be required by the 'ingest.py' script.

To resolve this issue, you need to install the 'dotenv' module. You can do this by running the following command in your terminal or command prompt:

```
pip install python-dotenv
```

Once the installation is complete, try running the 'ingest.py' script again, and it should hopefully work without the 'ModuleNotFoundError' related to 'dotenv'.
