### ISSUE TITLE
terminate called after throwing an instance of 'std::runtime_error'

### ISSUE THREAD

**Issue by BigGiAnts** [imartinez/privateGPT#751]
**Describe the bug and how to reproduce it**

when I run blow command, an error comes out:
python privateGPT.py
Using embedded DuckDB with persistence: data will be stored in: db
llama.cpp: loading model from /data1/privateGPT/models/ggml-gpt4all-j-v1.3-groovy.bin
terminate called after throwing an instance of 'std::runtime_error'
  what():  unexpectedly reached end of file

I setup the envrioment using conda, below is the .envs file for privateGPT:

PERSIST_DIRECTORY=db
MODEL_TYPE=LlamaCpp
MODEL_PATH=/data1/privateGPT/models/ggml-gpt4all-j-v1.3-groovy.bin
EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
MODEL_N_CTX=1000
MODEL_N_BATCH=8
TARGET_SOURCE_CHUNKS=4

**Environment (please complete the following information):**
 - OS / hardware: [e.g. centos7.8 ]
 - Python version [e.g. 3.8.17]
- gcc 9.3.1
- 125G mem
- 37 TB disk
- Intel(R) Xeon(R) Gold 6330 CPU *2; 112 core

**Additional context**
Please let me know if you need more info to solve the bug.
Thank you !

**Comment by darrinh** [comment]
Getting the same error:

Using embedded DuckDB with persistence: data will be stored in: db
llama.cpp: loading model from models/ggml-gpt4all-j-v1.3-groovy.bin
terminate called after throwing an instance of 'std::runtime_error'
  what():  unexpectedly reached end of file
Aborted (core dumped)
