### ISSUE TITLE
KeyboardInterrupt exception handling error

### ISSUE THREAD

**Issue by navneet-28** [imartinez/privateGPT#768]
The privateGPT.py script is unable to handle KeyboardInterrupt exception. On pressing Ctrl+C, it just throws the KeyboardInterrupt exception, but doesn't terminate the session.

**Environment:**
 - OS: Ubuntu 22.04
 - Python version: 3.10.6

**Comment by silvernailj** [comment]
Until they fix it, just type "exit" or modify the following in privateGPT.py

# Interactive questions and answers
while True:
    try:
        query = input("\nEnter a query: ")
    except KeyboardInterrupt:
        print("\nProgram interrupted. Exiting...")
        break

    if query == "exit":
        break
    if query.strip() == "":
        continue
