### ISSUE TITLE
no new documents to load when running ingest

### ISSUE THREAD

**Issue by ghost** [imartinez/privateGPT#770]
**Describe the bug and how to reproduce it**
When I run ingest it downloads all of the models and requirements first but it doesn't ingest the files in source_documents

**Expected behavior**
I expected the program to read and ingest the files

**Environment (please complete the following information):**
 - Linux
 - Python version 3.11

**Comment by mward29** [comment]
I had the same problem. My issue was I specified the source directory as an environment variable rather than through .env despite the code suggesting it possible.
