### ISSUE TITLE
Dependency conflict when installing

### ISSUE THREAD

**Issue by havietisov** [imartinez/privateGPT#771]
**Describe the bug and how to reproduce it**

dependency conflict when installing via pip3 install -requirements.txt  :

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-auth 2.18.1 requires urllib3<2.0, but you have urllib3 2.0.2 which is incompatible.
``` 

pip3 install -requirements.txt

**Expected behavior**
working

**Environment:**
 - ubuntu 22.04 on wsl2
 - Python version 3.10.6

**Additionally** 
Tried installing required version of urllib3 manually, script keeps uninstalling it however

**Comment by sudeepan** [comment]
On Fedora 38, I encountered the same issue for python v3.11.4 and pip v22.3.1. Upgrading pip to v23.2.1 seems to resolve the issue, as long as you keep `unstructured` line in _requirements.txt_ commented (see [this](https://github.com/imartinez/privateGPT/issues/884#issuecomment-1646344306) issue).

Also, for sake of safety, maybe work in a venv.
