### ISSUE TITLE
pip install llama-cpp-python error

### ISSUE THREAD

**Issue by ye-ye823** [imartinez/privateGPT#773]
Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [173 lines of output]

      --------------------------------------------------------------------------------
      -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is MSVC 19.36.32535.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: D:/applicationSoft/vs_BuildTools/vs/VC/Tools/MSVC/14.36.32532/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is MSVC 19.36.32535.0
      CMake Warning (dev) at C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-build-env-vjbi0lb3/overlay/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:168 (if):
        Policy CMP0054 is not set: Only interpret if() arguments as variables or
        keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
        details.  Use the cmake_policy command to set the policy and suppress this
        warning.

        Quoted variables like "MSVC" will no longer be dereferenced when the policy
        is set to NEW.  Since the policy is not set the OLD behavior will be used.
      Call Stack (most recent call first):
        CMakeLists.txt:4 (ENABLE_LANGUAGE)
      This warning is for project developers.  Use -Wno-dev to suppress it.

      CMake Warning (dev) at C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-build-env-vjbi0lb3/overlay/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:189 (elseif):
        Policy CMP0054 is not set: Only interpret if() arguments as variables or
        keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
        details.  Use the cmake_policy command to set the policy and suppress this
        warning.

        Quoted variables like "MSVC" will no longer be dereferenced when the policy
        is set to NEW.  Since the policy is not set the OLD behavior will be used.
      Call Stack (most recent call first):
        CMakeLists.txt:4 (ENABLE_LANGUAGE)
      This warning is for project developers.  Use -Wno-dev to suppress it.

      -- Detecting CXX compiler ABI info
      CMake Warning in C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-install-6m41_veo/llama-cpp-python_28c6c34830f34192b5e6669d19f1df6b/_cmake_test_compile/build/CMakeFiles/CMakeScratch/TryCompile-fc3sej/CMakeLists.txt:
        The object file directory

          C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-install-6m41_veo/llama-cpp-python_28c6c34830f34192b5e6669d19f1df6b/_cmake_test_compile/build/CMakeFiles/CMakeScratch/TryCompile-fc3sej/CMakeFiles/cmTC_ac727.dir/./

        has 225 characters.  The maximum full path to an object file is 250
        characters (see CMAKE_OBJECT_PATH_MAX).  Object file

          CMakeCXXCompilerABI.cpp.obj

        cannot be safely placed under this directory.  The build may not work
        correctly.

      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: D:/applicationSoft/vs_BuildTools/vs/VC/Tools/MSVC/14.36.32532/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (1.3s)
      -- Generating done (0.0s)
      -- Build files have been written to: C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-install-6m41_veo/llama-cpp-python_28c6c34830f34192b5e6669d19f1df6b/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator - success
      --------------------------------------------------------------------------------

      Configuring Project
        Working directory:
          C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-install-6m41_veo\llama-cpp-python_28c6c34830f34192b5e6669d19f1df6b\_skbuild\win-amd64-3.11\cmake-build
        Command:
          'C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-vjbi0lb3\overlay\Lib\site-packages\cmake\data\bin/cmake.exe' 'C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-install-6m41_veo\llama-cpp-python_28c6c34830f34192b5e6669d19f1df6b' -G Ninja '-DCMAKE_MAKE_PROGRAM:FILEPATH=C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-vjbi0lb3\overlay\Lib\site-packages\ninja\data\bin\ninja' -D_SKBUILD_FORCE_MSVC=1930 --no-warn-unused-cli '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-install-6m41_veo\llama-cpp-python_28c6c34830f34192b5e6669d19f1df6b\_skbuild\win-amd64-3.11\cmake-install' -DPYTHON_VERSION_STRING:STRING=3.11.4 -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-vjbi0lb3\overlay\Lib\site-packages\skbuild\resources\cmake' '-DPYTHON_EXECUTABLE:PATH=D:\applicationSoft\python3.11\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=D:\applicationSoft\python3.11\Include' '-DPYTHON_LIBRARY:PATH=D:\applicationSoft\python3.11\libs\python311.lib' '-DPython_EXECUTABLE:PATH=D:\applicationSoft\python3.11\python.exe' '-DPython_ROOT_DIR:PATH=D:\applicationSoft\python3.11' -DPython_FIND_REGISTRY:STRING=NEVER '-DPython_INCLUDE_DIR:PATH=D:\applicationSoft\python3.11\Include' '-DPython_LIBRARY:PATH=D:\applicationSoft\python3.11\libs\python311.lib' '-DPython3_EXECUTABLE:PATH=D:\applicationSoft\python3.11\python.exe' '-DPython3_ROOT_DIR:PATH=D:\applicationSoft\python3.11' -DPython3_FIND_REGISTRY:STRING=NEVER '-DPython3_INCLUDE_DIR:PATH=D:\applicationSoft\python3.11\Include' '-DPython3_LIBRARY:PATH=D:\applicationSoft\python3.11\libs\python311.lib' '-DCMAKE_MAKE_PROGRAM:FILEPATH=C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-vjbi0lb3\overlay\Lib\site-packages\ninja\data\bin\ninja' -DCMAKE_BUILD_TYPE:STRING=Release

      Not searching for unused variables given on the command line.
      -- The C compiler identification is MSVC 19.36.32535.0
      -- The CXX compiler identification is MSVC 19.36.32535.0
      -- Detecting C compiler ABI info
      CMake Warning in C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-install-6m41_veo/llama-cpp-python_28c6c34830f34192b5e6669d19f1df6b/_skbuild/win-amd64-3.11/cmake-build/CMakeFiles/CMakeScratch/TryCompile-gooqhk/CMakeLists.txt:
        The object file directory

          C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-install-6m41_veo/llama-cpp-python_28c6c34830f34192b5e6669d19f1df6b/_skbuild/win-amd64-3.11/cmake-build/CMakeFiles/CMakeScratch/TryCompile-gooqhk/CMakeFiles/cmTC_e1c94.dir/./

        has 235 characters.  The maximum full path to an object file is 250
        characters (see CMAKE_OBJECT_PATH_MAX).  Object file

          CMakeCCompilerABI.c.obj

        cannot be safely placed under this directory.  The build may not work
        correctly.

      -- Detecting C compiler ABI info - failed
      -- Check for working C compiler: D:/applicationSoft/vs_BuildTools/vs/VC/Tools/MSVC/14.36.32532/bin/Hostx86/x64/cl.exe
      CMake Warning in C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-install-6m41_veo/llama-cpp-python_28c6c34830f34192b5e6669d19f1df6b/_skbuild/win-amd64-3.11/cmake-build/CMakeFiles/CMakeScratch/TryCompile-a7ko0b/CMakeLists.txt:
        The object file directory

          C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-install-6m41_veo/llama-cpp-python_28c6c34830f34192b5e6669d19f1df6b/_skbuild/win-amd64-3.11/cmake-build/CMakeFiles/CMakeScratch/TryCompile-a7ko0b/CMakeFiles/cmTC_781fa.dir/./

        has 235 characters.  The maximum full path to an object file is 250
        characters (see CMAKE_OBJECT_PATH_MAX).  Object file

          testCCompiler.c.obj

        cannot be safely placed under this directory.  The build may not work
        correctly.

      -- Check for working C compiler: D:/applicationSoft/vs_BuildTools/vs/VC/Tools/MSVC/14.36.32532/bin/Hostx86/x64/cl.exe - broken
      CMake Error at C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-build-env-vjbi0lb3/overlay/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:67 (message):
        The C compiler

          "D:/applicationSoft/vs_BuildTools/vs/VC/Tools/MSVC/14.36.32532/bin/Hostx86/x64/cl.exe"

        is not able to compile a simple test program.

        It fails with the following output:

          Change Dir: C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-install-6m41_veo/llama-cpp-python_28c6c34830f34192b5e6669d19f1df6b/_skbuild/win-amd64-3.11/cmake-build/CMakeFiles/CMakeScratch/TryCompile-a7ko0b

          Run Build Command(s):C:/Users/Administrator.DESKTOP-VQCTQDA/AppData/Local/Temp/pip-build-env-vjbi0lb3/overlay/Lib/site-packages/ninja/data/bin/ninja -v cmTC_781fa && [1/2] D:\applicationSoft\vs_BuildTools\vs\VC\Tools\MSVC\14.36.32532\bin\Hostx86\x64\cl.exe  /nologo   /DWIN32 /D_WINDOWS  /Zi /Ob0 /Od /RTC1 -MDd /showIncludes /FoCMakeFiles\cmTC_781fa.dir\testCCompiler.c.obj /FdCMakeFiles\cmTC_781fa.dir\ /FS -c C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-install-6m41_veo\llama-cpp-python_28c6c34830f34192b5e6669d19f1df6b\_skbuild\win-amd64-3.11\cmake-build\CMakeFiles\CMakeScratch\TryCompile-a7ko0b\testCCompiler.c
          [2/2] cmd.exe /C "cd . && C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-vjbi0lb3\overlay\Lib\site-packages\cmake\data\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_781fa.dir --rc=C:\PROGRA~2\WINDOW~1\10\bin\100203~1.0\x86\rc.exe --mt=C:\PROGRA~2\WINDOW~1\10\bin\100203~1.0\x86\mt.exe --manifests  -- D:\applicationSoft\vs_BuildTools\vs\VC\Tools\MSVC\14.36.32532\bin\Hostx86\x64\link.exe /nologo CMakeFiles\cmTC_781fa.dir\testCCompiler.c.obj  /out:cmTC_781fa.exe /implib:cmTC_781fa.lib /pdb:cmTC_781fa.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
          FAILED: cmTC_781fa.exe
          cmd.exe /C "cd . && C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-vjbi0lb3\overlay\Lib\site-packages\cmake\data\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_781fa.dir --rc=C:\PROGRA~2\WINDOW~1\10\bin\100203~1.0\x86\rc.exe --mt=C:\PROGRA~2\WINDOW~1\10\bin\100203~1.0\x86\mt.exe --manifests  -- D:\applicationSoft\vs_BuildTools\vs\VC\Tools\MSVC\14.36.32532\bin\Hostx86\x64\link.exe /nologo CMakeFiles\cmTC_781fa.dir\testCCompiler.c.obj  /out:cmTC_781fa.exe /implib:cmTC_781fa.lib /pdb:cmTC_781fa.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
          RC Pass 1: command "C:\PROGRA~2\WINDOW~1\10\bin\100203~1.0\x86\rc.exe /fo CMakeFiles\cmTC_781fa.dir/manifest.res CMakeFiles\cmTC_781fa.dir/manifest.rc" failed (exit code 2) with the following output:
          Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384

          Copyright (C) Microsoft Corporation.  All rights reserved.

          CMakeFiles\cmTC_781fa.dir/manifest.rc(3) : error RC2136 : missing '=' in EXSTYLE=<flags>

          ninja: build stopped: subcommand failed.

        CMake will not be able to correctly generate this project.
      Call Stack (most recent call first):
        CMakeLists.txt:3 (project)

      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-vjbi0lb3\overlay\Lib\site-packages\skbuild\setuptools_wrap.py", line 666, in setup
          env = cmkr.configure(
                ^^^^^^^^^^^^^^^
        File "C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-vjbi0lb3\overlay\Lib\site-packages\skbuild\cmaker.py", line 357, in configure
          raise SKBuildError(msg)

      An error occurred while configuring with CMake.
        Command:
          'C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-vjbi0lb3\overlay\Lib\site-packages\cmake\data\bin/cmake.exe' 'C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-install-6m41_veo\llama-cpp-python_28c6c34830f34192b5e6669d19f1df6b' -G Ninja '-DCMAKE_MAKE_PROGRAM:FILEPATH=C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-vjbi0lb3\overlay\Lib\site-packages\ninja\data\bin\ninja' -D_SKBUILD_FORCE_MSVC=1930 --no-warn-unused-cli '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-install-6m41_veo\llama-cpp-python_28c6c34830f34192b5e6669d19f1df6b\_skbuild\win-amd64-3.11\cmake-install' -DPYTHON_VERSION_STRING:STRING=3.11.4 -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-vjbi0lb3\overlay\Lib\site-packages\skbuild\resources\cmake' '-DPYTHON_EXECUTABLE:PATH=D:\applicationSoft\python3.11\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=D:\applicationSoft\python3.11\Include' '-DPYTHON_LIBRARY:PATH=D:\applicationSoft\python3.11\libs\python311.lib' '-DPython_EXECUTABLE:PATH=D:\applicationSoft\python3.11\python.exe' '-DPython_ROOT_DIR:PATH=D:\applicationSoft\python3.11' -DPython_FIND_REGISTRY:STRING=NEVER '-DPython_INCLUDE_DIR:PATH=D:\applicationSoft\python3.11\Include' '-DPython_LIBRARY:PATH=D:\applicationSoft\python3.11\libs\python311.lib' '-DPython3_EXECUTABLE:PATH=D:\applicationSoft\python3.11\python.exe' '-DPython3_ROOT_DIR:PATH=D:\applicationSoft\python3.11' -DPython3_FIND_REGISTRY:STRING=NEVER '-DPython3_INCLUDE_DIR:PATH=D:\applicationSoft\python3.11\Include' '-DPython3_LIBRARY:PATH=D:\applicationSoft\python3.11\libs\python311.lib' '-DCMAKE_MAKE_PROGRAM:FILEPATH=C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-build-env-vjbi0lb3\overlay\Lib\site-packages\ninja\data\bin\ninja' -DCMAKE_BUILD_TYPE:STRING=Release
        Source directory:
          C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-install-6m41_veo\llama-cpp-python_28c6c34830f34192b5e6669d19f1df6b
        Working directory:
          C:\Users\Administrator.DESKTOP-VQCTQDA\AppData\Local\Temp\pip-install-6m41_veo\llama-cpp-python_28c6c34830f34192b5e6669d19f1df6b\_skbuild\win-amd64-3.11\cmake-build
      Please see CMake's output for more information.

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects

windows10 system

**Comment by derletztename** [comment]
Same for me, but Win 11 System

**Comment by ilias** [comment]
I got a similar error in windows 11:

  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Building wheels for collected packages: llama-cpp-python, hnswlib
  Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [308 lines of output]


      --------------------------------------------------------------------------------
      -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is unknown
      CMake Error at CMakeLists.txt:3 (ENABLE_LANGUAGE):
        No CMAKE_C_COMPILER could be found.

        Tell CMake where to find the compiler by setting either the environment
        variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
        the compiler, or to the compiler name if it is in the PATH.


      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator - failure
      --------------------------------------------------------------------------------



      --------------------------------------------------------------------------------
      -- Trying 'Visual Studio 17 2022 x64 v143' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Error at CMakeLists.txt:2 (PROJECT):
        Generator

          Visual Studio 17 2022

        could not find any instance of Visual Studio.



      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Visual Studio 17 2022 x64 v143' generator - failure
      --------------------------------------------------------------------------------



      --------------------------------------------------------------------------------
      -- Trying 'Ninja (Visual Studio 16 2019 x64 v142)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is unknown
      CMake Error at CMakeLists.txt:3 (ENABLE_LANGUAGE):
        No CMAKE_C_COMPILER could be found.

        Tell CMake where to find the compiler by setting either the environment
        variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
        the compiler, or to the compiler name if it is in the PATH.


      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja (Visual Studio 16 2019 x64 v142)' generator - failure
      --------------------------------------------------------------------------------



      --------------------------------------------------------------------------------
      -- Trying 'Visual Studio 16 2019 x64 v142' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Error at CMakeLists.txt:2 (PROJECT):
        Generator

          Visual Studio 16 2019

        could not find any instance of Visual Studio.



      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Visual Studio 16 2019 x64 v142' generator - failure
      --------------------------------------------------------------------------------



      --------------------------------------------------------------------------------
      -- Trying 'Ninja (Visual Studio 15 2017 x64 v141)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is unknown
      CMake Error at CMakeLists.txt:3 (ENABLE_LANGUAGE):
        No CMAKE_C_COMPILER could be found.

        Tell CMake where to find the compiler by setting either the environment
        variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
        the compiler, or to the compiler name if it is in the PATH.


      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja (Visual Studio 15 2017 x64 v141)' generator - failure
      --------------------------------------------------------------------------------



      --------------------------------------------------------------------------------
      -- Trying 'Visual Studio 15 2017 x64 v141' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Error at CMakeLists.txt:2 (PROJECT):
        Generator

          Visual Studio 15 2017

        could not find any instance of Visual Studio.



      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Visual Studio 15 2017 x64 v141' generator - failure
      --------------------------------------------------------------------------------



      --------------------------------------------------------------------------------
      -- Trying 'NMake Makefiles (Visual Studio 17 2022 x64 v143)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Error at CMakeLists.txt:2 (PROJECT):
        Running

         'nmake' '-?'

        failed with:

         The system cannot find the file specified


      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'NMake Makefiles (Visual Studio 17 2022 x64 v143)' generator - failure
      --------------------------------------------------------------------------------



      --------------------------------------------------------------------------------
      -- Trying 'NMake Makefiles (Visual Studio 16 2019 x64 v142)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Error at CMakeLists.txt:2 (PROJECT):
        Running

         'nmake' '-?'

        failed with:

         The system cannot find the file specified


      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'NMake Makefiles (Visual Studio 16 2019 x64 v142)' generator - failure
      --------------------------------------------------------------------------------



      --------------------------------------------------------------------------------
      -- Trying 'NMake Makefiles (Visual Studio 15 2017 x64 v141)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Error at CMakeLists.txt:2 (PROJECT):
        Running

         'nmake' '-?'

        failed with:

         The system cannot find the file specified


      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'NMake Makefiles (Visual Studio 15 2017 x64 v141)' generator - failure
      --------------------------------------------------------------------------------

                      ********************************************************************************
                      scikit-build could not get a working generator for your system. Aborting build.

                      Building windows wheels for Python 3.11 requires Microsoft Visual Studio 2022.
      Get it with "Visual Studio 2017":

        https://visualstudio.microsoft.com/vs/

      Or with "Visual Studio 2019":

          https://visualstudio.microsoft.com/vs/

      Or with "Visual Studio 2022":

          https://visualstudio.microsoft.com/vs/

                      ********************************************************************************
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
  Building wheel for hnswlib (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for hnswlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'hnswlib' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for hnswlib
Failed to build llama-cpp-python hnswlib
ERROR: Could not build wheels for llama-cpp-python, hnswlib, which is required to install pyproject.toml-based projects
[#]

**Comment by rx-ted** [comment]
Do you download visual studio 2022(2019) for install the PC？I don't install VS, can use other package of MinGW?

**Comment by ye-ye823** [comment]
> Yes, I've tried everything

**Comment by rx-ted** [comment]
> > Yes, I've tried everything

I'm going to reinstall it see the results.

**Comment by ye-ye823** [comment]
> > > Yes, I've tried everything
> 
> I'm going to reinstall it see the results.

Ok, thanks, I can build on windows11

**Comment by vual** [comment]
> Do you download visual studio 2022(2019) for install the PC？I don't install VS, can use other package of MinGW?

centos，how to resolve this error？

**Comment by ShishirMaidenCodeLife** [comment]
TO solve the issue I downloaded the **llama-cpp-python** file manually, from here : https://github.com/abetlen/llama-cpp-python/releases. Please choose the right version. I have a windows version 11, 64 bit and the python version that i have is 3.10 so the correct version for me is : **llama_cpp_python-0.1.73-cp310-cp310-win_amd64.whl** . Then place this file in a folder and install using pip : **pip install path/llama_cpp_python-0.1.73-cp310-cp310-win_amd64.whl**

**Comment by dyb5784** [comment]
IYH I fixed the issue by first calling
call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64

then pip3 install -r requirements.txt
ran without a hitch
