### ISSUE TITLE
Admits Spanish docs and allow Spanish question and answer?

### ISSUE THREAD

**Issue by johnfelipe** [imartinez/privateGPT#774]

**Comment by kpcrash** [comment]
You might be able to make this work by using paraphrase-multilingual-MiniLM-L12-v2 as your EMBEDDINGS_MODEL_NAME as it claims to support 50 different languages.

**Comment by johnfelipe** [comment]
Wich another model more stable?

**Comment by abundis-rmn2** [comment]
Would be great have a starting point to make this project multilang,
I try several EMBEDDINGS_MODEL_NAME with the default GPT model and all responses in spanish are gibberish.

For newbies would work some kind of table explaining the size of the models, the parameters in .env that could work in both GPT and Llama, and which kind of embeding models could be compatible.

Maybe with that startint point not experienced users may help.

**Comment by gapinvestor** [comment]
> You might be able to make this work by using paraphrase-multilingual-MiniLM-L12-v2 as your EMBEDDINGS_MODEL_NAME as it claims to support 50 different languages.

I've set that name in the .env file, but despite writing the question in Spanish, it gives me the answer in English. How can I change that?

**Comment by girowue** [comment]
How can we get answers in spanish??  I only get them in english.

thanks.
