### ISSUE TITLE
Problem with ingestion

### ISSUE THREAD

**Issue by smileyjay66** [imartinez/privateGPT#780]
I followed the instructions correctly the download requirements are satisfied, but every time I attempt to ingest a document I receive this error 

smileyjay@DESKTOP-5ID2855 privateGPT-main % /usr/bin/python3 /Users/smileyjay/Do
wnloads/privateGPT-main/ingest.py
Traceback (most recent call last):
  File "/Users/smileyjay/Downloads/privateGPT-main/ingest.py", line 5, in <module>
    from dotenv import load_dotenv
    ModuleNotFoundError: No module named 'dotenv'
        
 any feedback on this issue would be greatly appreciated thank you!

**Comment by uestadeus** [comment]
did you install all requirements packages?

`pip3 install -r requirements.txt`

**Comment by smileyjay66** [comment]
> did you install all requirements packages?
> 
> `pip3 install -r requirements.txt`

Yes I installed the  model, put it in the model folder and then ran the the “ pip3 install -r requirements.txt” script and the downloads requirements are satisfied but I still can not ingest documents

**Comment by uestadeus** [comment]
did you create .env file and set the variables? just checking the to do list ?

**Comment by smileyjay66** [comment]
> did you create .env file and set the variables? just checking the to do list ?

Yes I created the .env and the variables are how they should be

**Comment by seyekuyinu** [comment]
This frustrated me a lot but I ran the following:

`python3 -m pip install langchain` 

and then I ran 

`python3 ingest.py`

**Comment by saksham1211** [comment]
please check the python environment in which libraries are installed you maybe referring to wrong python kernel and library might be installed into some other kernel.
