### ISSUE TITLE
 pyproject.toml-based (from versions: none)

### ISSUE THREAD

**Issue by Crescentz** [imartinez/privateGPT#784]
Collecting llama-cpp-python==0.1.59
  Downloading llama_cpp_python-0.1.59.tar.gz (1.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 2.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting typing-extensions>=4.5.0 (from llama-cpp-python==0.1.59)
  Using cached typing_extensions-4.6.3-py3-none-any.whl (31 kB)
Collecting numpy>=1.20.0 (from llama-cpp-python==0.1.59)
  Using cached numpy-1.25.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.6 MB)
Collecting diskcache>=5.6.1 (from llama-cpp-python==0.1.59)
  Using cached diskcache-5.6.1-py3-none-any.whl (45 kB)
Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [101 lines of output]
      
      
      --------------------------------------------------------------------------------
      -- Trying 'Ninja' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is GNU 5.4.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is GNU 5.4.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (0.6s)
      -- Generating done (0.0s)
      -- Build files have been written to: /tmp/pip-install-x5mxgyzf/llama-cpp-python_799fbb3ac059468d8493544950b2cfc6/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja' generator - success
      --------------------------------------------------------------------------------
      
      Configuring Project
        Working directory:
          /tmp/pip-install-x5mxgyzf/llama-cpp-python_799fbb3ac059468d8493544950b2cfc6/_skbuild/linux-x86_64-3.10/cmake-build
        Command:
          /tmp/pip-build-env-ymsfywh8/overlay/lib/python3.10/site-packages/cmake/data/bin/cmake /tmp/pip-install-x5mxgyzf/llama-cpp-python_799fbb3ac059468d8493544950b2cfc6 -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-ymsfywh8/overlay/lib/python3.10/site-packages/ninja/data/bin/ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-x5mxgyzf/llama-cpp-python_799fbb3ac059468d8493544950b2cfc6/_skbuild/linux-x86_64-3.10/cmake-install -DPYTHON_VERSION_STRING:STRING=3.10.12 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-ymsfywh8/overlay/lib/python3.10/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/home1/zy/miniconda3/envs/pgpt/bin/python3.1 -DPYTHON_INCLUDE_DIR:PATH=/home1/zy/miniconda3/envs/pgpt/include/python3.10 -DPYTHON_LIBRARY:PATH=/home1/zy/miniconda3/envs/pgpt/lib/libpython3.10.so -DPython_EXECUTABLE:PATH=/home1/zy/miniconda3/envs/pgpt/bin/python3.1 -DPython_ROOT_DIR:PATH=/home1/zy/miniconda3/envs/pgpt -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/home1/zy/miniconda3/envs/pgpt/include/python3.10 -DPython3_EXECUTABLE:PATH=/home1/zy/miniconda3/envs/pgpt/bin/python3.1 -DPython3_ROOT_DIR:PATH=/home1/zy/miniconda3/envs/pgpt -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/home1/zy/miniconda3/envs/pgpt/include/python3.10 -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-ymsfywh8/overlay/lib/python3.10/site-packages/ninja/data/bin/ninja -DCMAKE_BUILD_TYPE:STRING=Release
      
      Not searching for unused variables given on the command line.
      -- The C compiler identification is GNU 5.4.0
      -- The CXX compiler identification is GNU 5.4.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (0.5s)
      -- Generating done (0.0s)
      -- Build files have been written to: /tmp/pip-install-x5mxgyzf/llama-cpp-python_799fbb3ac059468d8493544950b2cfc6/_skbuild/linux-x86_64-3.10/cmake-build
      [1/2] Generating /tmp/pip-install-x5mxgyzf/llama-cpp-python_799fbb3ac059468d8493544950b2cfc6/vendor/llama.cpp/libllama.so
      FAILED: /tmp/pip-install-x5mxgyzf/llama-cpp-python_799fbb3ac059468d8493544950b2cfc6/vendor/llama.cpp/libllama.so
      cd /tmp/pip-install-x5mxgyzf/llama-cpp-python_799fbb3ac059468d8493544950b2cfc6/vendor/llama.cpp && make libllama.so
      I llama.cpp build info:
      I UNAME_S:  Linux
      I UNAME_P:  x86_64
      I UNAME_M:  x86_64
      I CFLAGS:   -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS
      I CXXFLAGS: -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -march=native -mtune=native
      I LDFLAGS:
      I CC:       cc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
      I CXX:      g++ (GCC) 11.2.0
      
      g++ -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -march=native -mtune=native -c llama.cpp -o llama.o
      cc  -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS   -c ggml.c -o ggml.o
      ggml.c: In function ‘bytes_from_nibbles_32’:
      ggml.c:554:27: warning: implicit declaration of function ‘_mm256_set_m128i’ [-Wimplicit-function-declaration]
           const __m256i bytes = _mm256_set_m128i(_mm_srli_epi16(tmp, 4), tmp);
                                 ^
      ggml.c:554:27: error: incompatible types when initializing type ‘__m256i {aka const __vector(4) long long int}’ using type ‘int’
      Makefile:245: recipe for target 'ggml.o' failed
      make: *** [ggml.o] Error 1
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/tmp/pip-build-env-ymsfywh8/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 674, in setup
          cmkr.make(make_args, install_target=cmake_install_target, env=env)
        File "/tmp/pip-build-env-ymsfywh8/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 697, in make
          self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
        File "/tmp/pip-build-env-ymsfywh8/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 742, in make_impl
          raise SKBuildError(msg)
      
      An error occurred while building with CMake.
        Command:
           const __m256i bytes = _mm256_set_m128i(_mm_srli_epi16(tmp, 4), tmp);                                 ^
      ggml.c:554:27: error: incompatible types when initializing type ‘__m256i {aka const __vector(4) long long int}’ using type ‘int’
      Makefile:245: recipe for target 'ggml.o' failed
      make: *** [ggml.o] Error 1
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/tmp/pip-build-env-ymsfywh8/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 674, in setup          cmkr.make(make_args, install_target=cmake_install_target, env=env)
        File "/tmp/pip-build-env-ymsfywh8/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 697, in make
          self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
        File "/tmp/pip-build-env-ymsfywh8/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 742, in make_impl
          raise SKBuildError(msg)
      
      An error occurred while building with CMake.
        Command:
          /tmp/pip-build-env-ymsfywh8/overlay/lib/python3.10/site-packages/cmake/data/bin/cmake --build . --target install --config Release --        Install target:
          install
        Source directory:          /tmp/pip-install-x5mxgyzf/llama-cpp-python_799fbb3ac059468d8493544950b2cfc6
        Working directory:
          /tmp/pip-install-x5mxgyzf/llama-cpp-python_799fbb3ac059468d8493544950b2cfc6/_skbuild/linux-x86_64-3.10/cmake-build
      Please check the install target is valid and see CMake's output for more information.
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects
(pgpt) zy@NLP-GPU:~/Learn/privateGPT$ pip install pyproject.toml-based
ERROR: Could not find a version that satisfies the requirement pyproject.toml-based (from versions: none)
ERROR: No matching distribution found for pyproject.toml-based

**Environment (please complete the following information):**
linux  python3.10

**Comment by LSpekschoor** [comment]
This might be solved by installing a C++ compiler. The gpt4all has a Readme.md that mentions this:
https://github.com/nomic-ai/gpt4all/blob/main/gpt4all-bindings/python/README.md
If I remember correct I solved this kind of error with the Microsoft Visual C++ compiler, which might be a bit easier to install for someone not very familiar.
