### ISSUE TITLE
how can i use gpu to run?

### ISSUE THREAD

**Issue by ajavaer** [imartinez/privateGPT#79]
I use  windows , use cpu to run is to slow

**Comment by Jeru2023** [comment]
to be honest i don't really know why this is a high star project, ingest and query both are extremely slow. it takes hours to ask a simple question, are you kidding me?

**Comment by alxspiker** [comment]
> to be honest i don't really know why this is a high star project, ingest and query both are extremely slow. it takes hours to ask a simple question, are you kidding me?

What do you mean it takes hours? Running on a potato laptop and I get like 18 seconds per response.

**Comment by alxspiker** [comment]
> I use windows , use cpu to run is to slow

facebookresearch/llama/issues/4

You have  the space?

**Comment by teristam** [comment]
Tokenization is very slow, generation is ok. The major hurdle preventing GPU usage is that this project uses the llama.cpp integration from langchain, which default to use CPU. One way to use GPU is to recompile llama.cpp with cuBLAS support. I have tried but doesn't seem to work.

**Comment by Jeru2023** [comment]
> > to be honest i don't really know why this is a high star project, ingest and query both are extremely slow. it takes hours to ask a simple question, are you kidding me?
> 
> What do you mean it takes hours? Running on a potato laptop and I get like 18 seconds per response. The goal of this project is to speed it up even more than we have. An update is coming that also persists the model initialization to speed up time between following responses.

Please let me know how long it takes on your laptop to ingest the "state_of_the_union" file? this step alone took me at least 20 minutes on my PC with 4090 GPU, is there anything i'm missing?

**Comment by Jeru2023** [comment]
> Tokenization is very slow, generation is ok. The major hurdle preventing GPU usage is that this project uses the llama.cpp integration from langchain, which default to use CPU. One way to use GPU is to recompile llama.cpp with cuBLAS support. I have tried but doesn't seem to work.

I'm going to replace the embedding code with my own implementation. btw how long is the query response takes on your computer? 3 minutes on mine.

**Comment by rohanrichards** [comment]
Generation is **extremely slow** for me: windows10, 32gb RAM, and AMD Ryzen 7 5800X. I get about a word every 10 seconds. It also takes 15-20 minutes for generation to even start after entering my prompt.

**Comment by elcolie** [comment]
I would love to know how to turn on M2 MPS on MBP to run.

**Comment by CraftCanna** [comment]
> 

Any luck getting this to work?

**Comment by hsm207** [comment]
does gpt4all use GPU or is it easy to config a gpt4all model to use a GPU?

**Comment by teristam** [comment]
For anyone following this issue, llama-cpp-python has released a new version with GPU support from lama.cpp. Follow the instruction there: https://github.com/abetlen/llama-cpp-python to compile with cuBLAS support

**Comment by ChristianWeyer** [comment]
> https://github.com/abetlen/llama-cpp-python

@imartinez When we run privateGPT on an M1, it only uses CPU, right? There is currently no support for GPU (e.g. via MPS)?

**Comment by imartinez** [comment]
Currently it is only CPU, but there are open PRs to support GPU, just search, clone and test it out!

**Comment by MNLierman** [comment]
Would love to use this on Docker with my 128 Core Jetson GPU. From your previous comment, just so that I understand correctly, there are poll requests to fix this exact issue, and you would rather ignore them and not merge them and to the product? Why?
