### ISSUE TITLE
help me :   Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'

### ISSUE THREAD

**Issue by dinner-pig** [imartinez/privateGPT#790]
How can I solve this problem? I've been struggling for a long time and can't find a solution. Please help me thanks!!!

**Environment 
 - OS / hardware: macOS 13.2.1 / M1
 - Python version  3.11.3

![image](https://github.com/imartinez/privateGPT/assets/59759874/49417ecf-0c14-44c5-b08a-b9dd23a0be9b)
![image](https://github.com/imartinez/privateGPT/assets/59759874/2ca1852e-28fa-4527-9797-ec7dfd60fd51)
![image](https://github.com/imartinez/privateGPT/assets/59759874/7f7b9591-0a31-42b6-ac72-6c172e66a82f)

**Comment by mayTang726** [comment]
did you resolve this problem now ? I met the same problem too

**Comment by life00** [comment]
I am facing the same issue. It occurs as if randomly, and more frequently when loading large documents. Sometimes I am lucky not to get into it, but it is very annoying. I am on same hardware, but on linux.
