### ISSUE TITLE
Ingest Error, none is not allowed value

### ISSUE THREAD

**Issue by TrackLab** [imartinez/privateGPT#792]
**Describe the bug and how to reproduce it**
I installed the project, with the requirements over pip, downloaded the model, and followed the descriptions. Upon running ingest.py, I get this traceback

`(PrivateGPT) D:\Python\2023\PrivateGPT>python ingest.py
Traceback (most recent call last):
  File "D:\Python\2023\PrivateGPT\ingest.py", line 27, in <module>
    from constants import CHROMA_SETTINGS
  File "D:\Python\2023\PrivateGPT\constants.py", line 11, in <module>
    CHROMA_SETTINGS = Settings(
  File "pydantic\env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
persist_directory
  none is not an allowed value (type=type_error.none.not_allowed)`

**Expected behavior**
The Ingest script to run as described in the README

**Environment (please complete the following information):**
 - OS / hardware: Windows 10, GTX 1080, AMD Ryzen 7 2700x
 - Python version 3.9.16
 
The source_documents includes the example state_of_the_union.txt

**Comment by sansoy** [comment]
I got the same error running on an 8gb Intel Core5 Mac  running Ventura 13.4.1
Python version:  3.10.10

**Comment by bro33** [comment]
Same here, problem (in my case at least) was not having created the .env file and a "db" folder. Done that all went fine.

**Comment by TrackLab** [comment]
> Same here, problem (in my case at least) was not having created the .env file and a "db" folder. Done that all went fine.

Sounds like a easy fix, didnt help me unfortunately. I have the db folder, what .env file do you have? And where?

**Comment by bro33** [comment]
from the Read me file : 

```
Copy the example.env template into .env
cp example.env .env
and edit the variables appropriately in the .env file.

```

You should have a hidden file ".env", having used the suggested model, didn't have to configure it further (but needed to run the "cp example.env .env" command).  Missed it the first time as I was following some external tutorial which missed this part. 

Was actually able to replicate the problem, same error with a fresh install and not running the .env related command, "db" folder gets auto created. 

Hope it helps, it is altho a pretty generic error, so possibly it isn't the same problem you are experiencing.
