### ISSUE TITLE
The response contains the correct source document and relevant sections/pages, yet it does not meet my anticipated outcome.

### ISSUE THREAD

**Issue by smrsassa** [imartinez/privateGPT#794]
**Bug and how to reproduce it**
To reproduce the bug, it is necessary to follow the steps:
- Perform the environment setup outlined in the project's readme.
- Ask the following question: "What is the most fundamental right in America?"

**Output**
> Question:
what is the most fundamental right in America?

> Answer (took 532.75 s.):
 The answer to this question may vary depending upon one's personal beliefs or values, but it generally refers to a basic human need that must be protected and ensured by society as a whole - such rights might include freedom of speech (in democratic societies), due process under the law for all citizens regardless of their status in life, protection against arbitrary government action without adequate reasons given, equal treatment before courts or other public tribunals where decisions may result in punishment.

> source_documents\state_of_the_union.txt:
The most fundamental right in America is the right to vote – and to have it counted. And it’s under assault.
In state after state, new laws have been passed, not only to suppress the vote, but to subvert entire elections.
We cannot let this happen.
Tonight. I call on the Senate to: Pass the Freedom to Vote Act. Pass the John Lewis Voting Rights Act. And while you’re at it, pass the Disclose Act so Americans can know who is funding our elections.

**Expected behavior**
We can observe that the source of the response aligns with the expectations; however, the response itself does not conform to the source. The expected response would be to use the source and provide an answer like:

"The most fundamental right in America is the right to vote – and to have it counted. And it’s under assault."

**Environment:**
- OS / hardware: Windows 11, i5-10210U, 8GB RAM
- Python version 3.11.2

**Additional context**
- 
- The .env file:
PERSIST_DIRECTORY=db
MODEL_TYPE=GPT4All
MODEL_PATH=models/ggml-gpt4all-j-v1.3-groovy.bin
EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
MODEL_N_CTX=1000
MODEL_N_BATCH=8
TARGET_SOURCE_CHUNKS=4

**Comment by ho2103** [comment]
llm = HuggingFacePipeline.from_model_id(
        model_id="google/flan-t5-base",
        task="text2text-generation")

Just use this instead of the llm they provided in privateGPT.py

works perfect and gives answer very quickly
