### ISSUE TITLE
Error while running python privateGPT.py

### ISSUE THREAD

**Issue by javiermanzano** [imartinez/privateGPT#798]
**Describe the bug and how to reproduce it**

I cannot run privateGPT after running ingest process.

I'm running this and getting this output

```
(base) javiermanzano@home privateGPT % python privateGPT.py

  File "/Users/javiermanzano/Development/chatGPT/privateGPT/privateGPT.py", line 34
    match model_type:
          ^
SyntaxError: invalid syntax
```

**Expected behavior**

I want to query the model after that

**Environment:**
 - OS / hardware: macOS 12.6 / Intel
 - Python version 3.9.6

**Additional context**

This is the `.env` file that I'm using

```
PERSIST_DIRECTORY=db
MODEL_TYPE=GPT4All
MODEL_PATH=models/ggml-gpt4all-j-v1.3-groovy.bin
EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
MODEL_N_CTX=1000
MODEL_N_BATCH=8
TARGET_SOURCE_CHUNKS=4
```

**Comment by davideoliveri** [comment]
The error should disappear if you switch to python 3.10.

**Comment by trey-wallis** [comment]
I was running python 3.7. I upgraded to 3.11 by doing `brew install python`. The issue went away.
