### ISSUE TITLE
TypeError: Model.generate() got an unexpected keyword argument 'new_text_callback'

### ISSUE THREAD

**Issue by x4g4p3x** [imartinez/privateGPT#8]
Every time I run a query I get this output.

**Comment by imartinez** [comment]
Check https://github.com/imartinez/privateGPT/issues/2

Make sure the installed version of the dependencies is correct. There was a breaking change in one of the dependencies.

**Comment by imartinez** [comment]
Please pull the latest changes and reinstall dependencies. Latest changes update all libs to the stable version.
