### ISSUE TITLE
Use any small models, like LaMini, Flan-T5-783M etc.

### ISSUE THREAD

**Issue by gitknu** [imartinez/privateGPT#808]
Hello, sorry for the fact I couldn't find the solution in issues and if the question is dumb, but looking for the answer and trying by myself didn't give the result.

Details: 
The problem is I have low-end PC which is capable of running Alpaca and Vicuna (both 7B), but quite slowly. On the other hand, trying different models I saw that models under 1B parameters run quite well. Mainly they are based on Flan-T5. They give good results as for my machine and quickly enough (about 3-5 tokens per second). Using it with text is another better point. For example, asking it "basing on this text, answer -..." I have almost perfect answer. But giving it text each time is bad practice as for me. I mean, time spend etc.

Short question:
Is there any way to use this tool with any of these models?
- LaMini-Flan-T5-783M
- Flan-T5-Alpaca (770M or something)
- RWKV (under 1.5B)
- (any other good small models, under 1B parameters)
If you give the detailed manual I will be very grateful! Solutions, other than privateGPT etc. are also welcome!

Thank you for understanding, answers and sorry for any inconvenience!

**Comment by pruthviishere** [comment]
Hello,

I am currently developing a question answering system specifically designed for low-end devices. This system has the capability to ingest documents, allowing users to extract information from various sources. If you're interested, you can check out the repository at https://github.com/pruthviishere/QA_FlanT5_Ingestion. The system is designed to run locally and offline, without the need for any Hugging Face API token. Additionally, it utilizes the Flan-T5-large model, which is a zero-shot model known for its efficiency and faster response times compared to other language models.

Thank you for your understanding and interest in my project.
