### ISSUE TITLE
Can't use falcon model (ggml-model-gpt4all-falcon-q4_0.bin)

### ISSUE THREAD

**Issue by akmmuhitulislam** [imartinez/privateGPT#809]
I got this error when I tried to load the falcon binary.
![image](https://github.com/imartinez/privateGPT/assets/138411620/3d729aec-2b82-445c-bfc4-e08f2114f2da)

after upgrading gpt4all from version 0.3.4 to 1.0.1 the falcon model could be successfully loaded, but it crashes when a query is given.

![image](https://github.com/imartinez/privateGPT/assets/138411620/568bf5f0-7aec-45b4-aad8-4ae6e2d5b3a8)

after removing n_ctx from parameters, the following error occurs,
![image](https://github.com/imartinez/privateGPT/assets/138411620/61c701ae-bf29-4320-9922-00e27289fa5b)

**Expected behavior**
loading and running the falcon model 

**Environment:**
 - OS : [Ubuntu 22.04 ]
 - Python version [3.10]

**Comment by AgentJ-WR** [comment]
Upgrade langchain as well, and remove the ctx arg from GPT4ALL()

**Comment by goyalyug** [comment]
Having the same issue - help would be great. What versions is the upgrade?
