### ISSUE TITLE
root_validator is deprecated

### ISSUE THREAD

**Issue by gapinvestor** [imartinez/privateGPT#812]
While trying to execute 'ingest.py' for the first time I get this error:

pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

I can't execute the files

**Comment by goodglitch** [comment]
You can try to downgrade pydantic:

pip uninstall pydantic
pip install "pydantic==1.*"
