### ISSUE TITLE
 Unable to instantiate model (type=value_error)

### ISSUE THREAD

**Issue by wenzhao98** [imartinez/privateGPT#817]
Anybody has seen this error? MacOS with m2

% python privateGPT.py 
Using embedded DuckDB with persistence: data will be stored in: db
Found model file at  models/ggml-gpt4all-j-v1.3-groovy.bin
Invalid model file
Traceback (most recent call last):
  File "/Users/wenzhao/Downloads/privateGPT/privateGPT.py", line 83, in <module>
    main()
  File "/Users/wenzhao/Downloads/privateGPT/privateGPT.py", line 38, in main
    llm = GPT4All(model=model_path, n_ctx=model_n_ctx, backend='gptj', n_batch=model_n_batch, callbacks=callbacks, verbose=False)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GPT4All
__root__
  Unable to instantiate model (type=value_error)

**Comment by WORTI3** [comment]
You need to properly download the model file. 
^ error shows you haven't downloaded it correctly or the name of the file isn't being pointed to correctly.

I had the same issue but solved it with a fresh download.
