### ISSUE TITLE
Italian language

### ISSUE THREAD

**Issue by crix77** [imartinez/privateGPT#821]
Hi, I have use some italian docs as knowledge and the ingest process was fine.
But if i ask somenting in italian, it will replay in english, using the information stored in italian docs.
I have tried to change the embedded model with paraphrase-multilingual-MiniLM-L12-v2 but nothing is change.
Is there any other change to do?
Thanks, the project has big potential.
Cristian

**Comment by maozdemir** [comment]
Due to the nature of langchain, you HAVE to utilise a translation API. You can write your own modules too. Though, most models won't perform good when it comes to other Languages than Englishç
