### ISSUE TITLE
Does GPT4All or LlamaCpp support use the GPU to do the inference in privateGPT?

### ISSUE THREAD

**Issue by JustinZou1** [imartinez/privateGPT#823]
Does GPT4All or LlamaCpp support use the GPU to do the inference in privateGPT? As using the CPU to do inference , it is very slow.

**Comment by maozdemir** [comment]
https://github.com/maozdemir/privateGPT/tree/gpu

**Comment by darrinh** [comment]
> https://github.com/maozdemir/privateGPT/tree/gpu

When I run:

pip3 install llama-cpp-python --force-reinstall --upgrade --no-cache-dir

I get:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
argilla 1.12.0 requires numpy<1.24.0, but you have numpy 1.25.0 which is incompatible.

I removed 1.25.0 but the above command keeps re-installing it:

ollecting numpy>=1.20.0 (from llama-cpp-python)
  Downloading numpy-1.25.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.6 MB)

Any ideas?

**Comment by lindeer** [comment]
@darrinh not sure my solution would be working for you, just have a try:
1. git clone llama-cpp-python from source and checkout v0.1.65
2. update submodule of llama.cpp with latest code: `cd vendor/llama.cpp && git pull -r origin master`
3. install llama-cpp-python from local source: `pip install /path/to/llama-cpp-python`

**Comment by maozdemir** [comment]
> > https://github.com/maozdemir/privateGPT/tree/gpu
> 
> When I run: CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip3 install llama-cpp-python --force-reinstall --upgrade --no-cache-dir
> 
> I get:
> 
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. argilla 1.12.0 requires numpy<1.24.0, but you have numpy 1.25.0 which is incompatible.
> 
> I removed 1.25.0 but the above command keeps re-installing it:
> 
> ollecting numpy>=1.20.0 (from llama-cpp-python) Downloading numpy-1.25.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.6 MB)
> 
> Any ideas?

@darrinh use the sh/bat files I've added to the repo.

**Comment by darrinh** [comment]
ok, ive had some success with using the latest llama-cpp-python (has cuda support) with a cut down version of privateGPT.py:

llm = LlamaCpp(
    model_path="./koala-7B.ggmlv3.q2_K.bin",
    n_gpu_layers=n_gpu_layers,
    n_batch=n_batch,
    callback_manager=callback_manager,
    verbose=True,
    n_ctx=2048
)

when run, i see:

`Using embedded DuckDB with persistence: data will be stored in: db
ggml_init_cublas: found 2 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3060, compute capability 8.6
  Device 1: NVIDIA GeForce RTX 3060, compute capability 8.6
llama.cpp: loading model from ./koala-7B.ggmlv3.q2_K.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 10 (mostly Q2_K)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.08 MB
llama_model_load_internal: using CUDA for GPU acceleration
ggml_cuda_set_main_device: using device 0 (NVIDIA GeForce RTX 3060) as main device
llama_model_load_internal: mem required  = 1713.10 MB (+ 1026.00 MB per state)
llama_model_load_internal: allocating batch_size x (512 kB + n_ctx x 128 B) = 384 MB VRAM for the scratch buffer
llama_model_load_internal: offloading 32 repeating layers to GPU
llama_model_load_internal: offloading non-repeating layers to GPU
llama_model_load_internal: offloading v cache to GPU
llama_model_load_internal: offloading k cache to GPU
llama_model_load_internal: offloaded 35/35 layers to GPU
llama_model_load_internal: total VRAM used: 4042 MB
llama_new_context_with_model: kv self size  = 1024.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 | 
`

I just don't know yet how to modify the original privateGPT to work with this. Inference is now a lot faster:

`Enter a query: how do we beat inflation?
 Lower costs, lower deficit, fight inflation by making more cars and semiconductors in America, increase productive capacity of our economy, bury label "rust belt", time to build a better America
llama_print_timings:        load time =  3422.53 ms
llama_print_timings:      sample time =    12.47 ms /    47 runs   (    0.27 ms per token,  3769.95 tokens per second)
llama_print_timings: prompt eval time =  3422.49 ms /   578 tokens (    5.92 ms per token,   168.88 tokens per second)
llama_print_timings:        eval time =  1320.72 ms /    46 runs   (   28.71 ms per token,    34.83 tokens per second)
llama_print_timings:       total time =  4790.52 ms
. Lower costs, lower deficit, fight inflation by making more cars and semiconductors in America, increase productive capacity of our economy, bury label "rust belt", time to build a better America.
`

**Comment by darrinh** [comment]
ok, in privateGPT dir you can do:

pip uninstall -y llama-cpp-python
CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python --no-cache-dir

once that is done, modify privateGPT.py by adding:

model_n_gpu_layers = os.environ.get('MODEL_N_GPU_LAYERS')

underneath 'model_n_batch = int(os.environ.get('MODEL_N_BATCH',8))' line

also modify to include the gpu option:

llm = LlamaCpp(model_path=model_path, n_ctx=model_n_ctx, n_batch=model_n_batch, callbacks=callbacks, verbose=True,n_gpu_layers=model_n_gpu_layers)


modify the model in .env to change the model type and add gpu layers, etc, mine looks like:

PERSIST_DIRECTORY=db
MODEL_TYPE=LlamaCpp
MODEL_PATH=models/koala-7B.ggmlv3.q2_K.bin
EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
MODEL_N_CTX=2048
MODEL_N_BATCH=1024
TARGET_SOURCE_CHUNKS=4
MODEL_N_GPU_LAYERS=100

results:

Enter a query: how do we beat inflation?
 Lower your costs, not your wages. Make more cars and semiconductors in America
llama_print_timings:        load time =  3335.58 ms
llama_print_timings:      sample time =     5.92 ms /    21 runs   (    0.28 ms per token,  3549.70 tokens per second)
llama_print_timings: prompt eval time =  3335.54 ms /   578 tokens (    5.77 ms per token,   173.29 tokens per second)
llama_print_timings:        eval time =   576.33 ms /    20 runs   (   28.82 ms per token,    34.70 tokens per second)
llama_print_timings:       total time =  3937.84 ms


much, much faster and now a viable option for document qa.

cheers
Darrin

**Comment by maozdemir** [comment]
> /ok, ive had some success with using the latest llama-cpp-python (has cuda support) with a cut down version of privateGPT.py:
> ~snip~

"Original" privateGPT is actually more like just a clone of langchain's examples, and your code will do pretty much the same thing. We, as contributors, tried to make it a little bit more accessible to the people who don't know how to code. You don't need to worry about this repo if your code is working.

**Comment by BoBBer446** [comment]
```
Device
--
Name | NVIDIA GeForce GTX 1050 Ti
Driver version | 531.54.0.0
Type | DISCRETE_GPU
API Version | 1.3.245
Vendor | NVIDIA
Platform
Name | Windows
Architecture | x86_64
Version | 11
Report
Submitted by |  
Submitted at | 2023-04-06 06:56:54
Last update at |  
Reportversion | 3.2

<!--EndFragment-->
</body>
</html>Device
Name	[NVIDIA GeForce GTX 1050 Ti](https://vulkan.gpuinfo.org/listreports.php?displayname=NVIDIA%20GeForce%20GTX%201050%20Ti)
Driver version	531.54.0.0
Type	DISCRETE_GPU
API Version	1.3.245
Vendor	NVIDIA
Platform
Name	Windows
Architecture	x86_64
Version	11
Report
Submitted by	
Submitted at	2023-04-06 06:56:54
Last update at	
Reportversion	3.2
```

GPU is not working, just CPU. Gpt4all 2.4.19

![image](https://github.com/imartinez/privateGPT/assets/10163536/18f3d276-eefb-4618-b84f-933ecfad0e45)

**Comment by maozdemir** [comment]
> ```
> Device
> --
> Name | NVIDIA GeForce GTX 1050 Ti
> Driver version | 531.54.0.0
> Type | DISCRETE_GPU
> API Version | 1.3.245
> Vendor | NVIDIA
> Platform
> Name | Windows
> Architecture | x86_64
> Version | 11
> Report
> Submitted by |  
> Submitted at | 2023-04-06 06:56:54
> Last update at |  
> Reportversion | 3.2
> 
> 
> </body>
> </html>Device
> Name	[NVIDIA GeForce GTX 1050 Ti](https://vulkan.gpuinfo.org/listreports.php?displayname=NVIDIA%20GeForce%20GTX%201050%20Ti)
> Driver version	531.54.0.0
> Type	DISCRETE_GPU
> API Version	1.3.245
> Vendor	NVIDIA
> Platform
> Name	Windows
> Architecture	x86_64
> Version	11
> Report
> Submitted by	
> Submitted at	2023-04-06 06:56:54
> Last update at	
> Reportversion	3.2
> ```
> 
> GPU is not working, just CPU. Gpt4all 2.4.19
> 
> ![image](https://user-images.githubusercontent.com/10163536/271340745-18f3d276-eefb-4618-b84f-933ecfad0e45.png)

https://github.com/maozdemir/privateGPT
