### ISSUE TITLE
Old content is available after rerunning ingest.py over documents with changed content

### ISSUE THREAD

**Issue by leusch** [imartinez/privateGPT#826]
**Describe the bug and how to reproduce it**
When I change a document in source_documents, the changed chunks get added in the vectorstore but the old ones are not deleted

**Expected behavior**
When changing a document I expect that the old content is not available anymore

**Environment (please complete the following information):**
 - OS / hardware: Windows 10
 - Python version: 3.11.3

**Comment by maozdemir** [comment]
Currently there are no way of detecting the changed content, you have to recreate the database manually.

**Comment by pseudotensor** [comment]
In case you are curious, h2oGPT does that automatically for CLI db or at click of button for UI ("refresh sources").

**Comment by maozdemir** [comment]
> In case you are curious, h2oGPT does that automatically for CLI db or at click of button for UI ("refresh sources").

Off topic but this much of advertising is unethical now.

**Comment by MarcelSoftware** [comment]
@maozdemir I know. But when I have lots of documents it takes a very long time.
Maybe that's a new feature, not a bug then...

**Comment by maozdemir** [comment]
> @maozdemir I know. But when I have lots of documents it takes a very long time. Maybe that's a new feature, not a bug then...

Well, there are ways to do it, like storing also the hashes of the files and if anything changed, just reöoveıthem form the database and add the newer version of the file, but @imartinez seems to be inactive, so...

**Comment by pseudotensor** [comment]
> > In case you are curious, h2oGPT does that automatically for CLI db or at click of button for UI ("refresh sources").
> 
> Off topic but this much of advertising/promotion with no solution and contribution is unethical now.

You can see the specific code for chroma here:

https://github.com/h2oai/h2ogpt/blob/main/gpt_langchain.py#L128-L191

Basically I keep track of the file hashes in the meta data, and only add new files.

**Comment by maozdemir** [comment]
> > > In case you are curious, h2oGPT does that automatically for CLI db or at click of button for UI ("refresh sources").
> > 
> > 
> > Off topic but this much of advertising/promotion with no solution and contribution is unethical now.
> 
> You can see the specific code for chroma here:
> 
> https://github.com/h2oai/h2ogpt/blob/main/gpt_langchain.py#L128-L191
> 
> Basically I keep track of the file hashes in the meta data, and only add new files. I also handle case when file is simply changed or entirely new, by deleting the original content from the chroma db.
> 
> I also keep track of which embedding was used, and if that is changed, I re-embed, but that's not the topic of discussion here.
> 
> The specific code can be used in privateGPT no problem, I already hassled with the details of how to do this.

Thanks for your productive response!
