### ISSUE TITLE
The illusion problem of large models

### ISSUE THREAD

**Issue by LQY404** [imartinez/privateGPT#830]
Hello, thanks for your great work. 
In this work, you provide a method that ask question about local file(e.g., my pdf document), using the LLM, vector database, and langchain.
I have a question about the output of the PrivateGPT: Does it output content that does not exist in the local document?

**Comment by mehdipakistan** [comment]
yes, it will

**Comment by fatimatayeb** [comment]
How can we prevent it from doing so, I tried mentioning iit in the prompt but it doesn't seem to respect that.

**Comment by LQY404** [comment]
i think we can solve this problem by using Regular Expression, maybe. And you can see the website of **pdf.ai**,  it does not ouput the content that does not exist in the local document.
