### ISSUE TITLE
I wait more than...a day and...

### ISSUE THREAD

**Issue by huyremy** [imartinez/privateGPT#833]
I wait more than a day and nothing happen ! Have anything wrong ?
![image](https://github.com/imartinez/privateGPT/assets/2125897/5df2b69d-6c70-4878-8aa6-5d7e72348f2e)

**Comment by zba** [comment]
seems it uses cpu, i tried with [docker branch](https://github.com/imartinez/privateGPT/pull/120) (merged, with latest main, no conflicts, only trivial readme) , while nvidia-smi show correct result, my cpu uses all cores while gpu beame cold (nothing in nvtop),  seems we missing something in docs.

**Comment by mward29** [comment]
I ran into this issue as well. On ingest of docs I notice I have graphics processors that were tool old to be run by cuda despite nvidia-smi showing it as recognized.

UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 9010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:109.)
