### ISSUE TITLE
ERROR: The prompt size exceeds the context window size and cannot be processed.

### ISSUE THREAD

**Issue by sun8134** [imartinez/privateGPT#839]
Enter a query，
It show:

ERROR: The prompt size exceeds the context window size and cannot be processed.GPT-J ERROR: The prompt is2614tokens and the context window is2048!

ERROR: The prompt size exceeds the context window size and cannot be processed.

**Comment by mehdipakistan** [comment]
in .env file, increase the token number by changing 
MODEL_N_CTX=2048 
to some higher number

**Comment by tylorschafer** [comment]
Yes what @mehdipakistan said. This is not a bug.
