### ISSUE TITLE
privateGPT中文提问显示token超出限制，英文提问不存在这个问题

### ISSUE THREAD

**Issue by c384814079** [imartinez/privateGPT#850]
token的计算方式很奇怪五个字指令的token比七个字多
![微信图片_20230713094810](https://github.com/imartinez/privateGPT/assets/139415035/6346ae1f-9c65-4721-b7dd-a176fc9be4e1)
![微信图片_20230713094822](https://github.com/imartinez/privateGPT/assets/139415035/60f2d272-8a80-48d7-9032-4d915a83aa7d)

**Comment by c384814079** [comment]
![微信图片_20230713150433](https://github.com/imartinez/privateGPT/assets/139415035/6e87531f-ba80-4287-8eb9-3c2d4418b3d0)
token超出限制似乎是这段代码的问题，有人了解这个情况吗

**Comment by AbrahimZaman360** [comment]
Chinese Language is Not Allowed that's why error coming

**Comment by AbrahimZaman360** [comment]
Use Chinese LLMs for the Chinese Language, it only accepts few languages [Maybe]

**Comment by c384814079** [comment]
> Use Chinese LLMs for the Chinese Language, it only accepts few languages [Maybe]

如果需要中文处理，需要修改以上地方

中文的处理主要在embedding方式的变更上：

.env 配置如下

PERSIST_DIRECTORY=db
MODEL_TYPE=GPT4All
MODEL_PATH=models/ggml-gpt4all-j-v1.3-groovy.bin
EMBEDDINGS_MODEL_NAME=shibing624/text2vec-base-chinese
MODEL_N_CTX=1000

actually u just need to change the embedding method

**Comment by PandaBalls** [comment]
chromadb.errors.InvalidDimensionException: Dimensionality of (768) does not match index dimensionality (384)
