### ISSUE TITLE
When I execute python privateGPT.py, I get the pydantic.error_wrappers.ValidationError

### ISSUE THREAD

**Issue by Charirin** [imartinez/privateGPT#854]
When I execute python privateGPT.py, I get the error: pydantic.error_wrappers.ValidationError: 1 validation error for GPT4All
<img width="983" alt="image" src="https://github.com/imartinez/privateGPT/assets/42728100/f59f715d-3d9f-4a28-8fbc-71a4e1eea40d">

python3.10 and I use ggml-gpt4all-j-v1.3-groovy.bin and put it in models path
what should i do

**Comment by Charirin** [comment]
To add, I am using macbook m2

**Comment by testing-cs** [comment]
You may get the solution in  #691[https://github.com/imartinez/privateGPT/issues/691]. Good luck.
