### ISSUE TITLE
Fine Tune

### ISSUE THREAD

**Issue by DenizK7** [imartinez/privateGPT#858]
I am using privateGPT for read and analyze pdf files. How can I improve it, wtih my own pdfs. I want to train it with my pdf files. Also I am using GPT4All-13B-snoozy.ggmlv3.q4_0.bin and this model is always copying texts from pdfs. It is never try to answer my questions with analyze texts. Just understand my questions and try to find on text. But I want to see AI's own sentences. How can I do that ?

**Comment by owenpmckenna** [comment]
PrivateGPT allows Gpt4All to access your documents and pull data from them. If you want to _train_ (fine-tune) the model then you'll need to look at say https://github.com/nomic-ai/gpt4all/tree/main/gpt4all-training. (Disclaimer: I actually have no idea how training works but I do know that training is not what PrivateGPT is for, unless you were taking PrivateGPT outputs w/ document data and feeding them into model fine-tuning... which might actually work although it's also terribly inefficient and likely somewhat difficult to pull off) It's important to note that privategpt.py outputs the answer to your question, and then proceeds to cite its sources which is what you're seeing at the bottom of the output.
