### ISSUE TITLE
ValidationError: 1 validation error for GPT4All n_ctx. extra fields not permitted (type=value_error.extra)

### ISSUE THREAD

**Issue by yuukiqa** [imartinez/privateGPT#859]
Error occurs when trying to run PrivateGPT.py: pydantic.error_wrappers.ValidationError: 1 validation error for GPT4All
n_ctx
  extra fields not permitted (type=value_error.extra)

**Describe the bug and how to reproduce it**
git cloning the repo, downloading the model and installing requirements.txt, giving a html file as context and configuring the .env file

**Expected behavior**
For it to load in and wait for me to input my question

**Environment (please complete the following information):**
 - OS / hardware: Ubuntu 22.04

 - Python version 3.10.6
- Ubuntu is on a virtual machine

**Additional context**
None

![image](https://github.com/imartinez/privateGPT/assets/130604246/10f355de-8250-4458-bfdc-497e96afc356)

**Comment by mward29** [comment]
I had the same problem. My issue was running a newer langchain from Ubuntu. Somehow I got it into my virtualenv.
langchain 0.0.235
rather than 
langchain 0.0.197

**Comment by msagent007** [comment]
I had the same problem.

**Comment by msagent007** [comment]
Traceback (most recent call last):
  File "/home/msagent/Desktop/privateGPT/privateGPT/privateGPT.py", line 83, in <module>
    main()
  File "/home/msagent/Desktop/privateGPT/privateGPT/privateGPT.py", line 38, in main
    llm = GPT4All(model=model_path, n_ctx=model_n_ctx, backend='gptj', n_batch=model_n_batch, callbacks=callbacks, verbose=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/msagent/.local/lib/python3.11/site-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GPT4All
n_ctx
  extra fields not permitted (type=value_error.extra)

**Comment by owenpmckenna** [comment]
The changes described in [this pull request](https://github.com/imartinez/privateGPT/pull/881/files) fixed it for me.

**Comment by DataSpi** [comment]
> The changes described in [this pull request](https://github.com/imartinez/privateGPT/pull/881/files) fixed it for me.

Thanks, it works for me too

**Comment by nadagaber** [comment]
> The changes described in [this pull request](https://github.com/imartinez/privateGPT/pull/881/files) fixed it for me.
 
How can I use this pull request to fix the error?

**Comment by koalamind** [comment]
you nailed it. 
It worked fine to me too! tks!

**Comment by gokarakonda** [comment]
> The changes described in [this pull request](https://github.com/imartinez/privateGPT/pull/881/files) fixed it for me.

Thanks a lot it worked for me as well
