### ISSUE TITLE
index out of range 

### ISSUE THREAD

**Issue by janssja** [imartinez/privateGPT#86]
I have the list index out of range even for the standard installation with only "state_of_the_union.txt"

`Traceback (most recent call last):
  File "/Users/jackie/Desktop/Projects/privateGPT/ingest.py", line 22, in <module>
    main()
  File "/Users/jackie/Desktop/Projects/privateGPT/ingest.py", line 9, in main
    loader = TextLoader(argv[1], encoding="utf8")
IndexError: list index out of range`
`
No clue if it has to do with the installation

**Comment by alxspiker** [comment]
Are you on the latest branch?

**Comment by imartinez** [comment]
Please pull latest changes. https://github.com/imartinez/privateGPT/pull/74 will probably solve your issue

**Comment by janssja** [comment]
Yes. Cloned this morning.Verstuurd vanaf mijn iPhoneOp 13 mei 2023 om 09:20 heeft alxspiker ***@***.***> het volgende geschreven:﻿
Are you on the latest branch?

**Comment by janssja** [comment]
Latest branch works
