### ISSUE TITLE
I got issue with match model_type

### ISSUE THREAD

**Issue by lqhungpt** [imartinez/privateGPT#862]
I follow the install guide but I got the error as bellow:

hungluong@Hungs-MacBook-Pro privateGPT % /Users/hungluong/.pyenv/versions/3.9.12/bin/python /Users/hungluong/De
sktop/privateGPT/privateGPT.py
  File "/Users/hungluong/Desktop/privateGPT/privateGPT.py", line 34
    match model_type:
          ^
SyntaxError: invalid syntax 

Here is list of my .env file:
PERSIST_DIRECTORY=db
MODEL_TYPE=GPT4All
MODEL_PATH=models/ggml-model-gpt4all-falcon-q4_0.bin
EMBEDDINGS_MODEL_NAME=ggml-all-MiniLM-L6-v2-f16.bin
MODEL_N_CTX=1000
MODEL_N_BATCH=8
TARGET_SOURCE_CHUNKS=4

**Comment by ahernd2** [comment]
Have same issue

**Comment by lqhungpt** [comment]
> I believe this is due to Python version. Should be 3.10 instead of 3.9 in order to use match.

thank you for your support. I upgrade python to 3.10.1 then it worked. How can I improve the speed to get a response?
