### ISSUE TITLE
Non-English/Non-Latin language support

### ISSUE THREAD

**Issue by azharrudin** [imartinez/privateGPT#863]
I'm newbie here, please don't bully me.

I want ask how to make privateGPT support non-english and non-latin alphabet text such as Thai, Chinese or Indonesian.
I accept any solution or suggestion. 

Thank You

**Comment by gunners81** [comment]
you can try vicuna model, i tested it understand Indonesian question
[https://huggingface.co/CRD716/ggml-vicuna-1.1-quantized/tree/main](url)

**Comment by swaptoy** [comment]
I get the error below, any idea?

OSError: C:\Users\mobil/.cache\torch\sentence_transformers\eachadea_ggml-vicuna-13b-1.1 does not appear to have a file named config.json. Checkout 'https://huggingface.co/C:\Users\mobil/.cache\torch\sentence_transformers\eachadea_ggml-vicuna-13b-1.1/None' for available files.

**Comment by dudy5** [comment]
> I get the error below, any idea?
> 
> OSError: C:\Users\mobil/.cache\torch\sentence_transformers\eachadea_ggml-vicuna-13b-1.1 does not appear to have a file named config.json. Checkout '[https://huggingface.co/C:\Users\mobil/.cache\torch\sentence_transformers\eachadea_ggml-vicuna-13b-1.1/None](https://huggingface.co/C:%5CUsers%5Cmobil/.cache%5Ctorch%5Csentence_transformers%5Ceachadea_ggml-vicuna-13b-1.1/None)' for available files.

Your system is not support long text, You can check: https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=powershell#enable-long-paths-in-windows-10-version-1607-and-later
