### ISSUE TITLE
Invalid Model Name.

### ISSUE THREAD

**Issue by mraghbeerasi** [imartinez/privateGPT#865]
Hello,

Thank you for sharing this project.

ingest.py ran fine, when i ran the privateGPT.py I received the following error:

Using embedded DuckDB with persistence: data will be stored in: db
Found model file at  models/ggml-gpt4all-j-v1.3-groovy.bin
Invalid model file
Traceback (most recent call last):
  File "/**/**/**/**/**/privateGPT.py", line 83, in <module>
    main()
  File "/**/**/**/**/*/privateGPT.py", line 38, in main
    llm = GPT4All(model=model_path, n_ctx=model_n_ctx, backend='gptj', n_batch=model_n_batch, callbacks=callbacks, verbose=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GPT4All
__root__
  Unable to instantiate model (type=value_error)

**Environment **
 - OS / hardware: macOS 13.4.1 / M2
 - Python version 3.11.1

**.env
PERSIST_DIRECTORY=db
MODEL_TYPE=GPT4All
MODEL_PATH=models/ggml-gpt4all-j-v1.3-groovy.bin
EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
MODEL_N_CTX=1000
MODEL_N_BATCH=8
TARGET_SOURCE_CHUNKS=4
Thank you in advance for your support!

**Comment by rhodilover** [comment]
paste the content of your .env file.

**Comment by mraghbeerasi** [comment]
> paste the content of your .env file.

I just updated my comment with the .env info.

Thank you.

**Comment by tosundar40** [comment]
@thebetauser  tired still the same issue

**Comment by thebetauser** [comment]
> I had the same issue and reverting back to the old requirements, deleting the db entries and re-running ingestion fixed the issue for me.

**Comment by NemanSyed** [comment]
This worked for me:
1. Deleted contents of `./db`
2. Replaced the requirements.txt of https://github.com/imartinez/privateGPT/commit/86c2dcfe1b33ac467558487a1df408abee0d2321 with above from @thebetauser 
3. Re-ran `pip3 install -r requirements.txt`
4. Re-ran `python ingest.py`
5. `python privateGPT.py` ==> success

Thank you!

**Comment by SamuraiDjvak** [comment]
I follow this steps and now the ingest.py doesn't work 
Using embedded DuckDB with persistence: data will be stored in: db
Unable to connect optimized C data functions [No module named '_testbuffer'], falling back to pure Python
Loading documents from source_documents
Loading new documents: 0it [00:00, ?it/s]
No new documents to load

**Comment by tommygeee** [comment]
Still getting the same error:
Traceback (most recent call last):
  File "c:\Users\Tomas\Downloads\Tardis\privateGPT\privateGPT.py", line 83, in <module>
    main()
  File "c:\Users\Tomas\Downloads\Tardis\privateGPT\privateGPT.py", line 38, in main
    llm = GPT4All(model=model_path, max_tokens=model_n_ctx, backend='gptj', n_batch=model_n_batch, callbacks=callbacks, verbose=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GPT4All
max_tokens
  extra fields not permitted (type=value_error.extra)

**Comment by saurabhsjha** [comment]
i Still having the Same issue :Traceback (most recent call last):
  File "C:\AI\privateGPT\privateGPT.py", line 23, in <module>
    from constants import CHROMA_SETTINGS
  File "C:\AI\privateGPT\constants.py", line 11, in <module>
    CHROMA_SETTINGS = Settings(
  File "pydantic\env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
persist_directory
  none is not an allowed value (type=type_error.none.not_allowed)
