### ISSUE TITLE
Support for Llama2?

### ISSUE THREAD

**Issue by AMGMNPLK** [imartinez/privateGPT#868]
I got access to Llama2, could I use it with PrivateGPT?

Thank you for this contribution to humanity!

**Comment by dltacube** [comment]
If I'm not mistaken this requires one of the underlying llama-based/refined models to be updated since it needs to be GPT4All-J compatible.

**Comment by milver** [comment]
You can use HuggingFace/TheBloke Llama2 GGML bins: https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGML
I tried the [llama-2-7b-chat.ggmlv3.q4_0.bin](https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGML/blob/main/llama-2-7b-chat.ggmlv3.q4_0.bin) and it worked with PrivateGPT

**Comment by Vignesh1489** [comment]
@milver i have tried with same model its not working, i have changed the model type in .env also but still getting the error. Could you please help me with the changes to be done

**Comment by schwaa** [comment]
I also get en error using the bloke, it’s says is this really a gglm.  I’m using the q4_0, tried the 7b and 13b.

**Comment by Nikolanko** [comment]
Update llama-cpp-python to the latest version.

**Comment by mrshanth** [comment]
I get the following error when asked a query:

```
ValueError: Requested tokens (526) exceed context window of 512
```

Following is the ".env" file:
```
PERSIST_DIRECTORY=db
MODEL_TYPE=LlamaCpp
MODEL_PATH=models/llama-2-7b-chat.ggmlv3.q4_0.bin
EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
MODEL_N_CTX=1024
MODEL_N_BATCH=1024
TARGET_SOURCE_CHUNKS=4
```

**Comment by Nikolanko** [comment]
Try with `llama-2-7b-chat.ggmlv3.q2_K.bin `

“.env” file:
```
MODEL_TYPE=LlamaCpp
MODEL_PATH=models/llama-2-7b.ggmlv3.q2_K.bin
MODEL_N_CTX=1000
MODEL_N_BATCH=8
```

**Comment by mrshanth** [comment]
Error is based on the question asked. Got an answer for "What is python?", but I get an error for "How to add an element to a list in python?" through the above error. Source document is https://book.diveintopython.org/

**Comment by ThunderRod** [comment]
> @Vignesh1489 all I did was get the bin, change the bin name in .env and ran it. No errors for me.



> @milver i have tried with same model its not working, i have changed the model type in .env also but still getting the error. Could you please help me with the changes to be done

it worked for me with the following .env file:

PERSIST_DIRECTORY=db
MODEL_TYPE=**GPT4All**
MODEL_PATH=models/llama-2-7b-chat.ggmlv3.q4_0.bin
EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
MODEL_N_CTX=1000
MODEL_N_BATCH=8
TARGET_SOURCE_CHUNKS=4

**Comment by nilvaes** [comment]
> I get the following error when asked a query:
> 
> ```
> ValueError: Requested tokens (526) exceed context window of 512
> ```
> 
> Following is the ".env" file:
> 
> ```
> PERSIST_DIRECTORY=db
> MODEL_TYPE=LlamaCpp
> MODEL_PATH=models/llama-2-7b-chat.ggmlv3.q4_0.bin
> EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
> MODEL_N_CTX=1024
> MODEL_N_BATCH=1024
> TARGET_SOURCE_CHUNKS=4
> ```
Hey I had the same error as you did but then I changed MODEL_TYPE to GPT4All instead of LlamaCpp, and it worked for me. You can also update MODEL_N_BATCH to back 8 too if it gives error.

**Comment by ReconIII** [comment]
> > @Vignesh1489 all I did was get the bin, change the bin name in .env and ran it. No errors for me.
> 
> > @milver i have tried with same model its not working, i have changed the model type in .env also but still getting the error. Could you please help me with the changes to be done
> 
> it worked for me with the following .env file:
> 
> PERSIST_DIRECTORY=db MODEL_TYPE=**GPT4All** MODEL_PATH=models/llama-2-7b-chat.ggmlv3.q4_0.bin EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2 MODEL_N_CTX=1000 MODEL_N_BATCH=8 TARGET_SOURCE_CHUNKS=4

when doing this I get: gptj_model_load: loading model from 'models/llama-2-7b-chat.ggmlv3.q4_0.bin' - please wait ...
gptj_model_load: invalid model file 'models/llama-2-7b-chat.ggmlv3.q4_0.bin' (bad magic)

any suggestions? Thanks!

**Comment by ThunderRod** [comment]
> > Hi ReconIII, maybe it's a problem with the latest version of https://github.com/imartinez/privateGPT project. I cloned privateGPT project on 07-17-2023 and it works correctly for me. 2 additional files have been included since that date: poetry.lock and pyproject.toml. also privateGPT.py resize. Maybe it's possible to get a previous working version of the project, from some historical backup. Good Luck!
> 
> thanks for the input, but I had a build from about the same time and actually just tried updating it to the latest without luck :(

An extreme solution may be to start from scratch, using a specific conda environment to run privateGPT, in order to isolate the package collection from base system and other sources of incompatibility.

**Comment by ReconIII** [comment]
> > > Hi ReconIII, maybe it's a problem with the latest version of https://github.com/imartinez/privateGPT project. I cloned privateGPT project on 07-17-2023 and it works correctly for me. 2 additional files have been included since that date: poetry.lock and pyproject.toml. also privateGPT.py resize. Maybe it's possible to get a previous working version of the project, from some historical backup. Good Luck!
> > 
> > 
> > thanks for the input, but I had a build from about the same time and actually just tried updating it to the latest without luck :(
> 
> An extreme solution may be to start from scratch, using a specific conda environment to run privateGPT, in order to isolate the package collection from base system and other sources of incompatibility.

Thanks, I got it working! I updated everything but chromadb and had to reingest the documents. Works great now!

**Comment by ThunderRod** [comment]
happy to know! saved me from a lot of trouble. Now I am looking for an application/library with offline capability to backup conda environments to recover anytime a particular environment without relying on internet sources.
