### ISSUE TITLE
You are using a deprecated configuration of Chroma.

### ISSUE THREAD

**Issue by ronecharles** [imartinez/privateGPT#869]
raise ValueError(LEGACY_ERROR)
ValueError: You are using a deprecated configuration of Chroma.

If you do not have data you wish to migrate, you only need to change how you construct
your Chroma client. Please see the "New Clients" section of https://docs.trychroma.com/migration.
________________________________________________________________________________________________

If you do have data you wish to migrate, we have a migration tool you can use in order to
migrate your data to the new Chroma architecture.
Please `pip install chroma-migrate` and run `chroma-migrate` to migrate your data and then
change how you construct your Chroma client.

See https://docs.trychroma.com/migration for more information or join our discord at https://discord.gg/8g5FESbj for help!

But... after update Chroma dont run...

**Comment by muyemiy** [comment]
I had the same problem. After I updated chroma-migrate, I tried to run it, but it didn't work

**Comment by loginlogout3** [comment]
I had the same problem on my initial install, uninstalling chroma and chromadb, and then running `pip install -r requirements.txt` seemed to fix it.

**Comment by ronecharles** [comment]
I had the same problem on my initial install, uninstalling chroma and chromadb, and then running pip install -r requirements.txt seemed to fix it.

thanks, but i do this now.. and same problem

**Comment by aevedis** [comment]
Hi, it might be due to the version of Chroma and Langchain you are using. I had the same problem, fixed it like this: https://github.com/hwchase17/langchain/issues/7887#issuecomment-1643591945.

And you can also find some code by Chroma's founder here: https://gist.github.com/jeffchuber/a9ebc0ad5c7b053b8d1c50449c07f893.

**Comment by KristoWind** [comment]
Same issue here

**Comment by jayram1990** [comment]
Same issue for me 
raise ValueError(LEGACY_ERROR)
ValueError: You are using a deprecated configuration of Chroma.

**Comment by KristoWind** [comment]
I fixed it by downgrading chromadb to the last version before 0.4.0 (pip install --upgrade chromadb==0.3.29). When using >=0.4.0, the migration of data works differently, but the code from this repo is based on old migration (<0.4.0).

**Comment by rendoko** [comment]
> I fixed it by downgrading chromadb to the last version before 0.4.0 (pip install --upgrade chromadb==0.3.29). When using >=0.4.0, the migration of data works differently, but the code from this repo is based on old migration (<0.4.0).

Thank you KristoWind. That fixed the issue.

**Comment by pvbang** [comment]
I did the following and it worked properly, you can refer to:
p/s: First, note that you need to save the contents of your old requirements.txt file somewhere else so you don't lose it :)

- I deleted all pre-installed libraries with the command:
pip freeze > requirements.txt
pip uninstall -r requirements.txt -y
- Now delete the content of this new requirements.txt and replace it with the content of the old requirements.txt file
- Then change the version of chroma to 0.4.4 in your requirements.txt file: chromadb==0.4.4
- Then reinstall by: pip install -r requirements.txt
:)))

It's a bit clunky but it worked for me.
- Here is an example of my requirements.txt file:
openai
langchain
llama_index
tiktoken
pypdf
uvicorn
fastapi
pydantic
firebase_admin
docx2txt
openpyxl
python-multipart
aiofiles
chromadb==0.4.4
psutil

Hope it helps you.

**Comment by encycdata** [comment]
> I fixed it by downgrading chromadb to the last version before 0.4.0 (pip install --upgrade chromadb==0.3.29). When using >=0.4.0, the migration of data works differently, but the code from this repo is based on old migration (<0.4.0).

Thanks KristoWind!

**Comment by Zebratic** [comment]
> I fixed it by downgrading chromadb to the last version before 0.4.0 (pip install --upgrade chromadb==0.3.29). When using >=0.4.0, the migration of data works differently, but the code from this repo is based on old migration (<0.4.0).

Can confirm that this solution works. (no need to reinstall all requirements, just run "pip install --upgrade chromadb==0.3.29" and you're fine

**Comment by 8188** [comment]
I use chromadb==0.3.29 still report an error:
```
duckdb.InvalidInputException: Invalid Input Error: Required module 'pandas.core.arrays.arrow.dtype' failed to import, due to the following Python exception:
ModuleNotFoundError: No module named 'pandas.core.arrays.arrow.dtype'
```
and then pip install pandas==2.0.3[from here](https://github.com/chroma-core/chroma/issues/1069) solve it

**Comment by dineshpiyasamara** [comment]
> I fixed it by downgrading chromadb to the last version before 0.4.0 (pip install --upgrade chromadb==0.3.29). When using >=0.4.0, the migration of data works differently, but the code from this repo is based on old migration (<0.4.0).

It worked for me. Thank you

**Comment by marioaugustorama** [comment]
Nice, Worked for me too! Thank you!

**Comment by Mouhuss** [comment]
thanks that work with pip install --upgrade chromadb==0.3.29

**Comment by vyperid** [comment]
> thanks that work with pip install --upgrade chromadb==0.3.29

This worked for me, thanks!

**Comment by matthewshawnkehoe** [comment]
I have the same problem. Unfortunately, pip install --upgrade chromadb==0.3.29 doesn't work for my build.
