### ISSUE TITLE
Already get error in  "pip3 install -r requirements.txt" Please Help

### ISSUE THREAD

**Issue by erwinrnasution** [imartinez/privateGPT#873]
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
  Building wheel for hnswlib (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for hnswlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'hnswlib' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for hnswlib
Failed to build llama-cpp-python hnswlib
ERROR: Could not build wheels for llama-cpp-python, hnswlib, which is required to install pyproject.toml-based projects

**Comment by djibe** [comment]
Try
```python
pip uninstall llama-cpp-python
pip cache purge
pip install llama-cpp-python
```

**Comment by erwinrnasution** [comment]
It return this when write pip install llama-cpp-python:

Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for llama-cpp-python (pyproject.toml) did not run
successfully.
  │ exit code: 1
  ╰─> [380 lines of output]

**Comment by nikimol** [comment]
Getting the same error, even after uninstall, purge cache and install. 
I'm running Windows 11 and have tried pip install llama-cpp-python in cmd, powershell and gitbash - same errors.

**Comment by owenpmckenna** [comment]
"error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools":  https://visualstudio.microsoft.com/visual-cpp-build-tools/" (sorry, but duh unless you've already installed it, in which case I would suggest checking your PATH to make sure pip can find it)
Pip is trying to build the libraries on your machine because the publicly available ones don't match your arch/os/whatever for some reason. However, it can't find the build tool it needs ("Microsoft Visual C++ 14.0 or greater"). You need to install it.

A couple times I've had to manually clone the libraries and run "pip install ." in them because pip wasn't working.  Gpt4all has a annoying thing where you have to compile the backend before you can "pip install ." the bindings. Note: If you clone a library ALWAYS use --recurse-submodules (eg. "git clone --recurse-submodules github.com/nomic-ai/gpt4all") or you will get horrible errors. Also make sure you read the readme files (not just the ones in the root of the project).

**Comment by erwinrnasution** [comment]
Dear Owen,

Thank you for providing the necessary information regarding the error and
the solution to resolve it. I appreciate your prompt response and guidance.

I will make sure to follow the steps you mentioned and ensure that the
libraries are cloned correctly with the necessary submodules.

Thank you once again for your assistance.

Best regards,
Erwin

**Comment by nikimol** [comment]
**FIX**: This is on Windows 11. I had installed Visual Studio (including C++ tools) and Microsoft Build Tools, but it still wasn't working - so I'm not sure if either is needed with fixes below. You can try them without installing VS. I did have VSCode installed before that, though. This is the order I did it in, which worked.

```
pip uninstall llama-cpp-python
pip cache purge
# reinstall llama-cpp-python - you will get errors that it couldn't build wheels but ignore for now
pip install llama-cpp-python 
# fix to install wheels - see: https://github.com/abetlen/llama-cpp-python/issues/40
pip install https://github.com/abetlen/llama-cpp-python/releases/download/v0.1.32/llama_cpp_python-0.1.32-cp310-cp310-win_amd64.whl
# reinstall llama-cpp-python - just to make sure that all requirements are satisfied and no more errors
pip install llama-cpp-python
# manually install sentence_transformers - might not need to but I did
pip install sentence_transformers
# re-install chromadb - needs wheels fix
pip install chromadb 
# In ingest.py change ln 1: #!/usr/bin/env python3 to #!/usr/bin/env python3.10 (I added the .10 as mine was running 3.9 even though I had upgraded to 3.10)
```

Then python ingest.py worked for me.

**Comment by JSVJ** [comment]
Please try after installing Microsoft Visual Studio Build Tools. It will come with C++ embeddings. This problem was solved for me after installing Visual Studio Build Tools for C++

**Comment by sarvpriy** [comment]
I think the problem is not having a C++ compiler, I installed it using `sudo apt install build-essential` in `ubuntu 22.04` and it worked

**Comment by handsomexiaoyi** [comment]
> 我认为问题在于没有 C++ 编译器，我使用`sudo apt install build-essential`in安装了它`ubuntu 22.04`并且它有效

Thank you, It's useful for me

**Comment by bwithai** [comment]
@erwinrnasution have a look: https://github.com/imartinez/privateGPT/issues/958#issuecomment-1696844003

> Dear @AAbdullah1918 thanks to highlight this issue. These errors are usually related to compiling C/C++ code as part of the package installation process.
> 
> ### **llama-cpp-python:**
> There is an issue with configuring CMake for this package. It's complaining about not finding a C compiler and is asking for you to set the CC environment variable or update the CMAKE_C_COMPILER cache entry.
> 
> ### **chroma-hnswlib:**
> This package is failing to build because it requires C++11 support, but the build environment does not seem to have that support. The error message suggests that the minimum supported C++ version is C++11.
> 
> ## **How to resolve this issue**
> On Debian-based systems (e.g., Ubuntu) `sudo apt-get update` `sudo apt-get install build-essential`
> 
> if chroma-hnswlib is still failing due to issues related to the C++ compilation process. `sudo apt-get install python3-dev`
> 
> **Try Installing Packages Again**
