### ISSUE TITLE
How Should I fix this?

### ISSUE THREAD

**Issue by dv64bit** [imartinez/privateGPT#879]
> python ingest.py
Creating new vectorstore
Loading documents from source_documents
Loading new documents: 100%|██████████████████████| 1/1 [00:09<00:00,  9.03s/it]
Loaded 1 new documents from source_documents
Split into 91 chunks of text (max. 500 tokens each)
Creating embeddings. May take some minutes...
Traceback (most recent call last):
  File "C:\Users\darsh\Dropbox\AI\privateGPT-main\privateGPT-main\ingest.py", line 166, in <module>
    main()
  File "C:\Users\darsh\Dropbox\AI\privateGPT-main\privateGPT-main\ingest.py", line 158, in main
    db = Chroma.from_documents(texts, embeddings, persist_directory=persist_directory, client_settings=CHROMA_SETTINGS)        
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^        
  File "C:\Users\darsh\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\vectorstores\chroma.py", line 574, in from_documents
    return cls.from_texts(
           ^^^^^^^^^^^^^^^
  File "C:\Users\darsh\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\vectorstores\chroma.py", line 529, in from_texts
    chroma_collection = cls(
                        ^^^^
  File "C:\Users\darsh\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\vectorstores\chroma.py", line 109, in __init__
    self._client = chromadb.Client(_client_settings)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\darsh\AppData\Local\Programs\Python\Python311\Lib\site-packages\chromadb\__init__.py", line 107, in Client    
    system = System(settings)
             ^^^^^^^^^^^^^^^^
  File "C:\Users\darsh\AppData\Local\Programs\Python\Python311\Lib\site-packages\chromadb\config.py", line 175, in __init__    
    if settings[key] is not None:
       ~~~~~~~~^^^^^
  File "C:\Users\darsh\AppData\Local\Programs\Python\Python311\Lib\site-packages\chromadb\config.py", line 110, in __getitem__ 
    raise ValueError(LEGACY_ERROR)
ValueError: You are using a deprecated configuration of Chroma.

If you do not have data you wish to migrate, you only need to change how you construct
your Chroma client. Please see the "New Clients" section of https://docs.trychroma.com/migration.
________________________________________________________________________________________________

If you do have data you wish to migrate, we have a migration tool you can use in order to
migrate your data to the new Chroma architecture.
Please `pip install chroma-migrate` and run `chroma-migrate` to migrate your data and then
change how you construct your Chroma client.

See https://docs.trychroma.com/migration for more information or join our discord at https://discord.gg/8g5FESbj for help!

**Comment by royriver23** [comment]
The new chroma version requires you to instantiate a client first, so, you would need to do something like this:

```python
import os
from chromadb import PersistentClient
from langchain.vectorstores.chroma import Chroma

persist_directory = os.environ.get("PERSIST_DIRECTORY")

client = PersistentClient(path=persist_directory)

db = Chroma(
    persist_directory=persist_directory,
        embedding_function=embeddings,
        client=client,
    )

# Or, if loading from docs:

db = Chroma.from_documents(
        texts,
        embeddings,
        persist_directory=persist_directory,
        client=client,
    )
```

**Comment by dv64bit** [comment]
> The new chroma version requires you to instantiate a client first, so, you would need to do something like this:
> 
> ```python
> import os
> from chromadb import PersistentClient
> from langchain.vectorstores.chroma import Chroma
> 
> persist_directory = os.environ.get("PERSIST_DIRECTORY")
> 
> client = PersistentClient(path=persist_directory)
> 
> db = Chroma(
>     persist_directory=persist_directory,
>         embedding_function=embeddings,
>         client=client,
>     )
> 
> # Or, if loading from docs:
> 
> db = Chroma.from_documents(
>         texts,
>         embeddings,
>         persist_directory=persist_directory,
>         client=client,
>     )
> ```

Where should I write this code? In which file?
