### ISSUE TITLE
I also build a private GPT project use vicuna-13b,  it can connect local database.

### ISSUE THREAD

**Issue by csunny** [imartinez/privateGPT#88]
I build a private GPT project, It can deploy locally, and you can use it connect your private environment database and handler your data.   The project is there:  https://github.com/csunny/DB-GPT

**Comment by pboethig2** [comment]
Where is a english version ?

**Comment by csunny** [comment]
> Where is a english version ?

of course,  we will update readme and give some examples for english  version.

**Comment by csunny** [comment]
We update the english version.  Your can visitor from here:  https://github.com/csunny/DB-GPT/blob/main/README.en.md

**Comment by pseudotensor** [comment]
Ya, we built a privateGPT like project too.  I promise I didn't just copy privateGPT, I started like 1.5 weeks before it was out :) https://github.com/h2oai/h2ogpt
