### ISSUE TITLE
requirements.txt missing sentence_transformers

### ISSUE THREAD

**Issue by NemanSyed** [imartinez/privateGPT#883]
**Describe the bug and how to reproduce it**
On first run of ingest.py (Windows 11, not poetry), the error
`ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence_transformers`.`
is thrown
Similar to https://github.com/imartinez/privateGPT/issues/876

**Expected behavior**
sentence_transformers should be in requirements.txt

**Environment (please complete the following information):**
 - Windows 11 / Lenovo T14
 - Python 3.10.11
- Not Poetry

**Other
After `pip install sentence_transformers`, ingest.py worked.

**Comment by TiagoGouvea** [comment]
The only solution that worked for me was: `conda install -c conda-forge sentence-transformers` from issue [843](https://github.com/UKPLab/sentence-transformers/issues/843#issuecomment-1205085561)
