### ISSUE TITLE
After installing all necessary requirements and resolving the previous bugs, I have now encountered another issue while running privateGPT.py   File "C:\Users\GankZilla\Desktop\PrivateGpt\privateGPT.py", line 38, in main     llm = GPT4All(model=model_path, n_ctx=model_n_ctx, backend='gptj', n_batch=model_n_batch, callbacks=callbacks, verbose=False)

### ISSUE THREAD

**Issue by SamuraiDjvak** [imartinez/privateGPT#888]
PS C:\Users\GankZilla\Desktop\PrivateGpt> python privateGPT.py
Traceback (most recent call last):
  File "C:\Users\GankZilla\Desktop\PrivateGpt\privateGPT.py", line 83, in <module>
    main()
  File "C:\Users\GankZilla\Desktop\PrivateGpt\privateGPT.py", line 38, in main
    llm = GPT4All(model=model_path, n_ctx=model_n_ctx, backend='gptj', n_batch=model_n_batch, callbacks=callbacks, verbose=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GankZilla\Desktop\PrivateGpt\env\Lib\site-packages\langchain\load\serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for GPT4All
n_ctx
  extra fields not permitted (type=value_error.extra)
__root__
  Failed to retrieve model (type=value_error)

**Comment by twoPlankSlider** [comment]
I am assuming you figured out what resolved this.  I am running into the same issue.

**Comment by SamuraiDjvak** [comment]
> 

https://github.com/imartinez/privateGPT/issues/875#issuecomment-1646374790 this one helps me to figure out the issue, when you change row 38 in privateGPT.py it must be run without problems.
