### ISSUE TITLE
Syntax Error when running privateGPT.py

### ISSUE THREAD

**Issue by seeschweiler** [imartinez/privateGPT#89]
Hi, 

when running the script with 

`python privateGPT.py`

I got the following syntax error:

`  File "privateGPT.py", line 26
    match model_type:
          ^
SyntaxError: invalid syntax`

Any suggestions?

Thanks!

**Comment by Mohit-Gaur** [comment]
@seeschweiler How did you resolve this? I am facing the same error on Python 3.8

**Comment by hanwsf** [comment]
if model_type == "LlamaCpp":
            llm = LlamaCpp(model_path=model_path, n_ctx=model_n_ctx, callbacks=callbacks, verbose=False)
    elif model_type == "GPT4All":
            llm = GPT4All(model=model_path, n_ctx=model_n_ctx, backend='gptj', callbacks=callbacks, verbose=False)
    else:
            print(f"Model {model_type} not supported!")
            exit;
revise to this will work.

**Comment by recursionbane** [comment]
Can we make @hanwsf's suggestion the default so that privateGPT will work with Python 3.8?

**Comment by ashishfeb13** [comment]
python privateGPT.py 
  File "privateGPT.py", line 34
    match model_type:
          ^
SyntaxError: invalid syntax  

any suggestions, please?

**Comment by glasafactor** [comment]
"match" will run only on Python 3.10 or above - the code is now newer than the installed Python. Alternative solution with upgrading Pylance (not tested)
