### ISSUE TITLE
pydantic.error_wrappers.ValidationError: 1 validation error for GPT4All n_ctx -how to fix ?

### ISSUE THREAD

**Issue by noisetta** [imartinez/privateGPT#890]
Windows 11 
Python 3.10 (had to downgrade)

I'm getting this error:

PS C:\Users\name\Desktop\privateGPT> python privategpt.py
Found model file at  models/ggml-gpt4all-j-v1.3-groovy.bin
gptj_model_load: loading model from 'models/ggml-gpt4all-j-v1.3-groovy.bin' - please wait ...
gptj_model_load: n_vocab = 50400
gptj_model_load: n_ctx   = 2048
gptj_model_load: n_embd  = 4096
gptj_model_load: n_head  = 16
gptj_model_load: n_layer = 28
gptj_model_load: n_rot   = 64
gptj_model_load: f16     = 2
gptj_model_load: ggml ctx size = 5401.45 MB
gptj_model_load: kv self size  =  896.00 MB
gptj_model_load: ................................... done
gptj_model_load: model size =  3609.38 MB / num tensors = 285
Traceback (most recent call last):
  File "C:\Users\name\Desktop\privateGPT\privategpt.py", line 83, in <module>
    main()
  File "C:\Users\name\Desktop\privateGPT\privategpt.py", line 38, in main    
    llm = GPT4All(model=model_path, n_ctx=model_n_ctx, backend='gptj', n_batch=model_n_batch, callbacks=callbacks, verbose=False)
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\load\serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__     
pydantic.error_wrappers.ValidationError: 1 validation error for GPT4All      
n_ctx
  extra fields not permitted (type=value_error.extra)

This is what the privateGPT.py code looks like for lines 36 and 38:

`36    llm = LlamaCpp(model_path=model_path, max_tokens=model_n_ctx, n_batch=model_n_batch, callbacks=callbacks, verbose=False)`
`38    llm = GPT4All(model=model_path, max_tokens=model_n_ctx, backend='gptj', n_batch=model_n_batch, callbacks=callbacks, verbose=False)`

**Comment by royriver23** [comment]
See https://github.com/imartinez/privateGPT/issues/844#issuecomment-1632167884
