### ISSUE TITLE
error: metadata-generation-failed

### ISSUE THREAD

**Issue by xigua2202** [imartinez/privateGPT#898]
error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [86 lines of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by yaydos** [comment]
I had the same issue and I was using latest version of Python 3.11.x then I downgraded to 3.10.9 then It worked for this problem.

**Comment by vamsidharreddyyeddula** [comment]
im using 3.10 im still getting same error

**Comment by Atom5355** [comment]
same issue 3.10.9 didnt work

**Comment by jjaaybee** [comment]
I used 3.10.11 and had to:
python -m pip install sentence_transformers

Then it worked again
