### ISSUE TITLE
Longer output issue??

### ISSUE THREAD

**Issue by thedunston** [imartinez/privateGPT#9]
When I type a question, I get a lot of context output (based on the custom document I trained) and very short responses.  I added return_source_documents=False to privateGPT.py:

    qa = RetrievalQA.from_chain_type(llm=llm, chain_type="stuff", retriever=retriever, return_source_documents=False)

but that still prints the source documents.  I also increased the tokens to 4096 but the question I ask gets trimmed down.

Do you have any suggestions on settings I can apply to print longer responses? I don't know if the source documents being printed uses up Tokens?

**Comment by imartinez** [comment]
Pull the latest changes, install requirements.txt and then try to play with [n_predict](https://python.langchain.com/en/latest/reference/modules/llms.html#langchain.llms.GPT4All.n_predict) parameter. Default value is 256.

`llm = GPT4All(model='./models/ggml-gpt4all-j-v1.3-groovy.bin', backend='gptj', callbacks=callbacks, verbose=False, n_predict=512)`

**Comment by thedunston** [comment]
That is working better. I keep getting: 

ggml_new_tensor_impl: not enough space in the context's memory pool (needed 8037160208, available 8036235760)

and the program core dumps and I can't quite figure out what types of queries cause it to occur. I see that the gpt4all_j.py file is gone, though the program still works.

**Comment by imartinez** [comment]
I can reproduce that, usually happens with the second or third follow up question. Let's close this issue and open a specific one for this other topic.
