### ISSUE TITLE
Facing the below issue - Amateur Programmer, would love some help 

### ISSUE THREAD

**Issue by AtlasRover** [imartinez/privateGPT#904]
Hello, 

While running "ingest.py", after successful pip3 installation from requirements, the following traceback error is arising - 

"PS F:\New folder> python ingest.py
Traceback (most recent call last):
  File "F:\New folder\ingest.py", line 27, in <module>
    from constants import CHROMA_SETTINGS
  File "F:\New folder\constants.py", line 11, in <module>
    CHROMA_SETTINGS = Settings(
                      ^^^^^^^^^
  File "pydantic\env_settings.py", line 40, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
persist_directory
  none is not an allowed value (type=type_error.none.not_allowed)
"

Could you help me in figuring out what the issue is? Thank you so much in advance.

**Comment by Daethyra** [comment]
## What's wrong?
- notice: `type=type_error.none.not_allowed`
   - therefore, 'None' is not allowed
      - therefore, a setting isn't set, or a parameter is not being provided
- what to do: configure the default 'persist_directory' value in `constants.py`

## How do we know this?
[Direct code reference](https://github.com/imartinez/privateGPT/blob/main/constants.py):
```
# Define the folder for storing database
PERSIST_DIRECTORY = os.environ.get('PERSIST_DIRECTORY')
```

**Comment by Ciaranwuk** [comment]
Every time I've had a pydantic error it has never been something I've not set or something I've missed in running. IT has always been due to package issues. Your best bet is to create a new virtual environment (I like to use mamba) and reinstall the project and avoid installing anything else

**Comment by jlherren** [comment]
FWIW: This error happens when no `.env` has been created.
