### ISSUE TITLE
Error when executing "pip3 install -r requirements.txt"

### ISSUE THREAD

**Issue by pachico** [imartinez/privateGPT#909]
OS: Ubuntu 22.04, fresh vanilla EC2 instance
Python:  3.10.6
No virtual environment
g++ installed
latest master version

After a while I get this error:

```
Collecting mdurl~=0.1
  Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 389, in run
    to_install = resolver.get_installation_order(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 188, in get_installation_order
    weights = get_topological_weights(
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 276, in get_topological_weights
    assert len(weights) == expected_node_count
AssertionError
```

and cannot continue any further.

**Comment by ktalley-cinc** [comment]
Identical issue -- set up new Ubuntu 22.04 EC2 instance, cloned the repo, and attempted to install requirements.  Same exact error stack.

**Comment by ktalley-cinc** [comment]
Figured out my issue (hopefully it is your issue also, pachico!).  Needed to upgrade "pip"
**$ pip install --upgrade pip**

**Comment by pachico** [comment]
This is great news! I will try it later tonight and let you know.
I did upgraded the system but it obviously wasn't enough.
Cheers, mate! @ktalley-cinc

**Comment by ktalley-cinc** [comment]
One other warning (if you have not already encountered this), you likely will need to manually install "sentence_transformers" or your ingest step will fail

$  pip install sentence_transformers

(Not sure why this is not included in requirements.txt...)

**Comment by pachico** [comment]
@ktalley-cinc thanks a lot for both tips.
Indeed I made it work.
Now I'm in the process of finding out which instance type might work best.

From what I can see, it will use all the CPUs you throw at it, although I understand it will always be much slower than GPU powered instances.
If you have any tips about this, I'll be glad to hear!

Thanks again!

**Comment by pachico** [comment]
Solution:
```
pip install --upgrade pip
```

thx @ktalley-cinc

**Comment by sejba** [comment]
I can also confirm that upgrading pip from 22.0.2 to 23.2.1 helped. 
Thanks @ktalley-cinc
