### ISSUE TITLE
ValueError: Requested tokens (733) exceed context window of 512

### ISSUE THREAD

**Issue by MichaMaGit** [imartinez/privateGPT#911]
**Describe the bug and how to reproduce it**
I added a PDF and got this error trying to ask something
"ValueError: Requested tokens (733) exceed context window of 512"

**Environment (please complete the following information):**
 - Windows 10
 - Python version 3.10.7
 - Model: ggml-vic13b-q5_1

Thx

**Comment by AITEK-DEV** [comment]
The bug you encountered is a ValueError with the message "Requested tokens (733) exceed context window of 512". This error occurs when the number of tokens you try to process exceeds the maximum context window allowed by the model, which in this case is 512 tokens.

To reproduce the bug, you can follow these steps:

1. Add a PDF to the model.
2. Ask a question that requires a lot of context, resulting in more than 512 tokens being requested.
3. The model will throw the ValueError with the message mentioned above.

Environment:
- Windows 10
- Python version 3.10.7
- Model: ggml-vic13b-q5_1

To avoid this bug, you can try the following approaches:

1. Ask questions that require less context, reducing the number of tokens needed for processing.
2. Split your questions into smaller chunks to fit within the 512-token context window.
3. Use the `context` parameter to specify the number of tokens the model should access and ensure it does not exceed the limit.

**Comment by AITEK-DEV** [comment]
The error you are experiencing is an OSError that indicates that the file `config.json` is not found in the specified path: `C:\Users\mobil/.cache\torch\sentence_transformers\eachadea_ggml-vicuna-13b-1.1`. The message mentions that you can check the following URL to see the available files: `https://huggingface.co/C:\Users\mobil/.cache\torch\sentence_transformers\eachadea_ggml-vicuna-13b-1.1/None`.

This error usually occurs when a required model or resource is not correctly installed or cannot be found in the specified path. To fix it, you can follow these steps:

1. Make sure that the `eachadea_ggml-vicuna-13b-1.1` model is installed correctly in your environment.
2. Verify the model's path and ensure it is correct.
3. If the model is available at the mentioned URL, ensure that internet access is enabled, and the model can be downloaded properly.

If the issue persists, you can check the model's documentation or reach out to the community for further assistance regarding this specific error."
