### ISSUE TITLE
TypeError: 'SegmentAPI' object is not subscriptable

### ISSUE THREAD

**Issue by orenGIT11** [imartinez/privateGPT#912]
I ran the ingest.py file and got the following error:
Creating new vectorstore
Loading documents from source_documents
Loading new documents: 100%|██████████████████████| 1/1 [00:03<00:00,  3.61s/it]
Loaded 1 new documents from source_documents
Split into 91 chunks of text (max. 500 tokens each)
Creating embeddings. May take some minutes...
Traceback (most recent call last):
  File "C:\Users\oren\Desktop\private_GPT\privateGPT-main\ingest.py", line 166, in <module>
    main()
  File "C:\Users\oren\Desktop\private_GPT\privateGPT-main\ingest.py", line 158, in main
    db = Chroma.from_documents(texts, embeddings, persist_directory=persist_directory, client_settings=CHROMA_SETTINGS)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oren\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\vectorstores\chroma.py", line 578, in from_documents
    return cls.from_texts(
           ^^^^^^^^^^^^^^^
  File "C:\Users\oren\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\vectorstores\chroma.py", line 533, in from_texts
    chroma_collection = cls(
                        ^^^^
  File "C:\Users\oren\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\vectorstores\chroma.py", line 109, in __init__
    self._client = chromadb.Client(_client_settings)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oren\AppData\Local\Programs\Python\Python311\Lib\site-packages\chromadb\__init__.py", line 107, in Client
    system = System(settings)
             ^^^^^^^^^^^^^^^^
  File "C:\Users\oren\AppData\Local\Programs\Python\Python311\Lib\site-packages\chromadb\config.py", line 175, in __init__
    if settings[key] is not None:
       ~~~~~~~~^^^^^
TypeError: 'SegmentAPI' object is not subscriptable

Process finished with exit code 1


**Environmenא
 - OS / hardware: windows 11
 - Python version: 3.11.0
- I use pycharm

**Comment by AITEK-DEV** [comment]
It appears that the error is related to a TypeError in the `chromadb` module, specifically when trying to access a key in the `settings` object. The error message indicates that a 'SegmentAPI' object is not subscriptable.

To fix this issue, you can follow these steps:

1. Check version compatibility: Make sure all the packages (`langchain`, `chromadb`, etc.) you are using are compatible with Python 3.11.0.

2. Review the `settings` object: Verify the values in the `settings` object and ensure it is correctly configured as expected by the `chromadb` module.

3. Check API usage: Refer to the documentation of the `SegmentAPI` object or any other relevant class you are using. Ensure that you are using them correctly and handling them according to the provided guidelines.

4. Debug the code: Use debugging tools in PyCharm to step through the code and identify the exact point where the TypeError occurs. This will help you pinpoint the issue more accurately.

5. Seek help from the maintainers of the `chromadb` and `langchain` packages if you are unable to identify the cause of the problem.

Remember to create a backup of your code before making any changes and test any modifications in a controlled environment to avoid accidental data loss or additional issues.

**Comment by orenGIT11** [comment]
Thanks for the help

**Comment by AITEK-DEV** [comment]
worked?
