### ISSUE TITLE
privateGPT.py only answering questions about first page of documents

### ISSUE THREAD

**Issue by IanP7** [imartinez/privateGPT#919]
I have a multipage FAQ PDF that I have run ingest.py on. In lib/python3.11/site-packages/langchain/text_splitter.py, in defining split_documents, I have added a print statement print(doc.page_content) followed by texts.append(doc.page_content). When run, it prints out the entire contents of the PDF, which makes me think that it has ingested the whole document. If I ask privateGPT.py a question directly from the first page of the FAQ, it gives me the verbatim answer from the FAQ, which is great. However, when I ask it a question about any subsequent page, it hallucinates. I can't find any other issues mentioning this, other than the known issue with CSVs. I have made the changes that should allow CSVs to work correctly, but I have not tested it

To reproduce:
Upload a multipage PDF to source documents, ingest it, and ask a question whose answer is not on the first page.

Environment:
-Python 3.11.4
-macOS 13.2.1/M2

**Comment by AITEK-DEV** [comment]
Podría ser que el modelo no esté ingiriendo el documento por completo o que no tenga suficiente información para generar una respuesta.

Intente ejecutar el script ingest.py con la opción de ver más información sobre el proceso de ingesta. Esto puede ayudarle a identificar cualquier problema con el proceso de ingestión.-v

Intente aumentar el tamaño de privateGPT. Esto le dará al modelo más capacidad para generar respuestas precisas.

Espero que esto funcione.

**Comment by IanP7** [comment]
@AITEK-DEV when I run python3 -v ingest.py it gives me a massive wall that exceeds the storage of the terminal window. What should I be looking for?

**Comment by kripper** [comment]
I believe the problem is that:

1. The documents are split into chunks of max. 500 bytes before being added to Chroma
2. When the data is queried, Chroma returns these chunks of *incomplete documents* and feed them to the prompt
3. Thus, the LLM is not provided with all the required information

This is a big problem, especially when the split occurs in the middle of a list (eg: a text listing the 10 commandments of god).
The LLM won't have a chance to know they are 10.

**Comment by kripper** [comment]
I created a feature request to discuss more in detail:
https://github.com/langchain-ai/langchain/issues/9996#issuecomment-1699364724
