### ISSUE TITLE
Unable to instantiate model (type=value_error), Help me with this Error !!!

### ISSUE THREAD

**Issue by yashatkare** [imartinez/privateGPT#933]
Please Help me with this Error !!!
python 3.11

Found model file at  models/ggml-gpt4all-j-v1.3-groovy.bin
Invalid model file
Traceback (most recent call last):
  File "d:\2_temp\privateGPT\privateGPT.py", line 83, in <module>
    main()
  File "d:\2_temp\privateGPT\privateGPT.py", line 38, in main
    llm = GPT4All(model=model_path, max_tokens=model_n_ctx, backend='gptj', n_batch=model_n_batch, callbacks=callbacks, verbose=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\2_temp\privateGPT\.venv\Lib\site-packages\langchain\load\serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GPT4All
__root__
  Unable to instantiate model (type=value_error)
  
.env file 

PERSIST_DIRECTORY=db
MODEL_TYPE=GPT4All
MODEL_PATH=models/ggml-gpt4all-j-v1.3-groovy.bin
EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
MODEL_N_CTX=1000
MODEL_N_BATCH=8
TARGET_SOURCE_CHUNKS=4

**Comment by jiashaokun** [comment]
I encountered the same error

**Comment by luke-hale** [comment]
Same as me: `https://github.com/imartinez/privateGPT/issues/940`

**Comment by Selich** [comment]
Same error here

**Comment by Hekel1989** [comment]
Same error, identical .env

OS : Ubuntu 22.04 LTS
Python: Python 3.10.12

**Comment by NoxurnalGaming** [comment]
Same here. Same settings as the above post.

**Comment by SnoopyDevelops** [comment]
same error
