### ISSUE TITLE
Bug: Error during metadata generation when installing dependencies on Python 3.11.3

### ISSUE THREAD

**Issue by sponnify** [imartinez/privateGPT#938]
**Describe the bug and how to reproduce it:**

I encountered a compatibility issue while trying to install the `unstructured` package along with other dependencies using Python 3.11.3. The issue seems to be related to the `wrapt` package, which is causing an error during metadata generation.

**Steps to Reproduce:**

1. Create a new Python virtual environment with Python 3.11.3.
2. Install the `unstructured` package along with its dependencies using a `requirements.txt` file that includes the following packages and versions:

```plaintext
langchain==0.0.228
gpt4all==1.0.3
chromadb==0.3.26
llama-cpp-python==0.1.68
urllib3==2.0.3
PyMuPDF==1.22.5
python-dotenv==1.0.0
unstructured==0.8.0
extract-msg==0.41.5
tabulate==0.9.0
pandoc==2.3
pypandoc==1.11
tqdm==4.65.0
```

3. Run `pip install -r requirements.txt`.

**Expected behavior:**

I expected the packages to be installed successfully without any errors.

**Environment:**

- OS / Hardware: Windows 11 Pro
- Python version: 3.11.3
- Other relevant information: The error originates from the `inspect` module and is preventing successful metadata generation during package installation. This issue appears to be related to the compatibility of the `wrapt` package with Python 3.11.3.

**Comment by th4gamer** [comment]
Same problem here too.
Same Steps to Reproduce.

Environment:
- Windows 10 Pro
- Python version: 3.11.4

**Comment by ForestGlenMetro** [comment]
I am having the same problem on mac os 13.4.1 and python 3.11.4.
