### ISSUE TITLE
Preparing metadata (pyproject.toml) did not run successfully.

### ISSUE THREAD

**Issue by satishBohra** [imartinez/privateGPT#942]
Note: if you'd like to *ask a question* or *open a discussion*, head over to the [Discussions](https://github.com/imartinez/privateGPT/discussions) section and post it there.
Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [86 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Satish\AppData\Local\Temp\pip-build-env-om9hg96c\overlay\Lib\site-packages\setuptools\config\expand.py", line 81, in __getattr__
          return next(
                 ^^^^^
        File "C:\Users\Satish\AppData\Local\Temp\pip-build-env-om9hg96c\overlay\Lib\site-packages\setuptools\config\expand.py", line 82, in <genexpr>
          ast.literal_eval(value)
        File "C:\Users\Satish\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 110, in literal_eval
          return _convert(node_or_string)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Satish\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 109, in _convert
          return _convert_signed_num(node)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Satish\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 83, in _convert_signed_num
          return _convert_num(node)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\Satish\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 74, in _convert_num
          _raise_malformed_node(node)
        File "C:\Users\Satish\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 71, in _raise_malformed_node
          raise ValueError(msg + f': {node!r}')
      ValueError: malformed node or string on line 2: <ast.Call object at 0x0000025683AD1330>      

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "C:\Users\Satish\AppData\Local\Temp\pip-build-env-om9hg96c\overlay\Lib\site-packages\setuptools\config\expand.py", line 191, in read_attr
          return getattr(StaticModule(module_name, spec), attr_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Satish\AppData\Local\Temp\pip-build-env-om9hg96c\overlay\Lib\site-packages\setuptools\config\expand.py", line 87, in __getattr__
          raise AttributeError(f"{self.name} has no attribute {attr}") from e
      AttributeError: wrapt has no attribute __version__

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "D:\AI\privateGPT\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\AI\privateGPT\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\AI\privateGPT\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Satish\AppData\Local\Temp\pip-build-env-om9hg96c\overlay\Lib\site-packages\setuptools\build_meta.py", line 380, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\Users\Satish\AppData\Local\Temp\pip-build-env-om9hg96c\overlay\Lib\site-packages\setuptools\build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Satish\AppData\Local\Temp\pip-build-env-om9hg96c\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 41, in <module>
        File "C:\Users\Satish\AppData\Local\Temp\pip-build-env-om9hg96c\overlay\Lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Satish\AppData\Local\Temp\pip-build-env-om9hg96c\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 159, in setup
          dist.parse_config_files()
        File "C:\Users\Satish\AppData\Local\Temp\pip-build-env-om9hg96c\overlay\Lib\site-packages\setuptools\dist.py", line 894, in parse_config_files
          setupcfg.parse_configuration(
        File "C:\Users\Satish\AppData\Local\Temp\pip-build-env-om9hg96c\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 189, in parse_configuration
          meta.parse()
        File "C:\Users\Satish\AppData\Local\Temp\pip-build-env-om9hg96c\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 500, in parse
          section_parser_method(section_options)
        File "C:\Users\Satish\AppData\Local\Temp\pip-build-env-om9hg96c\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 475, in parse_section
          self[name] = value
          ~~~~^^^^^^
        File "C:\Users\Satish\AppData\Local\Temp\pip-build-env-om9hg96c\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 293, in __setitem__
          parsed = self.parsers.get(option_name, lambda x: x)(value)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Satish\AppData\Local\Temp\pip-build-env-om9hg96c\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 606, in _parse_version
          return expand.version(self._parse_attr(value, self.package_dir, self.root_dir))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Satish\AppData\Local\Temp\pip-build-env-om9hg96c\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 417, in _parse_attr
          return expand.read_attr(attr_desc, package_dir, root_dir)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Satish\AppData\Local\Temp\pip-build-env-om9hg96c\overlay\Lib\site-packages\setuptools\config\expand.py", line 194, in read_attr
          module = _load_spec(spec, module_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Satish\AppData\Local\Temp\pip-build-env-om9hg96c\overlay\Lib\site-packages\setuptools\config\expand.py", line 214, in _load_spec
          spec.loader.exec_module(module)  # type: ignore
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap_external>", line 940, in exec_module
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "C:\Users\Satish\AppData\Local\Temp\pip-install-ylbme06r\wrapt_dff331c8503648abaaedba4896fd2642\src\wrapt\__init__.py", line 10, in <module>
          from .decorators import (adapter_factory, AdapterFactory, decorator,
        File "C:\Users\Satish\AppData\Local\Temp\pip-install-ylbme06r\wrapt_dff331c8503648abaaedba4896fd2642\src\wrapt\decorators.py", line 34, in <module>
          from inspect import ismethod, isclass, formatargspec
      ImportError: cannot import name 'formatargspec' from 'inspect' (C:\Users\Satish\AppData\Local\Programs\Python\Python311\Lib\inspect.py)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
**Describe the bug and how to reproduce it**
A clear and concise description of what the bug is and the steps to reproduce the behavior.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Environment (please complete the following information):**
 - OS / hardware: Windows 11 pro
 - Python version3.11.4
- Other relevant information

**Additional context**
Add any other context about the problem here.

**Comment by gadams999** [comment]
Also seen on macOS using Python 3.11.4.

**Comment by bhavik-goplani** [comment]
Faced the same bug but installed dependencies one by one, which works.

**Comment by TristynAlxander** [comment]
I fixed a similar issue by using Python version 3.10.10 on linux-mint. I think it's a wrapt [issue](https://github.com/GrahamDumpleton/wrapt/issues/196) caused by python 3.11 [deprecations](https://github.com/python/cpython/pull/28618). I didn't try versions higher than 3.10.10, but given the other comments I suspect anything less than 3.11 would work. After downloading the LLM and editing the env to add its (absolute) path, I also had to use `pip install sentence_transformers` for langchain. 

Now I have it working.

**Comment by vivek5130** [comment]
same issue with me using python version 3.113 on windows 10 os.

**Comment by Johnny-Connor** [comment]
Same issue, solutions listed here did not work.

**Comment by rahulkjain** [comment]
faced the same with Python 3.11.4. Worked fine with 3.10 and installing C++ Universal Windows Platform Support

**Comment by admin0987iu** [comment]
I thonk i handle some of the error that i have try follow these steps

0.pip cache purge                                                                       😏pip install meson
1.python -m pip install --upgrade pip                                        😎pip install importlib-metadata
2.python -m pip install --upgrade setuptools                            😇pip install subprocess.run
3.pip3 install wheel setuptools pip --upgrade                            🤨pip install toml
4.pip install numpy --use-deprecated=legacy-resolver              🤨pip install setuptools-metadata

**Comment by admin0987iu** [comment]
I think i handle some of the error that i have try follow these steps

0.pip cache purge                                                                                                           
😏pip install meson
1.python -m pip install --upgrade pip 
😎pip install importlib-metadata
2.python -m pip install --upgrade setuptools 
😇pip install subprocess.run
3.pip3 install wheel setuptools pip --upgrade 
🤨pip install toml
4.pip install numpy --use-deprecated=legacy-resolver
 🤨pip install setuptools-metadata

**Comment by Hamaddah** [comment]
note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
-----------------------------------------------
problem still exists

**Comment by MatheusPerpetua** [comment]
Same problem here

**Comment by xueqings** [comment]
I have the same question, you can try python 3.8.

**Comment by xueqings** [comment]
you can try python 3.8, I solve  the problem successfully.

**Comment by Jawad-Khalil** [comment]
The same type of error occurred for me during the installation of the **scipy** package on **Python 3.9.13** 
Try to install nearly **below** or **above version** of **scipy** with the **Python version release date.**
For example, if you have **Python 3.9.13** (release date: May 17, 2022) (as in my case), try to install the **scipy** package **version 1.8.1** (release date: May 18, 2022). 
I don't know whether it will work for you in your case but it worked for me to install more than 2 packages with the same issue.
**Python       3.9.13
Pillow         9.5.0
scipy          1.8.1
matplotlib  3.7.1**
![meta data generation faild](https://github.com/imartinez/privateGPT/assets/152862298/74a68d6e-2b96-4de3-8999-7d164d4f1be5)

**Comment by originalsaizo** [comment]
I also get the same type of error. However, I'm on a RaspberryPi 4, and running Python 3.11.2.
What I'm trying to install (for Thonny), is QCustomPlot_PyQt5. I tested even QCustomPlot_PyQt6, still get the same issue.

Further research, on my system, I could see that some packages/software was not completely installed.

If someone else has same version of Python (3.11.2), and is running Bookworm, let me know if you solved it, and which steps to take.

**Comment by kickoffpro** [comment]
for me too in my MacAir Big Sur, every install using brew if its needed python-hatchling, this errors will in some way. 



 
![Captura de Tela 2024-01-16 às 14 49 59](https://github.com/imartinez/privateGPT/assets/155226458/1eaaa0c3-e6b8-47f6-b6b6-7a5c5b8badd3)

**Comment by Karthikeyakucham6918** [comment]
How can i resolve this error in windows 11 -Python 3.12.2

Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]

      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/

      Checking for Rust toolchain....
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by MikePendo** [comment]
I installed Cargo from here: [https://rustup.rs](https://rustup.rs)
and added to the path

**Comment by Harishprabhu30** [comment]
Yes! DOWNGRADING THE PYTHON VERSION SOLVES THE ERROR.

**Comment by Priyasdvh** [comment]
Could be resolved if you install required pip one by one

**Comment by Hypes-Astro** [comment]
### pip install matplotlib==3.8.4

it works

**Comment by Hypes-Astro** [comment]
> Same problem here

pip install matplotlib==3.8.4
it works. i got python 3.11

![image](https://github.com/user-attachments/assets/f251df12-d937-4fa7-97d7-595515f33ffa)

![image](https://github.com/user-attachments/assets/c7372eca-bdc6-4e50-a674-a009552e4c4e)

**Comment by tbiber2** [comment]
pip install matplotlib==3.8.4 worked for me, too.

**Comment by Carlolopespesia** [comment]
> ### pip install matplotlib==3.8.4
> it works

It works! Thank you a lot!!!

**Comment by Vikisss** [comment]
same problem

**Comment by jodomaq** [comment]
You are not writing the package correctly

**Comment by MACHINE010101** [comment]
> I think i handle some of the error that i have try follow these steps
> 
> 0.pip cache purge 😏pip install meson 1.python -m pip install --upgrade pip 😎pip install importlib-metadata 2.python -m pip install --upgrade setuptools 😇pip install subprocess.run 3.pip3 install wheel setuptools pip --upgrade 🤨pip install toml 4.pip install numpy --use-deprecated=legacy-resolver 🤨pip install setuptools-metadata

 Worked for me

**Comment by iravinandan** [comment]
In my case - 

The build process in Azure DevOps Pipeline was failing due to a permissions issue when using the default /tmp directory, which resulted in an error during the preparation of metadata for python-qpid-proton. To bypass this issue, I created a custom temporary directory and use it for the pipeline.

`- script: |
    mkdir -p ../temp
    export TMPDIR=../temp
    # Continue with the build
    pip install -r requirements.txt
  displayName: 'Set up temporary directory and install dependencies'
`

**Comment by adinathpangarkar** [comment]
> ## note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> problem still exists

same problem

**Comment by adinathpangarkar** [comment]
same problem

**Comment by Snail110** [comment]
i used conda install scipy

**Comment by LukasB1967** [comment]
I basically tried all of the above, but I still get this: 

C:\Users\Donal>pip install gensim
Defaulting to user installation because normal site-packages is not writeable
Collecting gensim
  Using cached gensim-4.3.3.tar.gz (23.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy<2.0,>=1.18.5 (from gensim)
  Using cached numpy-1.26.4.tar.gz (15.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting scipy<1.14.0,>=1.7.0 (from gensim)
  Using cached scipy-1.13.1.tar.gz (57.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      + meson setup C:\Users\Donal\AppData\Local\Temp\pip-install-jaseyjrr\scipy_034dbc6cbff44cf59182a6e0a936bbca C:\Users\Donal\AppData\Local\Temp\pip-install-jaseyjrr\scipy_034dbc6cbff44cf59182a6e0a936bbca\.mesonpy-syu6z11i -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\Donal\AppData\Local\Temp\pip-install-jaseyjrr\scipy_034dbc6cbff44cf59182a6e0a936bbca\.mesonpy-syu6z11i\meson-python-native-file.ini
      The Meson build system
      Version: 1.6.0
      Source dir: C:\Users\Donal\AppData\Local\Temp\pip-install-jaseyjrr\scipy_034dbc6cbff44cf59182a6e0a936bbca
      Build dir: C:\Users\Donal\AppData\Local\Temp\pip-install-jaseyjrr\scipy_034dbc6cbff44cf59182a6e0a936bbca\.mesonpy-syu6z11i
      Build type: native build
      Project name: scipy
      Project version: 1.13.1
      Activating VS 17.11.5
      C compiler for the host machine: cl (msvc 19.41.34123 "Microsoft (R) C/C++ Optimizing Compiler Version 19.41.34123 for x64")
      C linker for the host machine: link link 14.41.34123.0
      C++ compiler for the host machine: cl (msvc 19.41.34123 "Microsoft (R) C/C++ Optimizing Compiler Version 19.41.34123 for x64")
      C++ linker for the host machine: link link 14.41.34123.0
      Cython compiler for the host machine: cython (cython 3.0.11)
      Compiler for language cpp for the build machine not found.
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Program python found: YES (C:\Program Files\Python313\python.exe)
      Run-time dependency python found: YES 3.13
      Program cython found: YES (C:\Users\Donal\AppData\Local\Temp\pip-build-env-g2oy4gu_\overlay\Scripts\cython.EXE)
      Compiler for C supports arguments -Wno-unused-but-set-variable: NO
      Compiler for C supports arguments -Wno-unused-function: NO
      Compiler for C supports arguments -Wno-conversion: NO
      Compiler for C supports arguments -Wno-misleading-indentation: NO
      Library m found: NO

      ..\meson.build:78:0: ERROR: Unknown compiler(s): [['ifort'], ['gfortran'], ['flang-new'], ['flang'], ['pgfortran'], ['g95']]
      The following exception(s) were encountered:
      Running `ifort --help` gave "[WinError 2] Het systeem kan het opgegeven bestand niet vinden"
      Running `ifort --version` gave "[WinError 2] Het systeem kan het opgegeven bestand niet vinden"
      Running `ifort -V` gave "[WinError 2] Het systeem kan het opgegeven bestand niet vinden"
      Running `gfortran --help` gave "[WinError 2] Het systeem kan het opgegeven bestand niet vinden"
      Running `gfortran --version` gave "[WinError 2] Het systeem kan het opgegeven bestand niet vinden"
      Running `gfortran -V` gave "[WinError 2] Het systeem kan het opgegeven bestand niet vinden"
      Running `flang-new --help` gave "[WinError 2] Het systeem kan het opgegeven bestand niet vinden"
      Running `flang-new --version` gave "[WinError 2] Het systeem kan het opgegeven bestand niet vinden"
      Running `flang-new -V` gave "[WinError 2] Het systeem kan het opgegeven bestand niet vinden"
      Running `flang --help` gave "[WinError 2] Het systeem kan het opgegeven bestand niet vinden"
      Running `flang --version` gave "[WinError 2] Het systeem kan het opgegeven bestand niet vinden"
      Running `flang -V` gave "[WinError 2] Het systeem kan het opgegeven bestand niet vinden"
      Running `pgfortran --help` gave "[WinError 2] Het systeem kan het opgegeven bestand niet vinden"
      Running `pgfortran --version` gave "[WinError 2] Het systeem kan het opgegeven bestand niet vinden"
      Running `pgfortran -V` gave "[WinError 2] Het systeem kan het opgegeven bestand niet vinden"
      Running `g95 --help` gave "[WinError 2] Het systeem kan het opgegeven bestand niet vinden"
      Running `g95 --version` gave "[WinError 2] Het systeem kan het opgegeven bestand niet vinden"
      Running `g95 -V` gave "[WinError 2] Het systeem kan het opgegeven bestand niet vinden"

      A full log can be found at C:\Users\Donal\AppData\Local\Temp\pip-install-jaseyjrr\scipy_034dbc6cbff44cf59182a6e0a936bbca\.mesonpy-syu6z11i\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by LukasB1967** [comment]
waht am I doing wrong?

**Comment by BrettFraley** [comment]
Dec. 2024 and hit this issue today! Thanks for all the potential solutions above.

**Comment by 900000000** [comment]
March 2025 problem still persist

**Comment by LincolnFerreira** [comment]
Ambiente: Digital Ocean
Criei o arquivo runtime.txt e setei a versão do python: `python-3.10.11`

Tive problema com os pacotes:

orjson
asyncpg
httpx
bcrypt
httptools

Fiz o downgrade da versão com o runtime e funcionou!

**Comment by readonly24** [comment]
Also here, please help. Do I really have to install a compiler? Thanks.

    Collecting pycairo>=1.16.0 (from PyGObject==3.42.1->-r requirements.txt (line 49))
    Using cached pycairo-1.28.0.tar.gz (662 kB)
    Installing build dependencies ... done
    Getting requirements to build wheel ... done
    Installing backend dependencies ... done
    Preparing metadata (pyproject.toml) ... error
    error: subprocess-exited-with-error
    × Preparing metadata (pyproject.toml) did not run successfully.
    │ exit code: 1
    ╰─> [20 lines of output]
    + meson setup /tmp/pip-install-k6k_5lvq/pycairo_2a846c27b3b241608a15ee10b66d36a4 /tmp/pip-install-k6k_5lvq/pycairo_2a846c27b3b241608a15ee10b66d36a4/.mesonpy-rp80fu8b -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md -Dwheel=true -Dtests=false --native-file=/tmp/pip-install-k6k_5lvq/pycairo_2a846c27b3b241608a15ee10b66d36a4/.mesonpy-rp80fu8b/meson-python-native-file.ini
    The Meson build system
    Version: 1.8.2
      Source dir: /tmp/pip-install-k6k_5lvq/pycairo_2a846c27b3b241608a15ee10b66d36a4
      Build dir: /tmp/pip-install-k6k_5lvq/pycairo_2a846c27b3b241608a15ee10b66d36a4/.mesonpy-rp80fu8b
      Build type: native build
      Project name: pycairo
      Project version: 1.28.0

      ../meson.build:1:0: ERROR: Unknown compiler(s): [['cc'], ['gcc'], ['clang'], ['nvc'], ['pgcc'], ['icc'], ['icx']]
      The following exception(s) were encountered:
      Running `cc --version` gave "[Errno 2] No such file or directory: 'cc'"
      Running `gcc --version` gave "[Errno 2] No such file or directory: 'gcc'"
      Running `clang --version` gave "[Errno 2] No such file or directory: 'clang'"
      Running `nvc --version` gave "[Errno 2] No such file or directory: 'nvc'"
      Running `pgcc --version` gave "[Errno 2] No such file or directory: 'pgcc'"
      Running `icc --version` gave "[Errno 2] No such file or directory: 'icc'"
      Running `icx --version` gave "[Errno 2] No such file or directory: 'icx'"

      A full log can be found at /tmp/pip-install-k6k_5lvq/pycairo_2a846c27b3b241608a15ee10b66d36a4/.mesonpy-rp80fu8b/meson-logs/meson-log.txt
      [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed

    × Encountered error while generating package metadata.
    ╰─> See above for output.

    note: This is an issue with the package mentioned above, not pip.

**Comment by bluefalcon-max** [comment]
5 december 2025 issue still here
