### ISSUE TITLE
 The prompt size exceeds the context window size and cannot be processed.

### ISSUE THREAD

**Issue by cyz6668** [imartinez/privateGPT#943]
**Describe the bug and how to reproduce it**
A clear and concise description of what the bug is and the steps to reproduce the behavior.
I want the answer of my random quesion but I found the ERROR output as this:
![image](https://github.com/imartinez/privateGPT/assets/31882593/c7e693ff-2e00-47ad-9df9-cc34d0e0e929)

How to get larger context window size? Or do I need to pay attention to my questions?

**Comment by zhangruiyep** [comment]
Try these steps:
1. Check your .env file, set "MODEL_N_CTX" value.
2. In privateGPT.py, find LlamaCpp() or GPT4All(), add parameter "n_ctx=model_n_ctx" for them.
