### ISSUE TITLE
Model - out of doc information

### ISSUE THREAD

**Issue by aliammar182** [imartinez/privateGPT#953]
I have been able to use privateGPT and it is producing good results. 

But the issue is, this model would also produce answers even if the content is not there in documents, is there a way to handle this?

**Comment by Nova8** [comment]
How you getting this to work? 

I have created specific folders but when ask a question on the folder that is ticked. The models just starts making things up and gives a  references to the PDF. 

Also if you try to use the actual document name it refuses to look at the document. 

I'm a bit lost. Do have to use the coding guide to get it working properly?

**Comment by aliammar182** [comment]
I think it sounded wrong for you, what I meant was private GPT is working and all but having same issues as you. Even when the information is not there in documents, it just uses its own information (on which the model is trained on) to produce results
