### ISSUE TITLE
requests.exceptions.ConnectionError: (ProtocolError('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)), '(Request ID: e8978aac-8895-4ca1-b91e-e01f3c0a5f95)')

### ISSUE THREAD

**Issue by xigua2202** [imartinez/privateGPT#955]
requests.exceptions.ConnectionError: (ProtocolError('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)), '(Request ID: e8978aac-8895-4ca1-b91e-e01f3c0a5f95)')

**Comment by 0x766c6f6f6b** [comment]
vpn的问题，换个节点试试
