### ISSUE TITLE
Can it index from given web link or links only ? Instead of documents.

### ISSUE THREAD

**Issue by aetherujjwal** [imartinez/privateGPT#97]

**Comment by JimboDaDuck** [comment]
It can only ingest the 3 said documents (".txt", ".pdf", ".csv"), however I've made a python script which you can input a link and it will download all the text and save it to a ".txt" file:

import requests
from bs4 import BeautifulSoup
from urllib.parse import urlparse


def get_website_text(url):
    # Send a GET request to the website
    response = requests.get(url)

    # Parse the HTML content using BeautifulSoup
    soup = BeautifulSoup(response.content, 'html.parser')

    # Extract all text from the HTML
    text = soup.get_text()

    return text


def save_text_to_file(text, filename):

    # Write the text to the file
    with open(filename, 'w', encoding='utf-8') as file:
        file.write(text)

    print(f"Text saved as {filename}")


# Get the website URL from the user
website_url = input("Enter the website URL: ")

# Retrieve the website text
website_text = get_website_text(website_url)

# Get the website name from the URL
parsed_url = urlparse(website_url)
website_name = parsed_url.netloc

# Remove special characters from the website name to use it as the filename
filename = ''.join(c for c in website_name if c.isalnum()) + ".txt"

# Save the text to a file
save_text_to_file(website_text, filename)
