### ISSUE TITLE
Double Ingestion?

### ISSUE THREAD

**Issue by code-boxx** [imartinez/privateGPT#983]
I have not gone through all the madness... But in `ingest.py`, `def load_documents`, you guys are doing `all_files.extend(...)` twice. Not sure if this is deliberate, but overeating does seem to cause some issues. LOL.

**Comment by KasperVesteraa** [comment]
I have also wondered about this.
It seems to load each document twice. Also it references each section it uses twice.

**Comment by fkauffmann** [comment]
I think it makes sense on Linux, where filenames are case-sensitive, but not on Windows.

**Comment by aniketkhajanchi** [comment]
> I think it makes sense on Linux, where filenames are case-sensitive, but not on Windows.

so we can just remove the uppercase extension conversions?
