### ISSUE TITLE
Llama object has no attribute as ctx

### ISSUE THREAD

**Issue by azxan2009** [imartinez/privateGPT#986]
Note: if you'd like to *ask a question* or *open a discussion*, head over to the [Discussions](https://github.com/imartinez/privateGPT/discussions) section and post it there.

**Describe the bug and how to reproduce it**
A clear and concise description of what the bug is and the steps to reproduce the behavior.

**Expected behavior**

**Environment (please complete the following information):**
 - OS / hardware: [e.g. macOS 12.6 / M1]
 - Python version [e.g. 3.11.3]
- Other relevant information

**Additional context**

Error:
llama.cpp: loading model from models/ggml-model-q4_0.bin
error loading model: unexpectedly reached end of file
llama_load_model_from_file: failed to load model
Traceback (most recent call last):
  File "/content/localgpt/privateGPT.py", line 83, in <module>
    main()
  File "/content/localgpt/privateGPT.py", line 36, in main
    llm = LlamaCpp(model_path=model_path, max_tokens=model_n_ctx, n_batch=model_n_batch, callbacks=callbacks, verbose=False)
  File "/usr/local/lib/python3.10/dist-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LlamaCpp
__root__
  Could not load Llama model from path: models/ggml-model-q4_0.bin. Received error  (type=value_error)
Exception ignored in: <function Llama.__del__ at 0x7dd38b822950>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/llama_cpp/llama.py", line 1445, in __del__
    if self.ctx is not None:
AttributeError: 'Llama' object has no attribute 'ctx'

My Env file:

PERSIST_DIRECTORY=db
MODEL_TYPE=LlamaCpp
MODEL_PATH=models/ggml-model-q4_0.bin
EMBEDDINGS_MODEL_NAME=paraphrase-TinyBERT-L6-v2
MODEL_N_CTX=1000
MODEL_N_BATCH=8
TARGET_SOURCE_CHUNKS=4

**Comment by imartinez** [comment]
@azxan2009 make sure the path to the file is correct. Have you tried other models? Give a try to a GPT4All model type

**Comment by PhucHoang998** [comment]
Very

**Comment by azxan2009** [comment]
Gpt4all works fine. When I tried it with llamacpt it throws that error. Will it not work with any other embedding?

**Comment by edwinyoo44** [comment]
> Gpt4all works fine. When I tried it with llamacpt it throws that error. Will it not work with any other embedding?

Try using an older version of .llama.cpp conversion

**Comment by azxan2009** [comment]
i could not find the llama.cpp old version to download, can you please post a link here
