### ISSUE TITLE
CPU locked at 100% while ingesting

### ISSUE THREAD

**Issue by mattehicks** [imartinez/privateGPT#989]
Note: if you'd like to *ask a question* or *open a discussion*, head over to the [Discussions](https://github.com/imartinez/privateGPT/discussions) section and post it there.

**Describe the bug and how to reproduce it**
After installing for the first time, and installing all requirements.
Added a folder of a few dozen hand written text files.
Did:  "py ingest.py"

CPU is steady at 100% utilization for hours...
Progress is stuck at 25%

**Expected behavior**
Not sure.  I'm looking for info and advice here.

**Environment (please complete the following information):**
 - Windows 10, 64GB ram, Nvidia 1090 
 - python 3.10 / 3.11 

**Additional context**
Specs below:

![image](https://github.com/imartinez/privateGPT/assets/859222/cfe3a352-7ebe-4369-aea6-3f6ad36374ff)

**Comment by imartinez** [comment]
Maybe there is a specific document breaking the process. Have you tried ingesting subsets of your documents? You can ingest some and later on add some more to the folder and rerun ingest.py. It won't re-ingest the already ingested ones. That way you can monitor if there is a problem with a specific doc.
