### ISSUE TITLE
Stuck on a requirements.txt

### ISSUE THREAD

**Issue by pierceglenn12345** [imartinez/privateGPT#991]
Deleting my info here and moving this to #965 as it is the same problem.

**Comment by pierceglenn12345** [comment]
I tried from scratch on another computer and got the same issue as I did the first time. One change I made was to the .env file where I set PERSIST_DIRECTORY to \~/.emacs.d/projects/llm/privateGPT/db instead of an empty directory \~/.emacs.d/projects/llm/privateGPT/.


 Traceback (most recent call last):
  File "/home/pglenn/.emacs.d/privateGPT/privateGPT.py", line 87, in <module>
    main()
  File "/home/pglenn/.emacs.d/privateGPT/privateGPT.py", line 42, in main
    llm = GPT4All(model=model_path, max_tokens=model_n_ctx, backend='gptj', n_batch=model_n_batch, callbacks=callbacks, verbose=False)
  File "/home/pglenn/.local/lib/python3.10/site-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GPT4All
__root__
  Failed to retrieve model (type=value_error)


If someone could help me from this point, that surely will be much easier than to debug the mess I put myself in the above instance.

**Comment by pierceglenn12345** [comment]
Okay so I am trying to follow the trace back and I cannot seem to find where pydantic/main.py is? I found in the langchain repo a langchain/pydantic_v1/main.py but it is only 4 lines long, not >341 as the Traceback above shows. That file also says to try and import * from pydantic.vi.main.. in my mind that means it wants to load all(*) from itself? I don't know python well enough to know what this is trying to do.

**Comment by Zaheer-10** [comment]
Try downgrading the version of pydantic
