### ISSUE TITLE
Which model should i use for LLamaCpp ?

### ISSUE THREAD

**Issue by papipsycho** [imartinez/privateGPT#994]
Hello i've setup PrivatGPT and is working with GPT4ALL, but it slow, so i wanna use the CPU,

so i moved from GPT4ALL to LLamaCpp, but i've try several model and everytime i got some issue :

```
ggml_init_cublas: found 1 CUDA devices:
  Device 0: Tesla V100-SXM2-16GB, compute capability 7.0
Traceback (most recent call last):
  File "/content/privateGPT/privateGPT.py", line 89, in <module>
    main()
  File "/content/privateGPT/privateGPT.py", line 40, in main
    llm = LlamaCpp(model_path=model_path, n_ctx=4096, max_tokens=512, n_batch=model_n_batch, callbacks=callbacks, verbose=False, n_gpu_layers=43)
  File "/usr/local/lib/python3.10/dist-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LlamaCpp
__root__
  Could not load Llama model from path: models/koala-7B.ggmlv3.q8_0.bin. Received error  (type=value_error)
```

so i used with several model such like : 
ggml-gpt4all-j-v1.3-groovy.bin
ggml-vic13b-q4_0.bin
ggml-vic13b-q5_1.bin
koala-7B.ggmlv3.q4_1.bin
koala-7B.ggmlv3.q8_0.bin
nous-hermes-llama2-13b.ggmlv3.q6_K.bin

everytime i got the same error message.

if any one have an idea

**Comment by pierceglenn12345** [comment]
Join the club #965. Though it seems you were able to get GPT4ALL to work, so you're a little bit ahead of us.

**Comment by papipsycho** [comment]
mmh i'm not sure if is exactly the same issue, cause for me GPT4ALL was OK

**Comment by abhishekbhakat** [comment]
It's not a bug. You download any model which is supported by [llama.cpp](https://github.com/ggerganov/llama.cpp). Use specific converter to create a gguf model.

Example:
I downloaded https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGML
Used https://github.com/ggerganov/llama.cpp/blob/master/convert-llama-ggmlv3-to-gguf.py to convert the model by:

```
python convert-llama-ggmlv3-to-gguf.py --input models/llama-2-7b-chat.ggmlv3.q8_0.bin --output llama-2-7b-chat.gguf.bin
```

Now use the new bin file created in your `.env` file. It should work.

**Comment by Zaheer-10** [comment]
Since your using Lamacpp, you didn't change the model path, make sure that you have lamacpp downloaded or else try using hugging face api

**Comment by papipsycho** [comment]
thanks a lot, i download a gguf model and now is working,  unfortunalty still very slow, even with A100

**Comment by abhishekbhakat** [comment]
That totally depends on what model you choose. For faster inference, use a 7b or 13b parameter model.

**Comment by papipsycho** [comment]
yes, i tested with vicuna 13b and is really fast

**Comment by Musthafamoz** [comment]
@papipsycho can you tell me how fast is it. like how many seconds?
